Add MNLI compatible mode
huggingface/transformers pull request #10203
Opened 2021-02-16 05:40 UTC by JetRunner

In this PR:

- Upgrade `datasets` to `1.3.0`
- Rename `datasets` variable to `task_datasets` in `run_glue.py` to avoid confusion with the library `datasets`
- Add a `--compat_mode` option to use the old label assignment for MNLI

2021-02-16 05:43 UTC, JetRunner commented
The CI failed but it seems irrelevant. Could you please give it a check? @LysandreJik

2021-02-16 06:22 UTC, patil-suraj approved these changes
LGMT! I'm okay with `datasets` => `task_datasets`

2021-02-16 06:22 UTC, patil-suraj commented on examples/text-classification/run_glue.py
> +                    raise ImportError("Please update `datasets` to >1.3.0 to overwrite the labels.")
```suggestion
                    raise ImportError("Please update `datasets` to >=1.3.0 to overwrite the labels.")
```

2021-02-16 06:23 UTC, patil-suraj commented
The CI issue is `test_hf_api`, which is fixed on master now, rebasing should make the CI green!

2021-02-16 10:02 UTC, lhoestq approved these changes

2021-02-16 14:10 UTC, sgugger reviewed
I really dislike the change as it makes the script (which we showcase as an example for beginners) more complicated and less understandable. We can add a script instead that will add the proper label assignment in the model config, which this example will then use if available and put the warning in the README instead.

2021-02-16 19:11 UTC, JetRunner commented
@sgugger Sorry but I can't really agree with you here. It is a problem introduced by mistake and we shouldn't just try to ignore that. It just adds a few lines of if-else and I don't think it'll add too much burden for users. 

I am never a fan of trainer-style code since IMO capsulation is not simplicity (I believe our user survey supports my claim here). Besides, I do think back-compatibility matters especially when our success depends heavily on the prosperity of the model hub. This PR is meant to fix a bug though it's harsh. Happy to have more discussion here.

2021-02-18 19:48 UTC, sgugger commented
So we discussed it a bit more internally. This particular example script will stay as is with the backward-compatibility problem (which isn't one IMO since the problem is in the model config not having the right labels). As I said before it's an example aimed at data scientists that shouldn't necessarily have all the functionality.

There will be another script for GLUE (probably by the end of the month) very soon that doesn't use `Trainer` and has the training loop exposed, where we can integrate your fix.

2021-02-19 08:35 UTC, JetRunner commented
Looking forward to the new script you mentioned!

2021-02-25 16:28 UTC, AliHadizadeh requested changes

2021-02-25 16:28 UTC, AliHadizadeh commented on examples/text-classification/run_glue.py
> +                    "glue", data_args.task_name, label_classes=["contradiction", "entailment", "neutral"]
```suggestion
                    "glue", data_args.task_name, label_classes=["contradiction", "neutral" , "entailment"]
```
I believe this is the correct order!

2021-04-13 11:22 UTC, closed without merging