closes #10258
huggingface/transformers pull request #10703
Opened 2021-03-14 06:05 UTC by cronoik

# What does this PR do?

Fixes #10258

@BigBird01 Please upload these [files](https://drive.google.com/drive/folders/1gH5EMABR94iHO7SCb_AdNGCOOIdSloxh?usp=sharing) to your deberta repositories.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

- tokenizers:  @LysandreJik, @BigBird01

2021-03-15 12:59 UTC, LysandreJik commented
This is great @cronoik! I just tested it and reproduced identical results between the previous version and this one. Fantastic!

Could you add an integration tests for the DeBERTa tokenizer to ensure the implementations don't diverge? You can just copy paste the [test for ALBERT tokenizers](https://github.com/huggingface/transformers/blob/master/tests/test_tokenization_albert.py#L106) and change the values to DeBERTa.

If you don't have time, let us know and we'll take care of it.

2021-03-15 16:34 UTC, cronoik commented
@LysandreJik 
I will give it a try.

2021-03-18 18:24 UTC, cronoik commented
Hi,
a new test is now added for the debertatokenizer. I stuck more to the robertatokenizer test since the debertatokenizer is basically a robertatokenizer.

I can not interpret the failed check. I assume it is because the model hub is missing the new files? @LysandreJik could you please have a look?

2021-03-18 18:32 UTC, jeswan commented
I am trying out this PR with the following:

```
tokenizer = DebertaTokenizer.from_pretrained("microsoft/deberta-base")
target_tokenized = tokenizer.tokenize("Some test text")
```
but I see the following error (`TypeError: expected str, bytes or os.PathLike object, not NoneType`):
```
    def __init__(
        self,
        vocab_file,
        merges_file,
        errors="replace",
        unk_token="<|endoftext|>",
        bos_token="<|endoftext|>",
        eos_token="<|endoftext|>",
        add_prefix_space=False,
        **kwargs
    ):
        bos_token = AddedToken(bos_token, lstrip=False, rstrip=False) if isinstance(bos_token, str) else bos_token
        eos_token = AddedToken(eos_token, lstrip=False, rstrip=False) if isinstance(eos_token, str) else eos_token
        unk_token = AddedToken(unk_token, lstrip=False, rstrip=False) if isinstance(unk_token, str) else unk_token
        super().__init__(
            errors=errors,
            unk_token=unk_token,
            bos_token=bos_token,
            eos_token=eos_token,
            add_prefix_space=add_prefix_space,
            **kwargs,
        )

>       with open(vocab_file, encoding="utf-8") as vocab_handle:
E       TypeError: expected str, bytes or os.PathLike object, not NoneType

../../../../jeswan_transformers/src/transformers/models/gpt2/tokenization_gpt2.py:179: TypeError
```
Not sure if it is related to @cronoik's error above

2021-03-18 18:52 UTC, cronoik commented
@jeswan that will not work since the required files are not uploaded to the model hub yet. You can download them from the [link](https://drive.google.com/drive/folders/1gH5EMABR94iHO7SCb_AdNGCOOIdSloxh?usp=sharing) and load the tokenizer from local.

2021-03-22 15:51 UTC, BigBird01 commented on src/transformers/models/deberta/tokenization_deberta.py
> +        return cls + token_ids_0 + sep + sep + token_ids_1 + sep
In DeBERTa, the input schema is cls + seg1 + sep + seg2 + sep

2021-03-22 15:55 UTC, BigBird01 commented on src/transformers/models/deberta/tokenization_deberta.py
> +        return [1] + ([0] * len(token_ids_0)) + [1, 1] + ([0] * len(token_ids_1)) + [1]
The same as above comment

2021-03-22 15:56 UTC, BigBird01 commented on src/transformers/models/deberta/tokenization_deberta.py
> +        return len(cls + token_ids_0 + sep + sep + token_ids_1 + sep) * [0]
The same

2021-03-22 15:59 UTC, BigBird01 requested changes
Thanks for the effort. I just checked all the changes and left one comment which is important for the model performance.

2021-03-22 16:06 UTC, BigBird01 commented
@cronoik thanks for your effort. I just uploaded the files to the model repository and left one comment to the changes.

2021-03-30 14:52 UTC, cronoik commented
@BigBird01 Thank you for the review. I had only tested single sentences and completely ignored the sentence pairs before pushing.
@LysandreJik Can you please help me with the test error?

2021-03-30 19:18 UTC, LysandreJik approved these changes
I just pushed a style commit. LGTM!

2021-03-31 18:46 UTC, sgugger approved these changes
Thanks for the rework!

2021-03-31 19:49 UTC, cronoik commented
@sgugger Thanks for the review. I have pushed/accepted your change requests.

2021-04-01 17:53 UTC, merged

2021-04-01 17:54 UTC, LysandreJik commented
Thanks for your efforts @cronoik!