BLUE
huggingface/transformers pull request #1238
Opened 2019-09-10 11:37 UTC by anhnt170489

In this PR: 
- I add BertForMultiLabelClassification, RobertaForTokenClassification, RobertaForMultiLabelClassification. 
- I add examples for Finetuning the BERT, RoBERTa models for tasks on BLUE (https://github.com/ncbi-nlp/BLUE_Benchmark). BLUE (Biomedical Language Understanding Evaluation) is similar to GLUE, but for Biomedical data. The "run_blue", "utils_blue" are customized from "run_glue", "utils_glue", but more sufficient, because it contains not only sequence classification, but also token classification, multi-label classification. People may also have more options for examples of fine-tuning BERT/RoBERTa. 
- I also add test function to test_examples as well as test data (HOC)

2019-09-17 08:31 UTC, thomwolf commented
@LysandreJik @julien-c one of you want to give a look?

2019-09-25 04:52 UTC, anhnt170489 commented
@thomwolf : Hi, all checks have passed. Please review it again ;).

2019-10-06 12:59 UTC, dennlinger requested changes
Minor typos that make it hard to spot incosistencies later.

2019-10-06 12:59 UTC, dennlinger commented on pytorch_transformers/modeling_roberta.py
> +        tokenizer = RoertaTokenizer.from_pretrained('roberta-base')
This should probably be renamed to `RobertaTokenizer` (typo).

2019-10-06 12:59 UTC, dennlinger commented on pytorch_transformers/modeling_roberta.py
> +        tokenizer = RoertaTokenizer.from_pretrained('roberta-base')
Similar to the other highlight, his should probably be renamed to `RobertaTokenizer` (typo).

2019-10-07 10:06 UTC, anhnt170489 commented
This PR is out of date. 
I updated a new one here (https://github.com/huggingface/transformers/pull/1440).

2019-10-07 10:06 UTC, closed without merging