Add attention-mask support for ViTModel
huggingface/transformers pull request #13764
Opened 2021-09-27 16:28 UTC by Ryan-Qiyu-Jiang

# What does this PR do?

Transformers currently only support head-masks, however recent works
in vision language modeling have used the ViTModel with attention-masks.
Adding attention-masks to ViTSelfAttention and ViTModel allow
transformers modeling_vit to be used in implementing these models.

This commit adds attention-mask implementations from BertSelfAttention
as the forward param attention_mask. This change preserves the existing
behavior by default.

A specific example of how this change will be useful is being able to
implement ViLT https://arxiv.org/abs/2102.03334, using ViTModel as the main trunk.

Unit-tests seemed to pass, though there wasn't a unit-test for head_masks,
so I just added a check for attention_mask in the signature.
Thanks!

src/transformers/models/vit/modeling_vit.py @LysandreJik, @sgugger

2021-09-28 13:37 UTC, sgugger reviewed
Thanks for the PR! I'm not sure how the API can be used however. The attention mask is just added to the attention scores, so it should already be a tensor with big negative floats for the values masked, but the other Transformer models use a mask of booleans (converted to the format of floats behind the scenes). Shouldn't that conversion also be in this PR?

2021-09-28 13:37 UTC, sgugger commented on src/transformers/models/deit/modeling_deit.py
> +            # Apply the attention mask is (precomputed for all layers in DeiTModel forward() function)
Why the `is` here?

2021-09-28 13:50 UTC, patil-suraj reviewed
Adding `attention_mask` as you mentioned makes sense.

But as @sgugger said, the boolean mask should be modified into a broadcasted tensor with big negative floats for the values masked. This could be done in `ViTModel.forward ` method, as is done in `BertModel`.

https://github.com/huggingface/transformers/blob/5e3b4a70d3d17f2482d50aea230f7ed42b3a8fd0/src/transformers/models/bert/modeling_bert.py#L966-L969

This `extended_attention_mask` should then be passed to the attention layer instead of the boolean mask.

(Thank you for `ViLT` reference, that looks like an interesting model :) )

2021-09-28 16:18 UTC, Ryan-Qiyu-Jiang commented on src/transformers/models/deit/modeling_deit.py
> +            # Apply the attention mask is (precomputed for all layers in DeiTModel forward() function)
Fixed!

2021-09-29 13:57 UTC, NielsRogge commented on src/transformers/models/deit/modeling_deit.py
> +    def forward(self, hidden_states, head_mask=None, output_attentions=False, attention_mask=None):
```suggestion
    def forward(self, hidden_states, attention_mask=None, head_mask=None, output_attentions=False):
```
For consistency with other models ;)

2021-09-29 14:01 UTC, NielsRogge commented on src/transformers/models/deit/modeling_deit.py
> +        self_outputs = self.attention(hidden_states, head_mask, output_attentions, attention_mask)
```suggestion
        self_outputs = self.attention(hidden_states, attention_mask, head_mask, output_attentions)
```

2021-09-29 14:03 UTC, NielsRogge commented on src/transformers/models/deit/modeling_deit.py
> +            attention_mask=attention_mask,
```suggestion
            self.layernorm_before(hidden_states),  # in DeiT, layernorm is applied before self-attention
            attention_mask=attention_mask,
            head_mask,
            output_attentions=output_attentions,
```

2021-09-29 14:04 UTC, NielsRogge commented on src/transformers/models/deit/modeling_deit.py
> +        attention_mask=None,
For some reason Github doesn't allow me to comment on the lines above, but one should pass the `attention_mask` after `hidden_states`.

2021-09-29 14:04 UTC, NielsRogge commented on src/transformers/models/deit/modeling_deit.py
> +                layer_outputs = layer_module(hidden_states, layer_head_mask, output_attentions, attention_mask)
```suggestion
                layer_outputs = layer_module(hidden_states, attention_mask, layer_head_mask, output_attentions)
```

2021-09-29 14:05 UTC, NielsRogge commented on src/transformers/models/vit/modeling_vit.py
> +    def forward(self, hidden_states, head_mask=None, output_attentions=False, attention_mask=None):
```suggestion
    def forward(self, hidden_states, attention_mask=None, head_mask=None, output_attentions=False, attention_mask=None):
```

2021-09-29 14:05 UTC, NielsRogge commented on src/transformers/models/vit/modeling_vit.py
> +        self_outputs = self.attention(hidden_states, head_mask, output_attentions, attention_mask)
```suggestion
    def forward(self, hidden_states, attention_mask=None, head_mask=None, output_attentions=False):
        self_outputs = self.attention(hidden_states, attention_mask, head_mask, output_attentions)
```

2021-09-29 14:06 UTC, NielsRogge commented on src/transformers/models/vit/modeling_vit.py
> +        attention_mask=None,
Here similarly, please pass the `attention_mask` after the `pixel_values`.

2021-09-29 14:07 UTC, NielsRogge commented on src/transformers/models/vit/modeling_vit.py
> +            attention_mask=extended_attention_mask,
Same comment here.

2021-09-29 14:07 UTC, NielsRogge commented on src/transformers/models/vit/modeling_vit.py
> +            attention_mask=extended_attention_mask,
```suggestion
        encoder_outputs = self.encoder(
            embedding_output,
            attention_mask=extended_attention_mask,
            head_mask=head_mask,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
```
Same comment here.

2021-09-29 14:09 UTC, NielsRogge requested changes
Thanks for this PR!

I left only one comment everywhere: for consistency with other models, the `attention_mask` argument should come after the `pixel_values`/`hidden_states`.

2021-09-30 15:52 UTC, Ryan-Qiyu-Jiang commented
@NielsRogge reordered params!

2021-10-01 09:22 UTC, NielsRogge commented
Thanks. I think this should also be added for the Flax implementation of ViT, for consistency.

It could perhaps also be added for BEiT.

2021-10-01 18:15 UTC, Ryan-Qiyu-Jiang commented
@NielsRogge added to flax_vit, beit, and flax_beit.

2021-10-04 11:43 UTC, NielsRogge commented
Thanks. Can you also add the corresponding tests? In `test_modeling_vit.py` (and similarly, in test_modeling_deit.py, test_modeling_beit.py and the flax models), we can add the attention_mask to the `prepare_config_and_inputs` method, and use them in all tests.

2021-10-04 13:09 UTC, NielsRogge commented
@Ryan-Qiyu-Jiang the shape of the `attention_mask` provided to these models is equal to (batch_size, seq_len), with the sequence length equal to the number of patches + 1 for the [CLS] token (and + 2 for DeiT, as this model also adds a special distillation token to the sequence).

This should also be added to the docstrings of the respective models.

2021-10-04 17:08 UTC, patil-suraj requested changes
I left a couple of comments about how `attention_mask` should be passed in flax model. 
It should also be added in the call method of `FlaxViTPreTrainedModel` and `FlaxBeitPreTrainedModel` as is done in `FlaxBertPreTrainedModel`. This call method is the main interface for all flax models and is always called when we call any flax model.

https://github.com/huggingface/transformers/blob/6c08840628a22a4d53ae563d1041479649d1a8e7/src/transformers/models/bert/modeling_flax_bert.py#L566-L611

Let me know if you need help with this :)

2021-10-04 17:08 UTC, patil-suraj commented on src/transformers/models/beit/modeling_flax_beit.py
> +            mask=attention_mask,
the `dot_product_attention_weights` function does not have an argument called the mask. It takes `bias` as an argument that is expanded tensor with float values. beit uses relative attention, so the `attention_mask` here should be expanded and then added to `attention_bias`. T5 does something similar which you could use here

expand the mask
https://github.com/huggingface/transformers/blob/6c08840628a22a4d53ae563d1041479649d1a8e7/src/transformers/models/t5/modeling_flax_t5.py#L403

convert it to float tensor with large negative values for masked tokens
https://github.com/huggingface/transformers/blob/6c08840628a22a4d53ae563d1041479649d1a8e7/src/transformers/models/t5/modeling_flax_t5.py#L413-L418

add it to the position bias
https://github.com/huggingface/transformers/blob/6c08840628a22a4d53ae563d1041479649d1a8e7/src/transformers/models/t5/modeling_flax_t5.py#L426-L427

2021-10-04 17:08 UTC, patil-suraj commented on src/transformers/models/vit/modeling_flax_vit.py
> +            mask=attention_mask,
same comment as above, no `mask` argument. Should be expanded to a tensor and pass as bias. Here is how it's done in bert

https://github.com/huggingface/transformers/blob/6c08840628a22a4d53ae563d1041479649d1a8e7/src/transformers/models/bert/modeling_flax_bert.py#L229-L254

2021-11-13 15:02 UTC, closed without merging