Adding S4 Model
huggingface/transformers pull request #14837
Opened 2021-12-19 20:03 UTC by kamalkraj

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@Rocketknight1

2021-12-20 14:12 UTC, Rocketknight1 commented
@kamalkraj This looks great! Please let us know if you're encountering any problems, and of course ping me when it's ready for a final review.

2021-12-23 18:08 UTC, sgugger requested changes
Thanks for the PR, it's a complicated model you're adding!

The modeling file needs to be rewritten in depth before we can merge this PR IMO. This includes:
- using descriptive variable names: we can't use one-letter variable names with no comments in the code as we then won't be able to maintain code we do not understand
- use proper docstring that explain what the function/classes are doing
- don't use asserts but tests and raise proper errors of the right type.
- the building blocks of the model should all have names beginning with S4, like in other modeling files
- there shouldn't be code related to hyperparameters in the model, unless there is something very specific that requires it

2022-01-13 14:52 UTC, kamalkraj commented on docs/source/index.mdx
> +|             S4              |       ❌       |       ❌       |       ✅        |         ❌         |      ❌      |
done

2022-01-13 14:52 UTC, kamalkraj commented on docs/source/model_doc/s4.rst
> +..
done

2022-01-13 14:55 UTC, kamalkraj commented on src/transformers/models/s4/configuration_s4.py
> +    r"""
![Screenshot 2022-01-13 at 8 21 51 PM](https://user-images.githubusercontent.com/17096858/149353148-f91cbf2b-25b6-42ee-9f9c-c7b97d09ed0a.png)

ValueError: This script only converts rst files.

@sgugger

2022-01-13 15:06 UTC, kamalkraj commented on src/transformers/__init__.py
> +        ]
done

2022-01-13 15:06 UTC, kamalkraj commented on src/transformers/__init__.py
> +
done

2022-01-13 15:06 UTC, kamalkraj commented on src/transformers/__init__.py
> +
done.

2022-01-13 16:08 UTC, kamalkraj commented on src/transformers/models/s4/modeling_s4.py
> +# soft dependencies
https://github.com/huggingface/transformers/blob/master/src/transformers/models/tapas/modeling_tapas.py#L52-L60

Should I change to OSError like above ?
@sgugger

2022-01-19 13:19 UTC, kamalkraj commented on src/transformers/models/s4/modeling_s4.py
> +# soft dependencies
@Rocketknight1

2022-02-07 15:10 UTC, Rocketknight1 commented
Hi @kamalkraj ! We noticed there haven't been any commits here for a while - do you want us to find someone to take it over and resolve the issues from here? Either way, we appreciate everything you've done so far, so don't stress about it!

2022-02-14 07:16 UTC, kamalkraj commented
Hi @Rocketknight1,

Got a little busy with some work. Will work on this week

2022-02-16 11:20 UTC, kamalkraj commented
Sure @Rocketknight1. 
After the refractor also if you need any help from my side please ping here. 

Thanks

2022-03-20 15:02 UTC, closed without merging

2022-03-27 19:47 UTC, gaceladri commented
Hi, any news with this implementation? For some time I finished the @kamalkraj implementation, but I did not refactored the code. @Rocketknight1 was mentioning that the authors were planing to release a cleaner implementation. Do you have any update from the authors on it? also I think that it would be veeeeeery valuable if they also release his pre-trained model. Thanks!

2022-03-31 18:04 UTC, Rocketknight1 commented
@gaceladri This is something we're keeping an eye on. We were planning to do a port of the newer implementation, but we've seen [this paper ](https://twitter.com/ankgup2/status/1508807766093217804) recently. We believe this indicates that we're liable to see some significant updates to that architecture before the first foundation models arrive, and so we're backing away a little from porting S4 in its current form, at least until a significant foundation model arrives!

That said, we still think the architecture is likely to be very important, and we're seeing what we can do to get it to the point where those models exist. I know that's a little mysterious, but I don't want to over-promise anything just yet!

2022-03-31 18:16 UTC, gaceladri commented
@Rocketknight1 Thanks a lot for the answers and for the papers as well. I had not seen it! Thanks!!

2022-10-04 13:02 UTC, bratao commented
@Rocketknight1 do you think S4D is already mature enough to get into transformers? On https://github.com/HazyResearch/state-spaces/ it is already on version 3 and there is already a module with few dependencies https://github.com/HazyResearch/state-spaces/blob/main/src/models/s4/

I´m getting extraordinary results compared to regular transformers with small datasets