Spanish translation of the file training.mdx
huggingface/transformers pull request #16047
Opened 2022-03-10 14:54 UTC by yharyarias

I made the translation of the **training.mdx** file in collaboration to the transformers/doc/ documentation, there I created a new folder called source_es where I hosted my training.mdx document translated to Spanish, contributing to the Spanish-speaking community. 
[forum](https://github.com/huggingface/transformers/issues/15947)

Approved by @omarespejel
Documentation: @sgugger

2022-03-10 15:56 UTC, sgugger requested changes
I've just reviewed the beginning but there are a lot of differences with the English version of this doc in terms of syntax used. Could you keep the same syntax for tips, links to other classes in the doc etc?

2022-03-10 15:56 UTC, sgugger commented on docs/source_es/Hugging.mdx
> +>
This empty > is causing some issues.
```suggestion
```

2022-03-10 15:56 UTC, sgugger commented on docs/source_es/Hugging.mdx
> +- Aplicar fine-tuning a un modelo pre-entrenado con 🤗 Transformers [Trainer](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer).
```suggestion
- Aplicar fine-tuning a un modelo pre-entrenado con 🤗 Transformers [`Trainer`].
```
We shouldn't hardcode any link like this, as the version will never change.

2022-03-10 15:56 UTC, sgugger commented on docs/source_es/Hugging.mdx
> +🤗 Transformers proporciona una clase **[Trainer**](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.Trainer) optimizada para el entrenamiento de modelos 🤗 Transfo
```suggestion
🤗 Transformers proporciona una clase [`Trainer`] optimizada para el entrenamiento de modelos 🤗 Transformers, haciendo más fácil el inicio del entrenamiento sin necesidad de escribir manualmente su propio ciclo. La API del [`Trainer`] soporta una amplia gama de opciones de entrenamiento y características como el logging, el gradient accumulation y la mixed precision.
```

2022-03-10 15:56 UTC, sgugger commented on docs/source_es/Hugging.mdx
> +## Fine-tuning con [Trainer]
```suggestion
## Fine-tuning con `Trainer`
```

2022-03-10 15:56 UTC, sgugger commented on docs/source_es/Hugging.mdx
> +Note: Cada dataset debería ir acompañado de un [Dataset Card](https://huggingface.co/docs/datasets/v1.12.0/dataset_card.html) para promover el uso responsable, y alertar al usuario de cualquier posib
This is different from the English version.

2022-03-10 15:56 UTC, sgugger commented on docs/source_es/Hugging.mdx
> +> Verás una advertencia acerca de que algunos de los pesos pre-entrenados que no están siendo utilizados y que algunos pesos están siendo inicializados al azar. No te preocupes, esto es completamente
Use the <Tip> syntax as in the English version.

2022-03-10 15:56 UTC, sgugger commented on docs/source_es/Hugging.mdx
> +A continuación, crea una clase [TrainingArguments](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/trainer#transformers.TrainingArguments) que contenga todos los hiperparámetros que
```suggestion
A continuación, crea una clase [`TrainingArguments`] que contenga todos los hiperparámetros que puedes ajustar, así como los indicadores para activar las diferentes opciones de entrenamiento. Para este tutorial puedes empezar con los [hiperparámetros](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments) de entrenamiento por defecto, pero siéntete libre de experimentar con ellos para encontrar tu configuración óptima.
```

2022-03-10 16:06 UTC, yharyarias commented
@sgugger Of course, I will make the changes you indicate, leaving the syntax as per the original documentation. I have a question, I see that most of the conflicts are because of the links, do I leave all the links or remove them? I think they are important.

2022-03-10 16:13 UTC, sgugger commented
The links are automatically generated by our doc building tool. You should leave them as they are in the `training.mdx` file English version (for instance [`Trainer`]).

2022-03-10 23:01 UTC, yharyarias commented
I just uploaded the changes you suggested @sgugger I'll be watching for your review.

2022-03-11 01:08 UTC, sgugger approved these changes
Thanks a lot that's way better! You can remove the `Hugging.mdx` file from your PR.
I can't judge the translation itself but the format of the file is very good :-)

2022-03-11 01:56 UTC, omarespejel commented
Thanks! Will review the translation.

2022-03-11 08:57 UTC, LysandreJik approved these changes
This is great, thanks for working on it @yharyarias!

2022-03-11 16:57 UTC, omarespejel requested changes
Muy bueno @yharyarias! Thank you! I added some comments

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +Crea el learning rate por defecto desde el [`Trainer`]:
```suggestion
Crea el learning rate desde el [`Trainer`]:
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +Crea un `DataLoader` para sus datasets de entrenamiento y de prueba para poder iterar sobre batches de datos:
```suggestion
Crea un `DataLoader` para tus datasets de entrenamiento y de prueba para poder iterar sobre batches de datos:
```
Aquí por favor siempre usar la segunda persona del singular ya que lo hemos estado usando durante todo el doc

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +A continuación, haz un post-proceso manualmente al `tokenized_dataset` y así prepararlo para el entrenamiento.
```suggestion
A continuación, haremos un post-procesamiento manual al `tokenized_dataset` y así prepararlo para el entrenamiento.
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +El [`Trainer`] se encarga del ciclo de entrenamiento y permite aplicar fine-tuning a un modelo en una sola línea de código. Para los usuarios que prefieren escribir su propio ciclo de entrenamiento,
```suggestion
El [`Trainer`] se encarga del ciclo de entrenamiento y permite aplicar fine-tuning a un modelo en una sola línea de código. Para los usuarios que prefieren escribir su propio ciclo de entrenamiento, también puedes aplicar fine-tuning a un modelo de 🤗 Transformers en PyTorch nativo.
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +A continuación, compila y aplica fine-tuning a tu modelo con [`fit`](https://keras.io/api/models/model_training_apis/) como lo harías con cualquier otro modelo Keras:
```suggestion
A continuación, compila y aplica fine-tuning a tu modelo con [`fit`](https://keras.io/api/models/model_training_apis/) como lo harías con cualquier otro modelo de Keras:
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +A continuación, convierte los datasets0 tokenizados en datasets de TensorFlow con el método [`to_tf_dataset`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Dataset
```suggestion
A continuación, convierte los datasets tokenizados en datasets de TensorFlow con el método [`to_tf_dataset`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Dataset.to_tf_dataset). Especifica tus entradas en `columns` y tu etiqueta en `label_cols`:
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +[`Trainer`] utiliza [`DataCollatorWithPadding`] por defecto, por lo que no es necesario especificar explícitamente un intercalador de datos.
```suggestion
[`Trainer`] utiliza [`DataCollatorWithPadding`] por defecto por lo que no es necesario especificar explícitamente un intercalador de datos (data collator, en inglés).
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +Los modelos de 🤗 Transformers también permite realizar el entrenamiento en TensorFlow con la API de Keras. Sólo es necesario hacer algunos cambios antes de hacer fine-tuning.
```suggestion
Los modelos de 🤗 Transformers también permiten realizar el entrenamiento en TensorFlow con la API de Keras. Sólo es necesario hacer algunos cambios antes de hacer fine-tuning.
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +A continuación, aplique fine-tuning a su modelo llamando a [`~transformers.Trainer.train`]:
```suggestion
A continuación, aplique fine-tuning a su modelo llamando [`~transformers.Trainer.train`]:
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +Crea un objeto [`Trainer`] con su modelo, argumentos de entrenamiento, conjuntos de datos de entrenamiento y de prueba, y su función de evaluación:
```suggestion
Crea un objeto [`Trainer`] con tu modelo, argumentos de entrenamiento, conjuntos de datos de entrenamiento y de prueba, y tu función de evaluación:
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +Como ya sabes, necesitas un tokenizador para procesar el texto e incluir una estrategia para el padding y el truncamiento, manejando cualquier tamaño de una variable secuencial. Para procesar tu data
```suggestion
Como ya sabes, necesitas un tokenizador para procesar el texto e incluir una estrategia para el padding y el truncamiento para manejar cualquier longitud de secuencia variable. Para procesar tu dataset en un solo paso utiliza el método de 🤗 Datasets [`map`](https://huggingface.co/docs/datasets/process.html#map) para aplicar una función de preprocesamiento sobre todo el dataset:
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +🤗 Transformers proporciona una clase [`Trainer`] optimizada para el entrenamiento de modelos 🤗 Transformers, haciendo más fácil el inicio del entrenamiento sin necesidad de escribir manualmente su pr
```suggestion
🤗 Transformers proporciona una clase [`Trainer`] optimizada para el entrenamiento de modelos 🤗 Transformers, haciendo más fácil el inicio del entrenamiento sin necesidad de escribir manualmente tu propio ciclo. La API del [`Trainer`] soporta una amplia gama de opciones de entrenamiento y características como el logging, el gradient accumulation y el mixed precision.
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +Comienza cargando tu modelo y especifica el número de labels previstas. A partir del [Card Dataset](https://huggingface.co/datasets/yelp_review_full#data-fields) Yelp Review, que como ya sabemos tien
```suggestion
Comienza cargando tu modelo y especifica el número de labels previstas. A partir del [Card Dataset](https://huggingface.co/datasets/yelp_review_full#data-fields) de Yelp Review, que como ya sabemos tiene 5 labels:
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +A continuación, crea una clase [`TrainingArguments`] que contenga todos los hiperparámetros que puedes ajustar, así como los indicadores para activar las diferentes opciones de entrenamiento. Para es
```suggestion
A continuación, crea una clase [`TrainingArguments`] que contenga todos los hiperparámetros que puedes ajustar así como los indicadores para activar las diferentes opciones de entrenamiento. Para este tutorial puedes empezar con los [hiperparámetros](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments) de entrenamiento por defecto, pero siéntete libre de experimentar con ellos para encontrar tu configuración óptima.
```

2022-03-11 16:57 UTC, omarespejel commented on docs/source_es/training.mdx
> +No te preocupes, esto es completamente normal. El head/cabezal pre-entrenado del modelo BERT se descarta y se sustituye por un head de clasificación inicializado aleatoriamente. Puedes aplicar fine-t
```suggestion
No te preocupes, esto es completamente normal. El head/cabezal pre-entrenado del modelo BERT se descarta y se sustituye por un head de clasificación inicializado aleatoriamente. Puedes aplicar fine-tuning a este nuevo head del modelo en tu tarea de clasificación de secuencias haciendo transfer learning del modelo pre-entrenado.
```

2022-03-11 20:28 UTC, yharyarias commented
I made the last changes suggested by @omarespejel , I think everything is ok, this is my first contribution and there will be more to come, I have loved collaborating with open source. Thank you very much 🤗 @sgugger @LysandreJik  and @omarespejel

2022-03-13 22:01 UTC, omarespejel commented
Thanks, @yharyarias! There are still a couple of comments unresolved.

2022-03-14 02:27 UTC, omarespejel approved these changes

2022-03-14 02:29 UTC, omarespejel commented
IMO it is good to go :+1:

2022-03-14 14:12 UTC, merged

2022-03-14 14:13 UTC, sgugger commented
Thanks again for your PR. Merging this but we will wait a little bit more to serve a doc in Spanish mainly:
- to have a few more pages
- to automatically redirect to English doc when the page is not available in Spanish.

I will put a comment here when the page is live (hopefully in a week or two!)

2022-03-14 14:30 UTC, yharyarias commented
@sgugger Thank you, of course I will continue to contribute, I'm currently working on the translation of another document to add to source_es.