Translation from english to spanish of file pipeline_tutorial.mdx
huggingface/transformers pull request #16149
Opened 2022-03-14 18:58 UTC by FernandoLpz

Fixes #15947 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Message:
Add translation from english to spanish of file pipeline_tutorial.mdx

2022-03-14 19:05 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16149). All of your documentation changes will be reflected on that endpoint.

2022-03-15 01:14 UTC, omarespejel commented
Thanks @FernandoLpz! Will review it :)

2022-03-24 22:42 UTC, omarespejel requested changes
Thank you! Some nits

2022-03-24 22:42 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +Por ejemplo, clasifiquemos la emoción de un breve fragmento del famoso discurso de John F. Kennedy ["We choose to go to the Moon"](https://en.wikipedia.org/wiki/We_choose_to_go_to_the_Moon). Encuentr
```suggestion
Por ejemplo, clasifiquemos la emoción de un breve fragmento del famoso discurso de John F. Kennedy ["We choose to go to the Moon"](https://en.wikipedia.org/wiki/We_choose_to_go_to_the_Moon). Encuentra un modelo de [audio classification](https://huggingface.co/models?pipeline_tag=audio-classification) en Model Hub para el reconocimiento de emociones y cárgalo en el [`pipeline`]:
```

2022-03-25 19:29 UTC, FernandoLpz commented
Your welcome!

I just fix the typos. 

@omarespejel

2022-03-25 23:39 UTC, omarespejel requested changes
Thanks! Just some last nits.

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +Echa un vistazo a la documentación del [`pipeline`] para obtener una lista completa de tareas admitidas.
```suggestion
Echa un vistazo a la documentación de [`pipeline`] para obtener una lista completa de tareas admitidas.
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +2. Pasa tu texto de entrada a el [`pipeline`]:
```suggestion
2. Pasa tu texto de entrada al [`pipeline`]:
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +Cualquier parámetro adicional para tu tarea también se puede incluir en el [`pipeline`]. La tarea `text-generation` tiene un método [`~generation_utils.GenerationMixin.generate`] con varios parámetro
```suggestion
Cualquier parámetro adicional para tu tarea también se puede incluir en el [`pipeline`]. La tarea `text-generation` tiene un método [`~generation_utils.GenerationMixin.generate`] con varios parámetros para controlar la salida. Por ejemplo, si deseas generar más de una salida, defínelo en el parámetro `num_return_sequences`:
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +El [`pipeline`] acepta cualquier modelo de [Model Hub](https://huggingface.co/models). Hay etiquetas en Model Hub que te permiten filtrar por modelo que te gustaría utilizar para tu tarea. Una vez qu
```suggestion
El [`pipeline`] acepta cualquier modelo del [Model Hub](https://huggingface.co/models). Hay etiquetas en el Model Hub que te permiten filtrar por el modelo que te gustaría utilizar para tu tarea. Una vez que hayas elegido un modelo apropiado, cárgalo con la clase `AutoModelFor` y [`AutoTokenizer'] correspondientes. Por ejemplo, carga la clase [`AutoModelForCausalLM`] para una tarea de modelado de lenguaje causal:
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +Crea un [`pipeline`] para tu tarea y específica el modelo y el tokenizador que has cargado:
```suggestion
Crea un [`pipeline`] para tu tarea y específica el modelo y el tokenizador que cargaste:
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +La flexibilidad del [`pipeline`] significa que también se puede extender a tareas de audio.
```suggestion
La flexibilidad de [`pipeline`] significa que también se puede extender a tareas de audio.
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +Especifica tu tarea de visión y pasa tu imagen al clasificador. La imagen puede ser un enlace o una ruta local a la imagen. Por ejemplo, ¿qué especie de gato se muestra a continuación?
```suggestion
Específica tu tarea de visión y pasa tu imagen al clasificador. La imagen puede ser un enlace o una ruta local a la imagen. Por ejemplo, ¿qué especie de gato se muestra a continuación?
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +Pasa el archivo de audio a el [`pipeline`]:
```suggestion
Pasa el archivo de audio al [`pipeline`]:
```

2022-03-25 23:39 UTC, omarespejel commented on docs/source_es/pipeline_tutorial.mdx
> +Por ejemplo, clasifiquemos la emoción de un breve fragmento del famoso discurso de John F. Kennedy ["We choose to go to the Moon"](https://en.wikipedia.org/wiki/We_choose_to_go_to_the_Moon). Encuentr
```suggestion
Por ejemplo, clasifiquemos la emoción de un breve fragmento del famoso discurso de John F. Kennedy ["We choose to go to the Moon"](https://en.wikipedia.org/wiki/We_choose_to_go_to_the_Moon). Encuentra un modelo de [audio classification](https://huggingface.co/models?pipeline_tag=audio-classification) para reconocimiento de emociones en el Model Hub y cárgalo en el [`pipeline`]:
```

2022-03-25 23:43 UTC, omarespejel commented
Hi @sgugger! It seems to me that the failed checks are due to something else and not this doc. WDYT?

2022-03-28 14:30 UTC, sgugger approved these changes
All tests are failing because of the rename of the branch from master to main, but the code is not adapted. A rebase would fix them all, but it's not necessary since we know this PR only touches doc files.

Thanks a lot for working on this!

2022-03-28 14:31 UTC, merged