Added spanish translation of quicktour.mdx
huggingface/transformers pull request #16158
Opened 2022-03-14 22:36 UTC by Duedme

# Translation of quicktour.mdx into Spanish

I made the translation of quicktour.mdx into Spanish (fixes #15947). The document is located in the transformers/docs/source_es folder.

@omarespejel 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?

2022-03-14 22:42 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16158). All of your documentation changes will be reflected on that endpoint.

2022-03-15 01:10 UTC, omarespejel requested changes
Thanks! Just some nits changes.

2022-03-15 01:10 UTC, omarespejel commented on docs/source_es/quicktour.mdx
> +El [`pipeline`] también puede iterar sobre dataset entero. Comienza instalando la biblioteca [🤗 Datasets](https://huggingface.co/docs/datasets/):
```suggestion
El [`pipeline`] también puede iterar sobre un dataset entero. Comienza instalando la biblioteca [🤗 Datasets](https://huggingface.co/docs/datasets/):
```

2022-03-15 01:10 UTC, omarespejel commented on docs/source_es/quicktour.mdx
> +Para más de una oración, entrega una lista de frases al [`pipeline`], que devolverá una lista de diccionarios:
```suggestion
Para más de un enunciado entrega una lista de frases al [`pipeline`] que devolverá una lista de diccionarios:
```

2022-03-15 01:10 UTC, omarespejel commented on docs/source_es/quicktour.mdx
> +* Clasificación de audios: asigna una etiqueta dado un segmento de audio.
```suggestion
* Clasificación de audios: asigna una etiqueta a un segmento de audio.
```

2022-03-15 04:52 UTC, omarespejel approved these changes

2022-03-15 04:53 UTC, omarespejel commented
Thanks, @Duedme! LGTM!

2022-03-15 12:07 UTC, sgugger approved these changes
Thanks for working on this!
Merging but we won't build the Spanish documentation just yet, we're waiting:
- to have a few more pages in Spanish
- to have the frontend default to the English version of pages when there is no Spanish translation yet (not implemented yet).

I will put a comment here once this page is live (hopefully in one or two weeks!)

2022-03-15 12:07 UTC, merged