Translate installation.mdx to Spanish
huggingface/transformers pull request #16229
Opened 2022-03-17 15:33 UTC by lilianabs

# What does this PR do?

Adds the translation of [installation.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/installation.mdx) to Spanish.

Fixes # [15947](https://github.com/huggingface/transformers/issues/15947) (issue)

## Before submitting
- [✓] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [✓] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?

2022-03-17 15:56 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16229). All of your documentation changes will be reflected on that endpoint.

2022-03-18 23:45 UTC, omarespejel commented
Thanks @lilianabs! 🤗

2022-03-27 01:55 UTC, omarespejel requested changes

2022-03-27 01:55 UTC, omarespejel commented on docs/source_es/installation.mdx
> +Puedes añadir  [🤗 Datasets](https://huggingface.co/docs/datasets/) al flujo de entrenamiento offline declarando la variable de ambiente  `HF_DATASETS_OFFLINE=1`.
```suggestion
Puedes añadir [🤗 Datasets](https://huggingface.co/docs/datasets/) al flujo de entrenamiento offline declarando la variable de ambiente  `HF_DATASETS_OFFLINE=1`.
```

2022-03-28 16:47 UTC, lilianabs commented
@omarespejel all of the changes have been added, thank you! :)

2022-03-31 04:14 UTC, omarespejel approved these changes

2022-03-31 04:16 UTC, omarespejel commented
Thank you @lilianabs! 🤗.  @sgugger LGTM 👍

2022-03-31 11:44 UTC, sgugger approved these changes
Thanks a lot for your PR!

2022-03-31 11:44 UTC, merged