Spanish translation of the file preprocessing.mdx
huggingface/transformers pull request #16299
Opened 2022-03-21 14:23 UTC by yharyarias

Hi, I made the translation of the **preprocessing.mdx** file to add it to the Spanish documentation (transformers/docs/source_es/). 
I will be waiting for any correction, thanks.
@omarespejel @LysandreJik @sgugger

2022-03-21 14:35 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16299). All of your documentation changes will be reflected on that endpoint.

2022-03-21 15:11 UTC, sgugger commented
All good to me from the syntax point of view. Be careful though, as you PR files include the `training.mdx` so we can't know if there are small changes in it.

2022-03-21 17:30 UTC, yharyarias commented
You're right, it was a mistake, It's just the preprocessing file

2022-04-21 16:22 UTC, omarespejel commented
Hi @yharyarias! Could you please review what Sylvain[ commented above](https://github.com/huggingface/transformers/pull/16299#issuecomment-1074021882)? We are almost done.

2022-05-17 02:46 UTC, omarespejel requested changes
Thank you for your PR! It seems that your translation includes text that is not in the original English version (lines 491 onwards). I will eliminate them for now. Will also eliminate the training.mdx translation in this PR.

2022-05-17 02:46 UTC, omarespejel commented on docs/source_es/preprocessing.mdx
> +Por ejemplo, carga el dataset [LJ Speech](https://huggingface.co/datasets/lj_speech) que tiene un sampling rate de 22050kHz. Para utilizar el modelo Wav2Vec2 con este dataset, reduce el sampling rate
```suggestion
Por ejemplo, carga el dataset [LJ Speech](https://huggingface.co/datasets/lj_speech) que tiene una tasa de muestreo de 22050kHz. Para utilizar el modelo Wav2Vec2 con este dataset, reduce la tasa de muestreo a 16kHz:
```

2022-05-17 02:46 UTC, omarespejel commented on docs/source_es/preprocessing.mdx
> +1. Usa el método 🤗 Datasets' [`cast_column`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Dataset.cast_column) para reducir el sampling rate a 16kHz:
```suggestion
1. Usa el método 🤗 Datasets' [`cast_column`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Dataset.cast_column) para reducir la tasa de muestreo a 16kHz:
```

2022-05-17 02:46 UTC, omarespejel commented on docs/source_es/preprocessing.mdx
> +* `array` es la señal de voz cargada - y potencialmente resampled - como un array 1D.
```suggestion
* `array` es la señal de voz cargada - y potencialmente remuestreada - como un array 1D.
```

2022-05-17 02:46 UTC, omarespejel commented on docs/source_es/preprocessing.mdx
> +### Tokenize
```suggestion
### Tokenizar
```

2022-05-25 23:41 UTC, omarespejel approved these changes

2022-05-25 23:43 UTC, omarespejel commented
Muchas gracias @yharyarias for the PR! 🤗 Please let me know if you wish to translate another one. 

@sgugger LGTM :)

2022-05-26 11:28 UTC, sgugger approved these changes
Thanks for adding this new translation!

2022-05-26 11:28 UTC, merged