Added spanish translation of autoclass_tutorial.mdx
huggingface/transformers pull request #16348
Opened 2022-03-23 00:25 UTC by Duedme

# Translation of autoclass_tutorial.mdx into spanish

I made the translation of autoclass_tutorial.mdx into Spanish (fixes https://github.com/huggingface/transformers/issues/15947). The document is located in the transformers/docs/source_es folder.

@omarespejel 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?

2022-03-23 00:38 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16348). All of your documentation changes will be reflected on that endpoint.

2022-03-23 20:48 UTC, omarespejel requested changes
Thank you! Some nits.

2022-03-23 20:48 UTC, omarespejel commented on docs/source_es/autoclass_tutorial.mdx
> +* Carga un modelo preentrenado.
```suggestion
* Cargar un modelo preentrenado.
```

2022-03-25 23:45 UTC, omarespejel approved these changes

2022-03-31 04:38 UTC, omarespejel commented
Thank you @Duedme! 🤗

@sgugger LGTM 👍

2022-03-31 11:46 UTC, sgugger commented
There are a lot of conflicts in your branch, for just one added file. I think the easiest to fix this is to copy your file, create a new fresh branch from the main branch and open a new PR, as I can't review the diff here :-)

2022-04-01 17:13 UTC, closed without merging