Avoid accessing .dataset of a DataLoader in Trainer
huggingface/transformers pull request #16451
Opened 2022-03-28 14:19 UTC by sanderland

# What does this PR do?

* Respects get_train_dataloader and such, rather than going back and looking at .train_dataset or requiring attributes in the dataloader to be accessible directly.
   * This allows for overriding it by any object which implements the methods required by a DataLoader (`__len__` and `__iter__`) without additional requirements.
   * The original motivation was to train on a multi-task dataloader which defers to multiple dataloaders. 

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. 
     - Discussed in #16388
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

2022-03-28 14:33 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16451). All of your documentation changes will be reflected on that endpoint.

2022-03-29 10:22 UTC, sanderland commented
@[sgugger](https://github.com/sgugger) this should be ready for review.
You were right that there were a couple of more places to change, and the logic is quite inconsistent in places. I've tried to be on the defensive side in covering cases:

* dataloader.dataset can exist or not, and have a length or not
* dataloader always has a len, but it can raise an exception in fairly common cases

This implementation works for my particular case, giving the same output in training+evaluation as before, but without the really painful workarounds.

I had a look at tests and they look complicated, so I will add some after getting confirmation that this is ok otherwise.

2022-03-29 14:30 UTC, sgugger requested changes
Thanks for your PR! It tries to do too much at the same time however. There is no reason to change the signature of the function `get_train_dataloader` so it should be left as is IMO. Even if it's a change we would like to implement, it should be done on it own separate PR.

Then there is a lot of code that could be refactored using the `has_length` function (and improving it a tiny bit).

Lastly, this PR breaks the current logging of number of examples, this should be fixed before we can merge it.

2022-03-29 14:30 UTC, sgugger commented on src/transformers/trainer.py
> +        train_dataset = train_dataset if train_dataset is not None else self.train_dataset
This has no reason to be added, we can rely on `self.train_dataset`.

2022-03-29 14:30 UTC, sgugger commented on src/transformers/trainer.py
> +        if not has_length(train_dataset):
Let's make it explicit that we return `None` here when `self.train_dataset is None`.

```suggestion
        if self.train_dataset is None or not has_length(self.train_dataset):
```

2022-03-29 14:30 UTC, sgugger commented on src/transformers/trainer.py
> +            if is_datasets_available() and isinstance(train_dataset, datasets.Dataset):
All thos changes should be reverted.

2022-03-29 14:30 UTC, sgugger commented on src/transformers/trainer.py
> -        )
This should be kept and adapted, we need to log the number of examples.

2022-03-29 14:30 UTC, sgugger commented on src/transformers/trainer.py
> -        num_examples = self.num_examples(dataloader)
Same comment as above.

2022-03-29 16:01 UTC, sanderland commented on src/transformers/trainer.py
>          logger.info(f"  Num examples = {num_examples}")
num_examples was moved up inside the if statements that deal with the len/steps/size cases

2022-03-29 16:16 UTC, sanderland commented on src/transformers/trainer.py
> -            # see __init__. max_steps is set when the dataset has no __len__
Note that this comment was incorrect, it would still be -1 which causes strange outputs. Have change it to make it explicit that this should be set.

2022-03-29 17:10 UTC, sgugger approved these changes
Thanks for adapting, I added a few comments on the tests.

2022-03-29 17:10 UTC, sgugger commented on tests/trainer/test_trainer.py
> +        dataloaders = [super(CustomDataloaderTrainer, self).get_eval_dataloader(eval_dataset) for _ in range(2)]
```suggestion
        dataloaders = [super().get_eval_dataloader(eval_dataset) for _ in range(2)]
```

2022-03-29 17:18 UTC, sanderland commented on tests/trainer/test_trainer.py
> +        dataloaders = [super(CustomDataloaderTrainer, self).get_train_dataloader() for _ in range(2)]
This is not correct, as I took over an hour to figure out recently.
```
class A:
  def f(self):
   return 42

class B(A):
  def f(self):
   return [super().f() for _ in range(10)]

print(A().f())
print(B().f())
```
TypeError: super(type, obj): obj must be an instance or subtype of type

 something something super() magic and the list comprehension not being the right scope for it, so you need to explicitly call super(B,self) like python 2

2022-03-29 17:36 UTC, sgugger commented on tests/trainer/test_trainer.py
> +        dataloaders = [super(CustomDataloaderTrainer, self).get_train_dataloader() for _ in range(2)]
Remove the list comprehension then and just call the super method twice:
```
 dataloaders = [super().get_train_dataloader(), super().get_train_dataloader()]
```

2022-03-29 19:00 UTC, sgugger commented
Thanks for implementing all the tweaks!

2022-03-29 19:00 UTC, merged