Add inputs vector to calculate metric method
huggingface/transformers pull request #16461
Opened 2022-03-28 19:40 UTC by lmvasque

# What does this PR do?
This is a PR suggestion for including the inputs as well for metrics calculation. Simplification metrics such as SARI not only use the predictions and references but also the inputs for the score calculation. 

The actual implementation for production will need changes into compute_metrics() as well, but this gets into further dependencies across the code. I'm using this code with custom implementations of compute_metrics, into my new metric file. 

Supports #15966

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@sgugger

2022-03-28 19:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16461). All of your documentation changes will be reflected on that endpoint.

2022-03-28 20:41 UTC, sgugger commented
Unfortunately, we can't change the `EvalPredictions` namedtuple structure like this as it would be a massive breaking change. Users would suddenly have to unpack it with three objects instead of two, so every `compute_metrics` function out there in the wild would suddenly fail.

2022-03-31 18:12 UTC, sgugger commented
Ok, spent a bit of time on this and to enable an `EvalPredictions` that work with/without inputs, the class should be replaced by the following one:
```py
class EvalPrediction:
    """
    Evaluation output (always contains labels), to be used to compute metrics.

    Parameters:
        predictions (`np.ndarray`): Predictions of the model.
        label_ids (`np.ndarray`): Targets to be matched.
        inputs (`np.ndarray`, *optional*)
    """
    def __init__(
        self,
        predictions: Union[np.ndarray, Tuple[np.ndarray]],
        label_ids: Union[np.ndarray, Tuple[np.ndarray]],
        inputs: Optional[Union[np.ndarray, Tuple[np.ndarray]]] = None,
    ):
        self.predictions = predictions
        self.label_ids = label_ids
        self.inputs = inputs
    
    def __iter__(self):
        if self.inputs is not None:
            return iter((self.predictions, self.label_ids, self.inputs))
        else:
            return iter((self.predictions, self.label_ids))
    
    def __getitem__(self, idx):
        if idx < 0 or idx > 2:
            raise IndexError("tuple index out of range")
        if idx == 2 and self.inputs is None:
            raise IndexError("tuple index out of range")
        if idx == 0:
            return self.predictions
        elif idx ==1:
            return self.label_ids
        elif idx == 2:
            return self.inputs
```

Then we should add a flag so the user can choose whether or not they want the inputs included for metrics or not (default `False` so that there is no change). With those two things, we can enable your use case while maintaining backward compatibility.

Can you include them in your PR?

2022-04-01 12:03 UTC, lmvasque commented
Hi @sgugger ,

Thanks for adding this change. I've tested this code with the summarization examples from pytorch and I'm afraid this change will break other people's code. The problem is that since the inputs are passed in the trainer by default (based on my PR):

**trainer.py**
```
self.compute_metrics(EvalPrediction(inputs=all_inputs, predictions=all_preds, label_ids=all_labels))
```

The inputs in `EvalPrediction` will never be `None`, and then, it will fail when returning the predictions in `compute_metrics`:

**run_summarization.py**
```
def compute_metrics(eval_preds):
    preds, labels = eval_preds
```

```
  File "./transformers/examples/pytorch/summarization/run_summarization.py", line 575, in compute_metrics
    preds, labels = eval_preds
ValueError: too many values to unpack (expected 2)
```

You can see in the debugger that all 3 (inputs, preds and labels) are coming:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/6901031/161257829-5c146d32-2154-4151-bc7a-ae75b5470267.png">

In my case, I have my own implementation for compute_metrics, however, for other users it will fail by default. When you suggest the flag, where is it located? In the `class Trainer` and then an `if` before each call of `EvalPrediction`? 

This is my testing case:

```
./transformers/examples/pytorch/summarization/run_summarization.py
--model_name_or_path
t5-small
--do_train
--do_eval
--train_file test.json
--validation_file test.json
--source_prefix
"summarize: "
--output_dir
/tmp/tst-summarization
--overwrite_output_dir
--per_device_train_batch_size=4
--per_device_eval_batch_size=4
--predict_with_generate
```

**test.json**
```
{"text": "I'm sitting here in a boring room. It's just another rainy Sunday afternoon. I'm wasting my time I got nothing to do. I'm hanging around I'm waiting for you. But nothing ever happens. And I wonder", "summary": "I'm sitting in a room where I'm waiting for something to happen"}
{"text": "I see trees so green, red roses too. I see them bloom for me and you. And I think to myself what a wonderful world. I see skies so blue and clouds so white. The bright blessed day, the dark sacred night. And I think to myself what a wonderful world.", "summary": "I'm a gardener and I'm a big fan of flowers."}
{"text": "Christmas time is here. Happiness and cheer. Fun for all that children call. Their favorite time of the year. Snowflakes in the air. Carols everywhere. Olden times and ancient rhymes. Of love and dreams to share", "summary": "It's that time of year again."}
```

Thanks,

Laura

2022-04-01 12:52 UTC, sgugger commented
> The problem is that since the inputs are passed in the trainer by default (based on my PR):

As I said above, this needs to be controlled by a flag (for instance `include_inputs_for_metrics`) in `TrainingArguments` which would be `False` by default to avoid any breaking change.

2022-04-01 14:55 UTC, lmvasque commented
Thanks for the clarification, that sounds better. I've submitted an additional commit in the PR. Is the first time I update a PR, let me know if I've missed something.

2022-04-04 14:04 UTC, sgugger requested changes
Thanks for adding the flag. It should be in the `TrainingArguments` class however, not the `Trainer` class itself. Also, the inputs should only be gathered when the flag is set to `True`, otherwise users that do not need it might get OOM errors.

2022-04-04 14:04 UTC, sgugger commented on src/transformers/trainer.py
> +
```suggestion
```

2022-04-04 14:24 UTC, sgugger commented on src/transformers/trainer.py
> +            inputs_decode = inputs['input_ids']
Set `None` here if the flag is False

2022-04-04 14:25 UTC, sgugger commented
> should I add `if self.include_inputs_for_metrics:` Everywhere in the code? I can't think of a more elegant way :)

You should make sure that the inputs are left as None like the labels/losses by only setting some inputs when the flag is False. I've left a comment to show you where.

> And for the new changes, is it ok just another commit in the pull request just like I did the last time? Just checking, so I don't do a mess :P

That's completely ok, we will squash everything when merging.

2022-04-04 19:05 UTC, lmvasque commented
Changes done, let me know any further feedback :)

2022-04-04 19:27 UTC, sgugger reviewed
Thanks! Left some last comments and we should be good to merge.
Also remember to run `make style` on your branch once you're done to apply the code-formatting tools :-)

2022-04-04 19:27 UTC, sgugger commented on src/transformers/trainer.py
> +            args.include_inputs_for_metrics = False
The `TrainingArguments` should not be touched by the `Trainer`, I don't think this is necessary in any case.
```suggestion
```

2022-04-04 19:27 UTC, sgugger commented on src/transformers/trainer.py
> +
We'll need the comma back and no new line here.

2022-04-04 19:27 UTC, sgugger commented on src/transformers/trainer.py
> +                                                              label_ids=all_labels))
```suggestion
            if args.include_inputs_for_metrics:
                metrics = self.compute_metrics(EvalPrediction(predictions=all_preds,
                                                              label_ids=all_labels, inputs=all_inputs))
```
Needs to be last I think.

2022-04-04 19:27 UTC, sgugger commented on src/transformers/training_args.py
> +        include_inputs_for_metrics (bool, optional):
```suggestion
        include_inputs_for_metrics (`bool`, *optional*, defaults to `False`):
```

2022-04-05 21:13 UTC, lmvasque commented
I've added the requested changes. Also, I've run `make fixup`, so there are also some automatic indentation changes as well.

2022-04-06 19:05 UTC, sgugger approved these changes
Thanks a lot for all your work on this! It's all good to me apart from the changes at the start of the trainer file.

2022-04-06 23:08 UTC, lmvasque commented on src/transformers/trainer.py
> +from .dependency_versions_check import dep_version_check
Yes, I'm sorry. I tried to install manually some of the dependencies, but it was still failing some parts. I've done the changes to bring it back to its original state, adding your also the changes from your empty lines.

2022-04-07 11:37 UTC, sgugger commented
Thanks! There is one last issue with a docstring badly formatted. Could you run `make style` on your branch?

2022-04-07 11:55 UTC, lmvasque commented
Sure, no problem. I'm having issues with the dependencies to run `make style`, could you please let me know what's the full command for installing all the suite? 
`pip install .[quality] `

This is my log:
```
% make style
black examples tests src utils
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install black[jupyter]``
All done! ✨ 🍰 ✨
1519 files left unchanged.
isort examples tests src utils
WARNING: Unable to parse file examples due to [Errno 21] Is a directory: './transformers/examples'
WARNING: Unable to parse file tests due to [Errno 21] Is a directory: './transformers/tests'
WARNING: Unable to parse file src due to [Errno 21] Is a directory: './transformers/src'
WARNING: Unable to parse file utils due to [Errno 21] Is a directory: './transformers/utils'
/Library/Developer/CommandLineTools/usr/bin/make autogenerate_code
running deps_table_update
updating src/transformers/dependency_versions_table.py
/Library/Developer/CommandLineTools/usr/bin/make extra_style_checks
python utils/custom_init_isort.py
doc-builder style src/transformers docs/source --max_len 119 --path_to_docs docs/source
make[1]: doc-builder: No such file or directory
make[1]: *** [extra_style_checks] Error 1
make: *** [style] Error 2
```

2022-04-07 12:03 UTC, sgugger commented
It looks like your branch is not up to par with the main branch for the setup. Can you manually install `pip install hf-doc-builder`? It should be in the quality extras but maybe you don't have it because it was added recently-ish.

2022-04-07 12:11 UTC, lmvasque commented
Now is working :) Thanks for that one. I've committed the updated file. 

```
% make style
black examples tests src utils
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install black[jupyter]``
All done! ✨ 🍰 ✨
1519 files left unchanged.
isort examples tests src utils
/Library/Developer/CommandLineTools/usr/bin/make autogenerate_code
running deps_table_update
updating src/transformers/dependency_versions_table.py
/Library/Developer/CommandLineTools/usr/bin/make extra_style_checks
python utils/custom_init_isort.py
doc-builder style src/transformers docs/source --max_len 119 --path_to_docs docs/source
Overwriting content of src/transformers/training_args.py.
Cleaned 1 files
```

2022-04-07 14:02 UTC, sgugger commented
Yes, it's all good now. Thanks again for your contribution!

2022-04-07 14:02 UTC, merged

2022-04-07 15:05 UTC, lmvasque commented
Awesome! :) Thanks for leading this effort, good job :D