Documentation: Spanish translation of fast_tokenizers.mdx
huggingface/transformers pull request #16882
Opened 2022-04-21 19:32 UTC by jloayza10

# What does this PR do?

Fixes #15947
Translation to Spanish of fast_tokenizers.mdx

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? #15947

2022-05-03 18:39 UTC, omarespejel commented
Thank you @jloayza10! Could you please add `fast_tokenizers` to [`transformers/docs/source/es/_toctree.yml`](https://github.com/huggingface/transformers/blob/main/docs/source/es/_toctree.yml)? As a reference, you can use the [new Translation](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md) guide (section "✍️ Start translating"). This would allow the tests to pass.

2022-05-03 23:13 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16882). All of your documentation changes will be reflected on that endpoint.

2022-05-03 23:23 UTC, jloayza10 commented
Hi @omarespejel , I added `fast_tokenizers` to the _toctree.yml file.
There is still a `check_code_quality` check that is failing, are there further modifications on my part to perform to address this or is this ok?

2022-05-04 03:36 UTC, omarespejel requested changes

2022-05-04 03:36 UTC, omarespejel commented on docs/source/es/fast_tokenizers.mdx
> +cargados muy simplemente a 🤗 Transformers.
```suggestion
cargados de forma muy sencilla en los 🤗 Transformers.
```

2022-05-04 03:36 UTC, omarespejel commented on docs/source/es/fast_tokenizers.mdx
> +Antes de entrar en los detalles, podemos crear un tokenizador dummy en unas cuantas líneas:
```suggestion
Antes de entrar en detalles, comencemos creando un tokenizador dummy en unas cuantas líneas:
```

2022-05-04 03:36 UTC, omarespejel commented on docs/source/es/fast_tokenizers.mdx
> +Ahora tenemos un tokenizador entrenado con los archivos (files en el código) que fueron definidos. Lo podemos seguir utilizando en ese entorno de ejecución (runtime en inglés), o se lo puede guardar
```suggestion
Ahora tenemos un tokenizador entrenado en los archivos que definimos. Lo podemos seguir utilizando en ese entorno de ejecución (runtime en inglés), o puedes guardarlo
```

2022-05-04 03:36 UTC, omarespejel commented on docs/source/es/fast_tokenizers.mdx
> +Veamos como utilizar este objeto tokenizador en la librería 🤗 Transformers. La clase
```suggestion
Veamos cómo utilizar este objeto tokenizador en la biblioteca 🤗 Transformers. La clase
```

2022-05-04 03:36 UTC, omarespejel commented on docs/source/es/fast_tokenizers.mdx
> +[`PreTrainedTokenizerFast`] permite una instanciación simple, al aceptar el objeto
```suggestion
[`PreTrainedTokenizerFast`] permite una instanciación fácil, al aceptar el objeto
```

2022-05-12 02:14 UTC, omarespejel approved these changes

2022-05-12 03:25 UTC, merged

2022-05-12 03:26 UTC, omarespejel commented
Thank you very much @jloayza10! This was great. Please let me know if you would like to translate another file 🤗