Spanish translation of the file philosophy.mdx #15947
huggingface/transformers pull request #16922
Opened 2022-04-25 09:36 UTC by jkmg

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2022-04-25 09:37 UTC, jkmg commented
Spanish translation of the file philosophy.mdx #15947

2022-05-03 18:26 UTC, omarespejel commented
Thank you @jkmg! Could you please add `philosophy` to `../transformers/docs/source/es/_toctree.yml`. According to the [new Translation](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md) guide (section "✍️ Start translating")? This would allow the tests to pass.

2022-05-04 03:11 UTC, omarespejel requested changes

2022-05-04 03:11 UTC, omarespejel commented on docs/source/es/philosophy.mdx
> +  - Una forma sencilla/coherente de añadir nuevos tokens al vocabulario e incrustraciones ("embeddings") para optimización.
```suggestion
  - Una forma sencilla/coherente de añadir nuevos tokens al vocabulario e incrustraciones (embeddings, en inglés) para optimización.
```

2022-05-09 21:06 UTC, jkmg reviewed
Is it now OK?

2022-05-09 21:13 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_16922). All of your documentation changes will be reflected on that endpoint.

2022-05-12 01:40 UTC, omarespejel approved these changes

2022-05-12 01:47 UTC, merged