Guide to create custom models in Spanish
huggingface/transformers pull request #17158
Opened 2022-05-10 13:18 UTC by ignacioct

# What does this PR do?

Fixes #15947

## Before submitting
- [X ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

@omarespejel said he will review, otherwise anyone 😁.

2022-05-10 13:34 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_17158). All of your documentation changes will be reflected on that endpoint.

2022-05-12 22:27 UTC, omarespejel requested changes

2022-05-12 22:27 UTC, omarespejel commented on docs/source/es/create_a_model.mdx
> +Si no estas buscando ninguna personalización en específico, usa el método `from_pretrained` para cargar los parámetros del extractor de características por defecto del modelo.
```suggestion
Si no estás buscando ninguna personalización en específico, usa el método `from_pretrained` para cargar los parámetros del extractor de características por defecto del modelo.
```

2022-05-12 22:27 UTC, omarespejel commented on docs/source/es/create_a_model.mdx
> +Con dos clases base (la configuración y el modelo) y una clase de preprocesamiento adicional (*tokenizer*, extractor de características o procesador), puedes crear cualquier de los modelos compatible
```suggestion
Con dos clases base (la configuración y el modelo) y una clase de preprocesamiento adicional (*tokenizer*, extractor de características o procesador), puedes crear cualquiera de los modelos compatibles con 🤗 Transformers. Cada una de estas clases son configurares, permitiéndote usar sus atributos específicos. Puedes crear un modelo para entrenarlo de una forma fácil, o modificar un modelo preentrenado disponible para especializarlo.
```

2022-05-13 06:06 UTC, ignacioct commented
Thanks for the suggestions, I've committed all the changes you proposed.

2022-05-13 20:11 UTC, omarespejel commented
@ignacioct muchas gracias por tu PR! 🤗 Vamos a hacerle merge. If there is any other doc that you would like to translate you can tell me. 

@sgugger LGTM 🔥

2022-05-13 20:19 UTC, sgugger approved these changes

2022-05-13 20:19 UTC, merged