Added es version of bertology.mdx doc
huggingface/transformers pull request #17255
Opened 2022-05-14 19:09 UTC by jQuinRivero

Fixes #15947

Added spanish version of language_modeling.mdx documentation file.

@omarespejel @sgugger

2022-05-14 19:27 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_17255). All of your documentation changes will be reflected on that endpoint.

2022-05-16 19:12 UTC, omarespejel commented on docs/source/es/bertology.mdx
> +Para ayudarte a entender y usar estas features, hemos añadido un script específico de ejemplo: [bertology.py](https://github.com/huggingface/transformers/tree/main/examples/research_projects/bertolog
```suggestion
Para ayudarte a entender y usar estas features, hemos añadido un script específico de ejemplo: [bertology.py](https://github.com/huggingface/transformers/tree/main/examples/research_projects/bertology/run_bertology.py) mientras extraes información y cortas un modelo pre-entrenado en
```

2022-05-16 19:24 UTC, omarespejel requested changes

2022-05-17 00:29 UTC, jQuinRivero commented on docs/source/es/bertology.mdx
> +De manera de asistir al desarrollo de este nuevo campo, hemos incluido algunas features adicionales en los modelos BERT/GPT/GPT-2 para
Already commited this. I don't know why it's not working properly.

2022-05-25 21:55 UTC, omarespejel approved these changes

2022-05-25 22:08 UTC, omarespejel commented
Muchas gracias @jQuinRivero for the PR! 🤗 Please let me know if you wish to translate another one. 

@sgugger LGTM :)

2022-05-25 22:46 UTC, sgugger approved these changes
Thanks for your contribution!

2022-05-25 22:46 UTC, merged