Added it documentation for fast_tokenizers #17459
huggingface/transformers pull request #17622
Opened 2022-06-09 08:42 UTC by andreafailla

# What does this PR do?

Addresses #17459 with italian translation of fast_tokenizers.mdx

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

2022-06-09 08:55 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_17622). All of your documentation changes will be reflected on that endpoint.

2022-06-13 06:49 UTC, mfumanelli commented
Hi @andreafailla, I'm just taking a look at your PR. Can I ask you to change a little of thing? In the toctree please remove the quotation marks here "Usare i tokenizzatori di 🤗 Tokenizers". Everything else looks perfect to me!

2022-07-25 01:23 UTC, omarespejel requested changes
Hi @andreafailla! This is the change @mfumanelli is suggesting. I believe it could fix the error when merging into the main :)

2022-07-25 01:23 UTC, omarespejel commented on docs/source/it/_toctree.yml
> +    title: "Usare i tokenizzatori di 🤗 Tokenizers"
```suggestion
    title: Usare i tokenizzatori di 🤗 Tokenizers
```

2022-08-02 15:02 UTC, closed without merging