Add Spanish translation of custom_models.mdx
huggingface/transformers pull request #17807
Opened 2022-06-21 20:13 UTC by donelianc

# What does this PR do?

Add the Spanish translation for `custom_models.mdx` as part of the #15947 issue. 
Changes include the Spanish version of the original document and the updated `_toctree.yml` file.

Tried to follow the [guideline](https://github.com/huggingface/transformers/blob/26a6a426087582c48593f8be980603951a7bcddd/CONTRIBUTING.md#start-contributing-pull-requests) to generate the Markdown files and check them before submitting this PR but the command `doc-builder build transformers docs/source/ --build_dir ~/tmp/test-build` fails since the `_toctree.yml` file is no longer in `./docs/source/` (but in `./docs/source/en/`).

First contribution to the 🤗 Transformers project!

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests) Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Task assignment [here](https://github.com/huggingface/transformers/issues/15947#issuecomment-1161854258).
- [x] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] ~~Did you write any new necessary tests?~~

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

Tagging @omarespejel, @osanseviero, or @sgugger to review or assign reviewers :)

2022-06-21 20:25 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_17807). All of your documentation changes will be reflected on that endpoint.

2022-07-22 15:30 UTC, osanseviero commented
@omarespejel could you take a look at this PR Please?

2022-07-25 18:06 UTC, omarespejel requested changes

2022-07-25 18:06 UTC, omarespejel commented on docs/source/es/custom_models.mdx
> +Ilustraremos todo esto en un modelo ResNet, envolviendo la clase ResNet del [biblioteca timm](https://github.com/rwightman/pytorch-image-models/tree/master/timm) en un [`PreTrainedModel`].
```suggestion
Ilustraremos todo esto con un modelo ResNet, envolviendo la clase ResNet de la [biblioteca timm](https://github.com/rwightman/pytorch-image-models/tree/master/timm) en un [`PreTrainedModel`].
```

2022-07-25 18:06 UTC, omarespejel commented on docs/source/es/custom_models.mdx
> +configuraciones nos darán los diferentes tipos de ResNet que son posibles. Luego simplemente almacenamos esos argumentos,
```suggestion
configuraciones nos darán los diferentes tipos de ResNet que son posibles. Luego simplemente almacenamos esos argumentos 
```

2022-07-25 18:06 UTC, omarespejel commented on docs/source/es/custom_models.mdx
> +También puedes usar cualquier otro método de la clase [`PretrainedConfig`], como [`~PretrainedConfig.push_to_hub`] para cargar
```suggestion
También puedes usar cualquier otro método de la clase [`PretrainedConfig`], como [`~PretrainedConfig.push_to_hub`], para cargar 
```

2022-07-25 18:18 UTC, omarespejel requested changes

2022-07-25 18:18 UTC, omarespejel commented on docs/source/es/custom_models.mdx
> +en cualquier clase del modelo automático debe coincidir con `config_class ` de esos modelos.
```suggestion
en cualquier clase del modelo automático debe coincidir con el `config_class` de esos modelos.
```

2022-07-25 18:18 UTC, omarespejel commented on docs/source/es/custom_models.mdx
> +También se recomienda encarecidamente pasar un _hash_ de confirmación como una "revisión" para asegurarte que el autor
```suggestion
También se recomienda encarecidamente pasar un _hash_ de confirmación como una "revisión" para asegurarte de que el autor 
```

2022-07-26 03:27 UTC, omarespejel commented
Hola @donelianc! Thank you very much for your translation. Sorry for the delay in replying; it won't happen again.

I made some small comments to be applied.

Thank you!

2022-07-26 12:26 UTC, donelianc commented
@omarespejel I committed the suggested changes :) If you don't mind, can you assign me the translation of [run_scripts.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/run_scripts.mdx)? I'll be happy to help with one more doc.

2022-07-26 14:10 UTC, sgugger approved these changes
Thanks a lot for your contribution!

2022-07-26 14:10 UTC, merged