[WIP] Add custom config to quicktour
huggingface/transformers pull request #18115
Opened 2022-07-12 22:28 UTC by stevhliu

This PR updates the quicktour to include a section for building custom configurations that creates a randomly initialized model. Other changes include:

- Added a brief section for `Trainer`.
- Switched back to the code switcher (instead of code blocks) for some code examples which showed essentially the same thing and didn't have drastically different text associated with them. I think this will reduce the amount of scrolling and improve user experience.
- Minor maintenance work to improve conciseness.

2022-07-12 22:40 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_18115). All of your documentation changes will be reflected on that endpoint.

2022-07-15 14:34 UTC, sgugger requested changes
There are way too many changes for what was supposed to be a simple addition: show how to create a model with a custom config. Why reverting to the old syntax for framewrok specific content (which is not supported anymore)?

2022-07-15 14:34 UTC, sgugger commented on docs/source/en/quicktour.mdx
> -* Automatic speech recognition (ASR): transcribe audio data into text.
I think it was important to have this in the quick tour instead of sending the user to an API doc page (which they will very likely not go on).

2022-07-15 14:34 UTC, sgugger commented on docs/source/en/quicktour.mdx
> -</frameworkcontent>
The code won't work if neither PyTorch or TensorFlow is installed, so this needs to stay in some way.

2022-07-15 14:34 UTC, sgugger commented on docs/source/en/quicktour.mdx
> +For sentiment analysis, the [`pipeline`] downloads and caches a default [pretrained model](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english) and tokenizer. Now you can use the `
This gives the impression that this behavior is specific to the sentiment analysis task, when it's general. So the previous phrasing was better in that way.

2022-07-15 14:34 UTC, sgugger commented on docs/source/en/quicktour.mdx
> +The [`pipeline`] can also iterate over an entire dataset for a task like automatic speech recognition:
Again, this gives the impression that this is specific to automatic speech recognition when it's general.

2022-07-15 14:34 UTC, sgugger commented on docs/source/en/quicktour.mdx
> +Now load the pretrained model and it's associated tokenizer with [`AutoModelForSequenceClassification`] and [`AutoTokenizer`]:
Why remove the framework specific content?

2022-07-15 14:34 UTC, sgugger commented on docs/source/en/quicktour.mdx
> +## Trainer
I don't think adding this section here helps. For one it's PyTorch only (and not delimited as such) and it's making the quick tour really long. I'd remove it.

2022-07-15 18:49 UTC, stevhliu commented
Oops, sorry about all the changes! How about we keep the custom config section here and rollback all the other changes, which we can discuss in a separate issue?

2022-07-18 07:47 UTC, sgugger commented
Yes please!

2022-07-19 06:10 UTC, sgugger commented on docs/source/en/quicktour.mdx
> +>>> my_config = DistilBertConfig(n_heads=12)
We haven't used any specific model class up until know, only the auto classes. Maybe it's best to use auto classes here too?

2022-07-20 06:15 UTC, sgugger approved these changes

2022-07-20 17:23 UTC, merged