Added Type hints for XLM TF
huggingface/transformers pull request #19333
Opened 2022-10-05 07:52 UTC by IMvision12

Based on Issue #16059

I have added type hints for Tensorflow XLM model.

@Rocketknight1 Could you kindly check if this is fine?

2022-10-05 08:11 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_19333). All of your documentation changes will be reflected on that endpoint.

2022-10-06 17:47 UTC, Rocketknight1 requested changes
Hi, thanks for the PR! It looks mostly good, but there are a couple of issues:

1. Be careful not to overwrite the default value for `training`! Also, `training` cannot be `None`, so it shouldn't be `Optional`. Instead, those lines should be `training: bool = False`.
2. Be careful with some of the types! `output_attentions` and `output_hidden_states` should be `Optional[bool]`, while `start_positions` and `end_positions` are label tensors for QA models, so they should be `Optional[Union[np.ndarray, tf.Tensor]]`

Once those are fixed, though, this looks ready to be merged, so thank you!

2022-10-06 18:22 UTC, IMvision12 commented
@Rocketknight1 Thanks for the feedback, I have updated the files.

2022-10-07 12:32 UTC, Rocketknight1 approved these changes
LGTM! I also just realized the cache actually has a weird type too, but I can set that here and then merge once the tests pass. Thank you!

2022-10-07 12:32 UTC, Rocketknight1 commented on src/transformers/models/xlm/modeling_tf_xlm.py
> +        cache: Optional[Union[np.ndarray, tf.Tensor]] = None,
```suggestion
        cache: Optional[Dict[str, tf.Tensor]] = None,
```

2022-10-07 12:32 UTC, Rocketknight1 commented on src/transformers/models/xlm/modeling_tf_xlm.py
> +        cache: Optional[Union[np.ndarray, tf.Tensor]] = None,
```suggestion
        cache: Optional[Dict[str, tf.Tensor]] = None,
```

2022-10-07 12:32 UTC, Rocketknight1 commented on src/transformers/models/xlm/modeling_tf_xlm.py
> +        cache: Optional[Union[np.ndarray, tf.Tensor]] = None,
```suggestion
        cache: Optional[Dict[str, tf.Tensor]] = None,
```

2022-10-07 12:32 UTC, Rocketknight1 commented on src/transformers/models/xlm/modeling_tf_xlm.py
> +        cache: Optional[Union[np.ndarray, tf.Tensor]] = None,
```suggestion
        cache: Optional[Dict[str, tf.Tensor]] = None,
```

2022-10-07 12:32 UTC, Rocketknight1 commented on src/transformers/models/xlm/modeling_tf_xlm.py
> +        cache: Optional[Union[np.ndarray, tf.Tensor]] = None,
```suggestion
        cache: Optional[Dict[str, tf.Tensor]] = None,
```

2022-10-07 12:44 UTC, merged