Change the import of kenlm from github to pypi
huggingface/transformers pull request #19770
Opened 2022-10-20 12:02 UTC by raghavanone

# What does this PR do?

Fixes #19686 

## Who can review?

@patrickvonplaten

2022-10-20 13:18 UTC, sgugger reviewed
Thanks for your PR. The main interest of having the package on PiPy is that we can put it in our setup and not have to write a specific command to install it. You should add it to the extras for audio.

2022-10-20 13:28 UTC, raghavanone commented
> Thanks for your PR. The main interest of having the package on PiPy is that we can put it in our setup and not have to write a specific command to install it. You should add it to the extras for audio.

Done

2022-10-20 14:53 UTC, sgugger commented on setup.py
> +    "kenlm==0.1",
Why the specific pin, we want to test updated versions.

2022-10-20 14:53 UTC, sgugger commented on docker/transformers-all-latest-gpu/Dockerfile
> +RUN python3 -m pip install --no-cache-dir "kenlm==0.1"
Should be removed

2022-10-20 14:53 UTC, sgugger commented on .circleci/create_circleci_config.py
> +        "pip install kenlm==0.1",
All of those can be removed now.

2022-10-21 15:48 UTC, sgugger approved these changes
Yay, way better, thanks! @ydshieh could you also have a look?

2022-10-21 17:08 UTC, ydshieh commented
I think we still have 2 files to be clean up ?

- docker/transformers-pytorch-gpu/Dockerfile
- docker/transformers-doc-builder/Dockerfile

2022-10-21 17:11 UTC, ydshieh requested changes
See the comment, but we are close to merge. Thank you!

2022-10-21 17:11 UTC, ydshieh commented on docker/transformers-all-latest-gpu/Dockerfile
> -RUN python3 -m pip install --no-cache-dir git+https://github.com/facebookresearch/detectron2.git pytesseract https://github.com/kpu/kenlm/archive/master.zip
We should not remove the whole line, just the part `https://github.com/kpu/kenlm/archive/master.zip`

2022-10-24 08:25 UTC, ydshieh commented on docker/transformers-all-latest-gpu/Dockerfile
> -RUN python3 -m pip install --no-cache-dir git+https://github.com/facebookresearch/detectron2.git pytesseract https://github.com/kpu/kenlm/archive/master.zip
Hi @raghavanone , once this comment is addressed, we are good to merge I think :-)

2022-10-26 15:05 UTC, ydshieh approved these changes
Very nice @raghavanone ! Thank you for taking care of this `kenlm` dependency 💯

2022-10-26 15:06 UTC, merged