Use PyAV instead of Decord in examples
huggingface/transformers pull request #21572
Opened 2023-02-10 19:06 UTC by amyeroberts

# What does this PR do?

Replaces decord with pyav as the library to decode video files in examples. This resolves an issue where the CUDA crashes if `decode` has been imported. 

Note: decord is still being used in the video pipelines. cc @nateraw 

Fixes #21085

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

2023-02-10 19:26 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_21572). All of your documentation changes will be reflected on that endpoint.

2023-02-27 16:52 UTC, amyeroberts commented on docker/transformers-all-latest-gpu/Dockerfile
> +RUN python3 -m pip install --no-cache-dir decord av==9.2.0
Not removing decord yet as it's used in some other areas e.g. [video classification pipeline](https://github.com/huggingface/transformers/blob/92dfceb12446404fe547b1271ecaf86d2498546b/src/transformers/pipelines/video_classification.py#L12)

2023-02-27 16:52 UTC, amyeroberts commented on src/transformers/models/videomae/image_processing_videomae.py
> +
```suggestion
```

2023-02-28 14:40 UTC, amyeroberts commented on src/transformers/models/timesformer/modeling_timesformer.py
> +        [1, 1569, 768]
This lost me a lot of time 😅 

* These doc tests weren't being tested as they weren't in `utils/documentation_tests.txt` 
* Testing on the `huggingface/transformers-all-latest-gpu:latest` image on `main` I get the same `last_hidden_state` shape -- `[1, 1569, 768]` -- as with the pyav change.

2023-02-28 16:09 UTC, sgugger approved these changes
Thanks for all your work on this!

2023-03-01 23:20 UTC, nateraw requested changes
Nice! Thanks so much for working on this. One small change I'm requesting here WRT docstrings.

2023-03-01 23:20 UTC, nateraw commented on src/transformers/models/git/modeling_git.py
> +        ...         start_index (int): the starting frame.
`indices` in fn signature here not same as docstring (`start_index` / `end_index`).

2023-03-01 23:20 UTC, nateraw commented on src/transformers/models/git/modeling_git.py
> +        ...         result (np.ndarray): np array of decoded frames.
A shape here for reference would be nice :) `(T, C, H, W)` right?

2023-03-01 23:20 UTC, nateraw commented on src/transformers/models/git/modeling_git.py
> +        ...         start_index (int): the starting frame.
Applies to all other copies of this snippet below too (won't comment on each but wanted to make sure I noted this).

2023-03-02 10:57 UTC, amyeroberts commented
Thanks for the review @nateraw! I've updated the docstrings with your suggestions :)

2023-03-02 11:49 UTC, nateraw approved these changes

2023-03-02 12:30 UTC, merged