🌐 [i18n-KO] Translated `custom_models.mdx` to Korean
huggingface/transformers pull request #22534
Opened 2023-04-03 15:15 UTC by HanNayeoniee

# What does this PR do?

Translated the `custom_models.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Team PseudoLab, may you please review this PR?
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

May you please review this PR?
@sgugger, @ArthurZucker, @eunseojo

2023-04-03 15:34 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22534). All of your documentation changes will be reflected on that endpoint.

2023-04-05 07:52 UTC, HusseinMansourMohd reviewed
review 1

2023-04-05 07:52 UTC, HusseinMansourMohd reviewed
review pass

2023-04-09 00:19 UTC, sim-so commented on docs/source/ko/custom_models.mdx
> +🤗 Transformers 라이브러리에 없는 경우 것도 누구나 사용할 수 있도록 커뮤니티에 공유(의존하는 코드 포함)하는 방법을 배울 수 있습니다.
Some words seem to be missing in "라이브러리에 없는 경우 것도".

2023-04-09 08:54 UTC, wonhyeongseo commented on docs/source/ko/custom_models.mdx
> +🤗 Transformers 라이브러리에 없는 경우 것도 누구나 사용할 수 있도록 커뮤니티에 공유(의존하는 코드 포함)하는 방법을 배울 수 있습니다.
> 🤗 Transformers 라이브러리에 없는 경우에도 누구나 사용할 수 있도록 (의존성과 함께) 커뮤니티에 공유하는 방법을 배울 수 있습니다.

로 바꿔보시면 어떨까요?

2023-04-09 12:08 UTC, 0525hhgus reviewed
Thank you for the good translation!
Please check the review below 😄

2023-04-09 12:08 UTC, 0525hhgus commented on docs/source/ko/custom_models.mdx
> +주피터 노트북에서는 다음 코드를 실행해 확인할 수 있습니다:
If you translate `or from a notebook` into `주피터 노트북의 경우에는`, I think it will be a little concise.
The meaning is similar, so please just check ✏️

2023-04-10 14:36 UTC, HanNayeoniee commented on docs/source/ko/custom_models.mdx
> +🤗 Transformers 라이브러리에 없는 경우 것도 누구나 사용할 수 있도록 커뮤니티에 공유(의존하는 코드 포함)하는 방법을 배울 수 있습니다.
의견 주신대로 수정했습니다 🙂

2023-04-10 14:49 UTC, HanNayeoniee commented on docs/source/ko/custom_models.mdx
> +주피터 노트북에서는 다음 코드를 실행해 확인할 수 있습니다:
주피터 노트북의 경우에는 다음과 같습니다:

2023-04-10 14:50 UTC, HanNayeoniee commented on docs/source/ko/custom_models.mdx
> +주피터 노트북에서는 다음 코드를 실행해 확인할 수 있습니다:
`주피터 노트북의 경우에는 다음과 같습니다:` 로 조금 더 간결하게 수정했습니다.

2023-04-10 15:17 UTC, HanNayeoniee commented
> I think we should discuss whether to translate `configuration` to 구성. Since the configuration is the name of the class, I think it will be misunderstood when translated into Korean to understand that it is a class.
> 
> `configuration`이 class의 이름이기 때문에 한국어로 번역 시 class임을 이해하지 못하도록 오해할 것 같습니다.

저도 놓친 부분이네요. 클래스를 의미하는 부분은 `configuration`로, 클래스를 의미하지 않는 부분(본문에서 config라고 적힌 경우)은 `구성`으로 번역하는걸 검토해보겠습니다.

2023-04-13 06:03 UTC, KIHOON71 commented on docs/source/ko/custom_models.mdx
> +이전에 언급했듯이 이 예제에서는 단순하게 하기 위해 모델의 느슨한 래퍼만 작성할 것입니다.
한국어로 "래퍼"라는 표현이 직관적이지 않은 것 같아서 "래퍼(wrapper)" 처럼 명확하게 원어를 병기하는 게 괜찮을 것 같은데 어떻게 생각하시나요??

2023-04-13 08:01 UTC, sim-so requested changes
고생 많으셨습니다!
리뷰하고 몇 가지 의견을 붙여 보냅니다. :smile:

2023-04-15 07:39 UTC, HanNayeoniee commented on docs/source/ko/custom_models.mdx
> +이전에 언급했듯이 이 예제에서는 단순하게 하기 위해 모델의 느슨한 래퍼만 작성할 것입니다.
`느슨한 래퍼(loose wrapper)` 로 병기하겠습니다!

2023-04-15 07:48 UTC, HanNayeoniee commented on docs/source/ko/custom_models.mdx
> +그런 다음 몇 가지 유효성을 확인한 후 해당 인자를 저장합니다.
구글시트에 정의한 glossary에 따라 '인수'로 통일했습니다.

2023-04-16 11:55 UTC, HanNayeoniee commented
May you please review this PR?
@sgugger, @ArthurZucker, @eunseojo

2023-04-17 11:39 UTC, sgugger approved these changes
Thanks for your contribution!

2023-04-17 11:39 UTC, merged