[i18n-KO] fix: docs: ko: sagemaker anchors and  `_toctree.yml`
huggingface/transformers pull request #22549
Opened 2023-04-04 03:56 UTC by jungnerd

Co-authered-by: Wonhyeong Seo
<wonhseo@kakao.com>

# What does this PR do?
I fixed the anchors and `_toctree.yml`

Part of #20179 (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

Please review this PR: @sgugger

2023-04-04 05:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22549). All of your documentation changes will be reflected on that endpoint.

2023-04-04 06:32 UTC, wonhyeongseo commented
![Screenshot_20230404_151825_Chrome.jpg](https://user-images.githubusercontent.com/29195190/229707009-e1fca054-e464-4b98-af53-809e4c0778db.jpg)

We are getting a 500 error (probably due to spacing issues in `_toctree.yml`). Please do not merge until the problem is resolved.

2023-04-04 13:08 UTC, sgugger reviewed
I think the error in the doc preview comes from bad yaml syntax in the modified toctree.

2023-04-04 13:14 UTC, wonhyeongseo commented
> I think the error in the doc preview comes from bad yaml syntax in the modified toctree.

Yes, I agree @sgugger . There were 2 section titles in one section. Editing it like so fixed the issue for me locally.
![image](https://user-images.githubusercontent.com/29195190/229802966-94eabdb3-0fff-4453-a2ca-caf188dee1f9.png)

2023-04-04 13:22 UTC, wonhyeongseo requested changes
We should modify L13-19 to the following:
```yml
- sections:
  - sections:
    - local: sagemaker
      title: Amazon SageMaker에서 학습 실행하기
    - local: in_translation
      title: (번역 중)
    title: 일반 사용법
  - local: in_translation
    title: (번역 중)
  title: How-to 가이드
```
I understand the previous comment about how removing a single dash would resolve the issue might be misleading. Sorry for any confusion I may have caused.
Please let me know if you have further questions, @jungnerd !

2023-04-04 13:22 UTC, wonhyeongseo commented on docs/source/ko/_toctree.yml
>    title: How-to 가이드
We should modify these lines to:
```yml
- sections:
  - sections:
    - local: sagemaker
      title: Amazon SageMaker에서 학습 실행하기
    - local: in_translation
      title: (번역 중)
    title: 일반 사용법
  - local: in_translation
    title: (번역 중)
  title: How-to 가이드
```
I understand the previous comment about how removing a single dash would resolve the issue might be misleading. Sorry for any confusion I may have caused.
Please let me know if you have further questions, @jungnerd !

2023-04-04 13:36 UTC, wonhyeongseo commented
Also when squashing the commits, please fix the typo on `Co-auth*e*red-by` to `Co-auth*o*red-by` and add arrow brackets (`<>`) to the email.
You may also use Github Desktop to ease the process. Thank you for your PR @jungnerd and feel free to ask me any questions.

2023-04-04 15:07 UTC, wonhyeongseo commented
Great work, @jungnerd !
You solved the issue; now please squash the commits into one. You can use
- chat-gpt for the commit message and 
- Github Desktop to add co-authors
if you want. :raised_hands: Good night!

2023-04-12 06:40 UTC, wonhyeongseo commented
@jungnerd we can remove the `_toctree.yml` change completely as we updated it in the upstream `ko: complete toctree` commit. After that and rebasing, this PR should be good to go! Let's try to do this on Thursday.

2023-04-16 12:26 UTC, jungnerd commented
May you please review this PR?
@sgugger, @ArthurZucker, @eunseojo

2023-04-17 11:41 UTC, sgugger approved these changes
Thanks for the fixes!

2023-04-17 11:41 UTC, merged