[WIP] 🌐 [i18n-KO] Translated `tasks/translation.mdx` to Korean
huggingface/transformers pull request #22678
Opened 2023-04-09 08:40 UTC by wonhyeongseo

# What does this PR do?

Translated the `tasks/translation.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Team PseudoLab, may you please review this PR?

@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-09 08:48 UTC, wonhyeongseo commented on docs/source/ko/tasks/translation.mdx
> +이제 [`DataCollatorForSeq2Seq`]를 사용하여 예제 배치를 생성합니다. 데이터세트의 최대 길이로 전부를 padding하는 대신, 데이터 정렬 중 해당 배치의 최대 길이로 문장을 *동적으로 padding*하는 것이 더 효율적입니다.
'해당 배치'를 '각 배치'로 하는 것이 더 자연스러울까요?

2023-04-09 08:49 UTC, wonhyeongseo commented on docs/source/ko/tasks/translation.mdx
> +원한다면 `pipeline`의 결과를 직접 복제할 수도 있습니다.
결과를 복제한다는 의미가 무엇인지 잘 모르겠어요 😓 혹시 설명해주실 수 있을까요?

2023-04-09 08:53 UTC, gabrielwithappy commented on docs/source/ko/tasks/translation.mdx
> +이제 [`DataCollatorForSeq2Seq`]를 사용하여 예제 배치를 생성합니다. 데이터세트의 최대 길이로 전부를 padding하는 대신, 데이터 정렬 중 해당 배치의 최대 길이로 문장을 *동적으로 padding*하는 것이 더 효율적입니다.
각 배치가 좀 더 장확할 것 같습니다. 배치별로 패딩길이를 다르게 할 수 있을이 나타날 것 같습니다

2023-04-09 08:55 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22678). All of your documentation changes will be reflected on that endpoint.

2023-04-09 10:06 UTC, wonhyeongseo commented on docs/source/ko/tasks/translation.mdx
> +이제 [`DataCollatorForSeq2Seq`]를 사용하여 예제 배치를 생성합니다. 데이터세트의 최대 길이로 전부를 padding하는 대신, 데이터 정렬 중 해당 배치의 최대 길이로 문장을 *동적으로 padding*하는 것이 더 효율적입니다.
좋은 리뷰 정말 감사합니다! 반영되었어요 😆

2023-04-13 05:57 UTC, KIHOON71 commented on docs/source/ko/tasks/translation.mdx
> +훈련 중에 메트릭을 포함하면 모델의 성능을 평가하는 데 도움이 됩니다. 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index) 라이브러리로 평가 방법(evaluation method)을 빠르게 가져올 수 있습니다. 현재 태스크에 적합한 SacreBLEU 메트릭을 가져오세요. (메트릭을 가져오고 계산하는 방법에
metric은 한국어로 '평가 지표' 나 '성능 지표' 등으로 대체할 수 있다고 생각하는데 괜찮을까요??

2023-04-13 06:59 UTC, sim-so requested changes
항상 멋진 번역 감사합니다!
Draft 상태로 해두셨는데요, 리뷰를 해도 괜찮다면 계속 진행하겠습니다. 😄

2023-04-17 13:47 UTC, wonhyeongseo commented on docs/source/ko/tasks/translation.mdx
> +번역은 한 언어로 된 시퀀스를 다른 언어로 변환합니다. 받은 입력과 반환되는 출력으로 문제를 생각하는 강력한 프레임워크인 sequence-to-sequence 문제로 재구성할 수 있는 태스크 중 대표적인 예시가 번역이나 요약입니다. 번역 시스템은 일반적으로 다른 언어로 된 텍스트 간의 번역에 사용되지만, 음성 간의 통역이나 텍스트-음성 또는 음성-텍스트와
감사합니다! 반영되었습니다.

2023-04-17 13:58 UTC, wonhyeongseo commented on docs/source/ko/tasks/translation.mdx
> +훈련 중에 메트릭을 포함하면 모델의 성능을 평가하는 데 도움이 됩니다. 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index) 라이브러리로 평가 방법(evaluation method)을 빠르게 가져올 수 있습니다. 현재 태스크에 적합한 SacreBLEU 메트릭을 가져오세요. (메트릭을 가져오고 계산하는 방법에
메트릭으로 번역된 부분이 많기 때문에 부득이하게 놔둔뒤, 나중에 한번에 바꿔보는 것을 고려해볼게요. 리뷰 감사합니다!

2023-04-17 14:31 UTC, closed without merging

2023-04-17 14:46 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22678). All of your documentation changes will be reflected on that endpoint.

2023-04-21 03:40 UTC, wonhyeongseo commented
Closed in favor of https://github.com/huggingface/transformers/pull/22805