🌐 [i18n-KO] translate `create_a_model` doc to Korean
huggingface/transformers pull request #22754
Opened 2023-04-14 01:27 UTC by gabrielwithappy

# What does this PR do?

Translated the `create_a_model.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
This is a work in progress.
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-16 18:01 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22754). All of your documentation changes will be reflected on that endpoint.

2023-04-22 03:24 UTC, gabrielwithappy commented
Team PseudoLab, may you please review this PR?
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-22 12:02 UTC, sim-so requested changes
번역 작업이 점점 빨라지고 있네요!
몇 가지 수정 제안을 드립니다 😄

2023-04-22 13:35 UTC, 0525hhgus commented on docs/source/ko/create_a_model.mdx
> +- 텍스트에 대한 느리고 빠른 토큰화기를 만듭니다.
중의적으로 해석될 수 있는 부분이네요! 🤔 
원문에서도 `slow and fast tokenizer`와 같이 비슷한 맥락으로 되어 있어서 
- `느리고 빠른 토크나이저` (기존 유지)
- 또는. `느리거나 빠른 토크나이저` (번역에서 조금 차이가 존재)
로 번역되면 개인적으로 괜찮을 것 같습니다 👍

2023-04-22 14:18 UTC, 0525hhgus commented on docs/source/ko/create_a_model.mdx
> +사용자 지정이 필요하지 않은 경우 `from_pretrained` 메서드를 사용하여 모델의 기본 특징 추출기 매개 변수를 불러 오면 됩니다.
`메서드` → `메소드` 추가합니다!

2023-04-23 00:15 UTC, sim-so commented on docs/source/ko/create_a_model.mdx
> +사용자 지정이 필요하지 않은 경우 `from_pretrained` 메서드를 사용하여 모델의 기본 특징 추출기 매개 변수를 불러 오면 됩니다.
`메서드` -> `메소드`도 수정 제안 사항에 추가했습니다!

2023-04-23 16:03 UTC, gabrielwithappy commented
리뷰 해주신 내용 확인했습니다. 
확인해보고 다시 업데이트 할께요~

2023-04-24 13:07 UTC, gabrielwithappy commented on docs/source/ko/create_a_model.mdx
> +- 텍스트에 대한 느리고 빠른 토큰화기를 만듭니다.
Checked :-)

2023-04-24 13:09 UTC, gabrielwithappy commented on docs/source/ko/create_a_model.mdx
> +[configuration](main_classes/configuration)은 모델의 특정 속성을 나타냅니다. 각 모델 구성에는 서로 다른 속성이 있습니다. 예를 들어, 모든 NLP 모델에는 hidden_size, num_attention_heads, num_hidden_layers 및 vocab_size 속성이 공통으로 있습니다. 이러한 속성은 모델을
Checked :-)

2023-04-24 13:12 UTC, gabrielwithappy commented on docs/source/ko/create_a_model.mdx
> +다음 단계는 [model](main_classes/models)을 만드는 것입니다. 느슨하게 아키텍처라고도 불리는 model은 각 계층이 수행하는 동작과 발생하는 작업을 정의합니다. configuration의 `num_hidden_layers`와 같은 속성은 아키텍처를 정의하는 데 사용됩니다. 모든 모델은 기본 클래스 [`PreTrainedModel`]과
초기에는 model로 표현하는 것이 ***Model이라는 허깅페이스 구조를 좀 더 잘 이해할 수 있는 방식이라고 생각했는데요. 모델은 영어로 바로 Model이 연결되기 때문에 굳이 영어를 유지하지 않아도 될 것 같아서 변경했습니다. :-)

2023-04-24 13:16 UTC, gabrielwithappy commented on docs/source/ko/create_a_model.mdx
> +사용자 지정을 원하지 않는 경우 `from_pretrained` 메서드를 사용하여 모델의 기본 이미지 프로세서 매개 변수를 불러오면 됩니다.
checked

2023-04-24 13:17 UTC, gabrielwithappy commented on docs/source/ko/create_a_model.mdx
> +사용자 지정 이미지 프로세서(image processor)를 생성하려면 [`ViTImageProcessor`] 파라미터를 수정합니다:
아 맞습니다! 좋은 지적 감사합니다.

2023-04-24 13:55 UTC, sgugger commented
There are still a couple of comments left to address @gabrielwithappy

2023-04-24 14:12 UTC, wonhyeongseo commented on docs/source/ko/create_a_model.mdx
> +- [`PreTrainedTokenizerFast`]: Rust 기반 [🤗 Tokenizer](https://huggingface.co/docs/tokenizers/python/latest/) 라이브러리로 만들어진 토큰화 프로그램입니다. 이 토큰화 유형은 Rust 구현으로 인해 특히 일괄 토큰화 중에 훨씬 빠릅니다. 빠른 토큰화 도구는 토큰을 원래 단어나
파이썬*으로* 구현된 토크나이저

2023-04-24 14:33 UTC, gabrielwithappy commented
@sgugger oh, I just found! I will chech and change to draft before ready-to-review 
:-)

2023-04-24 16:45 UTC, gabrielwithappy commented
@sgugger, @ArthurZucker, @eunseojo May you please review this PR?
I checked anchors of titles in the doc and fixed all reviews 
BRs.

2023-04-24 17:02 UTC, sgugger approved these changes
Thanks!

2023-04-24 17:02 UTC, merged