[i18n-KO] Translated tasks/summarization.mdx to Korean
huggingface/transformers pull request #22783
Opened 2023-04-15 10:51 UTC by sim-so

# What does this PR do?

Translated the `tasks/summarization.mdx` file of the documentation to Korean.
Thank you in advance for your review!

Part of #20179 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

This is a work on progress.
Could you review this PR when I finish this work?
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-17 16:27 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22783). All of your documentation changes will be reflected on that endpoint.

2023-04-17 16:34 UTC, wonhyeongseo requested changes
Your writing ✍️ is on-par with the best 👌  I can read through your work with a cadence that resembles birds flying through the sky. Keep up the good work, @sim-so !

2023-04-17 16:34 UTC, wonhyeongseo commented on docs/source/ko/tasks/summarization.mdx
> +요약은 문서나 기사에서 중요한 정보를 모두 포함하여 짧은 버전으로 만드는 일입니다.
```suggestion
요약은 문서나 기사에서 중요한 정보를 모두 포함하되 짧게 만드는 일입니다.
```

2023-04-17 16:34 UTC, wonhyeongseo commented on docs/source/ko/tasks/summarization.mdx
> +- 생성(Abstractive) 요약: 가장 관련성 높은 정보를 포착하는 새로운 텍스트를 생성합니다.
```suggestion
- 생성(Abstractive) 요약: 가장 관련성 높은 정보를 포착해내는 새로운 텍스트를 생성합니다.
```
아주 좋아요!

2023-04-17 16:34 UTC, wonhyeongseo commented on docs/source/ko/tasks/summarization.mdx
> +(평가 지표를 불러오고 계산하는 대한 자세한 내용은 🤗 Evaluate [둘러보기](https://huggingface.co/docs/evaluate/a_quick_tour)를 참조하세요.)
```suggestion
(평가 지표를 불러오고 계산하는 데에 대한 자세한 내용은 🤗 Evaluate [둘러보기](https://huggingface.co/docs/evaluate/a_quick_tour)를 참조하세요.)
```

2023-04-17 16:34 UTC, wonhyeongseo commented on docs/source/ko/tasks/summarization.mdx
> +이제 모델 학습을 시작할 준비가 되었습니다! [`AutoModelForSeq2SeqLM`]로 T5를 로드하세요:
```suggestion
이제 모델 학습을 시작할 준비가 되었습니다! [`AutoModelForSeq2SeqLM`]로 T5를 가져오세요:
```

2023-04-17 16:34 UTC, wonhyeongseo commented on docs/source/ko/tasks/summarization.mdx
> +Keras로 모델 파인튜닝을 하는 것이 익숙하지 않다면, [here](../training#train-a-tensorflow-model-with-keras)에서 기본적인 튜토리얼을 확인하세요!
```suggestion
Keras로 모델 파인튜닝을 하는 것이 익숙하지 않다면, [여기](../training#train-a-tensorflow-model-with-keras)에서 기본적인 튜토리얼을 확인하세요!
```

2023-04-18 02:46 UTC, sim-so reviewed
I always learn from your review! Thank you!
I changed the lines as you suggested. 😄 @wonhyeongseo

2023-04-18 02:46 UTC, sim-so commented on docs/source/ko/tasks/summarization.mdx
> +TensorFlow에서 모델을 파인튜닝하려면, 먼저 옵티마이저, 학습률 스케줄 그리고 몇 가지 학습 하이퍼파라미터를 설정하세요:
저도 고민하다가 시간이 좀 걸릴 것 같아서 이대로 진행했습니다.
용어사전에 추가해두고, 생각나면 바꾸는 걸로 하겠습니다!

2023-04-18 10:22 UTC, gabrielwithappy commented on docs/source/ko/tasks/summarization.mdx
> +(평가 지표를 불러오고 계산하는 데에 대한 자세한 내용은 🤗 Evaluate [둘러보기](https://huggingface.co/docs/evaluate/a_quick_tour)를 참조하세요.)
계산하는 것에 대한
추천합니다 🙂

2023-04-18 23:10 UTC, 0525hhgus reviewed
Thank you for the good translation! 
Your translation is easy to understand 😀
I leave a short review below.

2023-04-18 23:35 UTC, wonhyeongseo commented on docs/source/ko/tasks/summarization.mdx
> +이제 `compute_metrics` 함수를 사용할 준비가 되었으며, 학습을 설정할 때 이 함수로 돌아가게 됩니다.
여기에서 `return`의 의미는 `다시 되돌아가다`에 가깝습니다. 만약 수정을 한다면,
```suggestion
이제 `compute_metrics` 함수를 사용할 준비가 되었으며, 학습을 설정할 때 이 함수로 되돌아올 것입니다.
```

2023-04-19 06:07 UTC, sim-so commented on docs/source/ko/tasks/summarization.mdx
> +이제 `compute_metrics` 함수를 사용할 준비가 되었으며, 학습을 설정할 때 이 함수로 돌아가게 됩니다.
두 분 모두 감사합니다!
원형님이 제안해주신 내용으로 반영하겠습니다!

2023-04-19 06:12 UTC, sim-so commented on docs/source/ko/tasks/summarization.mdx
> +(평가 지표를 불러오고 계산하는 데에 대한 자세한 내용은 🤗 Evaluate [둘러보기](https://huggingface.co/docs/evaluate/a_quick_tour)를 참조하세요.)
```suggestion
(평가 지표를 불러오고 계산하는 방법은 🤗 Evaluate [둘러보기](https://huggingface.co/docs/evaluate/a_quick_tour)를 참조하세요.)
```
제안 감사합니다!
계속 읽어보니 문장을 간결하게 하고 원문에 있던 `how to`를 살리면 좋을 것 같아 이렇게 수정하려고 해요.

2023-04-22 08:47 UTC, sim-so commented
Could you review this PR? 😄 
@sgugger, @ArthurZucker, @eunseojo

2023-04-24 13:02 UTC, sgugger approved these changes
Thanks for your contribution!

2023-04-24 13:03 UTC, merged