🌐 [i18n-KO] Translated `serialization.mdx` to Korean
huggingface/transformers pull request #22806
Opened 2023-04-17 14:47 UTC by wonhyeongseo

# What does this PR do?

Translated the `serialization.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

2023-04-17 15:08 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22806). All of your documentation changes will be reflected on that endpoint.

2023-04-24 15:48 UTC, wonhyeongseo commented
Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-25 04:09 UTC, sim-so requested changes
원형님의 번역 덕분에 많은 내용을 새로 알게 되었어요! 
수식어절이 긴 문장을 나누어 옮겨주신 점이 좋아서 저도 다음 번역에 참고하려고 해요 🙌 

`:` 뒤에 예시가 이어지는 문장과 몇 가지 표현에 대해 제안을 드립니다.
다른 의견이 있는 경우 편히 제안해주시면 좋겠습니다!

2023-04-25 04:09 UTC, sim-so commented on docs/source/ko/serialization.mdx
> +이미 만들어진 구성의 숫자를 늘리려고 노력하고 있으며, 커뮤니티의 기여를 환영합니다! 라이브러리에 당신만의 구성을 추가하려면 다음 단계를 기억해주세요:
```suggestion
미리 제작된 구성의 숫자를 늘리려고 노력하고 있으며, 커뮤니티의 기여를 환영합니다! 라이브러리에 당신만의 구성을 추가하려면 다음 단계를 기억해주세요:
```
`ready-made`를 앞에서 사용된 번역어와 맞추었습니다.

2023-04-25 04:09 UTC, sim-so commented on docs/source/ko/serialization.mdx
> +[`~onnx.config.OnnxConfig`]나 다른 구성 클래스에 연결된 모든 기본 속성 및 메서드는 필요에 따라 모두 재정의할 수 있습니다. 고급 예제로 [`BartOnnxConfig`]를 확인하세요.
```suggestion
[`~onnx.config.OnnxConfig`]나 다른 구성 클래스에 연결된 모든 기본 속성 및 메소드는 필요에 따라 모두 재정의할 수 있습니다. 고급 예제로 [`BartOnnxConfig`]를 확인하세요.
```

2023-04-25 14:28 UTC, 0525hhgus requested changes
번역 감사합니다! 문서 내 코드와 함께 표현을 고려하신 점이 느껴집니다 👍
저는 마지막 문단에 짧은 리뷰 덧붙였습니다 😄

2023-04-25 14:28 UTC, 0525hhgus commented on docs/source/ko/serialization.mdx
> +* [`~onnx.features.FeatureManager`]에 모델 아키텍처 및 해당 기능을 포함시키세요.
```suggestion
* [`~onnx.features.FeatureManager`]에 모델 아키텍처 및 해당 기능을 포함하세요.
```
전후 문장과 유사하게 능동으로 제안드립니다!

2023-04-25 15:15 UTC, wonhyeongseo reviewed
Thank you @sim-so and @0525hhgus for your wonderful reviews. Good night 🌙

2023-04-25 15:15 UTC, wonhyeongseo commented on docs/source/ko/serialization.mdx
> +각 미리 제작된 구성에는 다른 유형의 작업에 대한 모델을 내보내도록 하는 일련의 _기능_이 포함되어 있습니다. 아래 표에 나와 있는대로 각 기능은 다른 `AutoClass`와 연관되어 있습니다.
```suggestion
다른 유형의 태스크에 맞춰서 모델을 내보낼 수 있도록 미리 제작된 구성마다 일련의 _기능_이 포함되어 있습니다. 아래 표에 나와 있는대로 각 기능은 다른 `AutoClass`와 연관되어 있습니다.
```

2023-04-25 15:15 UTC, wonhyeongseo commented on docs/source/ko/serialization.mdx
> +출력 속성이 입력과 동일한 구조임을 유의하세요. 각 출력은 이름과 차원이 `OrderedDict`의 키-값으로 저장되어 있습니다. 출력 구조는 구성을 초기화할 때 선택한 기능과 관련이 있습니다. 기본적으로 ONNX 구성은 `AutoModel` 클래스로 가져온 모델을 내보낼 때 쓰이는 `default` 기능으로 초기화됩니다. 다른 태스크를 위해 모델을 내보
```suggestion
출력 속성이 입력과 동일한 구조임을 유의하세요. 각 출력은 이름과 차원이 `OrderedDict`의 키-값으로 저장되어 있습니다. 출력 구조는 구성을 초기화할 때 선택한 기능과 관련이 있습니다. 기본적으로 ONNX 구성은 `AutoModel` 클래스로 가져온 모델을 내보낼 때 쓰이는 `default` 기능으로 초기화됩니다. 다른 태스크를 위해 모델을 내보내려면 ONNX 구성을 초기화할 때 `task` 인수에 다른 기능을 넣으면 됩니다. 예를 들어, 시퀀스 분류 단계를 덧붙인 DistilBERT를 내보내려면, 이렇게 해볼 수 있습니다:
```

2023-04-25 15:15 UTC, wonhyeongseo commented on docs/source/ko/serialization.mdx
> +모델 크기가 2GB보다 큰 경우 내보내기 중에 여러 추가 파일들이 생성되는 것을 볼 수 있습니다. 사실 ONNX는 모델을 저장하기 위해 [Protocol Buffers](https://developers.google.com/protocol-buffers/)를 사용하는데, 버퍼는 2GB의 크기 제한이 있기 때문에 _예상대로_의 작동입니다. 외부 데이터를 사
```suggestion
모델 크기가 2GB보다 큰 경우 내보내는 중에 여러 추가 파일들이 생성되는 것을 볼 수 있습니다. 사실 ONNX는 모델을 저장하기 위해 [Protocol Buffers](https://developers.google.com/protocol-buffers/)를 사용하는데, 버퍼는 2GB의 크기 제한이 있기 때문에 _자연스러운_ 일입니다. 외부 데이터를 사용하여 모델을 가져오는 방법은 [ONNX 문서](https://github.com/onnx/onnx/blob/master/docs/ExternalData.md)를 참조하세요.
```

2023-04-25 15:48 UTC, wonhyeongseo commented
@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

2023-04-25 16:38 UTC, sgugger approved these changes
Thanks!

2023-04-25 16:38 UTC, merged