🌐 [i18n-KO] Translated `tasks/masked_language_modeling.mdx` to Korean
huggingface/transformers pull request #22838
Opened 2023-04-18 16:44 UTC by HanNayeoniee

# What does this PR do?

Translated the `tasks/masked_language_modeling.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Team PseudoLab, may you please review this PR?

@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-18 22:38 UTC, wonhyeongseo requested changes
~L189 리뷰 완료
고생 많으셨습니당. 작업 속도가 엄청 빨라지셨군요. 다음에도 리뷰해볼게요.
행복한 하루 보내시기 바래요 ...φ(・∀・*)

2023-04-19 12:06 UTC, sim-so requested changes
고생 많으셨습니다!
몇 가지 철자만 수정 제안 드립니다 😄

2023-04-19 12:06 UTC, sim-so commented on docs/source/ko/tasks/masked_language_modeling.mdx
> +이 전처리 함수를 전체 데이터 세드에 적용하기 위해 🤗 Datasets [`~datasets.Dataset.map`] 메소드를 사용합니다.
```suggestion
이 전처리 함수를 전체 데이터 세트에 적용하기 위해 🤗 Datasets [`~datasets.Dataset.map`] 메소드를 사용합니다. 
```

2023-04-19 12:06 UTC, sim-so commented on docs/source/ko/tasks/masked_language_modeling.mdx
> +데이터 세트 전체를 최대 길이로 패딩하는 것 보다 collation 단계에서 매 배치 안에서의 최대 길이로 문장을 *동적으로 패딩*하는 것이 더 효율적입니다.
```suggestion
데이터 세트 전체를 최대 길이로 패딩하는 것보다 collation 단계에서 매 배치 안에서의 최대 길이로 문장을 *동적으로 패딩*하는 것이 더 효율적입니다.
```

2023-04-22 13:21 UTC, 0525hhgus reviewed
좋은 번역 감사합니다 😄 저는 현재 번역 진행된 부분까지 모두 괜찮으며, 이전 리뷰어분들의 의견에 동의합니다 👍

2023-04-22 15:50 UTC, HanNayeoniee commented on docs/source/ko/tasks/masked_language_modeling.mdx
> +마스크드 언어 모델링은 전체 시퀀스에 대한 문맥적 이해가 필요한 작업에 적합하며, BERT가 그 예에 해당합니다.
[위키독스-딥러닝을 이용한 자연어처리 입문](https://wikidocs.net/153992)을 보고 Masked Language Model을 `마스크드 언어 모델링`으로 번역했는데, 어색해서 `마스킹된 언어 모델링`으로 변경하였습니다.

2023-04-22 15:51 UTC, HanNayeoniee commented on docs/source/ko/tasks/masked_language_modeling.mdx
> +
원형님의 빠른 리뷰 속도에 놀랐습니다 🫢 감사합니다!

2023-04-22 16:39 UTC, HanNayeoniee commented on docs/source/ko/_toctree.yml
> -        title: (번역중) Masked language modeling
`_toctree.yml` 파일이 아닌 `.mdx` 파일의 목차 부분이 문제였습니다!
L13 [[ ]] 안에 dash(-)를 사용해야하는데, underscore(_)을 써서 빌드가 안 됐었습니다.

@gabrielwithappy님, 도와주셔서 감사합니다 :)

2023-04-22 16:53 UTC, gabrielwithappy commented on docs/source/ko/tasks/masked_language_modeling.mdx
> +Once training is completed, use the [`~transformers.Trainer.evaluate`] method to evaluate your model and get its perplexity:
영어 부분이 아직 남아 있는 것 같습니다.

2023-04-22 17:04 UTC, HanNayeoniee commented on docs/source/ko/_toctree.yml
> -        title: (번역중) Masked language modeling
다른 부분에도 문제가 있는지 빌드가 안 되었네용... 내일 다시 확인해볼게요

2023-04-23 12:36 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22838). All of your documentation changes will be reflected on that endpoint.

2023-04-23 12:46 UTC, HanNayeoniee commented on docs/source/ko/_toctree.yml
> -        title: (번역중) Masked language modeling
해결했습니다 감사합니다 :)

2023-04-24 13:02 UTC, sgugger approved these changes
Thanks for your contribution!

2023-04-24 13:02 UTC, merged

2023-04-24 13:08 UTC, ArthurZucker reviewed
A very small nit 😉 Otherwise good job 🔥