🌐 [i18n-KO] Translated `tasks/image_captioning.mdx` to Korean
huggingface/transformers pull request #22943
Opened 2023-04-23 00:41 UTC by sim-so

# What does this PR do?

Translated the `tasks/image_captioning.mdx` file of the documentation to Korean.
Thank you in advance for your review!

- [ ] 이미지 캡셔닝 Image captioning
  - [ ] 포켓몬 BLIP 데이터셋 가져오기 Load the Pokémon BLIP captions dataset
  - [ ] 데이터셋 전처리 Preprocess the dataset
  - [ ] 기본 모델 가져오기 Load a base model
  - [ ] 평가 Evaluate
  - [ ] 학습! Train!
  - [ ] 추론 Inference

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

This is a work on progress.
Could you review this PR when I finish this work?
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-23 00:58 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_22943). All of your documentation changes will be reflected on that endpoint.

2023-04-23 02:29 UTC, sim-so commented
I quickly done it! 😅 
Would you review this PR?

2023-04-24 13:06 UTC, 0525hhgus approved these changes
좋은 번역 감사합니다 😄 문법까지 모두 완벽하네요..! 
~~전 다른 피드백 없습니다 👍~~ 하단에 리뷰 남겼습니다!

2023-04-24 13:49 UTC, 0525hhgus requested changes
추가로 리뷰드립니다!

2023-04-24 13:49 UTC, 0525hhgus commented on docs/source/ko/_toctree.yml
> +      title: (번역중) 이미지 캡셔닝
`(번역중)` 태그가 아직 붙어 있습니다! 
의도하신 제목인지 확실치 않아서, 짧게 납깁니다..!

2023-04-24 13:49 UTC, 0525hhgus commented on docs/source/ko/tasks/image_captioning.mdx
> +## 포켓몬 BLIP 캡션 데이터세트 가져오기[[load-the-pokémon-blip-captions-dataset]]
```suggestion
## 포켓몬 BLIP 캡션 데이터세트 가져오기[[load-the-pokmon-blip-captions-dataset]]
```
`load-the-pokmon-blip-captions-dataset`로 하시면, anchor가 작동할 것 같습니다!

2023-04-24 13:54 UTC, sim-so commented on docs/source/ko/_toctree.yml
> +      title: (번역중) 이미지 캡셔닝
의도한 것이 아니었어요! 😂 
확인 감사합니다!

2023-04-24 13:55 UTC, sim-so commented on docs/source/ko/tasks/image_captioning.mdx
> +## 포켓몬 BLIP 캡션 데이터세트 가져오기[[load-the-pokémon-blip-captions-dataset]]
수정 제안 감사합니다!

2023-04-24 14:30 UTC, wonhyeongseo approved these changes
LGTM ❤️

2023-04-26 04:42 UTC, sim-so commented
Happy Wednesday!
Could you review this PR? 😃
@sgugger, @ArthurZucker, @eunseojo

2023-04-26 11:54 UTC, sgugger approved these changes
Thanks a lot!

2023-04-26 11:54 UTC, merged