🌐 [i18n-KO] Translated `multilingual.mdx` to Korean
huggingface/transformers pull request #23008
Opened 2023-04-26 13:18 UTC by HanNayeoniee

# What does this PR do?

Translated the `multilingual.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

2023-04-26 13:36 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23008). All of your documentation changes will be reflected on that endpoint.

2023-04-26 22:53 UTC, 0525hhgus requested changes
좋은 번역 감사합니다! 주석도 번역해주셔서 이해하기 수월했습니다 :) 아래 리뷰 남깁니다 🙂

2023-04-26 22:53 UTC, 0525hhgus commented on docs/source/ko/multilingual.mdx
> +다음 예제에서는 `xlm-clm-enfr-1024` 체크포인트(코잘 언어 모델링(causal language modeling), 영어-프랑스어)를 로드합니다:
```suggestion
다음 예제에서는 `xlm-clm-enfr-1024` 체크포인트(코잘 언어 모델링(causal language modeling), 영어-프랑스어)를 가져옵니다:
```
Glossary에 맞춰서 수정했습니다!

2023-04-26 22:53 UTC, 0525hhgus commented on docs/source/ko/multilingual.mdx
> +이 예제에서는 `facebook/m2m100_418M` 체크포인트를 로드하여 중국어를 영어로 번역합니다.
```suggestion
이 예제에서는 `facebook/m2m100_418M` 체크포인트를 가져와서 중국어를 영어로 번역합니다. 
```

2023-04-26 22:53 UTC, 0525hhgus commented on docs/source/ko/multilingual.mdx
> +다음 MBart 모델 또한 다국어 다국어 태스크에 사용할 수 있습니다:
```suggestion
다음 MBart 모델 또한 다국어 태스크에 사용할 수 있습니다:
```
`다국어`가 중복되어 하나만 남겼습니다!

2023-04-26 22:53 UTC, 0525hhgus commented on docs/source/ko/multilingual.mdx
> +이 예제에서는 핀란드어를 영어로 번역하기 위해 `facebook/mbart-large-50-many-to-many-mmt` 체크포인트를 로드합니다.
```suggestion
이 예제에서는 핀란드어를 영어로 번역하기 위해 `facebook/mbart-large-50-many-to-many-mmt` 체크포인트를 가져옵니다. 
```

2023-04-26 22:53 UTC, 0525hhgus commented on docs/source/ko/multilingual.mdx
> +>>> input_ids = torch.tensor([tokenizer.encode("Wikipedia was used to")])  # 배치 사이즈는 1입니다
```suggestion
>>> input_ids = torch.tensor([tokenizer.encode("Wikipedia was used to")])  # 배치 크기는 1입니다
```
68 라인에서 size를 크기로 사용하고 있어서, 동일하게 맞췄습니다!

2023-04-26 22:53 UTC, 0525hhgus commented on docs/source/ko/multilingual.mdx
> +>>> langs = langs.view(1, -1)  # 이제 [1, sequence_length] shape이 되었습니다(배치 사이즈는 1입니다)
```suggestion
>>> langs = langs.view(1, -1)  # 이제 [1, sequence_length] shape이 되었습니다(배치 크기는 1입니다)
```

2023-04-27 00:57 UTC, jungnerd commented on docs/source/ko/multilingual.mdx
> +이전에 공개된 mBERT나 XLM과 같은 다국어 모델에 비해 분류, 시퀀스 라벨링, 질문 답변과 같은 다운스트림(downstream) 작업에서 이점이 있습니다.
```suggestion
이전에 공개된 mBERT나 XLM과 같은 다국어 모델에 비해 분류, 시퀀스 라벨링, 질의 응답과 같은 다운스트림(downstream) 작업에서 이점이 있습니다.
```
Glossary에 맞춰 수정했습니다!

2023-04-27 02:59 UTC, sim-so reviewed
주석을 번역해주신 점이 좋아요! 
수정 사항은 다른 분들의 의견과 같습니다 😄

2023-04-27 12:06 UTC, sgugger approved these changes
Thanks for your contribution!

2023-04-27 12:06 UTC, merged