🌐 [i18n-KO] Translated `<tasks/question_answering>.mdx` to Korean
huggingface/transformers pull request #23012
Opened 2023-04-26 15:35 UTC by jungnerd

# What does this PR do?

Translated the `<tasks/question_answering>.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-04-27 01:04 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23012). All of your documentation changes will be reflected on that endpoint.

2023-04-27 03:20 UTC, sim-so requested changes
다들 번역이 정말 빠르시네요!
몇 가지 수정 사항을 제안 드리오니 검토 부탁 드려요! 😃

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +몇 가지 중요한 항목:
```suggestion
이 중에서 몇 가지 중요한 항목이 있습니다:
```
다른 부분이랑 비슷하게 문장 형태로 맞추어보았습니다.

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +다음 단계에서는 `question` 및 `context` 항목을 처리하기 위해 DistilBERT 토크나이저를 로드합니다.
```suggestion
다음 단계에서는 `question` 및 `context` 항목을 처리하기 위해 DistilBERT 토크나이저를 가져옵니다.
```

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +3. 매핑을 완료하면, 이제 답변에서 시작 토큰과 종료 토큰을 찾을 수 있습니다. 오프셋의 어느 부분이 `question`과 `context`에 해당하는지 찾기 위해 [`~tokenizers.Encoding.sequence_ids`] 매서드를 사용하세요.
```suggestion
3. 매핑을 완료하면, 이제 답변에서 시작 토큰과 종료 토큰을 찾을 수 있습니다. 오프셋의 어느 부분이 `question`과 `context`에 해당하는지 찾을 수 있도록 [`~tokenizers.Encoding.sequence_ids`] 메소드를 사용하세요.
```

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +훈련이 완료되면, [`~transformers.Trainer.push_to_hub`] 매서드를 사용해 모델을 Hub에 공유해서 모든 사람들이 사용할 수 있게 공유해주세요.
```suggestion
훈련이 완료되면, [`~transformers.Trainer.push_to_hub`] 메소드를 사용해 모델을 Hub에 공유해서 모든 사람들이 사용할 수 있게 공유해주세요.
```

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +질문과 모델이 예측하기 원하는 context를 생각해보세요.
```suggestion
질문과 모델이 예측하기 원하는 문맥(context)을 생각해보세요.
```
한국어 단어도 같이 표기해보면 어떨까요?

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +훈련을 시작하기 전 마지막으로 해야할 것은 모델을 Hub로 푸시할 방법을 설정하는 것 입니다. [`~transformers.PushToHubCallback`]에서 모델과 토크나이저를 푸시할 경로를 설정합니다.
```suggestion
훈련을 시작하기 전 마지막으로 모델을 Hub로 푸시할 방법을 설정합니다. [`~transformers.PushToHubCallback`]에서 모델과 토크나이저를 푸시할 경로를 설정합니다.
```
혹은 전반적인 흐름이 있으니 `훈련을 시작하기 전`을 생략해도 무방할 것 같아요.

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +1. [`TrainingArguments`]에서 훈련 하이퍼파라미터를 정합니다. 꼭 필요한 매개변수는 모델을 저장할 위치를 지정하는 `output_dir` 입니다. `push_to_hub=True`로 설정해서 이 모델을 Hub로 푸시합니다 (모델을 업로드하려면 허깅페이스에 로그인해야 합니다).
```suggestion
1. [`TrainingArguments`]에서 훈련 하이퍼파라미터를 정합니다. 꼭 필요한 매개변수는 모델을 저장할 위치를 지정하는 `output_dir` 입니다. `push_to_hub=True`로 설정해서 이 모델을 Hub로 푸시합니다 (모델을 업로드하려면 Hugging Face에 로그인해야 합니다).
```
`Hugging Face`는 한국어로 옮기지 않았던 것 같아요.

2023-04-27 03:20 UTC, sim-so commented on docs/source/ko/tasks/question_answering.mdx
> +## 학습[[train]]
```suggestion
## 훈련[[train]]
```
다른 부분은 모두 `훈련`이라고 사용하고 있어서 맞추었습니다.

2023-04-27 14:20 UTC, 0525hhgus requested changes
좋은 번역 감사합니다! 새로운 용어도 잘 이해되도록 번역해주셨군요 👍 
glossary 및 `:` 관련 리뷰를 하단에 남겼습니다 😄 (`:` 관련 코멘트가 길어져서 마지막에 라인 번호로 남겼으니, 참고해주세요!)

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +이제 세 단계만 남았습니다.
```suggestion
이제 세 단계만 남았습니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +시작하기 전에, 필요한 라이브러리가 모두 설치되어 있는지 확인하세요.
```suggestion
시작하기 전에, 필요한 라이브러리가 모두 설치되어 있는지 확인하세요:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +여러분의 모델을 업로드하고 커뮤니티에 공유할 수 있도록 Hugging Face 계정에 로그인하는 것이 좋습니다. 메시지가 표시되면 토큰을 입력해서 로그인합니다.
```suggestion
여러분의 모델을 업로드하고 커뮤니티에 공유할 수 있도록 Hugging Face 계정에 로그인하는 것이 좋습니다. 메시지가 표시되면 토큰을 입력해서 로그인합니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +데이터 세트의 분할된 `train`을 [`~datasets.Dataset.train_test_split`] 메소드를 사용해 훈련 데이터 세트와 테스트 데이터 세트로 나누어줍니다.
```suggestion
데이터 세트의 분할된 `train`을 [`~datasets.Dataset.train_test_split`] 메소드를 사용해 훈련 데이터 세트와 테스트 데이터 세트로 나누어줍니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +그리고 나서 예시로 데이터를 하나 살펴봅니다.
```suggestion
그리고 나서 예시로 데이터를 하나 살펴봅니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +다음 단계에서는 `question` 및 `context` 항목을 처리하기 위해 DistilBERT 토크나이저를 로드합니다.
```suggestion
다음 단계에서는 `question` 및 `context` 항목을 처리하기 위해 DistilBERT 토크나이저를 가져옵니다:
```
`:(Colons)`를 추가하였습니다!

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +질의 응답 태스크와 관련해서 특히 유의해야할 몇 가지 전처리 단계가 있습니다.
```suggestion
질의 응답 태스크와 관련해서 특히 유의해야할 몇 가지 전처리 단계가 있습니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +다음은 `answer`의 시작 토큰과 종료 토큰을 잘라내서 `context`에 매핑하는 함수를 만드는 방법입니다.
```suggestion
다음은 `answer`의 시작 토큰과 종료 토큰을 잘라내서 `context`에 매핑하는 함수를 만드는 방법입니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +모든 데이터 세트에 전처리를 적용하려면, 🤗 Datasets [`~datasets.Dataset.map`] 함수를 사용하세요. `batched=True`로 설정해 데이터 세트의 여러 요소들을 한 번에 처리하면 `map` 함수의 속도를 빠르게 할 수 있습니다. 필요하지 않은 열은 모두 제거합니다.
```suggestion
모든 데이터 세트에 전처리를 적용하려면, 🤗 Datasets [`~datasets.Dataset.map`] 함수를 사용하세요. `batched=True`로 설정해 데이터 세트의 여러 요소들을 한 번에 처리하면 `map` 함수의 속도를 빠르게 할 수 있습니다. 필요하지 않은 열은 모두 제거합니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +이제 [`DefaultDataCollator`]를 이용해 예시 배치를 생성합니다. 🤗 Transformers의 다른 데이터 콜레이터(data collator)와 달리, [`DefaultDataCollator`]는 패딩과 같은 추가 전처리를 적용하지 않습니다.
```suggestion
이제 [`DefaultDataCollator`]를 이용해 예시 배치를 생성합니다. 🤗 Transformers의 다른 데이터 콜레이터(data collator)와 달리, [`DefaultDataCollator`]는 패딩과 같은 추가 전처리를 적용하지 않습니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +이제 모델 훈련을 시작할 준비가 되었습니다! [`AutoModelForQuestionAnswering`]으로 DistilBERT를 가져옵니다.
```suggestion
이제 모델 훈련을 시작할 준비가 되었습니다! [`AutoModelForQuestionAnswering`]으로 DistilBERT를 가져옵니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +훈련이 완료되면, [`~transformers.Trainer.push_to_hub`] 매서드를 사용해 모델을 Hub에 공유해서 모든 사람들이 사용할 수 있게 공유해주세요.
```suggestion
훈련이 완료되면, [`~transformers.Trainer.push_to_hub`] 매소드를 사용해 모델을 Hub에 공유해서 모든 사람들이 사용할 수 있게 공유해주세요:
```
`:`을 추가했습니다!

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +TensorFlow를 이용한 모델을 미세 조정하려면 옵티마이저 함수, 학습률 스케쥴 및 몇 가지 훈련 하이퍼파라미터를 설정하는 것부터 시작해야합니다.
```suggestion
TensorFlow를 이용한 모델을 미세 조정하려면 옵티마이저 함수, 학습률 스케쥴 및 몇 가지 훈련 하이퍼파라미터를 설정하는 것부터 시작해야합니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +그 다음 [`TFAutoModelForQuestionAnswering`]으로 DistilBERT를 가져옵니다.
```suggestion
그 다음 [`TFAutoModelForQuestionAnswering`]으로 DistilBERT를 가져옵니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +[`~transformers.TFPreTrainedModel.prepare_tf_dataset`]을 사용해서 데이터 세트를 `tf.data.Dataset` 형식으로 변환합니다.
```suggestion
[`~transformers.TFPreTrainedModel.prepare_tf_dataset`]을 사용해서 데이터 세트를 `tf.data.Dataset` 형식으로 변환합니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +[`compile`](https://keras.io/api/models/model_training_apis/#compile-method)로 훈련할 모델을 설정합니다.
```suggestion
[`compile`](https://keras.io/api/models/model_training_apis/#compile-method)로 훈련할 모델을 설정합니다:
```

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +훈련을 시작하기 전 마지막으로 해야할 것은 모델을 Hub로 푸시할 방법을 설정하는 것 입니다. [`~transformers.PushToHubCallback`]에서 모델과 토크나이저를 푸시할 경로를 설정합니다.
```suggestion
훈련을 시작하기 전 마지막으로 해야할 것은 모델을 Hub로 푸시할 방법을 설정하는 것 입니다. [`~transformers.PushToHubCallback`]에서 모델과 토크나이저를 푸시할 경로를 설정합니다:
```
`:`을 추가하였습니다.

2023-04-27 14:20 UTC, 0525hhgus commented on docs/source/ko/tasks/question_answering.mdx
> +드디어 모델 훈련을 시작할 준비가 되었습니다! 훈련 데이터 세트와 평가 데이터 세트, 에폭 수, 콜백을 설정한 후 [`fit`](https://keras.io/api/models/model_training_apis/#fit-method)을 이용해 모델을 미세 조정합니다.
```suggestion
드디어 모델 훈련을 시작할 준비가 되었습니다! 훈련 데이터 세트와 평가 데이터 세트, 에폭 수, 콜백을 설정한 후 [`fit`](https://keras.io/api/models/model_training_apis/#fit-method)을 이용해 모델을 미세 조정합니다:
```
추가로 307 라인 다음부터는 332, 339, 352, 356, 365, 375, 382, 391, 400, 409, 416 라인을 참고하시면 됩니다!
리뷰가 코멘트가 많아져서 라인 번호로 남깁니다!

2023-04-27 23:28 UTC, gabrielwithappy commented on docs/source/ko/tasks/question_answering.mdx
> +그리고 나서 예시로 데이터를 하나 살펴봅니다.
그리고나서 
그리고

2023-04-30 15:07 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +그리고 나서 예시로 데이터를 하나 살펴봅니다.
```suggestion
그리고나서 예시로 데이터를 하나 살펴봅니다:
```

2023-04-30 15:09 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +훈련을 시작하기 전 마지막으로 해야할 것은 모델을 Hub로 푸시할 방법을 설정하는 것 입니다. [`~transformers.PushToHubCallback`]에서 모델과 토크나이저를 푸시할 경로를 설정합니다.
```suggestion
마지막으로 모델을 Hub로 푸시할 방법을 설정합니다. [`~transformers.PushToHubCallback`]에서 모델과 토크나이저를 푸시할 경로를 설정합니다:
```

2023-04-30 15:10 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +드디어 모델 훈련을 시작할 준비가 되었습니다! 훈련 데이터 세트와 평가 데이터 세트, 에폭 수, 콜백을 설정한 후 [`fit`](https://keras.io/api/models/model_training_apis/#fit-method)을 이용해 모델을 미세 조정합니다.
감사합니다! 제가 콜론을 다 온점으로 바꿔서 번역을 했군요 ㅠㅠ

2023-04-30 15:15 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +질문과 모델이 예측하기 원하는 context를 생각해보세요.
```suggestion
질문과 모델이 예측하기 원하는 문맥(context)를 생각해보세요:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +추론을 위해 미세 조정한 모델을 테스트하는 가장 쉬운 방법은 [`pipeline`]을 사용하는 것 입니다. 모델을 사용해 질의 응답을 하기 위해서 `pipeline`을 인스턴스화하고 텍스트를 입력합니다.
```suggestion
추론을 위해 미세 조정한 모델을 테스트하는 가장 쉬운 방법은 [`pipeline`]을 사용하는 것 입니다. 모델을 사용해 질의 응답을 하기 위해서 `pipeline`을 인스턴스화하고 텍스트를 입력합니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +원한다면 `pipeline`의 결과를 직접 복제할 수도 있습니다.
```suggestion
원한다면 `pipeline`의 결과를 직접 복제할 수도 있습니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +텍스트를 토큰화해서 PyTorch 텐서를 반환합니다.
```suggestion
텍스트를 토큰화해서 PyTorch 텐서를 반환합니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +모델에 입력을 전달하고 `logits`을 반환합니다.
```suggestion
모델에 입력을 전달하고 `logits`을 반환합니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +모델의 출력에서 시작 및 종료 위치가 어딘지 가장 높은 확률을 얻습니다.
```suggestion
모델의 출력에서 시작 및 종료 위치가 어딘지 가장 높은 확률을 얻습니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +예측된 토큰을 해독해서 답을 얻습니다.
```suggestion
예측된 토큰을 해독해서 답을 얻습니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +텍스트를 토큰화해서 TensorFlow 텐서를 반환합니다.
```suggestion
텍스트를 토큰화해서 TensorFlow 텐서를 반환합니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +모델에 입력을 전달하고 `logits`을 반환합니다.
```suggestion
모델에 입력을 전달하고 `logits`을 반환합니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +모델의 출력에서 시작 및 종료 위치가 어딘지 가장 높은 확률을 얻습니다.
```suggestion
모델의 출력에서 시작 및 종료 위치가 어딘지 가장 높은 확률을 얻습니다:
```

2023-04-30 15:17 UTC, jungnerd commented on docs/source/ko/tasks/question_answering.mdx
> +예측된 토큰을 해독해서 답을 얻습니다.
```suggestion
예측된 토큰을 해독해서 답을 얻습니다:
```

2023-05-01 14:46 UTC, jungnerd commented
May you please review this PR? 😄
@sgugger, @ArthurZucker, @eunseojo

2023-05-01 15:05 UTC, sgugger approved these changes
Thanks for your contribution!

2023-05-01 15:05 UTC, merged