[i18n-KO] Translated video_classification.mdx to Korean
huggingface/transformers pull request #23026
Opened 2023-04-27 11:34 UTC by KIHOON71

# What does this PR do?

Translated the video_classification.mdx file of the documentation to Korean.
Thank you in advance for your review.

## Before reviewing
 - [x] Check for missing / redundant translations (번역 누락/중복 검사)
 - [x] Grammar Check (맞춤법 검사)
 - [x] Review or Add new terms to glossary (용어 확인 및 추가)
 - [x] Check Inline TOC (e.g. [[lowercased-header]])
 - [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review(initial)?

Team PseudoLab, may you please review this PR? @0525hhgus, @HanNayeoniee, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review(initial)?

@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

2023-04-27 11:49 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23026). All of your documentation changes will be reflected on that endpoint.

2023-04-27 14:27 UTC, harshsingh32 approved these changes
lgtm

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +영상 분류는 영상 전체에 레이블 또는 클래스를 지정하는 작업입니다. 각 영상에는 하나의 클래스가 있을 것으로 예상됩니다. 영상 분류 모델은 영상를 입력으로 받아 어느 클래스에 속하는지에 대한 예측을 반환합니다. 이러한 모델은 영상가 어떤 내용인지 분류하는 데 사용될 수 있습니다. 영상 분류의 실제 응용 예는 피트니스 앱에서 유용한 동작 / 운동 인식 서비
```suggestion
영상 분류는 영상 전체에 레이블 또는 클래스를 지정하는 작업입니다. 각 영상에는 하나의 클래스가 있을 것으로 예상됩니다. 영상 분류 모델은 영상을 입력으로 받아 어느 클래스에 속하는지에 대한 예측을 반환합니다. 이러한 모델은 영상이 어떤 내용인지 분류하는 데 사용될 수 있습니다. 영상 분류의 실제 응용 예는 피트니스 앱에서 유용한 동작 / 운동 인식 서비스가 있습니다. 이는 또한 시각 장애인이 이동할 때 보조하는데 사용될 수 있습니다
```
어색한 조사를 수정했습니다.

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +1. [UCF101](https://www.crcv.ucf.edu/data/UCF101.php) 데이터셋의 하위 집합을 통해 [VideoMAE](https://huggingface.co/docs/transformers/main/en/model_doc/videomae) 모델을 미세 조정하는 법.
```suggestion
1. [UCF101](https://www.crcv.ucf.edu/data/UCF101.php) 데이터 세트의 하위 집합을 통해 [VideoMAE](https://huggingface.co/docs/transformers/main/en/model_doc/videomae) 모델을 미세 조정하는 법.
```
Glossary에 `dataset`가 `데이터 세트`로 되어있어 수정했습니다!

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +[UCF-101](https://www.crcv.ucf.edu/data/UCF101.php) 데이터셋의 하위 집합(subset)을 불러오는 것으로 시작할 수 있습니다. 전체 데이터 셋을 학습하는데 더 많은 시간을 할애하기 전에 데이터의 하위 집합을 불러와 모든 것이 잘 작동하는지 실험하고 확인할 수 있습니다.
```suggestion
[UCF-101](https://www.crcv.ucf.edu/data/UCF101.php) 데이터 세트의 하위 집합(subset)을 불러오는 것으로 시작할 수 있습니다. 전체 데이터 세트를 학습하는데 더 많은 시간을 할애하기 전에 데이터의 하위 집합을 불러와 모든 것이 잘 작동하는지 실험하고 확인할 수 있습니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +데이터셋의 하위 집합이 다운로드 되면, 압축된 아카이브를 해제해야 합니다.
```suggestion
데이터 세트의 하위 집합이 다운로드 되면, 압축된 아카이브를 해제해야 합니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +전체 데이터셋의 구성은 다음과 같이 구성되어 있습니다.
```suggestion
전체 데이터 세트는 다음과 같이 구성되어 있습니다.
```
'구성'이 두 번 들어가면 문장이 조금 어색한 것 같아서 수정해보았습니다!

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +그 다음으로, 데이터셋에 존재하는 라벨을 추출합니다. 또한, 모델을 초기화할 때 도움이 될 딕셔너리(dictionary data type)를 생성합니다.
```suggestion
그 다음으로, 데이터 세트에 존재하는 라벨을 추출합니다. 또한, 모델을 초기화할 때 도움이 될 딕셔너리(dictionary data type)를 생성합니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +이 데이터셋에는 총 10개의 고유한 클래스가 있습니다. 각 클래스마다 30개의 영상이 훈련 세트에 있습니다
```suggestion
이 데이터 세트에는 총 10개의 고유한 클래스가 있습니다. 각 클래스마다 30개의 영상이 훈련 세트에 있습니다
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +사전 학습된 체크포인트와 체크포인트에 연관된 이미지 프로세서를 사용하여 영상 분류 모델을 인스턴스화합니다. 모델의 인코더는 미리 학습된 매개변수가 제공되며, 분류 헤드(데이터를 분류하는 마지막 레이어)는 무작위로 초기화됩니다. 데이터셋의 전처리 파이프라인을 작성할 때 이미지 프로세서가 유용합니다.
```suggestion
사전 학습된 체크포인트와 체크포인트에 연관된 이미지 프로세서를 사용하여 영상 분류 모델을 인스턴스화합니다. 모델의 인코더는 미리 학습된 매개변수가 제공되며, 분류 헤드(데이터를 분류하는 마지막 레이어)는 무작위로 초기화됩니다. 데이터 세트의 전처리 파이프라인을 작성할 때 이미지 프로세서가 유용합니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +**참고** 이 [체크포인트](https://huggingface.co/MCG-NJU/videomae-base-finetuned-kinetics)는 도메인이 많이 중첩된 유사한 다운스트림 작업을 미세 조정하여 얻은 체크포인트이므로 이 작업에서 더 나은 성능을 보일 수 있습니다. `MCG-NJU/videomae-base-finetuned-kinetics`의
```suggestion
**참고** 이 [체크포인트](https://huggingface.co/MCG-NJU/videomae-base-finetuned-kinetics)는 도메인이 많이 중첩된 유사한 다운스트림 작업을 미세 조정하여 얻은 체크포인트이므로 이 작업에서 더 나은 성능을 보일 수 있습니다. `MCG-NJU/videomae-base-finetuned-kinetics`의 데이터 세트를 미세 조정하여 얻은 [체크포인트](https://huggingface.co/sayakpaul/videomae-base-finetuned-kinetics-finetuned-ucf101-subset)입니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +학습 데이터셋 변환에는 '균일한 시간 샘플링(uniform temporal subsampling)', '픽셀 정규화(pixel normalization)', '무작위 잘라내기(random cropping)' 및 '무작위 수평 뒤집기(random horizontal flipping)'의 조합을 사용합니다. 검증 및 평가 데이터셋 변환에는 '무작위 잘라내기'
```suggestion
훈련 데이터 세트 변환에는 '균일한 시간 샘플링(uniform temporal subsampling)', '픽셀 정규화(pixel normalization)', '무작위 잘라내기(random cropping)' 및 '무작위 수평 뒤집기(random horizontal flipping)'의 조합을 사용합니다. 검증 및 평가 데이터셋 변환에는 '무작위 잘라내기'와 '수평 뒤집기'를 제외한 동일한 변환 체인을 유지합니다. 이러한 변환의 자세한 내용을 알아보려면 [PyTorchVideo 공식 문서](https://pytorchvideo.org)를 확인하세요.
```
`학습`과 `훈련`이 혼용돼서 glossary에 있는 `훈련`으로 수정했습니다!

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +이제 데이터셋에 특화된 전처리(transform)과 데이터셋 자체를 정의합니다. 먼저 훈련 데이터셋으로 시작합니다.
```suggestion
이제 데이터 세트에 특화된 전처리(transform)과 데이터 세트 자체를 정의합니다. 먼저 훈련 데이터 세트로 시작합니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +같은 방식의 작업 흐름을 검증과 평가 셋에도 적용할 수 있습니다.
```suggestion
같은 방식의 작업 흐름을 검증과 평가 세트에도 적용할 수 있습니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +**참고**: 위의 데이터셋 파이프라인은 [공식 파이토치 예제](https://pytorchvideo.org/docs/tutorial_classification#dataset)에서 가져온 것입니다. 우리는 UCF-101 데이터셋에 맞게 [`pytorchvideo.data.Ucf101()`](https://pytorchvideo.readthedocs.io/
```suggestion
**참고**: 위의 데이터 세트 파이프라인은 [공식 파이토치 예제](https://pytorchvideo.org/docs/tutorial_classification#dataset)에서 가져온 것입니다. 우리는 UCF-101 데이터 세트에 맞게 [`pytorchvideo.data.Ucf101()`](https://pytorchvideo.readthedocs.io/en/latest/api/data/data.html#pytorchvideo.data.Ucf101) 함수를 사용하고 있습니다. 내부적으로, 이 함수는 [`pytorchvideo.data.labeled_video_dataset.LabeledVideoDataset`](https://pytorchvideo.readthedocs.io/en/latest/api/data/data.html#pytorchvideo.data.LabeledVideoDataset) 객체를 반환합니다. `LabeledVideoDataset` 클래스는 PyTorchVideo 데이터 세트에서 모든 영상 관련 작업의 기본 클래스입니다. 따라서 PyTorchVideo에서 미리 제공하지 않는 사용자 지정 데이터 세트를 사용하려면, 이 클래스를 적절하게 확장하면 됩니다. 더 자세한 사항이 알고 싶다면 `data` API [documentation](https://pytorchvideo.readthedocs.io/en/latest/api/data/data.html) 를 참고하세요. 또한 위의 예시와 유사한 구조를 갖는 데이터 세트를 사용하고 있다면, `pytorchvideo.data.Ucf101()` 함수를 사용하는 데 문제가 없을 것입니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +데이터셋에 영상의 개수를 알기 위해 `num_videos` 인수에 접근할 수 있습니다.
```suggestion
데이터 세트에 영상의 개수를 알기 위해 `num_videos` 인수에 접근할 수 있습니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +`pytorchvideo.data.Ucf101()` 함수로 반환되는 데이터셋은 `__len__` 메소드가 이식되어 있지 않습니다. 따라서,  `TrainingArguments`를 인스턴스화할 때 `max_steps`를 정의해야 합니다.
```suggestion
`pytorchvideo.data.Ucf101()` 함수로 반환되는 데이터 세트는 `__len__` 메소드가 이식되어 있지 않습니다. 따라서,  `TrainingArguments`를 인스턴스화할 때 `max_steps`를 정의해야 합니다.
```

2023-05-02 09:40 UTC, jungnerd commented on docs/source/ko/tasks/video_classification.mdx
> +그런 다음 이 모든 것을 데이터셋과 함께 `Trainer`에 전달하기만 하면 됩니다.
```suggestion
그런 다음 이 모든 것을 데이터 세트와 함께 `Trainer`에 전달하기만 하면 됩니다.
```

2023-05-02 10:14 UTC, sim-so requested changes
번역하는 데 고생이 정말 많으셨을 것 같아요!
저도 열심히 리뷰를 해보았습니다🔥

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +`pytorchvideo.data.Ucf101()` 함수로 반환되는 데이터셋은 `__len__` 메소드가 이식되어 있지 않습니다. 따라서,  `TrainingArguments`를 인스턴스화할 때 `max_steps`를 정의해야 합니다.
```suggestion
`pytorchvideo.data.Ucf101()` 함수로 반환되는 데이터 세트에는 `__len__` 메소드가 이식되어 있지 않습니다. 따라서,  `TrainingArguments`를 인스턴스화할 때 `max_steps`를 정의해야 합니다.
```

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +[VideoMAE paper](https://arxiv.org/abs/2203.12602) 논문에서, 저자는 다음과 같은 평가 전략을 사용합니다. 테스트 영상에서 여러 클립을 선택하고 그 클립에 다양한 크롭을 적용하여 집계 점수를 보고합니다. 그러나 이번 튜토리얼에서는 간단함과 간결함을 위해 해당 전략을 고려하지 않습니다.
```suggestion
[VideoMAE 논문](https://arxiv.org/abs/2203.12602)에서 저자는 다음과 같은 평가 전략을 사용합니다. 테스트 영상에서 여러 클립을 선택하고 그 클립에 다양한 크롭을 적용하여 집계 점수를 보고합니다. 그러나 이번 튜토리얼에서는 간단함과 간결함을 위해 해당 전략을 고려하지 않습니다.
```

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +데이터를 이미 처리했는데도 불구하고 `image_processor`를 토크나이저 인자에 넣은 이유는, JSON으로 저장 되는 이미지 처리 설정 파일이 Hub의 저장소에 업로드되도록 하기 위함입니다.
```suggestion
데이터를 이미 처리했는데도 불구하고 `image_processor`를 토크나이저 인수로 넣은 이유는 JSON으로 저장되는 이미지 프로세서 구성 파일이 Hub의 저장소에 업로드되도록 하기 위함입니다.
```
glossary에 따라 수정합니다.

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +## 추론하기 [[inference]]
```suggestion
## 추론하기[[inference]]
```

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +추론을 위해 영상를 불러오세요.
```suggestion
추론에 사용할 영상을 불러오세요:
```

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +좋습니다. 이제 미세 조정된 모델을 갖고 추론하는데 사용할 수 있습니다.
```suggestion
좋습니다. 이제 미세 조정된 모델을 갖고 추론하는 데 사용할 수 있습니다.
```

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +미세 조정된 모델을 추론에 사용하는 가장 간단한 방법은 [`pipeline`](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.VideoClassificationPipeline)에서 모델을 사용하는 것입니다. 모델로 영상 분류를 하기 위해 `pipeli
```suggestion
미세 조정된 모델을 추론에 사용하는 가장 간단한 방법은 [`pipeline`](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.VideoClassificationPipeline)에서 모델을 사용하는 것입니다. 모델로 영상 분류를 하기 위해 `pipeline`을 인스턴스화하고 영상을 전달하세요:
```

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +모델에 입력값을 넣고 `logits`을 반환받으세요.
```suggestion
모델에 입력값을 넣고 `logits`을 반환받으세요:
```

2023-05-02 10:14 UTC, sim-so commented on docs/source/ko/tasks/video_classification.mdx
> +`logits`을 디코딩하면, 우리는 다음을 얻을 수 있습니다.
```suggestion
`logits`을 디코딩하면, 다음 결과를 얻을 수 있습니다.
```

2023-05-02 10:26 UTC, 0525hhgus requested changes
좋은 번역 감사합니다! 긴 글인데 코드까지 고려해서 번역해주셨군요 👍 
아래 리뷰 코멘트 남깁니다 😄

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +## 미세 조정하기 위해 모델 불러오기 [[load-a-model-to-fine-tune]]
```suggestion
## 미세 조정하기 위해 모델 가져오기 [[load-a-model-to-fine-tune]]
```
54라인과 동일한 코멘트입니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +모델을 불러오는 동안, 다음과 같은 경고를 마주칠 수 있습니다.
```suggestion
모델을 가져오는 동안, 다음과 같은 경고를 마주칠 수 있습니다:
```
54라인과 동일한 코멘트입니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +추론을 위해 영상를 불러오세요.
```suggestion
추론을 위해 영상을 가져오세요:
```
54라인과 동일한 코멘트이며, 조사를 수정했습니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +데이터셋의 하위 집합이 다운로드 되면, 압축된 아카이브를 해제해야 합니다.
원문에서 `.` 대신 `:`이 사용되어 추가로 남깁니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +정렬된 영상의 경로는 다음과 같습니다.
```suggestion
(`정렬된`) 영상의 경로는 다음과 같습니다:
``` 
> The (`sorted`) video paths appear like so:

원문에서 괄호를 살려서 첨삭하였으니, 참고 부탁드립니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +전체 데이터셋의 구성은 다음과 같이 구성되어 있습니다.
추가로 원문에서 `.` 대신 `:`이 사용되어 코멘트 남깁니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +동일한 그룹 / 장면에 속하는 영상 클립은 파일 경로에서 "g"로 표시되어 있습니다. 예를 들자면, "v_ApplyEyeMakeup_g07_c04.avi"와 "v_ApplyEyeMakeup_g07_c06.avi" 이 있습니다. 이 둘은 같은 그룹입니다.
```suggestion
동일한 그룹 / 장면에 속하는 영상 클립은 파일 경로에서 `g`로 표시됩니다. 예를 들자면, `v_ApplyEyeMakeup_g07_c04.avi`와 `v_ApplyEyeMakeup_g07_c06.avi`이 있습니다. 이 둘은 동일한 그룹입니다.
```
원문에 맞춰 `"`를 '``로 변경하고, 단어를 이전 문장에서 사용된 `동일한`과 같이 수정했습니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +그 다음으로, 데이터셋에 존재하는 라벨을 추출합니다. 또한, 모델을 초기화할 때 도움이 될 딕셔너리(dictionary data type)를 생성합니다.
`:` 대신 `.` 사용되어 코멘트 남깁니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +이제 데이터셋에 특화된 전처리(transform)과 데이터셋 자체를 정의합니다. 먼저 훈련 데이터셋으로 시작합니다.
`.` -> `:`으로 번경되어야 하여 코멘트 남깁니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +같은 방식의 작업 흐름을 검증과 평가 셋에도 적용할 수 있습니다.
`.` -> `:`으로 번경되어야 하여 코멘트 남깁니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +다음으로, 평가지표를 불러올 함수를 정의해야 합니다. 이 함수는 예측값에서 평가지표를 계산하는 데 사용됩니다. 전처리로 수행해야 하는 작업은 예측된 로짓(logits)에 argmax 값을 취하는 것뿐입니다.
```suggestion
다음으로, 평가지표를 불러올 함수를 정의해야 합니다. 이 함수는 예측값에서 평가지표를 계산하는 데 사용됩니다. 전처리로 수행해야 하는 작업은 예측된 로짓(logits)에 argmax 값을 취하는 것뿐입니다:
```

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +그런 다음 이 모든 것을 데이터셋과 함께 `Trainer`에 전달하기만 하면 됩니다.
`.` -> `:` 추가합니다!

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +`train` 메소드를 호출하여 모델을 미세 조정하세요.
```suggestion
`train` 메소드를 호출하여 모델을 미세 조정하세요:
```

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +학습이 완료되면, 모델을 [`~transformers.Trainer.push_to_hub`] 메소드를 사용하여 허브에 공유하여 누구나 모델을 사용할 수 있도록 합니다.
```suggestion
학습이 완료되면, 모델을 [`~transformers.Trainer.push_to_hub`] 메소드를 사용하여 허브에 공유하여 누구나 모델을 사용할 수 있도록 합니다:
```

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +미세 조정된 모델을 추론에 사용하는 가장 간단한 방법은 [`pipeline`](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.VideoClassificationPipeline)에서 모델을 사용하는 것입니다. 모델로 영상 분류를 하기 위해 `pipeli
```suggestion
미세 조정된 모델을 추론에 사용하는 가장 간단한 방법은 [`pipeline`](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.VideoClassificationPipeline)에서 모델을 사용하는 것입니다. 모델로 영상 분류를 하기 위해 `pipeline`을 인스턴스화하고 영상를 전달하세요:
```

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +만약 원한다면 수동으로 `pipeline`의 결과를 재현할 수 있습니다.
```suggestion
만약 원한다면 수동으로 `pipeline`의 결과를 재현할 수 있습니다:
```

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +모델에 입력값을 넣고 `logits`을 반환받으세요.
```suggestion
모델에 입력값을 넣고 `logits`을 반환받으세요:
```

2023-05-02 10:26 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +`logits`을 디코딩하면, 우리는 다음을 얻을 수 있습니다.
```suggestion
`logits`을 디코딩하면, 우리는 다음을 얻을 수 있습니다:
```

2023-05-02 10:31 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +다음으로, 평가지표를 불러올 함수를 정의해야 합니다. 이 함수는 예측값에서 평가지표를 계산하는 데 사용됩니다. 전처리로 수행해야 하는 작업은 예측된 로짓(logits)에 argmax 값을 취하는 것뿐입니다.
원문에서 `.` 대신 `:`이 사용되어 추가로 코멘트 남깁니다!

2023-05-02 10:33 UTC, 0525hhgus commented on docs/source/ko/tasks/video_classification.mdx
> +`logits`을 디코딩하면, 우리는 다음을 얻을 수 있습니다.
`.` -> `:`으로 수정이 필요하여 코멘트 남깁니다!

2023-05-02 12:49 UTC, KIHOON71 commented on docs/source/ko/tasks/video_classification.mdx
> +<!--흠...-->
아 주석 부분 말씀이신가요??

2023-05-26 10:03 UTC, ArthurZucker commented
Hey! Sorry for the long delay. There seems to be 2 suggestions not adresses, should we wait for these? 🤗

2023-05-29 07:59 UTC, KIHOON71 commented
@ArthurZucker the suggestions that i didn't accept were about same sentences or ealier version of our glossary so you don't need to wait for the other suggestions to be accepted!! Thank you!!

2023-05-30 13:28 UTC, sgugger approved these changes
Thanks for your contribution!

2023-05-30 13:28 UTC, merged