🌐 [i18n-KO] Translated `torchscript.mdx` to Korean
huggingface/transformers pull request #23060
Opened 2023-04-29 00:51 UTC by sim-so

# What does this PR do?

Translated the `torchscript.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-04-29 01:06 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23060). All of your documentation changes will be reflected on that endpoint.

2023-04-30 01:26 UTC, gabrielwithappy commented on docs/source/ko/torchscript.mdx
> +# 입력 텍스트 토큰화하기
TOC가 없어도 되는지요?

2023-04-30 01:29 UTC, gabrielwithappy commented on docs/source/ko/torchscript.mdx
> +Neuron SDK는 다음과 같은 기능을 제공합니다:
Inf1. 이 약자로 Neuron SDK와 함께 기술되어야 하는 지 확인 부탁드립니다.

2023-04-30 01:33 UTC, gabrielwithappy commented on docs/source/ko/torchscript.mdx
> +`torch.neuron` 프레임워크 확장을 가져와 Python API를 통해 Neuron SDK의 구성 요소에 접근합니다:
확장 과 익스텐션 중 어떤게 좋을지 고민하면 좋을 것 같습니다.
`익스텐션`이라고 하면 SW적 추가기능 패키지가 떠오르는데 확장은 다른 의미로 받아들일 수 있을 것 같아요.

2023-04-30 01:45 UTC, sim-so commented on docs/source/ko/torchscript.mdx
> +# 입력 텍스트 토큰화하기
77에서 121까지 코드 블록이고, 해당 줄은 코드 내 주석입니다 😃

2023-04-30 03:41 UTC, sim-so commented on docs/source/ko/torchscript.mdx
> +Neuron SDK는 다음과 같은 기능을 제공합니다:
[AWS 문서](https://aws.amazon.com/ko/ec2/instance-types/inf1/)를 보면 인스턴스 이름으로 Inf1을 쓰고 있으며, Neuron SDK에 대한 설명이 함께 기술되어 있습니다. 혹시 문장에 어색한 점이 있을까요?

2023-05-01 11:35 UTC, 0525hhgus requested changes
Thank you for the good translation 😄 You even translated the new term carefully!
I leave reviews below.

2023-05-01 11:35 UTC, 0525hhgus commented on docs/source/en/torchscript.mdx
> +Python](torchscript#using-torchscript-in-python) to trace a `BertModel`. Import the
```suggestion
Python](serialization#using-torchscript-in-python) to trace a `BertModel`. Import the
```
원본 english 파일이 수정된 것 같습니다!

2023-05-01 11:45 UTC, sim-so commented on docs/source/ko/torchscript.mdx
> +`torch.neuron` 프레임워크 확장을 가져와 Python API를 통해 Neuron SDK의 구성 요소에 접근합니다:
```suggestion
`torch.neuron` 프레임워크 익스텐션을 가져와 Python API를 통해 Neuron SDK의 구성 요소에 접근합니다:
```
`익스텐션`으로 번역하고, 추후 논의된 단어가 있다면 변경하겠습니다!

2023-05-02 04:48 UTC, KIHOON71 commented on docs/source/ko/torchscript.mdx
> +더미 입력(dummy inputs)은 모델의 순방향 패스(forward pass)에 사용됩니다.
```suggestion
더미 입력(dummy inputs)은 모델의 순전파에 사용됩니다. 
```

2023-05-02 06:28 UTC, sim-so commented on docs/source/ko/torchscript.mdx
> +더미 입력(dummy inputs)은 모델의 순방향 패스(forward pass)에 사용됩니다.
```suggestion
더미 입력(dummy inputs)은 모델의 순전파(forward pass)에 사용됩니다. 
```
계속 떠올리고 싶었던 단어였어요! 감사합니다 😄

2023-05-02 06:35 UTC, sim-so commented on docs/source/ko/torchscript.mdx
> +- 더미 입력을 사용한 순방향 패스(forward pass)
```suggestion
- 더미 입력을 사용한 순전파(forward pass)
```

2023-05-02 13:09 UTC, sim-so commented
Could you review this PR? 😃 
@sgugger, @ArthurZucker, @eunseojo

2023-05-02 13:27 UTC, sgugger approved these changes
Thanks a lot!

2023-05-02 13:28 UTC, merged