🌐 [i18n-KO] Translated `tasks/zero_shot_object_detection.mdx` to Korean
huggingface/transformers pull request #23068
Opened 2023-04-29 15:57 UTC by HanNayeoniee

# What does this PR do?

Translated the `tasks/zero_shot_object_detection.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-04-29 16:14 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23068). All of your documentation changes will be reflected on that endpoint.

2023-05-01 01:51 UTC, gabrielwithappy commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +여기서는 [NASA](https://www.nasa.gov/multimedia/imagegallery/index.html) Great Images dataset의 일부인 우주비행사 에일린 콜린스(Eileen Collins) 사진을 사용하겠습니다.
Grate Images 가 데이터 세트 이름같습니다.
Grate Images 데이터 세트
는 어떻까요.

2023-05-01 01:51 UTC, gabrielwithappy commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +모델에 입력을 전달하고, 결과를 후처리하고 시각화합니다.
```suggestion
모델에 입력을 전달하고 결과를 후처리 및 시각화합니다.
```

2023-05-01 07:23 UTC, HanNayeoniee commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +여기서는 [NASA](https://www.nasa.gov/multimedia/imagegallery/index.html) Great Images dataset의 일부인 우주비행사 에일린 콜린스(Eileen Collins) 사진을 사용하겠습니다.
Grate Images 데이터 세트
로 수정했습니다!

2023-05-01 14:44 UTC, 0525hhgus requested changes
좋은 번역 감사합니다! 긴 글이었는데 꼼꼼하게 번역해주셨네요 💯 
아래 리뷰 코멘트 남겼습니다 😄

2023-05-01 14:44 UTC, 0525hhgus commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +개방형 어휘 탐지는 CLIP의 텍스트 인코더로 free-text 쿼리를 임베딩하고, 객체 분류와 지역화(localization) 헤드의 입력으로 사용합니다.
```suggestion
개방형 어휘 탐지는 CLIP의 텍스트 인코더로 free-text 쿼리를 임베딩하고, 객체 분류와 지역화 헤드의 입력으로 사용합니다.
```
24 라인에서 `localization`에 대해 한 번 언급되어서 여기서 사용하지 않아도 될 것 같습니다!

2023-05-01 14:44 UTC, 0525hhgus commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +## Text-prompted zero-shot object detection by hand[[textprompted-zeroshot-object-detection-by-hand]]
소제목이 영문으로 되어 있습니다!

2023-05-01 14:44 UTC, 0525hhgus commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +- 객체 탐지 일괄 처리
```suggestion
- 일괄 객체 탐지
```
192 라인의 `batch-processing` -> `일괄 처리` 번역과 전후 문장 형태를 고려하여 
`for batch object detection`를 `일괄 객체 탐지`로 번역되는게 조금 더 자연스러울 것 같습니다!

2023-05-01 23:25 UTC, HanNayeoniee commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +## Text-prompted zero-shot object detection by hand[[textprompted-zeroshot-object-detection-by-hand]]
`텍스트 프롬프트 기반 객체 탐지`로 수정했습니다.

2023-05-02 00:13 UTC, sgugger commented
Can you solve the conflicts so we can merge this PR?

2023-05-02 01:08 UTC, sim-so requested changes
모두 좋습니다! 고생 많으셨습니다 🙌

2023-05-02 01:08 UTC, sim-so commented on docs/source/ko/tasks/zero_shot_object_detection.mdx
> +candidate_labels는 이 예시처럼 간단한 단어일 수도 있고 좀 더 설명적인 단어일 수도 있습니다.
```suggestion
`candidate_labels`는 이 예시처럼 간단한 단어일 수도 있고 좀 더 설명적인 단어일 수도 있습니다.
```
`zero_shot_image_classification.mdx`에서와 같은 제안 드립니다!

2023-05-02 14:13 UTC, HanNayeoniee commented
> Can you solve the conflicts so we can merge this PR?

toctree file of this branch causes a conflict because it's different from the new version. 
As shown in  [[docs] Doc TOC updates](https://github.com/huggingface/transformers/pull/23049)
Let me fix this after I update korean toctree first!

2023-05-17 15:31 UTC, HanNayeoniee commented
Closed in favor of #23430

2023-05-17 15:31 UTC, closed without merging