🌐 [i18n-KO] doc: ko: Translate `multiple_choice.mdx`
huggingface/transformers pull request #23064
Opened 2023-04-29 13:46 UTC by gabrielwithappy

# What does this PR do?

Translated the `multiple_choice.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-04-29 14:01 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23064). All of your documentation changes will be reflected on that endpoint.

2023-04-30 01:09 UTC, gabrielwithappy commented
Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-04-30 06:52 UTC, HanNayeoniee reviewed
수고하셨습니다! 즐거운 연휴 보내세요 🙂

2023-04-30 06:52 UTC, HanNayeoniee commented on docs/source/ko/tasks/multiple_choice.mdx
> +- `레이블`: 올바른 문장 어미를 식별합니다.
- `레이블(label)`: 올바른 문장 어미를 식별합니다.

영어를 병기해서 label이 데이터의 구성에 해당하는 것을 알려주는건 어떨까요?

2023-04-30 06:52 UTC, HanNayeoniee commented on docs/source/ko/tasks/multiple_choice.mdx
> +다음 단계는 문장의 시작과 네 가지 가능한 어미를 처리하기 위해 BERT 토큰화기를 로드하는 것입니다:
다음 단계로 문장의 시작과 네 가지 가능한 어미를 처리하기 위해 BERT 토크나이저를 로드합니다:

- 토큰화기 -> 토크나이저
- 번역 느낌이 나는 "~하는 것입니다" 문장을 자연스러운 한국어로 수정해봤습니다.

2023-04-30 06:52 UTC, HanNayeoniee commented on docs/source/ko/tasks/multiple_choice.mdx
> +전체 데이터 집합에 전처리 기능을 적용하려면 🤗 Datasets [`~datasets.Dataset.map`] 메서드를 사용합니다. `batched=True`를 설정하여 데이터 집합의 여러 요소를 한 번에 처리하면 `map` 함수의 속도를 높일 수 있습니다:
전체 데이터 집합에 전처리 기능을 적용하려면 🤗 Datasets [`~datasets.Dataset.map`] 메소드를 사용합니다. `batched=True`를 설정하여 데이터 집합의 여러 요소를 한 번에 처리하면 `map` 함수의 속도를 높일 수 있습니다:

`method`를 `메소드`로 번역해야 저희 glossary와 통일성이 있어 보입니다!

2023-05-01 02:15 UTC, gabrielwithappy commented on docs/source/ko/tasks/multiple_choice.mdx
> +전체 데이터 집합에 전처리 기능을 적용하려면 🤗 Datasets [`~datasets.Dataset.map`] 메서드를 사용합니다. `batched=True`를 설정하여 데이터 집합의 여러 요소를 한 번에 처리하면 `map` 함수의 속도를 높일 수 있습니다:
checked :-)

2023-05-01 02:17 UTC, gabrielwithappy commented on docs/source/ko/tasks/multiple_choice.mdx
> +다음 단계는 문장의 시작과 네 가지 가능한 어미를 처리하기 위해 BERT 토큰화기를 로드하는 것입니다:
checked.
불러옵니다 로 추가 수정했습니다.
감사합니다. :-)

2023-05-01 12:06 UTC, 0525hhgus requested changes
좋은 번역 감사합니다! 태스크의 특징이 잘 드러난 번역이었다고 생각합니다 👍 
아래 리뷰를 남겼습니다 😄

2023-05-01 12:06 UTC, 0525hhgus commented on docs/source/ko/tasks/multiple_choice.mdx
> +훈련을 시작하기 전에 설정해야 할 마지막 두 가지는 예측의 정확도를 계산하고 모델을 Hub로 푸시하는 방법을 제공하는 것입니다. 이 두 가지 작업은 모두 [Keras 콜백](../main_classes/keras_callbacks)을 사용하여 수행할 수 있습니다.
```suggestion
훈련을 시작하기 전에 설정해야 할 마지막 두 가지는 예측의 정확도를 계산하고 모델을 허브로 푸시하는 방법을 제공하는 것입니다. 이 두 가지 작업은 모두 [Keras 콜백](../main_classes/keras_callbacks)을 사용하여 수행할 수 있습니다.
```
해당 문서에서 `허브`로 많이 사용되어 `허브`로 변경했습니다!

2023-05-01 12:35 UTC, sim-so requested changes
새로운 내용이 많은 문서였어요!
즐거운 연휴를 보내셨길 바라며, 몇 가지 수정 제안을 보내드립니다 😸

2023-05-01 12:35 UTC, sim-so commented on docs/source/ko/tasks/multiple_choice.mdx
> +먼저 🤗 Datasets  라이브러리에서 SWAG 데이터셋의 '일반' 구성을 불러옵니다:
```suggestion
먼저 🤗 Datasets  라이브러리에서 SWAG 데이터 세트의 '일반' 구성을 가져옵니다:
```

2023-05-01 12:35 UTC, sim-so commented on docs/source/ko/tasks/multiple_choice.mdx
> +- `레이블(label)`: 올바른 문장 어미를 식별합니다.
`ending`이 `어미`라는 뜻도 있지만 여기에서는 `종결(어구/어절)`에 더 가깝게 느껴집니다.
`종결 구절`은 너무 딱딱한 표현이라 고민되는데, `어미`는 문법적 의미이니 다른 표현을 고민해보면 좋을 것 같아요.
그리고 `ending`과 `label`의 한국어 표현을 써주신 것처럼, `startphrase`도 한국어 표현을 추가하는 것은 어떨까요?

2023-05-01 12:35 UTC, sim-so commented on docs/source/ko/tasks/multiple_choice.mdx
> +훈련 중에 메트릭을 포함하면 모델의 성능을 평가하는 데 도움이 되는 경우가 많습니다. 🤗[Evaluate](https://huggingface.co/docs/evaluate/index) 라이브러리를 사용하여 평가 방법을 빠르게 불러올 수 있습니다. 이 작업에서는 [accuracy](https://huggingface.co/spaces/evaluate-me
```suggestion
훈련 중에 메트릭을 포함하면 모델의 성능을 평가하는 데 도움이 되는 경우가 많습니다. 🤗[Evaluate](https://huggingface.co/docs/evaluate/index) 라이브러리를 사용하여 평가 방법을 빠르게 가져올 수 있습니다. 이 작업에서는 [accuracy](https://huggingface.co/spaces/evaluate-metric/accuracy) 지표를 가져옵니다(🤗 Evaluate [둘러보기](https://huggingface.co/docs/evaluate/a_quick_tour)를 참조하여 지표를 가져오고 계산하는 방법에 대해 자세히 알아보세요):
```
1. 현재 glossary 기준으로 수정합니다.
2. transformers 기준으로 `quick tour`는 `둘러보기`로 되어 있어서 맞추었습니다.

2023-05-01 12:35 UTC, sim-so commented on docs/source/ko/tasks/multiple_choice.mdx
> +이제 모델 훈련을 시작할 준비가 되었습니다! [`AutoModelForMultipleChoice`]로 BERT를 로드합니다:
```suggestion
이제 모델 훈련을 시작할 준비가 되었습니다! [`AutoModelForMultipleChoice`]로 BERT를 가져옵니다:
```

2023-05-01 12:35 UTC, sim-so commented on docs/source/ko/tasks/multiple_choice.mdx
> +Keras로 모델을 미세 조정하는 데 익숙하지 않다면 기본 튜토리얼 [여기](../training#train-a-tensorflow-model-with-keras)을 살펴보시기 바랍니다!
```suggestion
Keras로 모델을 미세 조정하는 데 익숙하지 않다면 기본 튜토리얼 [여기](../training#train-a-tensorflow-model-with-keras)를 살펴보시기 바랍니다!
```
`여기` 뒤에 오는 조사를 `를`로 바꾸었습니다.

2023-05-02 02:41 UTC, KIHOON71 commented on docs/source/ko/tasks/multiple_choice.mdx
> +- `레이블(label)`: 올바른 문장 어미를 식별합니다.
후행어절 혹은 후행문장 같은 표현은 어떨까요?

2023-05-02 15:32 UTC, wonhyeongseo commented on docs/source/ko/tasks/multiple_choice.mdx
> +- `레이블(label)`: 올바른 문장 어미를 식별합니다.
```suggestion
- `sent1` 및 `sent2`: 두 필드는 문장이 어떻게 시작되는지 나타내며, 합치면 `첫 구절(startphrase)` 필드가 됩니다.
- `마지막 구절(ending)`: 문장이 끝날 수 있는 수많은 구절 중 하나만 정답으로 삼습니다.
- `레이블(label)`: 문장에 알맞은 마지막 구절을 식별합니다.
```

2023-05-05 02:03 UTC, gabrielwithappy commented on docs/source/ko/tasks/multiple_choice.mdx
> +- `레이블(label)`: 올바른 문장 어미를 식별합니다.
구절은 온전하기 끝나지 않는 문장으로 구절이 문서에 가장 적합한 것 같습니다.
리뷰 감사드립니다. :-)

2023-05-05 03:06 UTC, gabrielwithappy commented
@sgugger, @ArthurZucker, @eunseojo 
May you please review this PR?

2023-05-05 15:36 UTC, sgugger approved these changes
Thanks for your contribution!

2023-05-05 15:36 UTC, merged