🌐 [i18n-KO] Translated `asr.mdx` to Korean
huggingface/transformers pull request #23106
Opened 2023-05-02 12:00 UTC by sim-so

# What does this PR do?

Translated the `<your_file>.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-05-02 12:46 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23106). All of your documentation changes will be reflected on that endpoint.

2023-05-02 13:17 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +## Load MInDS-14 dataset[[load-minds-14-dataset]]
```suggestion
## MInDS-14 데이터 세트 가져오기[[load-minds-14-dataset]]
```

2023-05-02 13:17 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +MInDS-14 데이터 세트의 샘플링 레이트는 8000kHz이므로(이 정보는 [데이터 세트 카드](https://huggingface.co/datasets/PolyAI/minds14)에서 확인할 수 있습니다), 사전 훈련된 Wav2Vec2 모델을 사용하려면 데이터 세트를 16000kHz로 리샘플링해야 합니다:
```suggestion
MInDS-14 데이터 세트의 샘플링 레이트는 8000kHz이므로([데이터 세트 카드](https://huggingface.co/datasets/PolyAI/minds14)에서 확인), 사전 훈련된 Wav2Vec2 모델을 사용하려면 데이터 세트를 16000kHz로 리샘플링해야 합니다:
```

2023-05-02 13:17 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +좋아요, 이제 모델을 파인튜닝했으니 추론에 사용할 수 있습니다!
```suggestion
좋아요, 이제 모델을 미세 조정했으니 추론에 사용할 수 있습니다!
```

2023-05-02 13:17 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +텍스트로 변환된 결과가 꽤 괜찮지만 더 좋을 수도 있습니다! 더 나은 결과를 얻으려면 더 많은 예제로 모델을 세밀하게 조정하세요!
```suggestion
텍스트로 변환된 결과가 꽤 괜찮지만 더 좋을 수도 있습니다! 더 나은 결과를 얻으려면 더 많은 예제로 모델을 미세 조정하세요!
```

2023-05-08 15:00 UTC, gabrielwithappy commented on docs/source/ko/tasks/asr.mdx
> +[`~Dataset.train_test_split`] 메소드를 사용하여 데이터 세트의 `train` 분할을 훈련 세트와 테스트 세트로 나누세요:
[`~Dataset.train_test_split`] 메소드를 사용하여 데이터 세트의 `train` 분할을 훈련 세트와 테스트 세트로 나누세요:
[`~Dataset.train_test_split`] 메소드를 사용하여 데이터 세트의 `train` 을 훈련 세트와 테스트 세트로 나누세요:

-> mind dataset에서 'train' key에 해당하는 데이터를 split하는 의미라서 분할이 빠지는 것이 좋을 것 같습니다.

2023-05-08 15:00 UTC, gabrielwithappy commented on docs/source/ko/tasks/asr.mdx
> +그런 다음 데이터 세트를 확인해보세요:
그런 다음 데이터 세트를 확인해보세요:
그리고 데이터 세트를 확인하세요:
를 추천합니다.

2023-05-08 15:16 UTC, gabrielwithappy commented on docs/source/ko/tasks/asr.mdx
> +🤗 Transformers에는 자동 음성 인식용 데이터 콜레이터가 없으므로 예제 배치를 생성하려면 [`DataCollatorWithPadding`]을 조정해야 합니다. 데이터 콜레이터는 이렇게 하면 텍스트와 레이블을 배치에서 가장 긴 요소의 길이에 동적으로 패딩하여 길이를 균일하게 합니다. `tokenizer` 함수에서 `padding=True`를 설정하
이렇게 하면 데이터 콜레이터는 텍스트와 레이블을 배치에서 가장 긴 요소의 길이에 동적으로 패딩하여 길이를 균일하게 합니다

2023-05-11 23:03 UTC, 0525hhgus requested changes
좋은 번역 감사합니다 👍
사전에 설명해주셔서 개념과 용어를 이해하기 수월하네요! 아래 리뷰를 남겼습니다 😀

2023-05-15 04:10 UTC, sim-so reviewed
성모님이 제안해주신 수정 사항을 반영합니다!

2023-05-15 04:10 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +[`~Dataset.train_test_split`] 메소드를 사용하여 데이터 세트의 `train` 분할을 훈련 세트와 테스트 세트로 나누세요:
```suggestion
[`~Dataset.train_test_split`] 메소드를 사용하여 데이터 세트의 `train`을 훈련 세트와 테스트 세트로 나누세요:
```
위 내용으로 수정하겠습니다!

2023-05-15 04:10 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +그런 다음 데이터 세트를 확인해보세요:
```suggestion
그리고 데이터 세트를 확인하세요:
```

2023-05-15 04:10 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +🤗 Transformers에는 자동 음성 인식용 데이터 콜레이터가 없으므로 예제 배치를 생성하려면 [`DataCollatorWithPadding`]을 조정해야 합니다. 데이터 콜레이터는 이렇게 하면 텍스트와 레이블을 배치에서 가장 긴 요소의 길이에 동적으로 패딩하여 길이를 균일하게 합니다. `tokenizer` 함수에서 `padding=True`를 설정하
```suggestion
🤗 Transformers에는 자동 음성 인식용 데이터 콜레이터가 없으므로 예제 배치를 생성하려면 [`DataCollatorWithPadding`]을 조정해야 합니다. 이렇게 하면 데이터 콜레이터는 텍스트와 레이블을 배치에서 가장 긴 요소의 길이에 동적으로 패딩하여 길이를 균일하게 합니다. `tokenizer` 함수에서 `padding=True`를 설정하여 텍스트를 패딩할 수 있지만, 동적 패딩이 더 효율적입니다.
```

2023-05-15 04:10 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +자동 음성 인식을 위해 모델을 미세 조정하는 더 자세한 예제는 영어 자동 음성 인식을 위한 [블로그 포스트](https://huggingface.co/blog/fine-tune-wav2vec2-english)과 다국어 자동 음성 인식을 위한 [포스트](https://huggingface.co/blog/fine-tune-xlsr-wav2vec2)를 참조하세
```suggestion
자동 음성 인식을 위해 모델을 미세 조정하는 더 자세한 예제는 영어 자동 음성 인식을 위한 [블로그 포스트](https://huggingface.co/blog/fine-tune-wav2vec2-english)와 다국어 자동 음성 인식을 위한 [포스트](https://huggingface.co/blog/fine-tune-xlsr-wav2vec2)를 참조하세요.
```

2023-05-15 04:10 UTC, sim-so commented on docs/source/ko/tasks/asr.mdx
> +추론에 사용할 오디오 파일을 가져오세요. 필요한 경우 오디오 파일의 샘플링 비율을 모델의 샘플링 비율에 맞게 리샘플링하는 것을 잊지 마세요!
```suggestion
추론에 사용할 오디오 파일을 가져오세요. 필요한 경우 오디오 파일의 샘플링 비율을 모델의 샘플링 레이트에 맞게 리샘플링하는 것을 잊지 마세요!
```

2023-05-15 08:37 UTC, sim-so commented
Hope you have a great week!
Could you please review this PR?
@sgugger, @ArthurZucker, @eunseojo

2023-05-16 13:22 UTC, sgugger approved these changes
Thanks for your contribution!

2023-05-16 13:22 UTC, merged