🌐 [i18n-KO] Translated object_detection.mdx to Korean
huggingface/transformers pull request #23164
Opened 2023-05-05 10:53 UTC by KIHOON71

# What does this PR do?
Translated the object_detection.mdx file of the documentation to Korean.
Thank you in advance for your review.

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing

- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. [[lowercased-header]])
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

2023-05-05 11:11 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23164). All of your documentation changes will be reflected on that endpoint.

2023-05-21 10:50 UTC, 0525hhgus requested changes
좋은 번역 감사합니다 👍 아래 짧은 리뷰 남겼습니다!

2023-05-21 10:50 UTC, 0525hhgus commented on docs/source/ko/tasks/object_detection.mdx
> +이 메서드는 데이터 세트의 요소를 가져올 때마다 전처리 함수를 적용합니다.
```suggestion
이 메소드는 데이터 세트의 요소를 가져올 때마다 전처리 함수를 적용합니다.
```
Glossary에 맞춰서 수정했습니다!

2023-05-21 10:50 UTC, 0525hhgus commented on docs/source/ko/tasks/object_detection.mdx
> +1. [`AutoModelForObjectDetection`]을 사용하여 전처리와 동일한 체크포인트를 사용하여 모델을 로드합니다.
```suggestion
1. [`AutoModelForObjectDetection`]을 사용하여 전처리와 동일한 체크포인트를 사용하여 모델을 가져옵니다.
```

2023-05-25 14:28 UTC, sim-so requested changes
고생 많으셨습니다!
조금 늦었지만 리뷰한 내용을 전달 드립니다 😅

2023-05-25 14:28 UTC, sim-so commented on docs/source/ko/tasks/object_detection.mdx
> +그러나 `objects` 내부의 필드의 그룹화는 DETR이 요구하는 어노테이션 형식과 다릅니다. 따라서 이 데이터를 학습에 사용하기 전에 전처리를 적용해야 합니다.
```suggestion
그러나 `objects` 내부의 필드 그룹은 DETR이 요구하는 어노테이션 형식과 다릅니다. 따라서 이 데이터를 학습에 사용하기 전에 전처리를 적용해야 합니다.
```
`의`가 두 번인 것이 어색하여 수정합니다! 그리고 여기서 `grouping`은 한국어로 `그룹`이 되어도 괜찮을 것 같습니다.

2023-05-25 14:28 UTC, sim-so commented on docs/source/ko/tasks/object_detection.mdx
> +`image_processor`에 이미지를 전달하기 전에, 데이터 세트에 두 개의 전처리를 적용해야 합니다:
```suggestion
`image_processor`에 이미지를 전달하기 전에, 데이터 세트에 두 가지 전처리를 적용해야 합니다:
```

2023-05-25 14:28 UTC, sim-so commented on docs/source/ko/tasks/object_detection.mdx
> +이전 단계에서 만든 전처리 함수를 🤗 Datasets의 [`~datasets.Dataset.with_transform`] 메서드를 사용하여 데이터 세트 전체에 적용합니다.
```suggestion
이전 단계에서 만든 전처리 함수를 🤗 Datasets의 [`~datasets.Dataset.with_transform`] 메소드를 사용하여 데이터 세트 전체에 적용합니다.
```

2023-05-25 14:28 UTC, sim-so commented on docs/source/ko/tasks/object_detection.mdx
> +3. 모델, 데이터 세트, 이미지 프로세서 및 데이터 콜레이터와 함께 [`Trainer`]에 학습 인자를 전달합니다.
```suggestion
3. 모델, 데이터 세트, 이미지 프로세서 및 데이터 콜레이터와 함께 [`Trainer`]에 훈련 인수를 전달합니다.
```
glossary에서 `training`은 `훈련`, `arguments`는 `인수`로 정해두었습니다!
문서 내 다른 `training` 등장 부분에도 참고 부탁 드립니다.

2023-05-25 14:28 UTC, sim-so commented on docs/source/ko/tasks/object_detection.mdx
> +먼저, cppe5["test"] 세트를 준비합니다: 어노테이션을 포맷에 맞게 만들고 데이터를 디스크에 저장합니다.
```suggestion
먼저, `cppe5["test"]` 세트를 준비합니다: 어노테이션을 포맷에 맞게 만들고 데이터를 디스크에 저장합니다.
```

2023-05-25 14:28 UTC, sim-so requested changes
고생 많으셨습니다!
조금 늦었지만 리뷰한 내용을 전달 드립니다 😅

2023-05-30 07:44 UTC, wonhyeongseo requested changes
좋은 번역 감사합니다! 💯

2023-05-30 07:44 UTC, wonhyeongseo commented on docs/source/ko/tasks/object_detection.mdx
> + 1. 합성곱 백본(인풋 데이터의 특성을 추출하는 합성곱 네트워크)과 인코더-디코더 트랜스포머 모델을 결합한 [DETR](https://huggingface.co/docs/transformers/model_doc/detr) 모델을 [CPPE-5](https://huggingface.co/datasets/cppe-5) 데이터 세트에 대해 미세조정 하기.
아래 방법 대신에 이 줄의 끝점을 없애도 될 것 같아요!
```suggestion
 1. 합성곱 백본(인풋 데이터의 특성을 추출하는 합성곱 네트워크)과 인코더-디코더 트랜스포머 모델을 결합한 [DETR](https://huggingface.co/docs/transformers/model_doc/detr) 모델을 [CPPE-5](https://huggingface.co/datasets/cppe-5) 데이터 세트에 대해 미세조정 하기
```

2023-05-30 07:44 UTC, wonhyeongseo commented on docs/source/ko/tasks/object_detection.mdx
> +이 튜토리얼에서 설명하는 작업은 다음 모델 아키텍처에서 지원됩니다:
```suggestion
이 튜토리얼의 태스크는 다음 모델 아키텍처에서 지원됩니다:
```

2023-05-30 07:44 UTC, wonhyeongseo commented on docs/source/ko/tasks/object_detection.mdx
> +이러한 바운딩 박스를 "넘어가는 것(run away)"은 훈련 중에 오류를 발생시킬 수 있기에 이 단계에서 처리해야 합니다.
아주 좋아요 👍

2023-06-02 08:50 UTC, ArthurZucker approved these changes
Congrats on getting this long one done! 🔥 
Thanks!

2023-06-02 11:43 UTC, sgugger approved these changes

2023-06-02 11:43 UTC, merged