🌐 [i18n-KO] Translated `tasks/monocular_depth_estimation.mdx` to Korean
huggingface/transformers pull request #23621
Opened 2023-05-21 05:31 UTC by HanNayeoniee

# What does this PR do?

Translated the `tasks/monocular_depth_estimation.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-05-21 05:45 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23621). All of your documentation changes will be reflected on that endpoint.

2023-05-21 06:30 UTC, sim-so requested changes
관심 있던 주제의 문서를 읽을 수 있어서 좋았습니다!
고생 많으셨습니다😄

2023-05-21 06:30 UTC, sim-so commented on docs/source/ko/tasks/monocular_depth_estimation.mdx
> +단일 영상 기반 깊이 추정에는 3D 재구성, 증강 현실, 자율 주행, 로봇 공학 등 다양한 분야에서 응용됩니다.
```suggestion
단일 영상 기반 깊이 추정은 3D 재구성, 증강 현실, 자율 주행, 로봇 공학 등 다양한 분야에서 응용됩니다. 
```

2023-05-21 06:30 UTC, sim-so commented on docs/source/ko/tasks/monocular_depth_estimation.mdx
> +[Hugging Face Hub 체크포인트](https://huggingface.co/models?pipeline_tag=depth-estimation&sort=downloads) 에서 파이프라인을 초기화합니다:
```suggestion
[Hugging Face Hub 체크포인트](https://huggingface.co/models?pipeline_tag=depth-estimation&sort=downloads)에서 파이프라인을 초기화합니다:
```

2023-05-21 06:30 UTC, sim-so commented on docs/source/ko/tasks/monocular_depth_estimation.mdx
> +[Hugging Face Hub 체크포인트](https://huggingface.co/models?pipeline_tag=depth-estimation&sort=downloads)에서 모델과 관련 프로세서를 로드하는 것부터 시작합니다.
```suggestion
[Hugging Face Hub 체크포인트](https://huggingface.co/models?pipeline_tag=depth-estimation&sort=downloads)에서 모델과 관련 프로세서를 가져오는 것부터 시작합니다.
```

2023-05-21 06:30 UTC, sim-so commented on docs/source/ko/tasks/monocular_depth_estimation.mdx
> +필요한 이미지 변환을 처리하는 'image_processor'를 사용하여 모델에 대한 이미지 입력을 준비합니다.
```suggestion
필요한 이미지 변환을 처리하는 `image_processor`를 사용하여 모델에 대한 이미지 입력을 준비합니다.
```

2023-05-21 06:30 UTC, sim-so commented on docs/source/ko/tasks/monocular_depth_estimation.mdx
> +'image_processor'는 크기 조정 및 정규화 등 필요한 이미지 변환을 처리합니다:
```suggestion
`image_processor`는 크기 조정 및 정규화 등 필요한 이미지 변환을 처리합니다:
```

2023-05-21 06:30 UTC, sim-so requested changes
관심 있던 주제의 문서를 읽을 수 있어서 좋았습니다!
고생 많으셨습니다😄

2023-05-21 06:30 UTC, sim-so requested changes
관심 있던 주제의 문서를 읽을 수 있어서 좋았습니다!
고생 많으셨습니다😄

2023-05-22 23:21 UTC, 0525hhgus requested changes
좋은 번역 감사합니다 😀 
저는 다른 피드백 없이 toc 부분만 리뷰 남겼습니다 👍

2023-05-22 23:21 UTC, 0525hhgus commented on docs/source/ko/tasks/monocular_depth_estimation.mdx
> +## 직접 깊이 추정 추론하기
```suggestion
## 직접 깊이 추정 추론하기[[depth-estimation-inference-by-hand]]
```
TOC를 추가했습니다!

2023-05-23 13:54 UTC, ArthurZucker approved these changes
Thanks for keeping up with the effort! 
LGTM!

2023-05-23 13:54 UTC, merged