🌐 [i18n-KO] Translated `pad_truncation.mdx` to Korean
huggingface/transformers pull request #23823
Opened 2023-05-28 01:49 UTC by sim-so

# What does this PR do?

Translated the `pad_truncation.mdx` file of the documentation to Korean.
Thank you in advance for your review!

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-05-28 02:03 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23823). All of your documentation changes will be reflected on that endpoint.

2023-05-28 02:18 UTC, sim-so commented on docs/source/ko/pad_truncation.mdx
> +|                                      | 특정 길이로 패딩                  | Not possible                                                                              |
```suggestion
|                                      | 특정 길이로 패딩                  | 사용 불가                                                                              |
```

2023-05-28 02:18 UTC, sim-so commented on docs/source/ko/pad_truncation.mdx
> +|                                      | 모델의 최대 입력 길이로 패딩       | Not possible                                                                             |
```suggestion
|                                      | 모델의 최대 입력 길이로 패딩       | 사용 불가                                                                             |
```

2023-05-28 02:18 UTC, sim-so commented on docs/source/ko/pad_truncation.mdx
> +    이렇게 하면 적절한 길이에 도달할 때까지 시퀀스 쌍에서 가장 긴 시퀀스의 토큰을 제거하며 토큰을 하나씩 잘라냅니다.
```suggestion
    시퀀스 쌍에서 가장 긴 시퀀스의 토큰을 적절한 길이에 도달할 때까지 하나씩 제거합니다.
```

2023-05-28 02:18 UTC, sim-so commented on docs/source/ko/pad_truncation.mdx
> +    이것은 시퀀스 쌍(또는 시퀀스 쌍의 배치)가 제공된 경우 쌍의 두 번째 문장만 잘라냅니다.
```suggestion
    시퀀스 쌍(또는 시퀀스 쌍의 배치)가 제공된 경우 쌍의 두 번째 문장만 잘라냅니다.
```

2023-05-28 02:18 UTC, sim-so commented on docs/source/ko/pad_truncation.mdx
> +    이것은 시퀀스 쌍(또는 시퀀스 쌍의 배치)가 제공된 경우 쌍의 첫 번째 문장만 잘라냅니다.
```suggestion
    시퀀스 쌍(또는 시퀀스 쌍의 배치)가 제공된 경우 쌍의 첫 번째 문장만 잘라냅니다.
```

2023-05-29 23:16 UTC, 0525hhgus requested changes
좋은 번역 감사합니다 👍
옵션이 적용되는 시퀀스를 명확히 번역해주셔서 쉽게 이해할 수 있었습니다! 
아래 짧은 리뷰를 남깁니다 😀

2023-05-30 08:10 UTC, wonhyeongseo approved these changes
연휴 잘 보내셨나요? 좋은 번역 감사합니다!
LGTM!

2023-05-31 08:18 UTC, sim-so commented
Could you review this PR? 😃 
@sgugger, @ArthurZucker, @eunseojo

2023-05-31 08:23 UTC, ArthurZucker approved these changes
Thanks for working on this 😉

2023-05-31 08:24 UTC, merged