🌐 [i18n-KO] Translated `language-modeling.mdx
huggingface/transformers pull request #23969
Opened 2023-06-03 05:13 UTC by wonhyeongseo

# What does this PR do?

Translated the `language-modeling.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-06-03 06:08 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_23969). All of your documentation changes will be reflected on that endpoint.

2023-06-03 10:20 UTC, sim-so requested changes
한 번에 많은 문서를 번역하시느라 고생 많으셨어요!
glossary 관련 의견 몇 가지를 전달 드려요.

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +위의 예제에서 알 수 있듯이, `text` 필드는 `answers` 아래에 중첩되어 있습니다. 따라서 [`flatten`](https://huggingface.co/docs/datasets/process.html#flatten) 메서드를 사용하여 중첩 구조에서 `text` 하위 필드를 추출해야 합니다.
```suggestion
위의 예제에서 알 수 있듯이, `text` 필드는 `answers` 아래에 중첩되어 있습니다. 따라서 [`flatten`](https://huggingface.co/docs/datasets/process.html#flatten) 메소드를 사용하여 중첩 구조에서 `text` 하위 필드를 추출해야 합니다.
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +이 전처리 함수를 전체 데이터셋에 적용하려면 🤗 Datasets [`~datasets.Dataset.map`] 메서드를 사용하세요. `batched=True`로 설정하여 데이터셋의 여러 요소를 한 번에 처리하고, `num_proc`를 증가시켜 프로세스 수를 늘릴 수 있습니다. 필요 없는 열은 제거하세요:
```suggestion
이 전처리 함수를 전체 데이터 세트에 적용하려면 🤗 Datasets [`~datasets.Dataset.map`] 메소드를 사용하세요. `batched=True`로 설정하여 데이터셋의 여러 요소를 한 번에 처리하고, `num_proc`를 증가시켜 프로세스 수를 늘릴 수 있습니다. 필요 없는 열은 제거하세요:
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +전체 데이터셋에 `group_texts` 함수를 적용하세요:
```suggestion
전체 데이터 세트에 `group_texts` 함수를 적용하세요:
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +이제 데이터셋은 시퀀스가 토큰화됐지만, 일부 시퀀스는 모델의 최대 입력 길이보다 길 수 있습니다.
```suggestion
이제 데이터 세트는 시퀀스가 토큰화됐지만, 일부 시퀀스는 모델의 최대 입력 길이보다 길 수 있습니다.
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +## ELI5 데이터셋 불러오기[[load-eli5-dataset]]
```suggestion
## ELI5 데이터 세트 불러오기[[load-eli5-dataset]]
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +먼저, 🤗 Datasets 라이브러리에서 r/askscience의 작은 하위 집합인 ELI5 데이터셋을 불러옵니다.
```suggestion
먼저, 🤗 Datasets 라이브러리에서 r/askscience의 작은 하위 집합인 ELI5 데이터 세트를 불러옵니다.
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +이를 통해 전체 데이터셋에서 학습하는 데 더 많은 시간을 투자하기 전에, 실험해봄으로써 모든 것이 작동하는지 확인할 수 있습니다.
```suggestion
이를 통해 전체 데이터 세트에서 학습하는 데 더 많은 시간을 투자하기 전에, 실험해봄으로써 모든 것이 작동하는지 확인할 수 있습니다.
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +2. 훈련 인수를 [`Trainer`]에 모델, 데이터셋 및 데이터 콜레이터와 함께 전달하세요.
```suggestion
2. 훈련 인수를 [`Trainer`]에 모델, 데이터 세트 및 데이터 콜레이터와 함께 전달하세요.
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +훈련이 완료되면 [`~transformers.Trainer.evaluate`] 메서드를 사용하여 모델을 평가하고 퍼플렉서티를 얻을 수 있습니다:
```suggestion
훈련이 완료되면 [`~transformers.Trainer.evaluate`] 메소드를 사용하여 모델을 평가하고 퍼플렉서티를 얻을 수 있습니다:
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +그런 다음 [`~transformers.Trainer.push_to_hub`] 메서드를 사용하여 모델을 허브에 공유하세요. 이렇게 하면 누구나 모델을 사용할 수 있습니다:
```suggestion
그런 다음 [`~transformers.Trainer.push_to_hub`] 메소드를 사용하여 모델을 허브에 공유하세요. 이렇게 하면 누구나 모델을 사용할 수 있습니다:
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +[`~transformers.TFPreTrainedModel.prepare_tf_dataset`]을 사용하여 데이터셋을 `tf.data.Dataset` 형식으로 변환하세요:
```suggestion
[`~transformers.TFPreTrainedModel.prepare_tf_dataset`]을 사용하여 데이터 세트를 `tf.data.Dataset` 형식으로 변환하세요:
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +마지막으로, 모델을 훈련하기 위해 [`fit`](https://keras.io/api/models/model_training_apis/#fit-method)을 호출하세요. 훈련 데이터셋, 검증 데이터셋, epoch 수 및 콜백을 전달하세요:
glossary를 참고하여 `epoch`을 `에폭`으로 수정합니다.
```suggestion
마지막으로, 모델을 훈련하기 위해 [`fit`](https://keras.io/api/models/model_training_apis/#fit-method)을 호출하세요. 훈련 데이터 세트, 검증 데이터 세트, 에폭 수 및 콜백을 전달하세요:
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +[`~transformers.generation_utils.GenerationMixin.generate`] 메서드를 사용하여 텍스트를 생성하세요. 생성을 제어하는 다양한 텍스트 생성 전략과 매개변수에 대한 자세한 내용은 [텍스트 생성 전략](../generation_strategies) 페이지를 확인하세요.
```suggestion
[`~transformers.generation_utils.GenerationMixin.generate`] 메소드를 사용하여 텍스트를 생성하세요. 생성을 제어하는 다양한 텍스트 생성 전략과 매개변수에 대한 자세한 내용은 [텍스트 생성 전략](../generation_strategies) 페이지를 확인하세요.
```

2023-06-03 10:20 UTC, sim-so commented on docs/source/ko/tasks/language_modeling.mdx
> +[`~transformers.generation_tf_utils.TFGenerationMixin.generate`] 메서드를 사용하여 요약을 생성하세요. 생성을 제어하는 다양한 텍스트 생성 전략과 매개변수에 대한 자세한 내용은 [텍스트 생성 전략](../generation_strategies) 페이지를 확인하세요.
```suggestion
[`~transformers.generation_tf_utils.TFGenerationMixin.generate`] 메소드를 사용하여 요약을 생성하세요. 생성을 제어하는 다양한 텍스트 생성 전략과 매개변수에 대한 자세한 내용은 [텍스트 생성 전략](../generation_strategies) 페이지를 확인하세요.
```

2023-06-06 04:03 UTC, wonhyeongseo reviewed
@sim-so 님 감사합니다!

2023-06-06 04:03 UTC, wonhyeongseo commented on docs/source/ko/_toctree.yml
> +        title: 인과 언어 모델링(Causal language modeling)
```suggestion
        title: 인과적 언어 모델링(Causal language modeling)
```
정확하십니다. 제가 용어집을 꼼꼼히 살피지 못했어요. 잡아주셔서 감사합니다!

2023-06-06 04:13 UTC, wonhyeongseo commented
@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

2023-06-06 08:38 UTC, ArthurZucker approved these changes
Looks good to go! Thanks for the contribution 😉

2023-06-06 13:08 UTC, merged