🌐 [i18n-KO] Translated `tflite.mdx` to Korean
huggingface/transformers pull request #24435
Opened 2023-06-22 22:22 UTC by 0525hhgus

# What does this PR do?

Translated the `tflite.mdx` file of the documentation to Korean 😄 
Thank you in advance for your review!

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-06-22 22:40 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24435). All of your documentation changes will be reflected on that endpoint.

2023-06-24 12:19 UTC, wonhyeongseo requested changes
간단한 수정만 거쳤습니다. 이번주에 번역해주셔서 정말 감사드립니다 @0525hhgus 님! 👍

2023-06-24 12:19 UTC, wonhyeongseo commented on docs/source/ko/tflite.md
> +명령줄에서 도움말을 살펴보세요:
```suggestion
터미널에서 도움말을 살펴보세요:
```

2023-06-24 12:19 UTC, wonhyeongseo commented on docs/source/ko/tflite.md
> +예를 들어 🤗 Hub에서 `bert-base-uncased` 모델의 체크포인트를 내보내려면, 다음 명령을 실행하세요:
```suggestion
예를 들어 🤗 Hub에서의 `bert-base-uncased` 모델 체크포인트를 내보내려면, 다음 명령을 실행하세요:
```

2023-06-24 12:19 UTC, wonhyeongseo commented on docs/source/ko/tflite.md
> +체크포인트 이름 대신 `model` 인수에 `local_path`를 전달합니다.
```suggestion
위 예제는 🤗 Hub에서의 체크포인트를 내보내는 방법을 보여줍니다. 로컬 모델을 내보낸다면, 먼저 모델 가중치와 토크나이저 파일이 모두 같은 디렉터리( `local_path` )에 저장됐는지 확인하세요. CLI를 사용할때, 🤗 Hub에서의 체크포인트 이름 대신 `model` 인수에 `local_path`를 전달하면 됩니다. 
```

2023-06-27 11:24 UTC, 0525hhgus commented on docs/source/ko/tflite.md
> +명령줄에서 도움말을 살펴보세요:
CLI가 번역하기 조금 애매했는데, 터미널로 하니 이해가 수월하네요 👍

2023-06-27 11:34 UTC, sim-so commented
번역 문장 모두 좋습니다. 앞서 반영된 내용 외에 추가 의견 없습니다! 👍

2023-06-27 12:17 UTC, 0525hhgus commented
May you please review this PR? 😄 
@sgugger, @ArthurZucker, @eunseojo

2023-06-27 12:18 UTC, sgugger approved these changes
Thanks!

2023-06-27 12:18 UTC, merged