Fixed OwlViTModel inplace operations
huggingface/transformers pull request #24529
Opened 2023-06-27 16:37 UTC by pasqualedem

# What does this PR do?

This PR replaces the "/=" operator in OwlViTModel which causes an error in the backward pass with the non-inplace version.

Fixes #24525 

#24525 

## Who can review?

@ydshieh

2023-06-27 16:45 UTC, ydshieh approved these changes
Thank you for opening the PR to fix it.
LGTM, but ping a core maintainer @sgugger to have a look too.

2023-06-27 16:46 UTC, ydshieh commented on src/transformers/models/owlvit/modeling_owlvit.py
> +        image_class_embeds = image_class_embeds / torch.linalg.norm(image_class_embeds, dim=-1, keepdim=True) + 1e-6
wait. I think we should do

(torch.linalg.norm(image_class_embeds, dim=-1, keepdim=True) + 1e-6) instead

2023-06-27 16:49 UTC, ydshieh requested changes

2023-06-27 16:49 UTC, ydshieh commented on src/transformers/models/owlvit/modeling_owlvit.py
> +        image_class_embeds = image_class_embeds / torch.linalg.norm(image_class_embeds, dim=-1, keepdim=True) + 1e-6
```suggestion
        image_class_embeds = image_class_embeds / (torch.linalg.norm(image_class_embeds, dim=-1, keepdim=True) + 1e-6)
```

2023-06-27 16:49 UTC, ydshieh commented on src/transformers/models/owlvit/modeling_owlvit.py
> +        query_embeds = query_embeds / torch.linalg.norm(query_embeds, dim=-1, keepdim=True) + 1e-6
```suggestion
        query_embeds = query_embeds / (torch.linalg.norm(query_embeds, dim=-1, keepdim=True) + 1e-6)
```

2023-06-27 17:19 UTC, sgugger approved these changes
LGTM with @ydshieh suggestions, thanks!

2023-06-27 17:35 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24529). All of your documentation changes will be reflected on that endpoint.

2023-06-29 05:41 UTC, ydshieh commented
@pasqualedem Could you apply the commit suggestions, then we can merge 🙏 Thanks.

2023-06-29 08:11 UTC, ydshieh approved these changes
Thanks again!

2023-06-29 08:17 UTC, merged

2023-06-29 08:34 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24529). All of your documentation changes will be reflected on that endpoint.