🌐 [i18n-KO] Translated `custom_tools.mdx` to Korean
huggingface/transformers pull request #24580
Opened 2023-06-29 15:03 UTC by sim-so

# What does this PR do?

Translated the `custom_tools.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

Team PseudoLab, may you please review this PR? 
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-06-29 15:19 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24580). All of your documentation changes will be reflected on that endpoint.

2023-06-30 18:35 UTC, jungnerd commented
LGTM👍

2023-07-11 17:49 UTC, amyeroberts commented
Thanks for the PR, @sim-so! 

There's since been an update on main to all of our documentation files. Could you update the extension from `.mdx` to `.md` to match please?

2023-07-15 00:52 UTC, 0525hhgus requested changes
It's a new type of documentation, but you translated it perfectly! 
Thanks for the good translation 😀
Please check out the review below!

2023-07-16 00:15 UTC, sim-so commented on docs/source/ko/custom_tools.mdx
> +`.chat`을 실행하면 사용자의 입력 또는 *task*가 미완성된 양식의 예시로 캐스팅됩니다:
> task가 프롬프트에 있는 "Task: "를 해석될 수도 있어서 참고 부탁드립니다!
비슷한 고민을 하다 후자로 이해하고 `task`를 그대로 썼었는데요, 이 문장에서는 번역한 단어가 더 자연스러운 것 같아요. 수정 제안 감사합니다!

2023-07-16 00:28 UTC, sim-so commented
Thanks for letting me know about the change! @amyeroberts! 
I updated the extention to `.md`.

Could you review this PR?
@sgugger, @ArthurZucker, @eunseojo

2023-07-17 11:04 UTC, sgugger approved these changes
Thanks for your contribution!

2023-07-17 11:04 UTC, merged