🌐 [i18n-KO] Translated`tasks/document_question_answering.md` to Korean
huggingface/transformers pull request #24588
Opened 2023-06-30 08:21 UTC by jungnerd

# What does this PR do?

Translated the `tasks/document_question_answering.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-06-30 08:39 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24588). All of your documentation changes will be reflected on that endpoint.

2023-07-15 01:04 UTC, 0525hhgus requested changes
It was easy to understand, thanks to the careful translation of the annotations👍
Thanks for the good translation!
I commented below a review related to glossary.

2023-07-16 00:50 UTC, sim-so requested changes
몇 가지 수정 의견 보내 드리오니 참고 부탁 드립니다.
고생 많으셨습니다! 😸

2023-07-16 00:50 UTC, sim-so commented on docs/source/ko/tasks/document_question_answering.md
> +DocVQA의 전체 데이터 세트를 사용하고 싶다면, [DocVQA homepage](https://rrc.cvc.uab.es/?ch=17)에 가입 후 다운로드 할 수 있습니다. 전체 데이터 세트를 다운로드 했다면, 이 가이드를 계속 진행하기 위해 [🤗 dataset에 파일을 로드하는 방법](https://huggingface.co/docs/datasets
```suggestion
DocVQA의 전체 데이터 세트를 사용하고 싶다면, [DocVQA homepage](https://rrc.cvc.uab.es/?ch=17)에 가입 후 다운로드 할 수 있습니다. 전체 데이터 세트를 다운로드 했다면, 이 가이드를 계속 진행하기 위해 [🤗 dataset에 파일을 가져오는 방법](https://huggingface.co/docs/datasets/loading#local-and-remote-files)을 확인하세요.
```

2023-07-16 00:50 UTC, sim-so commented on docs/source/ko/tasks/document_question_answering.md
> +이 가이드에서 사용하는 LayoutLMv2 체크포인트는 `max_position_embeddings = 512`로 훈련되었습니다(이 정보는 [checkpoint's `config.json` file](https://huggingface.co/microsoft/layoutlmv2-base-uncased/blob/main/config.json#L18)에서 확
```suggestion
이 가이드에서 사용하는 LayoutLMv2 체크포인트는 `max_position_embeddings = 512`로 훈련되었습니다(이 정보는 [체크포인트의 `config.json` 파일](https://huggingface.co/microsoft/layoutlmv2-base-uncased/blob/main/config.json#L18)에서 확인할 수 있습니다).
```

2023-07-16 00:50 UTC, sim-so commented on docs/source/ko/tasks/document_question_answering.md
> +문맥은 OCR 엔진의 출력에서 가져오며, 여기서는 Google의 테서랙트(Tesseract)를 사용합니다.
```suggestion
문맥은 OCR 엔진의 출력에서 가져오며, 여기서는 Google의 Tesseract를 사용합니다.
```
Transformers를 한국어로 쓰지 않는 규칙을 Tesseract에도 적용해야 하지 않을까 생각해 보았습니다. 
참고 부탁 드립니다!

2023-07-16 00:50 UTC, sim-so commented on docs/source/ko/tasks/document_question_answering.md
> +위에서 언급한 전처리 외에도 모델울 위해 레이블을 추가해야 합니다. 🤗 Transformers의 `xxxForQuestionAnswering` 모델의 경우, 레이블은 `start_positions`와 `end_positions`로 구성되며 어떤 토큰이 답변의 시작과 끝에 있는지를 나타냅니다.
```suggestion
위에서 언급한 전처리 외에도 모델 위해 레이블을 추가해야 합니다. 🤗 Transformers의 `xxxForQuestionAnswering` 모델의 경우, 레이블은 `start_positions`와 `end_positions`로 구성되며 어떤 토큰이 답변의 시작과 끝에 있는지를 나타냅니다.
```

2023-07-16 00:57 UTC, wonhyeongseo commented on docs/source/ko/tasks/document_question_answering.md
> +위에서 언급한 전처리 외에도 모델울 위해 레이블을 추가해야 합니다. 🤗 Transformers의 `xxxForQuestionAnswering` 모델의 경우, 레이블은 `start_positions`와 `end_positions`로 구성되며 어떤 토큰이 답변의 시작과 끝에 있는지를 나타냅니다.
울 -> 을

2023-07-16 00:57 UTC, wonhyeongseo commented on docs/source/ko/tasks/document_question_answering.md
> +위에서 언급한 전처리 외에도 모델울 위해 레이블을 추가해야 합니다. 🤗 Transformers의 `xxxForQuestionAnswering` 모델의 경우, 레이블은 `start_positions`와 `end_positions`로 구성되며 어떤 토큰이 답변의 시작과 끝에 있는지를 나타냅니다.
울 -> 을

2023-07-18 12:13 UTC, jungnerd reviewed
fix: resolve suggestions

2023-07-18 12:16 UTC, jungnerd reviewed
fix: resolve suggestions

2023-07-20 04:23 UTC, jungnerd commented
May you please review this PR? 🤗
@sgugger, @ArthurZucker, @eunseojo

2023-07-20 10:19 UTC, sgugger approved these changes
Thanks!

2023-07-20 10:19 UTC, merged