🌐 [i18n-KO] Translated `model_summary.md` to Korean
huggingface/transformers pull request #24625
Opened 2023-07-02 11:38 UTC by 0525hhgus

# What does this PR do?

Translated the `model_summary.mdx` file of the documentation to Korean 😄 
Thank you in advance for your review!

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-02 11:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24625). All of your documentation changes will be reflected on that endpoint.

2023-07-06 08:40 UTC, wonhyeongseo requested changes
Reviewed until ~L39

2023-07-16 01:53 UTC, sim-so requested changes
~L61

I'll keep reviewing soon!

2023-07-16 01:53 UTC, sim-so commented on docs/source/ko/model_summary.md
> +[Vision Transformer(ViT)](model_doc/vit)는 합성곱 없이 컴퓨터 비전 작업을 할 수 있도록 문을 열었습니다. ViT는 표준 Transformer 인코더를 사용하지만, 이미지를 처리하는 방식이 가장 큰 혁신이었습니다. 문장을 토큰으로 분할하는 방법과 같이, 이미지를 고정된 크기의 패치로 분할하고 이를 사용하여 임베딩을 생성합니
```suggestion
[Vision Transformer(ViT)](model_doc/vit)는 합성곱 없는 컴퓨터 비전 작업의 막을 열었습니다. ViT는 표준 Transformer 인코더를 사용하지만, 가장 큰 혁신은 이미지를 처리하는 방식이었습니다. 문장을 토큰으로 분할하는 것처럼 이미지를 고정된 크기의 패치로 분할하고, 이를 사용하여 임베딩을 생성합니다. ViT는 Transformer의 효율적인 아키텍처를 활용하여 훈련에 더 적은 자원을 사용하면서도 당시 CNN에 비견하는 결과를 입증했습니다. 그리고 ViT를 뒤이어 분할(segmentation)과 같은 고밀도 비전 작업과 탐지 작업도 다룰 수 있는 다른 비전 모델이 등장했습니다.
```

2023-07-16 01:53 UTC, sim-so commented on docs/source/ko/model_summary.md
> +기본 Transformer 모델에 익숙하지 않거나 복습이 필요한 경우, Hugging Face 강의의 [트랜스포머는 어떻게 동작하나요?](https://huggingface.co/course/chapter1/4?fw=pt) 챕터를 확인하세요.
```suggestion
기본 Transformer 모델에 익숙하지 않거나 복습이 필요한 경우, Hugging Face 강의의 [Transformer는 어떻게 동작하나요?](https://huggingface.co/course/chapter1/4?fw=pt) 챕터를 확인하세요. 
```
다른 줄에서 모두 `Transformer`로 부르고 있어 제안 드리오니 참고 부탁 드립니다!

2023-07-16 01:53 UTC, sim-so commented on docs/source/ko/model_summary.md
> +이러한 모델 중 하나가 [Swin](model_doc/swin) Transformer입니다. 이 모델은 작은 크기의 패치에서 계층적 특징 맵(CNN 👀과 같지만 ViT와는 다름)을 만들고 더 깊은 레이어의 인접 패치와 병합합니다. 어텐션(Attention)은 지역 윈도우 내에서만 계산되며, 어텐션 레이어 간에 윈도우를 이동하여 모델이 더 잘 학습할 수 있
```suggestion
이러한 모델 중 하나가 [Swin](model_doc/swin) Transformer입니다. 이 모델은 작은 크기의 패치에서 계층적 특징 맵(CNN 👀과 같지만 ViT와는 다름)을 만들고 더 깊은 레이어의 인접 패치와 병합합니다. 어텐션(Attention)은 지역 윈도우 내에서만 계산되며, 모델이 더 잘 학습할 수 있도록 어텐션 레이어 간에 윈도우를 이동하며 연결을 생성합니다. Swin Transformer는 계층적 특징 맵을 생성할 수 있으므로, 분할(segmentation)과 탐지와 같은 고밀도 예측 작업에 적합합니다. [SegFormer](model_doc/segformer) 역시 Transformer 인코더를 사용하여 계층적 특징 맵을 구축하지만, 상단에 간단한 다층 퍼셉트론(MLP) 디코더를 추가하여 모든 특징 맵을 결합하고 예측을 수행합니다. 
```

2023-07-16 01:53 UTC, sim-so commented on docs/source/ko/model_summary.md
> +대부분의 비전 모델은 이미지 표현을 학습하기 위해 인코더에 의존하기 때문에 디코더 전용 비전 모델은 드뭅니다. 하지만 이미지 생성과 같은 사례의 경우, GPT-2와 같은 텍스트 생성 모델에서 보았듯이 디코더가 가장 적합합니다. [ImageGPT](model_doc/imagegpt)는 GPT-2와 동일한 아키텍처를 사용하지만, 시퀀스의 다음 토큰을 예측하는
```suggestion
대부분의 비전 모델은 인코더에 의존하여 이미지 표현을 학습하기 때문에 디코더 전용 비전 모델은 드뭅니다. 하지만 이미지 생성 등의 사례의 경우, GPT-2와 같은 텍스트 생성 모델에서 보았듯이 디코더가 가장 적합합니다. [ImageGPT](model_doc/imagegpt)는 GPT-2와 동일한 아키텍처를 사용하지만, 시퀀스의 다음 토큰을 예측하는 대신 이미지의 다음 픽셀을 예측합니다. ImageGPT는 이미지 생성 뿐만 아니라 이미지 분류를 위해 미세 조정할 수도 있습니다. 
```

2023-07-16 01:53 UTC, sim-so commented on docs/source/ko/model_summary.md
> +[BERT](model_doc/bert)는 인코더 전용 Transformer로 입력에서 다른 토큰이 보지 못하도록 특정 토큰을 임의로 마스킹하며, 이는 "부정 행위(cheat)"를 가능하게 합니다. 사전훈련의 목표는 컨텍스트를 기반으로 마스킹된 토큰을 예측하는 것입니다. 이를 통해 BERT는 왼쪽과 오른쪽 컨텍스트를 충분히 활용하여 입력에 대해 더 깊고
```suggestion
[BERT](model_doc/bert)는 인코더 전용 Transformer로, 다른 토큰을 보고 소위 "부정 행위"를 저지르는 걸 막기 위해 입력에서 특정 토큰을 임의로 마스킹합니다. 사전훈련의 목표는 컨텍스트를 기반으로 마스킹된 토큰을 예측하는 것입니다. 이를 통해 BERT는 왼쪽과 오른쪽 컨텍스트를 충분히 활용하여 입력에 대해 더 깊고 풍부한 표현을 학습할 수 있습니다. 그러나 BERT의 사전훈련 전략에는 여전히 개선의 여지가 남아 있었습니다. [RoBERTa](model_doc/roberta)는 더 긴 시간 동안 더 큰 배치에 대한 훈련을 포함하고, 전처리 중에 한 번만 마스킹하는 것이 아니라 각 에폭에서 토큰을 임의로 마스킹하고, 다음 문장 예측 목표를 제거하는 새로운 사전훈련 방식을 도입함으로써 이를 개선했습니다. 
```

2023-07-16 01:53 UTC, sim-so commented on docs/source/ko/model_summary.md
> +성능 개선을 위한 지배적인 전략은 모델 크기를 키우는 것입니다. 하지만 큰 모델을 훈련하는 것은 계산 비용이 많이 듭니다. 계산 비용을 줄이는 한 가지 방법은 [DistilBERT](model_doc/distilbert)와 같이 작은 모델을 사용하는 것입니다. DistilBERT는 압축 기법인 [지식 증류(knowledge distillation)](ht
```suggestion
성능 개선을 위한 전략으로 모델 크기를 키우는 것이 지배적입니다. 하지만 큰 모델을 훈련하려면 계산 비용이 많이 듭니다. 계산 비용을 줄이는 한 가지 방법은 [DistilBERT](model_doc/distilbert)와 같이 작은 모델을 사용하는 것입니다. DistilBERT는 압축 기법인 [지식 증류(knowledge distillation)](https://arxiv.org/abs/1503.02531)를 사용하여, 거의 모든 언어 이해 능력을 유지하면서 더 작은 버전의 BERT를 만듭니다. 
```

2023-07-18 13:50 UTC, sim-so requested changes
현서님 고생 많으셨습니다 😢 
간소하오나 리뷰 의견을 몇 가지 남깁니다. 참고 부탁 드립니다!

2023-07-18 13:50 UTC, sim-so commented on docs/source/ko/model_summary.md
> +[GPT-2](model_doc/gpt2)는 시퀀스에서 다음 단어를 예측하는 디코더 전용 Transformer입니다. 토큰을 오른쪽으로 마스킹하여 모델이 이전 토큰을 보고 "부정 행위"하지 못하도록 합니다. 방대한 텍스트에 대한 사전훈련으로, GPT-2는 텍스트가 일부만 정확하거나 사실일지라도 텍스트를 생성하는 것에 상당히 능숙해졌습니다. 하지만 GPT-
```suggestion
[GPT-2](model_doc/gpt2)는 시퀀스에서 다음 단어를 예측하는 디코더 전용 Transformer입니다. 토큰을 오른쪽으로 마스킹하여 모델이 이전 토큰을 보고 "부정 행위"를 하지 못하도록 합니다. GPT-2는 방대한 텍스트에 대해 사전훈련하여 텍스트가 일부만 정확하거나 사실인 경우에도 상당히 능숙하게 텍스트를 생성할 수 있게 되었습니다. 하지만 GPT-2는 BERT가 사전훈련에서 갖는 양방향 컨텍스트가 부족하기 때문에 특정 작업에 적합하지 않았습니다. [XLNET](model_doc/xlnet)은 양방향 훈련이 가능한 permutation language modeling objective(PLM)를 사용하여 BERT와 GPT-2의 사전훈련 목표에 대한 장점을 함께 가지고 있습니다.
```

2023-07-18 13:50 UTC, sim-so commented on docs/source/ko/model_summary.md
> +[Wav2Vec2](model_doc/wav2vec2)는 Transformer 인코더를 사용하여 원본 오디오 파형(raw audio waveform)에서 직접 음성 표현을 학습합니다. 허위 음성 표현 세트에서 실제 음성 표현을 판별하기 위해 대조 작업으로 사전훈련됩니다. [HuBERT](model_doc/hubert)는 Wav2Vec2와 유사하지만 훈련
```suggestion
[Wav2Vec2](model_doc/wav2vec2)는 Transformer 인코더를 사용하여 원본 오디오 파형(raw audio waveform)에서 직접 음성 표현을 학습합니다. 허위 음성 표현 세트에서 실제 음성 표현을 판별하는 대조 작업으로 사전훈련됩니다. [HuBERT](model_doc/hubert)는 Wav2Vec2와 유사하지만 훈련 과정이 다릅니다. 타겟 레이블이 유사한 오디오 세그먼트가 클러스터에 할당되어 은닉 단위(unit)가 되는 군집화(clustering) 단계에서 생성됩니다. 은닉 단위는 예측을 위한 임베딩에 매핑됩니다.
```

2023-07-18 13:50 UTC, sim-so commented on docs/source/ko/model_summary.md
> +Decision 및 Trajectory Transformer는 상태(state), 행동(action), 보상(reward)을 시퀀스 모델링 문제로 표현합니다. [Decision Transformer](model_doc/decision_transformer)는 returns-to-go, 과거 상태 및 행동을 기반으로 미래의 원하는 수익(return)으로 이
```suggestion
Decision 및 Trajectory Transformer는 상태(state), 행동(action), 보상(reward)을 시퀀스 모델링 문제로 표현합니다. [Decision Transformer](model_doc/decision_transformer)는 기대 보상(returns-to-go), 과거 상태 및 행동을 기반으로 미래의 원하는 수익(return)으로 이어지는 일련의 행동을 생성합니다. 마지막 *K* 시간 스텝(timestep)에 대해, 세 가지 모달리티는 각각 토큰 임베딩으로 변환되고 GPT와 같은 모델에 의해 처리되어 미래의 액션 토큰을 예측합니다. [Trajectory Transformer](model_doc/trajectory_transformer)도 상태, 행동, 보상을 토큰화하여 GPT 아키텍처로 처리합니다. 보상 조건에 중점을 둔 Decision Transformer와 달리 Trajectory Transformer는 빔 서치(beam search)로 미래 행동을 생성합니다.
```
`return-to-go`를 각 행동에 대한 기대 보상으로 이해하여 이렇게 제안을 드려봅니다. 👀

2023-07-21 16:51 UTC, 0525hhgus commented on docs/source/ko/model_summary.md
> +기본 Transformer 모델에 익숙하지 않거나 복습이 필요한 경우, Hugging Face 강의의 [트랜스포머는 어떻게 동작하나요?](https://huggingface.co/course/chapter1/4?fw=pt) 챕터를 확인하세요.
꼼꼼하게 확인해주셔서 감사합니다 👍 
이 부분은 NLP 코스의 번역 목차가 `트랜스포머`로 되어 있어서 `트랜스포머`로 나타낸 항목이라, NLP 코스의 목차를 따라가겠습니다 😄

2023-07-21 16:53 UTC, 0525hhgus commented on docs/source/ko/model_summary.md
> +Decision 및 Trajectory Transformer는 상태(state), 행동(action), 보상(reward)을 시퀀스 모델링 문제로 표현합니다. [Decision Transformer](model_doc/decision_transformer)는 returns-to-go, 과거 상태 및 행동을 기반으로 미래의 원하는 수익(return)으로 이
이 용어 번역에 고민이 많았는데 훨씬 자연스럽고 딱 맞는 번역이네요! 😄

2023-07-21 16:57 UTC, 0525hhgus commented on docs/source/ko/model_summary.md
> +[Vision Transformer](https://arxiv.org/abs/2010.11929)가 확장성과 효율성을 입증하기 전까지 오랫동안 합성곱 네트워크(CNN)가 컴퓨터 비전 작업의 지배적인 패러다임이었습니다. 그럼에도 불구하고, 이동 불변성(translation invariance)과 같은 CNN의 우수한 성능 중 일부가 매우 뛰어나기 때문에 (
훨씬 자연스러운 번역 제안과 상세한 리뷰 감사합니다! 👍 
앞으로도 어휘 선택에 많이 고민해봐야겠군요! L39까지 번역 주신 내용 추가했습니다 😄

2023-08-08 21:55 UTC, stevhliu commented
Thanks for translating the `model_summary` file! Feel free to mark as ready for review whenever you're ready 😄

2023-08-09 14:37 UTC, 0525hhgus commented
> Thanks for translating the `model_summary` file! Feel free to mark as ready for review whenever you're ready 😄

Thank you for mentioning it! I changed the status to ready for review. 

May you please review this PR? 😄 
@sgugger, @ArthurZucker, @eunseojo

2023-08-09 16:27 UTC, sgugger approved these changes
Thanks for your contribution!

2023-08-09 16:27 UTC, merged