🌐 [i18n-KO] Fixed Korean and English `quicktour.md`
huggingface/transformers pull request #24664
Opened 2023-07-05 08:44 UTC by wonhyeongseo

# What does this PR do?

Updated and fixed some issues on the `quicktour.md` file for the Korean and English documentation.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-05 08:54 UTC, wonhyeongseo commented on docs/source/en/quicktour.md
> +2. Load preprocessing class like a tokenizer, image processor, feature extractor, or processor:
```suggestion
2. Load a preprocessing class like a tokenizer, image processor, feature extractor, or processor:
```

2023-07-05 09:38 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24664). All of your documentation changes will be reflected on that endpoint.

2023-07-16 02:48 UTC, sim-so requested changes
Thanks for the update! I'm happy to read your careful writing.

Based on our translation glossary, I suggested the below changes:
- `pretrain` : 사전 훈련하다
- `method` : 메소드

The words below are also not matched with the glossary but translated consistently within the documentation. Can I hear any suggestions or concerns about it from you? 
- ` load` : 가져오다 / 로드하다
- `dataset` : 데이터 세트 / 데이터셋

Best,

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +데이터셋의 샘플링 속도가 기존 모델인 [`facebook/wav2vec2-base-960h`](https://huggingface.co/facebook/wav2vec2-base-960h)의 훈련 당시 샘플링 속도와 일치하는지 확인해야 합니다:
```suggestion
데이터셋의 샘플링 레이트가 기존 모델인 [`facebook/wav2vec2-base-960h`](https://huggingface.co/facebook/wav2vec2-base-960h)의 훈련 당시 샘플링 레이트와 일치하는지 확인해야 합니다:
```
현재 glossary 기준으로 변경했습니다. 혹시 수정 제안이 있으시다면 말씀해주세요!

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +오디오 파일은 `"audio"` 열을 호출할 때 자동으로 로드되고 리샘플링됩니다. 첫 4개 샘플에서 원시 웨이브폼 배열을 추출하고 파이프라인에 리스트로 전달하세요:
```suggestion
`"audio"` 열을 호출하면 자동으로 오디오 파일을 로드해서 리샘플링합니다. 첫 4개 샘플에서 원시 웨이브폼 배열을 추출하고 파이프라인에 리스트로 전달하세요:
```

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +[`AutoModelForSequenceClassification`]과 [`AutoTokenizer`]를 사용하여 사전학습된 모델과 관련된 토크나이저를 로드하세요 (다음 섹션에서 [`AutoClass`]에 대해 더 자세히 알아보겠습니다):
```suggestion
[`AutoModelForSequenceClassification`]과 [`AutoTokenizer`]를 사용하여 사전 훈련된 모델과 관련된 토크나이저를 로드하세요 (다음 섹션에서 [`AutoClass`]에 대해 더 자세히 알아보겠습니다):
```

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +마땅한 모델을 찾을 수 없는 경우 데이터를 기반으로 사전학습된 모델을 파인튜닝해야 합니다. 파인튜닝 방법에 대한 자세한 내용은 [파인튜닝 튜토리얼](./training)을 참조하세요. 사전학습된 모델을 파인튜닝한 후에는 모델을 Hub의 커뮤니티와 공유하여 머신러닝 민주화에 기여해주세요! 🤗
```suggestion
마땅한 모델을 찾을 수 없는 경우 데이터를 기반으로 사전 훈련된 모델을 파인튜닝해야 합니다. 파인튜닝 방법에 대한 자세한 내용은 [파인튜닝 튜토리얼](./training)을 참조하세요. 사전 훈련된 모델을 파인튜닝한 후에는 모델을 Hub의 커뮤니티와 공유하여 머신러닝 민주화에 기여해주세요! 🤗
```
`파인튜닝`이 문서 전체적으로 쓰이고 있네요! glossary와 다르게 되어 있는데요, 혹시 생각하신 바가 있으실까 하여 코멘트만 남깁니다. 참고 부탁 드립니다!

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +[`AutoModelForSequenceClassification`]과 [`AutoTokenizer`] 클래스는 위에서 다룬 [`pipeline`]의 기능을 구현하는 데 사용됩니다. [AutoClass](./model_doc/auto)는 사전학습된 모델의 아키텍처를 이름이나 경로에서 자동으로 가져오는 '바로가기'입니다. 과업에 적합한 `AutoClass`
```suggestion
[`AutoModelForSequenceClassification`]과 [`AutoTokenizer`] 클래스는 위에서 다룬 [`pipeline`]의 기능을 구현하는 데 사용됩니다. [AutoClass](./model_doc/auto)는 사전 훈련된 모델의 아키텍처를 이름이나 경로에서 자동으로 가져오는 '바로가기'입니다. 과업에 적합한 `AutoClass`를 선택하고 해당 전처리 클래스를 선택하기만 하면 됩니다.
```

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +토크나이저는 텍스트를 모델의 입력으로 사용하기 위해 숫자 배열 형태로 전처리하는 역할을 담당합니다. 토큰화 과정에는 단어를 어디에서 끊을지, 어느 수준까지 나눌지와 같은 여러 규칙들이 있습니다 (토큰화에 대한 자세한 내용은 [토크나이저 요약](./tokenizer_summary)을 참조하세요). 가장 중요한 점은 모델이 사전학습된 모델과 동일한 토큰화 규
```suggestion
토크나이저는 텍스트를 모델의 입력으로 사용하기 위해 숫자 배열 형태로 전처리하는 역할을 담당합니다. 토큰화 과정에는 단어를 어디에서 끊을지, 어느 수준까지 나눌지와 같은 여러 규칙들이 있습니다 (토큰화에 대한 자세한 내용은 [토크나이저 요약](./tokenizer_summary)을 참조하세요). 가장 중요한 점은 모델이 사전 훈련된 모델과 동일한 토큰화 규칙을 사용하도록 동일한 모델 이름으로 토크나이저를 인스턴스화해야 한다는 것입니다.
```

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +모델의 구성 클래스를 수정하여 모델의 구조를 바꿀 수 있습니다. (숨은 레이어나 어텐션 헤드의 수와 같은) 모델의 속성은 구성에서 지정되기 때문입니다. 커스텀 구성 클래스로 모델을 만들면 처음부터 시작해야 합니다. 모델 속성은 무작위로 초기화되므로 의미 있는 결과를 얻으려면 먼저 모델을 학습시켜야 합니다.
```suggestion
모델의 구성 클래스를 수정하여 모델의 구조를 바꿀 수 있습니다. (은닉층이나 어텐션 헤드의 수와 같은) 모델의 속성은 구성에서 지정되기 때문입니다. 커스텀 구성 클래스로 모델을 만들면 처음부터 시작해야 합니다. 모델 속성은 무작위로 초기화되므로 의미 있는 결과를 얻으려면 먼저 모델을 훈련시켜야 합니다.
```
'은닉층'은 한국어 ML 자료에서 많이 쓰이고 있어서 추천 드립니다!

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +모든 모델은 [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model)이므로 [Keras](https://keras.io/) API를 통해 TensorFlow에서 훈련시킬 수 있습니다. 🤗 Transformers는 데이터셋을 쉽게 `tf.data.Dataset` 형태로 쉽게
```suggestion
모든 모델은 [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model)이므로 [Keras](https://keras.io/) API를 통해 TensorFlow에서 훈련시킬 수 있습니다. 🤗 Transformers는 데이터셋을 쉽게 `tf.data.Dataset` 형태로 쉽게 로드할 수 있는 [`~TFPreTrainedModel.prepare_tf_dataset`] 메소드를 제공하기 때문에, Keras의 [`compile`](https://keras.io/api/models/model_training_apis/#compile-method) 및 [`fit`](https://keras.io/api/models/model_training_apis/#fit-method) 메소드로 바로 훈련을 시작할 수 있습니다.
```

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +[`Trainer`] 내의 메서드를 서브클래스화하여 훈련 루프를 바꿀 수도 있습니다. 이러면 손실 함수, 옵티마이저, 스케줄러와 같은 기능 또한 바꿀 수 있게 됩니다. 변경 가능한 메서드에 대해서는 [`Trainer`] 문서를 참고하세요.
```suggestion
[`Trainer`] 내의 메서드를 서브클래스화하여 훈련 루프를 바꿀 수도 있습니다. 이러면 손실 함수, 옵티마이저, 스케줄러와 같은 기능 또한 바꿀 수 있게 됩니다. 변경 가능한 메소드에 대해서는 [`Trainer`] 문서를 참고하세요.
```

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +🤗 Transformers는 사전학습된 인스턴스를 간단하고 통합된 방법으로 로드할 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`AutoModel`]을 로드할 수 있습니다. 유일한 차이점은 과업에 알맞은 [`AutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`AutoModelForSequenceClassi
```suggestion
🤗 Transformers는 사전 훈련된 인스턴스를 간단하고 통합된 방법으로 로드할 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`AutoModel`]을 로드할 수 있습니다. 유일한 차이점은 과업에 알맞은 [`AutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`AutoModelForSequenceClassification`]을 로드해야 합니다:
```

2023-07-16 02:48 UTC, sim-so commented on docs/source/ko/quicktour.md
> +🤗 Transformers는 사전학습된 인스턴스를 간단하고 통합된 방법으로 로드할 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`TFAutoModel`]을 로드할 수 있습니다. 유일한 차이점은 과업에 알맞은 [`TFAutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`TFAutoModelForSequence
```suggestion
🤗 Transformers는 사전 훈련된 인스턴스를 간단하고 통합된 방법으로 로드할 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`TFAutoModel`]을 로드할 수 있습니다. 유일한 차이점은 과업에 알맞은 [`TFAutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`TFAutoModelForSequenceClassification`]을 로드해야 합니다:
```

2023-07-16 09:54 UTC, 0525hhgus requested changes
Thank you for the good translation 👍 
It became a more natural document!
I commented the review related to glossary 😄

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +| 오디오 분류      | 오디오 파일에 알맞은 라벨 붙이기                                    | 오디오           | pipeline(task="audio-classification")         |
```suggestion
| 텍스트 분류      | 텍스트에 알맞은 레이블 붙이기                                         | 자연어 처리(NLP) | pipeline(task="sentiment-analysis")           |
| 텍스트 생성      | 주어진 문자열 입력과 이어지는 텍스트 생성하기                       | 자연어 처리(NLP) | pipeline(task="text-generation")              |
| 개체명 인식      | 문자열의 각 토큰마다 알맞은 레이블 붙이기 (인물, 조직, 장소 등등)     | 자연어 처리(NLP) | pipeline(task="ner")                          |
| 질의응답         | 주어진 문맥과 질문에 따라 올바른 대답하기                           | 자연어 처리(NLP) | pipeline(task="question-answering")           |
| 빈칸 채우기      | 문자열의 빈칸에 알맞은 토큰 맞추기                                  | 자연어 처리(NLP) | pipeline(task="fill-mask")                    |
| 요약             | 텍스트나 문서를 요약하기                                            | 자연어 처리(NLP) | pipeline(task="summarization")                |
| 번역             | 텍스트를 한 언어에서 다른 언어로 번역하기                           | 자연어 처리(NLP) | pipeline(task="translation")                  |
| 이미지 분류      | 이미지에 알맞은 레이블 붙이기                                         | 컴퓨터 비전(CV)  | pipeline(task="image-classification")         |
| 이미지 분할      | 이미지의 픽셀마다 레이블 붙이기(시맨틱, 파놉틱 및 인스턴스 분할 포함) | 컴퓨터 비전(CV)  | pipeline(task="image-segmentation")           |
| 객체 탐지        | 이미지 속 객체의 경계 상자를 그리고 클래스를 예측하기               | 컴퓨터 비전(CV)  | pipeline(task="object-detection")             |
| 오디오 분류      | 오디오 파일에 알맞은 레이블 붙이기                                    | 오디오           | pipeline(task="audio-classification")         |
```
Glossary 기준 `레이블`로 수정하였습니다!

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +데이터셋을 로드할 차례입니다. (자세한 내용은 🤗 Datasets [시작하기](https://huggingface.co/docs/datasets/quickstart#audio)을 참조하세요) 여기에서는 [MInDS-14](https://huggingface.co/datasets/PolyAI/minds14) 데이터셋을 로드하겠습니다:
```suggestion
데이터셋을 가져올 차례입니다. (자세한 내용은 🤗 Datasets [시작하기](https://huggingface.co/docs/datasets/quickstart#audio)을 참조하세요) 여기에서는 [MInDS-14](https://huggingface.co/datasets/PolyAI/minds14) 데이터셋을 가져오겠습니다:
```

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +음성이나 비전과 같이 입력이 큰 대규모 데이터셋의 경우, 모든 입력을 메모리에 로드하려면 리스트 대신 제너레이터를 전달해야 합니다. 자세한 내용은 [Pipelines API 참조](./main_classes/pipelines)를 확인하세요.
```suggestion
음성이나 비전과 같이 입력이 큰 대규모 데이터셋의 경우, 모든 입력을 메모리에 가져오려면 리스트 대신 제너레이터를 전달해야 합니다. 자세한 내용은 [Pipelines API 참조](./main_classes/pipelines)를 확인하세요.
```

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +[`TFAutoModelForSequenceClassification`]과 [`AutoTokenizer`]를 사용하여 사전 훈련된 모델과 관련된 토크나이저를 로드하세요 (다음 섹션에서 [`TFAutoClass`]에 대해 더 자세히 알아보겠습니다):
```suggestion
[`TFAutoModelForSequenceClassification`]과 [`AutoTokenizer`]를 사용하여 사전 훈련된 모델과 관련된 토크나이저를 가져오세요 (다음 섹션에서 [`TFAutoClass`]에 대해 더 자세히 알아보겠습니다):
```

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +[`AutoTokenizer`]로 토크나이저를 로드하세요:
```suggestion
[`AutoTokenizer`]로 토크나이저를 가져오세요:
```

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +🤗 Transformers는 사전학습된 인스턴스를 간단하고 통합된 방법으로 로드할 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`AutoModel`]을 로드할 수 있습니다. 유일한 차이점은 과업에 알맞은 [`AutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`AutoModelForSequenceClassi
> Glossary 관련하여 추가하였습니다!

```suggestion
🤗 Transformers는 사전 훈련된 인스턴스를 간단하고 통합된 방법으로 로드할 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`AutoModel`]을 가져올 수 있습니다. 유일한 차이점은 과업에 알맞은 [`AutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`AutoModelForSequenceClassification`]을 가져와야 합니다:
```

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +[`AutoModelForSequenceClassification`]과 [`AutoTokenizer`]를 사용하여 사전학습된 모델과 관련된 토크나이저를 로드하세요 (다음 섹션에서 [`AutoClass`]에 대해 더 자세히 알아보겠습니다):
> Glossary 관련하여 추가하였습니다!

```suggestion
[`AutoModelForSequenceClassification`]과 [`AutoTokenizer`]를 사용하여 사전 훈련된 모델과 관련된 토크나이저를 가져오세요 (다음 섹션에서 [`AutoClass`]에 대해 더 자세히 알아보겠습니다):
```

2023-07-16 09:54 UTC, 0525hhgus commented on docs/source/ko/quicktour.md
> +🤗 Transformers는 사전학습된 인스턴스를 간단하고 통합된 방법으로 로드할 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`TFAutoModel`]을 로드할 수 있습니다. 유일한 차이점은 과업에 알맞은 [`TFAutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`TFAutoModelForSequence
> Glossary 관련하여 추가하였습니다!

문서에서 `load` 가 `로드하다`로 번역된 것 같습니다. 
*확인해보니 `import`를 `가져오다`로 사용하셔서 그런 것으로 추측되어 해당 부분은 참고 부탁드립니다!*
해당 부분은 라인 번호으로 남겨 놓겠습니다 :)
329, 344, 352, 377, 428, 436, 506, 516 라인입니다!

```suggestion
🤗 Transformers는 사전 훈련된 인스턴스를 간단하고 통합된 방법으로 가져올 수 있습니다. 즉, [`AutoTokenizer`]처럼 [`TFAutoModel`]을 가져올 수 있습니다. 유일한 차이점은 과업에 알맞은 [`TFAutoModel`]을 선택해야 한다는 점입니다. 텍스트 (또는 시퀀스) 분류의 경우 [`TFAutoModelForSequenceClassification`]을 가져와야 합니다:
```

2023-07-18 14:21 UTC, kihoon71 commented on docs/source/ko/quicktour.md
> +오디오 파일은 `"audio"` 열을 호출할 때 자동으로 로드되고 리샘플링됩니다. 첫 4개 샘플에서 원시 웨이브폼 배열을 추출하고 파이프라인에 리스트로 전달하세요:
로드하다가 glosary 후보군에 있긴한데, 가져오기로 되어 있네요.. 흠 이런 마이너한건 크게 상관 없을까요?

2023-07-18 14:37 UTC, kihoon71 commented on docs/source/ko/quicktour.md
> +음성이나 비전과 같이 입력이 큰 대규모 데이터셋의 경우, 모든 입력을 메모리에 로드하려면 리스트 대신 제너레이터를 전달해야 합니다. 자세한 내용은 [Pipelines API 참조](./main_classes/pipelines)를 확인하세요.
```suggestion
음성이나 비전과 같이 입력이 큰 대규모 데이터셋의 경우, 모든 입력을 메모리에 로드하려면 리스트 대신 제너레이터 형태로 전달해야 합니다. 자세한 내용은 [Pipelines API 참조](./main_classes/pipelines)를 확인하세요.
```
In my opinion, this way can make the meaning of the sentence clear.

2023-07-18 14:49 UTC, kihoon71 commented on docs/source/ko/quicktour.md
> +[`pipeline`]은 [Hub](https://huggingface.co/models)의 모든 모델을 사용할 수 있기 때문에, [`pipeline`]을 다른 용도에 맞게 쉽게 수정할 수 있습니다. 예를 들어, 프랑스어 텍스트를 처리할 수 있는 모델을 사용하려면 Hub의 태그를 사용하여 적절한 모델을 필터링하면 됩니다. 상위 필터링 결과로는 프랑스어 텍
```suggestion
[`pipeline`]은 [Hub](https://huggingface.co/models)의 모든 모델을 사용할 수 있기 때문에, [`pipeline`]을 다른 용도에 맞게 쉽게 수정할 수 있습니다. 예를 들어, 프랑스어 텍스트를 처리할 수 있는 모델을 사용하기 위해선 Hub의 태그를 사용하여 적절한 모델을 필터링하면 됩니다. 필터링된 결과의 상위 항목으로는 프랑스어 텍스트에 사용할 수 있는 다국어 [BERT 모델](https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment)이 반환됩니다:
```
For me, some of the former version of text seems to be more easy to understand : 'filtering' => '찾다', but it still can deliver precise meaning so i think this improves the clarity.  I just suggested minor parts related with nuance.

2023-07-21 06:50 UTC, wonhyeongseo reviewed
리뷰를 보며 생각난 더 좋은 번역본입니다. 모두들 감사합니다!

2023-07-21 06:50 UTC, wonhyeongseo commented on docs/source/ko/quicktour.md
> +오디오 파일은 `"audio"` 열을 호출할 때 자동으로 로드되고 리샘플링됩니다. 첫 4개 샘플에서 원시 웨이브폼 배열을 추출하고 파이프라인에 리스트로 전달하세요:
```suggestion
`"audio"` 열을 호출하면 자동으로 오디오 파일을 가져와서 리샘플링합니다. 첫 4개 샘플에서 원시 웨이브폼 배열을 추출하고 파이프라인에 리스트로 전달하세요:
```

2023-07-21 06:50 UTC, wonhyeongseo commented on docs/source/ko/quicktour.md
> +마땅한 모델을 찾을 수 없는 경우 데이터를 기반으로 사전학습된 모델을 파인튜닝해야 합니다. 파인튜닝 방법에 대한 자세한 내용은 [파인튜닝 튜토리얼](./training)을 참조하세요. 사전학습된 모델을 파인튜닝한 후에는 모델을 Hub의 커뮤니티와 공유하여 머신러닝 민주화에 기여해주세요! 🤗
앗 실수입니다. 이번 resolve suggestions 커밋하고 fix: 파인튜닝 커밋을 올려야겠어요. 캐치해주셔서 감사합니다!

2023-07-21 08:19 UTC, wonhyeongseo commented
@sgugger, @ArthurZucker, @eunseojo May you please review this PR?
Thank you so much for your support!

2023-07-21 08:58 UTC, ArthurZucker approved these changes
좋아요! Thanks for adding the anchors to the titles ! 
I am also fine with the changes in the english quicktour

2023-07-21 12:19 UTC, sgugger approved these changes
Thanks!

2023-07-21 12:19 UTC, merged