🌐[i18n-KO] Translated pipeline_webserver.md to Korean
huggingface/transformers pull request #24828
Opened 2023-07-14 18:21 UTC by kihoon71

# What does this PR do?

Translated the pipeline_webserver.md file of the documentation to Korean 😄
Thank you in advance for your review!

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing

- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. [[lowercased-header]])
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ x Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

2023-07-14 18:45 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24828). All of your documentation changes will be reflected on that endpoint.

2023-07-18 13:45 UTC, augustinLib requested changes

2023-07-18 13:45 UTC, augustinLib commented on docs/source/ko/pipeline_webserver.md
> +이 방식을 사용하면 큐가 비어 있어도 항상 1ms 기다리게 될 것입니다.
```suggestion
이 방식을 사용하면 큐가 비어 있어도 항상 1ms를 기다리게 될 것입니다. 
```

`1ms` -> `1ms를` 로 수정하는 것이 문맥상 조금 더 자연스러울것같아서 제안드립니다!

2023-07-18 13:45 UTC, augustinLib commented on docs/source/ko/pipeline_webserver.md
> +일반적으로 배치 처리는 1개 항목을 한 번에 전달하는 것보다 반드시 개선되는 것은 아닙니다(자세한 내용은 [`batching details`](./main_classes/pipelines#pipeline-batching)을 참고하세요).
```suggestion
일반적으로, 배치 처리가 1개 항목을 한 번에 전달하는 것에 비해 반드시 성능 향상이 있는 것은 아닙니다(자세한 내용은 [`batching details`](./main_classes/pipelines#pipeline-batching)을 참고하세요).
```

문맥상 이렇게 하면 조금 더 좋지 않을까 싶어 제안드립니다!

2023-07-18 13:54 UTC, kihoon71 commented on docs/source/ko/pipeline_webserver.md
> +일반적으로 배치 처리는 1개 항목을 한 번에 전달하는 것보다 반드시 개선되는 것은 아닙니다(자세한 내용은 [`batching details`](./main_classes/pipelines#pipeline-batching)을 참고하세요).
꼼꼼한 리뷰를 해주셨네ㅎㅎㅎㅎ감사합니다!!!

2023-07-19 12:28 UTC, 54data commented on docs/source/ko/pipeline_webserver.md
> +제안된 코드에는 단일 큐가 있으므로 구현하기가 비교적 쉽습니다
```suggestion
제안된 코드에는 단일 큐가 있으므로 구현하기가 비교적 쉽습니다.
```
해당 문장에 마침표가 생략되어 있으니 참고 부탁드립니다.

2023-07-20 23:04 UTC, 0525hhgus requested changes
빠르고 좋은 번역 감사합니다 😀
아래 리뷰를 남겼으니, 확인 부탁드립니다!

2023-07-20 23:04 UTC, 0525hhgus commented on docs/source/ko/pipeline_webserver.md
> +큐 사이즈를 확인하는 것은 웹 서버가 과부하 상항 하에 있을 때 에러를 반환하기 위한 가장 기초적인 작업입니다.
```suggestion
큐 크기를 확인하는 것은 웹 서버가 과부하 상항 하에 있을 때 에러를 반환하기 위한 가장 기초적인 작업입니다.
```

2023-07-20 23:04 UTC, 0525hhgus commented on docs/source/ko/pipeline_webserver.md
> +추론 엔진을 만드는 것은 복잡한 주제이며, '최선의' 솔루션은 문제 공간에 따라 달라질 가능성이 높습니다. CPU 또는 GPU를 사용하는지에 따라 다르고 낮은 지연 시간을 원하는지, 높은 처리량을 원하는지, 다양한 모델을 지원할 수 있길 원하는지, 하나의 특정 모델을 고도로 최적화하길 원하는지 등에 따라 달라집니다. 이 주제를 해결하는 방법에는 여러 가지
```suggestion
추론 엔진을 만드는 것은 복잡한 주제이며, "최선의" 솔루션은 문제 공간에 따라 달라질 가능성이 높습니다. CPU 또는 GPU를 사용하는지에 따라 다르고 낮은 지연 시간을 원하는지, 높은 처리량을 원하는지, 다양한 모델을 지원할 수 있길 원하는지, 하나의 특정 모델을 고도로 최적화하길 원하는지 등에 따라 달라집니다. 이 주제를 해결하는 방법에는 여러 가지가 있으므로, 이 장에서 제시하는 것은 처음 시도해 보기에 좋은 출발점일 수는 있지만, 이 장을 읽는 여러분이 필요로 하는 최적의 솔루션은 아닐 수 있습니다.
```
원문에서 큰 따옴표로 되어 있어서 수정했습니다!

2023-07-21 08:12 UTC, seank021 commented on docs/source/ko/pipeline_webserver.md
> +핵심적으로 이해해야 할 점은 [dataset](pipeline_tutorial#using-pipelines-on-a-dataset)를 다룰 때와 마찬가지로 반복자를 사용 가능하다는 것입니다. 왜냐하면, 웹 서버는 기본적으로 요청을 기다리고 들어오는 대로 처리하는 시스템이기 때문입니다.
dataset 발음이 "셋"으로 끝나니 dataset"을"로 고치는 게 낫지 않을까 건의드려봅니다!
또한, 왜냐하면 다음에 쉼표를 없애는 것이 좋을 것 같습니다. (이후 13번째 줄과의 통일성)

2023-07-21 17:07 UTC, kihoon71 commented on docs/source/ko/pipeline_webserver.md
> +핵심적으로 이해해야 할 점은 [dataset](pipeline_tutorial#using-pipelines-on-a-dataset)를 다룰 때와 마찬가지로 반복자를 사용 가능하다는 것입니다. 왜냐하면, 웹 서버는 기본적으로 요청을 기다리고 들어오는 대로 처리하는 시스템이기 때문입니다.
Glossary 상에는 '데이터 세트'로 되어 있어서 일단 '를'로 했는데, 영문으로 되어 있는 경우에는 읽을 걸 고려하면 '을'로 해도 되겠네요!

2023-07-22 00:46 UTC, Sunmin0520 commented
별도의 리뷰 사항 없습니다. 수고하셨습니다 :)

2023-07-26 12:40 UTC, sgugger approved these changes
Thanks!

2023-07-26 12:40 UTC, merged