Ko debugging
huggingface/transformers pull request #24869
Opened 2023-07-17 20:46 UTC by kj021

# What does this PR do?

Fixes # (issue)

## Before submitting
- [v] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [v] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [v] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [v] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2023-07-23 09:55 UTC, sim-so commented on docs/source/ko/_toctree.yml
> +    - local: Debugging
```suggestion
    - local: debugging
```
_toctree.yml 내용이 실제 문서와 연결되지 않는 경우 doc preview가 생성되지 않을 수 있어요!
이 문서의 경우, 이 부분이 대문자로 시작하여 실제 local 파일명과 일치하지 않는 점이 원인인 것 같습니다.
해당 부분을 한 번 바꿔보시겠어요?

2023-07-24 14:01 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24869). All of your documentation changes will be reflected on that endpoint.

2023-07-28 15:28 UTC, sim-so requested changes
첫 번역 고생 많으셨습니다! 🎉
리뷰가 너무 늦어 면목 없습니다 🥲

전체적으로 코드 서식이 누락된 부분을 수정하고, 일부 문장에 새 제안을 드려보았습니다!
검토해주시면 감사하겠습니다!

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +두 번째 열은 절대적으로 가장 큰 요소의 값이며, 따라서 마지막 몇 개의 프레임을 자세히 살펴보면 입력과 출력이 1e4 범위에 있음을 알 수 있습니다. 따라서 이 훈련은 fp16 혼합 정밀도로 수행될 때 가장 마지막 단계에서 오버플로우가 발생했습니다 (fp16에서 inf 이전의 가장 큰 숫자는 64e3입니다). fp16 아래에서 오버플로우를 피하기 위해서
```suggestion
두 번째 열은 절대적으로 가장 큰 요소의 값이며, 따라서 마지막 몇 개의 프레임을 자세히 살펴보면 입력과 출력이 `1e4` 범위에 있음을 알 수 있습니다. 따라서 이 훈련은 `fp16` 혼합 정밀도로 수행될 때 가장 마지막 단계에서 오버플로우가 발생했습니다 (`fp16`에서 `inf` 이전의 가장 큰 숫자는 `64e3`입니다). `fp16` 아래에서 오버플로우를 피하기 위해서는 활성화는 `1e4`보다 훨씬 작아야 합니다. 왜냐하면 `1e4 * 1e4 = 1e8`이기 때문에 큰 활성화와의 행렬 곱은 수치적인 오버플로우 조건으로 이어질 것입니다.
```
코드 서식이 누락되어 수정했습니다!

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +보고서를 models/t5/modeling_t5.py의 코드와 일치시켜 보겠습니다.
```suggestion
보고서를 `models/t5/modeling_t5.py`의 코드와 일치시켜 보겠습니다.
```

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +여기에서는 T5DenseGatedGeluDense.forward가 출력 활성화를 생성하는데, 절대적으로 가장 큰 값이 약 62.7K인 것을 볼 수 있습니다. 이 값은 fp16의 최대 제한인 64K에 매우 근접합니다. 다음 프레임에서는 일부 요소를 0으로 만든 후 가중치를 재정규화하는 Dropout이 있습니다. 이로 인해 절대 최대값이 64K를 초과하고 오
```suggestion
여기에서는 `T5DenseGatedGeluDense.forward`가 출력 활성화를 생성하는데, 절대적으로 가장 큰 값이 약 62.7K인 것을 볼 수 있습니다. 이 값은 fp16의 최대 제한인 64K에 매우 근접합니다. 다음 프레임에서는 일부 요소를 0으로 만든 후 가중치를 재정규화하는 `Dropout`이 있습니다. 이로 인해 절대 최대값이 64K를 초과하고 오버플로우(`inf`)가 발생합니다.
```

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +감지는 forward 후크에서 발생하므로, 이러한 보고서는 각 `forward`가 반환된 직후에 즉시 출력됩니다.
```suggestion
감지는 `forward` 후크에서 발생하므로, 이러한 보고서는 각 `forward`가 반환된 직후에 즉시 출력됩니다.
```

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +전체 보고서로 돌아가서 문제에 대한 조치 및 수정을 하려면, 숫자가 증가하기 시작한 몇 개의 프레임 위로 이동하고 아마도 여기서 fp32 모드로 전환해야 합니다. 이렇게 하면 숫자가 곱해지거나 합쳐질 때 오버플로우되지 않습니다. 물론 다른 해결책도 있을 수 있습니다. 예를 들어, amp가 활성화된 경우 일시적으로 끄고 원래의 forward를 도우미 래퍼로
```suggestion
전체 보고서로 돌아가서 문제에 대한 조치 및 수정을 하려면, 숫자가 증가하기 시작한 몇 개의 프레임 위로 이동해서 여기서 `fp32` 모드로 전환해야 합니다. 이렇게 해야 숫자가 곱해지거나 합쳐질 때 오버플로우되지 않을 가능성이 높습니다. 물론 다른 해결책도 있을 수 있습니다. 예를 들어, `amp`가 활성화된 경우 일시적으로 끄고 원래의 `forward`를 도우미 래퍼로 이동한 후 다음과 같이 할 수 있습니다:
```
1. 문장 해석을 조금 바꾸어보았는데 어떠실까요? 하나의 의견일 뿐이오니 편히 검토해주세요!
2. 코드 서식이 누락된 부분을 수정했습니다!

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +자동 감지기는 전체 프레임의 입력과 출력에 대해서만 보고하므로, 어디를 살펴봐야 하는지 알면 특정 forward 함수의 중간 단계도 분석할 수 있습니다. 이 경우에는 detect_overflow 도우미 함수를 사용하여 원하는 위치에 감지기를 삽입할 수 있습니다. 예를 들어:
```suggestion
자동 감지기는 전체 프레임의 입력과 출력에 대해서만 보고하므로, 어디를 살펴봐야 하는지 알면 특정 `forward` 함수의 중간 단계도 분석할 수 있습니다. 이 경우에는 `detect_overflow` 도우미 함수를 사용하여 원하는 위치에 감지기를 삽입할 수 있습니다. 예를 들어:
```

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +여기서는 이를 추가하여 2개의 것을 추적하고 이제 forwarded_states의 inf 또는 nan이 중간에 감지되었는지를 추적합니다.
```suggestion
여기서는 이를 추가하여 2개의 것을 추적하고 이제 `forwarded_states`의 `inf` 또는 `nan`이 중간에 감지되었는지를 추적합니다.
```

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +실제로, 예시에서 각 호출이 nn.Module인 경우 감지기가 이미 이를 보고합니다. 그러나 가정해 봅시다. 만약 로컬 직접 계산이 있는 경우, 다음과 같이 수행할 수 있습니다.
```suggestion
실제로 위의 예제에서 각 호출이 `nn.Module`이기 때문에 탐지기가 이미 이를 보고합니다. 로컬에서 직접 계산하는 경우 이렇게 수행한다고 가정해 봅시다.
```
'가정해 봅시다'를 한 문장으로 따로 나누어 쓰니, 문장을 읽는 호흡이 들어가서 좋은 것 같아요!

여기서 가정하는 상황이 위 내용인 것 같아 수정해보았습니다.
문장도 조금 바뀌었는데요, 괜찮으실지 검토 부탁 드립니다!

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +예를 들어, 특정 배치의 각 forward 호출의 모든 구성 성분에 대한 절대 최솟값과 최댓값을 확인하고, 이를 배치 1과 3에 대해서만 수행하려면 다음과 같이 이 클래스를 인스턴스화합니다.
```suggestion
예를 들어, 특정 배치의 각 `forward` 호출의 모든 구성 성분에 대한 절대 최솟값과 최댓값을 확인하고, 이를 배치 1과 3에 대해서만 수행하려면 다음과 같이 이 클래스를 인스턴스화합니다:
```

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +배치는 0부터 시작합니다.
이 부분의 번역이 무척 매끄러운 것 같아요!👍

2023-07-28 15:28 UTC, sim-so commented on docs/source/ko/debugging.md
> +추적의 맨 처음에서 어느 배치 번호에서 문제가 발생했는지 알 수 있습니다 (여기서 Detected inf/nan during batch_number=0은 문제가 첫 번째 배치에서 발생했음을 의미합니다).
```suggestion
추적의 맨 처음에서 어느 배치 번호에서 문제가 발생했는지 알 수 있습니다 (여기서 `Detected inf/nan during batch_number=0`은 문제가 첫 번째 배치에서 발생했음을 의미합니다).
```

2023-07-30 11:56 UTC, HanNayeoniee commented
소현님이 리뷰를 꼼꼼하게 해주셨네요!
LGTM 👍

2023-08-08 22:04 UTC, stevhliu reviewed
Thanks for your contribution!

2023-08-08 22:04 UTC, stevhliu commented on docs/source/ko/debugging.md
> +### 특정 배치의 절댓값 최소 및 최대 값 추적
I think the following is missing, which is causing the section header to not show up in the right navbar :)

```suggestion
### 특정 배치의 절댓값 최소 및 최대 값 추적 [[specific-batch-absolute-min-and-max-value-tracing]]
```

2023-08-18 14:21 UTC, wonhyeongseo commented
안녕하세요 @kj021 님, 혹시 시간이 나실때 위의 수정사항들을 반영해주시길 바랍니다! 감사합니다.

2023-09-21 08:03 UTC, closed without merging