🌐 [i18n-KO] Translated `testing.md` to Korean
huggingface/transformers pull request #24900
Opened 2023-07-19 02:19 UTC by Sunmin0520

# What does this PR do?

Translated the `testing.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-19 21:10 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24900). All of your documentation changes will be reflected on that endpoint.

2023-07-20 03:06 UTC, 0525hhgus requested changes
긴 글이었지만, 주석까지 꼼꼼하게 번역해주셨군요! 
좋은 번역 감사합니다 👍
TOC와 용어 관련하여 리뷰를 남겼으니, 확인 부탁드립니다 :)

2023-07-21 08:04 UTC, seank021 commented
위에 현서 멘토님께서 올려주신 것 외에는 리뷰 사항 없습니다!

2023-07-21 23:47 UTC, Sunmin0520 commented on docs/source/ko/testing.md
> +## Transformers 테스트 방법[[how transformers are tested]]
확인 감사합니다. 알려주신 것처럼 수정하겠습니다:)

2023-07-21 23:47 UTC, Sunmin0520 commented on docs/source/ko/testing.md
> +### 파라미터화[[parametrization]]
제가 보기에도 매개변수화가 조금 더 자연스러워서 그렇게 수정하겠습니다!

2023-07-22 03:45 UTC, 54data commented on docs/source/ko/testing.md
> +테스트나 설정 메서드가 실패하면 캡처된 출력은 일반적으로 실패 추적 정보와 함께 표시됩니다.
```suggestion
테스트나 설정 메소드가 실패하면 캡처된 출력은 일반적으로 실패 추적 정보와 함께 표시됩니다.
```
Glossary에 따라 메서드 -> 메소드로 제안드립니다!

2023-07-22 03:45 UTC, 54data commented on docs/source/ko/testing.md
> +이 헬퍼 메서드는 `os.environ` 객체의 사본을 생성하므로 원본은 그대로 유지됩니다.
```suggestion
이 헬퍼 메소드는 `os.environ` 객체의 사본을 생성하므로 원본은 그대로 유지됩니다.
```

2023-07-23 02:01 UTC, Sunmin0520 commented on docs/source/ko/testing.md
> +테스트나 설정 메서드가 실패하면 캡처된 출력은 일반적으로 실패 추적 정보와 함께 표시됩니다.
감사합니다. Glossary에 따라 수정했습니다 :)

2023-07-24 13:24 UTC, sgugger approved these changes
Thanks!

2023-07-24 13:24 UTC, merged