🌐 [i18n-KO] Translated `<tf_xla>.md` to Korean
huggingface/transformers pull request #24904
Opened 2023-07-19 06:22 UTC by 54data

# What does this PR do?

Translated the `<tf_xla>.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@kihoon71, @0525hhgus, @54data, @Sunmin0520, @seank021, @augustinLib

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-19 11:47 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24904). All of your documentation changes will be reflected on that endpoint.

2023-07-20 14:53 UTC, 0525hhgus requested changes
용어에 대한 적절한 한국어 표현을 고려해서 번역해주셨군요 👍 
좋은 번역 감사합니다! 코드 주석 관련하여 리뷰를 남겼으니, 참고 부탁드립니다 😄

2023-07-21 04:33 UTC, augustinLib commented
리뷰 사항 없습니다!

2023-07-21 16:59 UTC, kihoon71 commented
꼼꼼한 번역 잘 보았습니다! 수고 많으셨습니다!

2023-07-22 00:27 UTC, Sunmin0520 commented on docs/source/ko/tf_xla.md
> +정확한 속도 향상은 모델에 따라 다르지만, 🤗 Transformers 내의 TensorFlow 텍스트 생성 모델의 경우 약 100배의 속도 향상을 확인했습니다. 이 문서에서는 이러한 모델에 대해 XLA를 사용하여 최대 성능을 얻는 방법을 설명합니다. 또한 XLA 통합의 벤치마크 및 디자인 철학에 대한 추가 자료 링크도 제공할 것입니다.
'..모델의 경우 최대 100배의 속도 향상을 확인했습니다'로 제안드립니다. 
정말 사소하지만, '100배'와 '최대 100배'의 의미 차이는 조금 있는 것 같아 댓글 남깁니다 :)

2023-07-25 11:43 UTC, sgugger approved these changes
Thanks!

2023-07-25 11:43 UTC, merged