[i18n-KO] Translated `perf_train_cpu.md to Korean
huggingface/transformers pull request #24911
Opened 2023-07-19 08:54 UTC by seank021

# What does this PR do?

Translated the `perf_train_cpu.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@kihoon71 @0525hhgus @54data @Sunmin0520 @augustinLib

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-20 15:33 UTC, 0525hhgus requested changes
제품명이 많이 나와서 번역하기 까다로우셨을텐데, 정확하게 번역해주셔서 수월하게 이해했습니다 😄 좋은 번역 감사합니다 👍 
아래 리뷰를 남기니, 확인 부탁드립니다!

2023-07-20 15:33 UTC, 0525hhgus commented on docs/source/ko/perf_train_cpu.md
> +# CPU에서 효율적인 훈련
```suggestion
# CPU에서 효율적인 훈련[[efficient-training-on-cpu]]
```
TOC마다 `[[lowercased-header]]`를 추가하시면, 서브 목차 작동을 확인하실 수 있습니다!

2023-07-20 15:33 UTC, 0525hhgus commented on docs/source/ko/perf_train_cpu.md
> +## IPEX와 혼합 정밀도
```suggestion
## IPEX와 혼합 정밀도[[mixed-precision-with-ipex]]
```
Title에서 언급드렸던 사항으로, 아래 TOC도 확인 부탁드립니다 🙂

2023-07-20 15:33 UTC, 0525hhgus commented on docs/source/ko/perf_train_cpu.md
> +[자세한 정보](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/features/amp.html)를 확인하십시오.
```suggestion
[자동 혼합 정밀도](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/features/amp.html)에 대한 자세한 정보를 확인하십시오.
```

원문에 `Auto Mixed Precision`에 대한 내용이 포함되어 있어서 추가했습니다!
```
Check more detailed information for [Auto Mixed Precision](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/features/amp.html).
```

2023-07-21 04:34 UTC, augustinLib commented
리뷰 사항 없습니다!

2023-07-21 08:02 UTC, seank021 commented on docs/source/ko/perf_train_cpu.md
> +# CPU에서 효율적인 훈련
아, 이게 단순히 영어 번역인 줄 알고 지웠는데 서브 목차 작동이었군요! 감사합니다 :)

2023-07-21 12:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24911). All of your documentation changes will be reflected on that endpoint.

2023-07-22 00:21 UTC, Sunmin0520 commented
저도 @0525hhgus 님의 댓글 부분 외에는 별도의 리뷰 사항 없습니다 :)

2023-07-22 02:56 UTC, 54data commented on docs/source/ko/perf_train_cpu.md
> +저정밀도 데이터 타입인 BFloat16은 3세대 Xeon® Scalable 프로세서 (코드명: Cooper Lake)에서 AVX512 명령어 집합을 네이티브로 지원해 왔으며, 다음 세대의 Intel® Xeon® Scalable 프로세서에서 Intel® Advanced Matrix Extensions (Intel® AMX) 명령어 집합을 지원하여 성능을 크
```suggestion
저정밀도 데이터 타입인 BFloat16은 3세대 Xeon® Scalable 프로세서 (코드명: Cooper Lake)에서 AVX512 명령어 집합을 네이티브로 지원해 왔으며, 다음 세대의 Intel® Xeon® Scalable 프로세서에서 Intel® Advanced Matrix Extensions (Intel® AMX) 명령어 집합을 지원하여 성능을 크게 향상시킬 예정입니다. CPU 백엔드의 자동 혼합 정밀도 기능은 PyTorch-1.10부터 활성화되었습니다. 동시에, Intel® Extension for PyTorch에서 BFloat16에 대한 CPU의 자동 혼합 정밀도 및 연산자의 BFloat16 최적화를 대규모로 활성화하고, PyTorch 마스터 브랜치로 부분적으로 업스트림을 반영했습니다. 사용자들은 IPEX 자동 혼합 정밀도를 사용하여 더 나은 성능과 사용자 경험을 얻을 수 있습니다.
```
원문에서 master로 얘기하고 있어서 주 -> 마스터로 번역하는 게 더 직관적일 것 같아서 제안 드립니다! (혹은 현재 기본 브랜치 명을 반영해서 메인으로 번역하는 것도 좋을 것 같습니다)

2023-07-24 15:51 UTC, ArthurZucker approved these changes
LGTM thanks!

2023-07-24 15:54 UTC, merged