🌐 [i18n-KO] Translated `perf_infer_cpu.md` to Korean
huggingface/transformers pull request #24920
Opened 2023-07-19 13:44 UTC by junejae

# What does this PR do?

Translated the `<your_file>.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-19 21:10 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24920). All of your documentation changes will be reflected on that endpoint.

2023-07-21 14:04 UTC, junejae reviewed
초벌 수정

2023-07-21 14:04 UTC, junejae commented on docs/source/ko/_toctree.yml
> +      title: 단일 CPU 환경에서 추론하기
```suggestion
      title: CPU로 추론하기
```

2023-07-21 14:04 UTC, junejae commented on docs/source/ko/perf_infer_cpu.md
> +TorchScript에 대한 친절한 소개는 [PyTorch TorchScript 튜토리얼](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html#tracing-modules)의 소개를 참조하세요.
```suggestion
TorchScript에 대한 친절한 소개는 [PyTorch TorchScript 튜토리얼](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html#tracing-modules)을 참조하세요.
```

2023-07-23 07:30 UTC, keonju2 reviewed
저는 리뷰할 것이 없습니다...!! 잘 읽히는 것 같습니다 👍

2023-07-23 22:38 UTC, wonhyeongseo requested changes
지난 목요일 서울대에서 볼 수 있어서 반가웠어요! 우와, 번역이 깔끔해서 좋았고, `fix: manual edits` 커밋에 고민하신 흔적이 고스란히 보여서 너무 좋았어요! 활발하게 참여해주셔서 정말 감사합니다!!

리뷰는 일방적인 수용이 아닌 서로간의 대화를 전제로 이루어집니다. 때문에 "어라, 이건 내가 맞아!"라고 주장해주시면 오히려 더 재밌는 리뷰 시간이 될 것입니다. @harheem 님, @keonju2 님, @HongB1 님 모두 리뷰 자유롭게 올려주세요. 정말 기대됩니다. 💯 😆

2023-07-23 22:38 UTC, wonhyeongseo commented on docs/source/ko/perf_infer_cpu.md
> +PyTorch >= 1.14.0의 경우 jit 모드는 jit.trace에서 dict 입력이 지원되므로, 모든 모델의 예측 및 평가에 이점을 제공할 수 있습니다.
```suggestion
PyTorch의 버전이 1.14.0 이상이라면, jit 모드는 jit.trace에서 dict 입력이 지원되므로, 모든 모델의 예측과 평가가 개선될 수 있습니다.
```
이것도 마찬가지이지만, 한국어는 숫자 대소 비교에 워낙 간단한 구조를 가지고 있어 이상/이하/초과/미만 등을 사용하는게 더 자연스러울 수 있어요 🔢

2023-07-23 22:38 UTC, wonhyeongseo commented on docs/source/ko/perf_infer_cpu.md
> +PyTorch < 1.14.0의 경우, 질의 응답 모델과 같이 forward 매개변수의 순서가 jit.trace의 튜플 입력 순서와 일치하는 모델에 이점을 제공할 수 있습니다. 텍스트 분류 모델과 같이 forward 매개변수 순서가 jit.trace의 튜플 입력 순서와 일치하지 않는 경우, jit.trace가 실패하며 예외가 발생합니다. 이를 사용자에게
```suggestion
PyTorch의 버전이 1.14.0 미만이라면, 질의 응답 모델과 같이 forward 매개변수의 순서가 jit.trace의 튜플 입력 순서와 일치하는 모델에 득이 될 수 있습니다. 텍스트 분류 모델과 같이 forward 매개변수 순서가 jit.trace의 튜플 입력 순서와 다른 경우, jit.trace가 실패하며 예외가 발생합니다. 이때 예외상황을 사용자에게 알리기 위해 Logging이 사용됩니다.
```

2023-07-25 14:04 UTC, ArthurZucker approved these changes
Looks good to me thanks! 🔥

2023-07-25 14:04 UTC, merged