🌐 [i18n-KO] Translated `hpo_train.md` to Korean
huggingface/transformers pull request #24968
Opened 2023-07-21 04:35 UTC by harheem

# What does this PR do?

Translated the `your_file.md` file of the documentation to Korean 😄 
Thank you in advance for your review!

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-21 04:59 UTC, harheem commented on docs/source/ko/hpo_train.md
> +🤗 Transformers는 트레이닝을 더욱 간편하게 시작할 수 있도록 Transformers 모델을 최적화한 [`Trainer`] 클래스를 제공합니다. 🤗 이 클래스를 사용하면 사용자는 직접 훈련 루프를 작성할 필요 없이 학습을 진행할 수 있습니다. 또한, [`Trainer`]는 하이퍼파라미터 탐색을 위한 API를 제공합니다. 이 문서에서는 이 API들
API들을 -> API를

2023-07-21 06:21 UTC, wonhyeongseo requested changes
전반적으로 고민하신 흔적이 보여서 너무 좋았어요! 특히 바로 셀프 리뷰를 시도하신다는 점에서 놀랐고, 활발하게 참여해주셔서 정말 감사합니다!!

리뷰는 일방적인 수용이 아닌 서로간의 대화를 전제로 이루어집니다. 때문에 "어라, 이건 내가 맞아!"라고 주장해주시면 오히려 더 재밌는 리뷰 시간이 될 것입니다. @junejae 님, @keonju2 님, @HongB1 님 모두 리뷰 자유롭게 올려주세요. 정말 기대됩니다. 💯 😆

2023-07-21 06:21 UTC, wonhyeongseo commented on docs/source/ko/hpo_train.md
> +현재, DDP(Distributed Data Parallelism)를 위한 하이퍼파라미터 탐색은 optuna와 sigopt에서 가능합니다. 최상위 프로세스가 하이퍼파라미터 탐색 과정을 시작하고 그 결과를 다른 프로세스에 전달합니다.
```suggestion
현재, DDP(Distributed Data Parallelism; 분산 데이터 병렬처리)를 위한 하이퍼파라미터 탐색은 optuna와 sigopt에서 가능합니다. 최상위 프로세스가 하이퍼파라미터 탐색 과정을 시작하고 그 결과를 다른 프로세스에 전달합니다.
```
참고자료: [DP vs DDP 차이 정리 블로그](https://algopoolja.tistory.com/m/95)

2023-07-21 06:33 UTC, harheem commented on docs/source/ko/hpo_train.md
> +🤗 Transformers는 트레이닝을 더욱 간편하게 시작할 수 있도록 Transformers 모델을 최적화한 [`Trainer`] 클래스를 제공합니다. 🤗 이 클래스를 사용하면 사용자는 직접 훈련 루프를 작성할 필요 없이 학습을 진행할 수 있습니다. 또한, [`Trainer`]는 하이퍼파라미터 탐색을 위한 API를 제공합니다. 이 문서에서는 이 API들
아, 저는 이 부분이 제일 번역하기 어려웠고 그렇기에 고민을 정말 많이했답니다. 
리뷰를 보고 다시 읽으니 정말 어색하네요 ㅎㅎㅎ 제안해주신 커밋 저는 좋습니다!

2023-07-21 06:37 UTC, harheem commented on docs/source/ko/hpo_train.md
> +현재, [`Trainer`]는 아래와 같은 네 가지 하이퍼파라미터 탐색 백엔드를 지원합니다.
네 가지와 4가지 모두 옳은 표현이군요! 국립국어원 트위터: https://twitter.com/urimal365/status/423267727734628352
이 부분을 통일하면 좋겠다고 생각했답니다. 4가지가 더 자연스럽다고 느끼신것이죠?!

2023-07-21 06:43 UTC, wonhyeongseo commented on docs/source/ko/hpo_train.md
> +현재, [`Trainer`]는 아래와 같은 네 가지 하이퍼파라미터 탐색 백엔드를 지원합니다.
네, 저는 숫자가 보이는게 더 직관적이라고 느껴요. 국립국어원 트윗을 찾아오시다니 ㅋㅋ 아주 좋아요.

2023-07-25 09:53 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24968). All of your documentation changes will be reflected on that endpoint.

2023-07-25 10:54 UTC, ArthurZucker approved these changes
Thanks for working on this! 🚀

2023-07-25 11:44 UTC, sgugger commented
Can you just solve the conflict so we can merge this PR?

2023-07-25 12:28 UTC, merged