🌐 [i18n-KO] Translated perf_hardware.md to Korean
huggingface/transformers pull request #24966
Opened 2023-07-21 00:35 UTC by augustinLib

# What does this PR do?

Translated the `<your_file>.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)
@0525hhgus, @Sunmin0520, @54data, @seank021, @kihoon71

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-21 09:25 UTC, 0525hhgus requested changes
빠른 번역 감사합니다 👍
아래 목차와 누락된 문장 관련하여 우선적으로 리뷰를 올렸으니, 참고 부탁드립니다!
(52 라인까지 검토)

2023-07-21 09:37 UTC, augustinLib commented on docs/source/ko/perf_hardware.md
> +- 더 많은 CPU 및 NVMe (DeepSpeed-Infinity를 통한 offload)
이 부분은 생각을 못했었네요 ㅠㅠ 다음부터는 이러한 부분도 신경써서 올리겠습니다! ㅠㅠ

2023-07-21 12:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24966). All of your documentation changes will be reflected on that endpoint.

2023-07-22 00:19 UTC, Sunmin0520 commented
위에서 @0525hhgus 님의 댓글을 제외하고는 별도의 리뷰사항 없습니다 :)

2023-07-24 13:39 UTC, 54data commented on docs/source/ko/perf_hardware.md
> +GPU가 과열될 때 정확한 적정 온도를 알기 어려우나, 아마도 +80도C 미만이면 좋지만 더 낮을수록 좋습니다. 70℃-75℃ 정도가 훌륭한 온도 범위입니다. 성능 저하가 발생하기 시작하는 온도는 대략 84℃-90℃ 정도일 것입니다. 하지만 성능 저하 이외에도 지속적으로 매우 높은 온도는 GPU 수명을 단축시킬 수 있습니다.
```suggestion
GPU가 과열될 때 정확한 적정 온도를 알기 어려우나, 아마도 +80℃ 미만이면 좋지만 더 낮을수록 좋습니다. 70℃-75℃ 정도가 훌륭한 온도 범위입니다. 성능 저하가 발생하기 시작하는 온도는 대략 84℃-90℃ 정도일 것입니다. 하지만 성능 저하 이외에도 지속적으로 매우 높은 온도는 GPU 수명을 단축시킬 수 있습니다.
```
해당 부분도 다른 표기와 같이 맞춰주는 게 좋을 것 같아서 제안 드립니다!

2023-07-25 11:00 UTC, ArthurZucker approved these changes
Looks good! Could you update the ## GPU [[gpu]] in the english version as well? Seems like it is not rendering properly, let's kill two birds with one stone! 

<img width="959" alt="image" src="https://github.com/huggingface/transformers/assets/48595927/d22d9839-7263-47d6-988b-408ed3bec0aa">

2023-07-25 11:44 UTC, merged

2023-07-26 01:31 UTC, augustinLib commented
> Looks good! Could you update the ## GPU [[gpu]] in the english version as well? Seems like it is not rendering properly, let's kill two birds with one stone!
> 
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/48595927/255879037-d22d9839-7263-47d6-988b-408ed3bec0aa.png">

@ArthurZucker 
I updated that issue! and also i could confirm [here](https://huggingface.co/docs/transformers/main/en/perf_hardware) that it worked successfully. 
This part didn't work well in previous versions, but it works well in the current `main`. It was a problem that appeared because the newline was omitted in the markdown file

Thank you for your hard work and dedication, it is greatly appreciated.