🌐 [i18n-KO] Translated `perf_infer_gpu_one.md` to Korean
huggingface/transformers pull request #24978
Opened 2023-07-21 08:02 UTC by eenzeenee

# What does this PR do?

Translated the `perf_infer_gpu_one.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

May you please review this PR? @sronger, @TaeYupNoh, @kj021, @HanNayeoniee, @eenzeenee, @sim-so

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-21 12:47 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24978). All of your documentation changes will be reflected on that endpoint.

2023-07-21 15:37 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +`bitsandbytes`를 설치하고 GPU에서 쉬운 모델 압축의 이점을 얻을 수 있습니다. FP4 양자화를 사용하면 원래의 전체 정밀도 버전과 비교하여 모델 크기를 최대 8배 줄일 수 있습니다. 아래에서 시작하는 방법을 확인하세요.
```suggestion
`bitsandbytes`를 설치하고 GPU에서 쉬운 모델 압축의 이점을 얻을 수 있습니다. FP4 양자화를 사용하면 원래의 전체 정밀도 버전과 비교하여 모델 크기를 최대 8배 줄일 수 있습니다. 아래에서 방법을 확인하세요.
```

보다 자연스럽게 읽히도록 수정하겠습니다.

2023-07-21 15:37 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +Int8 혼합 정밀도 행렬 분해는 행렬 곱셈을 두 개의 스트림으로 분리합니다: (1) fp16로 곱해지는 체계적인 특이값 이상치 스트림 행렬(0.01%) 및 (2) int8 행렬 곱셈의 일반적인 스트림(99.9%). 이 방법을 사용하면 매우 큰 모델에 대해 예측적인 저하 없이 int8 추론이 가능합니다.
```suggestion
Int8 혼합 정밀도 행렬 분해는 행렬 곱셈을 두 개의 스트림으로 분리합니다: (1) fp16로 곱해지는 체계적인 특이값 이상치 스트림 행렬(0.01%) 및 (2) int8 행렬 곱셈의 일반적인 스트림(99.9%). 이 방법을 사용하면 매우 큰 모델에 대해 예측 저하 없이 int8 추론이 가능합니다.
```

자연스럽게 읽히도록 수정하겠습니다.

2023-07-21 16:28 UTC, sim-so requested changes
첫 번째 번역 PR 고생 많으셨습니다! 🥳
전반적으로 문장을 잘 다듬어주셔서 읽기 쉬웠어요!
서식이나 glossary 중심으로 수정 제안을 드렸습니다. 참고 부탁 드립니다!

추가로, '어텐션 고속 경로'라는 표현이 제게 너무 낯설어서 고민해봤는데 무척 어려웠어요.
우선 다른 분들의 리뷰를 기다릴게요 😆

2023-07-21 16:28 UTC, sim-so commented on docs/source/ko/perf_infer_gpu_one.md
> +하지만 `accelerate`를 사용하여 각 GPU에 할당할 GPU RAM을 제어할 수 있습니다. 다음과 같이 `max_memory` 인자를 사용하세요:
```suggestion
하지만 `accelerate`를 사용하여 각 GPU에 할당할 GPU RAM을 제어할 수 있습니다. 다음과 같이 `max_memory` 인수를 사용하세요:
```
glossary에 기반한 수정 제안입니다.

2023-07-21 16:28 UTC, sim-so commented on docs/source/ko/perf_infer_gpu_one.md
> +다중 GPU에서 혼합 4비트 모델을 로드하는 방법은 단일 GPU 설정과 동일합니다(동일한 명령어 사용):
```suggestion
다중 GPU에서 혼합 4비트 모델을 가져오는 방법은 단일 GPU 설정과 동일합니다(동일한 명령어 사용):
```
glossary에 기반하여 수정 제안을 드립니다!

2023-07-21 16:28 UTC, sim-so commented on docs/source/ko/perf_infer_gpu_one.md
> +* `pipeline()` 함수 대신 모델의 `generate()` 메소드를 사용하는 것을 권장합니다. `pipeline()` 함수로는 추론이 가능하지만, 혼합 8비트 모델에 최적화되지 않았기 때문에 `generate()` 메소드를 사용하는 것보다 느릴 수 있습니다. 또한, nucleus 샘플링과 같은 일부 샘플링 전략은 혼합 8비트 모델에 대해 `pip
원문에 `nucleaus`라고 오타가 있어서 한글 문서에서는 정정해주셨군요! 👍

2023-07-21 16:28 UTC, sim-so commented on docs/source/ko/perf_infer_gpu_one.md
> +하지만 `accelerate`를 사용하여 각 GPU에 할당할 GPU RAM을 제어할 수 있습니다. 다음과 같이 `max_memory` 인자를 사용하세요:
```suggestion
하지만 `accelerate`를 사용하여 각 GPU에 할당할 GPU RAM을 제어할 수 있습니다. 다음과 같이 `max_memory` 인수를 사용하세요:
```
glossary에 따른 수정 제안입니다.

2023-07-21 16:28 UTC, sim-so commented on docs/source/ko/perf_infer_gpu_one.md
> +Google Colab에서 T5-11b(42GB in fp32)를 실행하는 데모를 확인하세요. Google Colab에서 8비트 양자화를 사용:
```suggestion
Google Colab에서 8비트 양자화를 사용하여 T5-11b(42GB in fp32)를 실행하는 데모를 확인하세요:
```
끝나는 문장을 자연스럽게 해보고자 두 문장을 이어보았는데, 어떠실까요?

2023-07-21 16:28 UTC, sim-so commented on docs/source/ko/perf_infer_gpu_one.md
> +또는 BLOOM-3B에 대한 데모:
```suggestion
또는 BLOOM-3B에 대한 데모를 확인하세요:
```
이 줄도 전체적인 문장 톤에 맞추어 보았습니다.

2023-07-22 04:20 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +하지만 `accelerate`를 사용하여 각 GPU에 할당할 GPU RAM을 제어할 수 있습니다. 다음과 같이 `max_memory` 인자를 사용하세요:
놓친 부분이 있었네요 감사합니다!

2023-07-22 06:19 UTC, TaeYupNoh commented on docs/source/ko/perf_infer_gpu_one.md
> +이 예에서는 첫 번째 GPU가 1GB의 메모리를 사용하고 두 번째 GPU가 2GB를 사용합니다.
```suggestion
이 예시에서는 첫 번째 GPU가 1GB의 메모리를 사용하고 두 번째 GPU가 2GB를 사용합니다.
```

조금 더 자연스러운 느낌으로 수정해 보았습니다.

2023-07-22 06:19 UTC, TaeYupNoh commented on docs/source/ko/perf_infer_gpu_one.md
> +필요한 라이브러리를 설치한 후 혼합 8비트 모델을 로드하는 방법은 다음과 같습니다:
```suggestion
필요한 라이브러리를 설치한 후 혼합 8비트 모델을 가져오는 방법은 다음과 같습니다:
```
glossary에 기반하여 수정해 보았습니다.

2023-07-22 07:41 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +`bitsandbytes`를 설치하고 GPU에서 쉬운 모델 압축의 이점을 얻을 수 있습니다. FP4 양자화를 사용하면 원래의 전체 정밀도 버전과 비교하여 모델 크기를 최대 8배 줄일 수 있습니다. 아래에서 시작하는 방법을 확인하세요.
훨씬 자연스러운 흐름이 된 것 같습니다! 감사합니다!

2023-07-22 07:41 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +필요한 라이브러리를 설치한 후 혼합 8비트 모델을 로드하는 방법은 다음과 같습니다:
감사합니다!

2023-07-23 10:09 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +### 요구 사항 [[requirements]]
```suggestion
### 요구 사항 [[requirements-for-fp4-mixedprecision-inference]]
```

올려주신 문서 참고하여 anchor link 수정했습니다! 감사합니다~

2023-07-23 10:09 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +### 요구 사항 [[requirements]]
```suggestion
### 요구 사항 [[requirements-for-int8-mixedprecision-matrix-decomposition]]]]
```

51 line과 함께 anchor link 오류를 해결하기 위한 수정입니다!

2023-07-23 10:09 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +PyTorch의 어텐션 고속 경로는 커널 퓨전과 [중첩된 텐서](https://pytorch.org/docs/stable/nested.html)의 사용을 통해 추론 속도를 높일 수 있습니다. 자세한 벤치마크는 [이 블로그 글](https://medium.com/pytorch/bettertransformer-out-of-the-box-performance-
```suggestion
PyTorch의 어텐션 패스트패스는 커널 퓨전과 [중첩된 텐서](https://pytorch.org/docs/stable/nested.html)의 사용을 통해 추론 속도를 높일 수 있습니다. 자세한 벤치마크는 [이 블로그 글](https://medium.com/pytorch/bettertransformer-out-of-the-box-performance-for-huggingface-transformers-3fbe27d50ab2)에서 확인할 수 있습니다.
```

https://pytorch.org/blog/accelerated-pytorch-2/
https://www.youtube.com/watch?v=CVyggj3Nv-g&t=123

fastpath 관련하여 여러 참고자료들을 살펴보니 Transformer의 attention과 같이 Better Transformer에서 활용되는 일종의 아키텍처인 것으로 짐작됩니다. 어텐션과의 일관성을 위해 패스트패스로 수정하고자 합니다!

2023-07-23 10:09 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +## Better Transformer: PyTorch 네이티브 Transformer 고속 경로 [[better-transformer-pytorchnative-transformer-fastpath]]
```suggestion
## Better Transformer: PyTorch 네이티브 Transformer 패스트패스 [[better-transformer-pytorchnative-transformer-fastpath]]
```

https://pytorch.org/blog/accelerated-pytorch-2/
https://www.youtube.com/watch?v=CVyggj3Nv-g&t=123

fastpath 관련하여 여러 참고자료들을 살펴보니 Transformer의 attention과 같이 Better Transformer에서 활용되는 일종의 아키텍처인 것으로 짐작됩니다. 어텐션과의 일관성을 위해 패스트패스로 수정하고자 합니다!

2023-07-23 10:09 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +PyTorch 네이티브 [`nn.MultiHeadAttention`](https://pytorch.org/blog/a-better-transformer-for-fast-transformer-encoder-inference/) 어텐션 고속 경로인 BetterTransformer는 [🤗 Optimum 라이브러리](https://huggingface.co/do
```suggestion
PyTorch 네이티브 [`nn.MultiHeadAttention`](https://pytorch.org/blog/a-better-transformer-for-fast-transformer-encoder-inference/) 어텐션 패스트패스인 BetterTransformer는 [🤗 Optimum 라이브러리](https://huggingface.co/docs/optimum/bettertransformer/overview)의 통합을 통해 Transformers와 함께 사용할 수 있습니다.
```

https://pytorch.org/blog/accelerated-pytorch-2/
https://www.youtube.com/watch?v=CVyggj3Nv-g&t=123

fastpath 관련하여 여러 참고자료들을 살펴보니 Transformer의 attention과 같이 Better Transformer에서 활용되는 일종의 아키텍처인 것으로 짐작됩니다. 어텐션과의 일관성을 위해 패스트패스로 수정하고자 합니다!

2023-07-23 10:09 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +PyTorch 2.0부터는 어텐션 고속 경로가 인코더와 디코더 모두에서 지원됩니다. 지원되는 아키텍처 목록은 [여기](https://huggingface.co/docs/optimum/bettertransformer/overview#supported-models)에서 확인할 수 있습니다.
```suggestion
PyTorch 2.0부터는 어텐션 패스트패스가 인코더와 디코더 모두에서 지원됩니다. 지원되는 아키텍처 목록은 [여기](https://huggingface.co/docs/optimum/bettertransformer/overview#supported-models)에서 확인할 수 있습니다.
```

https://pytorch.org/blog/accelerated-pytorch-2/
https://www.youtube.com/watch?v=CVyggj3Nv-g&t=123

fastpath 관련하여 여러 참고자료들을 살펴보니 Transformer의 attention과 같이 Better Transformer에서 활용되는 일종의 아키텍처인 것으로 짐작됩니다. 어텐션과의 일관성을 위해 패스트패스로 수정하고자 합니다!

2023-07-23 10:13 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +### 요구 사항 [[requirements]]
영문 원본 문서 수정을 위해 몇가지 질문이 있어 코멘트를 남깁니다!

1. 현재 제 깃허브에 올라온 main과 허깅페이스의 main 간 commit 차이가 있는데 이를 PR로 당겨온 뒤 새로운 브랜치를 판 뒤 수정하는 것이 현재 브랜치에서 진행하는 것보다 더 나은 방법일지 궁금합니다!

2. 영문 원본 문서 수정에 있어서도 리뷰어로 저희 팀원들을 멘션해도 괜찮을까요?

2023-07-23 11:37 UTC, sim-so commented on docs/source/ko/perf_infer_gpu_one.md
> +### 요구 사항 [[requirements]]
1. 
> 현재 제 깃허브에 올라온 main과 허깅페이스의 main 간 commit 차이가 있는데 이를 PR로 당겨온 뒤 새로운 브랜치를 판 뒤 수정하는 것이 현재 브랜치에서 진행하는 것보다 더 나은 방법일지 궁금합니다!
- 네, PR별로 브랜치를 따로 사용하시는 것이 좋습니다. 새 PR을 열어 영어 원본을 수정하신다면 말씀하신 방법으로 새 브랜치를 만들어 진행해주세요!
2. 
> 영문 원본 문서 수정에 있어서도 리뷰어로 저희 팀원들을 멘션해도 괜찮을까요?
- 번역 이슈가 아니라서 팀원들을 멘션하지 않으셔도 괜찮습니다. 물론 수정한 부분에 대해 의견을 구하고 싶다면 멘션을 해주셔도 문제 없습니다!
 
문의 주신 내용과 관련하여 참고하실 수 있는 이슈가 하나 더 있더라구요. 원본 문서 수정 건만 따로 올린 PR이라 이슈/PR 본문을 쓰시거나 브랜치 이름을 정하실 때 보다 참고가 되실 것 같아 추가로 공유 드립니다:
- 이슈: https://github.com/huggingface/transformers/issues/23729

2023-07-24 05:38 UTC, eenzeenee commented on docs/source/ko/perf_infer_gpu_one.md
> +### 요구 사항 [[requirements]]
```suggestion
### 요구 사항 [[requirements-for-int8-mixedprecision-matrix-decomposition]]
```

2023-08-02 11:28 UTC, ArthurZucker approved these changes
Looks good to me! The images don't seem to render in both `main` and here for ![HFxbitsandbytes.png](https://s3.amazonaws.com/moonup/production/uploads/1659861207959-62441d1d9fdefb55a0b7d12c.png) cc @younesbelkada  if you have time to upload them to https://huggingface.co/datasets/huggingface/documentation-images

2023-08-02 11:41 UTC, younesbelkada commented on docs/source/ko/perf_infer_gpu_one.md
> +![MixedInt8.gif](https://s3.amazonaws.com/moonup/production/uploads/1660567469965-62441d1d9fdefb55a0b7d12c.gif)
```suggestion
![MixedInt8.gif](https://cdn-uploads.huggingface.co/production/uploads/1660567469965-62441d1d9fdefb55a0b7d12c.gif)
```
same here

2023-08-07 06:37 UTC, ArthurZucker commented
Thanks for fixing! 🔥

2023-08-07 06:37 UTC, merged