🌐 [i18n-KO] Translated perf_infer_gpu_one.md to Korean
huggingface/transformers pull request #24983
Opened 2023-07-21 10:00 UTC by hyunhp

# What does this PR do?

Translated the `<your_file>.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

May you please review this PR? @nuatmochoi, @bolizabeth, @heuristicwave, @mjk0618, @jungnerd, @hyunhp

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-21 12:32 UTC, sgugger commented
Please do not open and close several PRs for the same file. You can update a PR by pushing more commits to it.

2023-07-21 12:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24983). All of your documentation changes will be reflected on that endpoint.

2023-07-21 13:36 UTC, hyunhp commented
> Please do not open and close several PRs for the same file. You can update a PR by pushing more commits to it.

Duly noted

2023-07-21 16:13 UTC, nuatmochoi requested changes

2023-07-21 16:13 UTC, nuatmochoi commented on docs/source/ko/perf_train_gpu_many.md
> +**⇨ 멀티-노드 / 멀티-GPU**
```suggestion
**⇨ 다중 노드 /  다중 GPU**
```
glossary 따라 `다중 GPU`로 변경하였고, 동일한 형식을 맞추기 위해 앞부분도 `다중 노드`으로 수정하였습니다.

2023-07-24 01:10 UTC, hyunhp commented on docs/source/ko/perf_train_gpu_many.md
> +4. **Zero Redundancy Optimizer (ZeRO)** - TP와 유사하게 텐서를 샤딩하지만, 전체 텐서는 순방향 또는 역방향 계산을 위해 재구성되므로 모델을 수정할 필요가 없습니다. 또한 제한된 GPU 메모리를 보상하기 위해 다양한 오프로드 기술을 지원합니다.
감사합니다, 보상보다는 확실히 보완이 문맥이 부드러워지네여 :)

2023-07-24 01:10 UTC, hyunhp commented on docs/source/ko/perf_train_gpu_many.md
> +**⇨ 멀티-노드 / 멀티-GPU**
glossary 놓친 부분이 있었네요, 감사합니다 ~~~

2023-07-26 07:00 UTC, sjlee-wise commented on docs/source/ko/perf_train_gpu_many.md
> +**⇨ 다중 노드 /  다중 GPU**
이전 문단에서는 Multi-GPU를 "멀티-GPU"라고 표기했어서 같은 용어로 통일이 필요해 보입니다.

2023-07-26 07:00 UTC, sjlee-wise commented on docs/source/ko/perf_train_gpu_many.md
> +- 이 방식을 "naive" MP라고 부르는 이유는 주어진 상황에 하나의 GPU를 제외한 모든 GPU가 유휴 상태라는 점입니다. 따라서 4개의 GPU를 사용하는 경우 단일 GPU의 메모리 양을 4배로 늘리고 나머지 하드웨어는 무시하는 것과 거의 동일합니다. 또한 장치 간 데이터 복사의 오버헤드도 있습니다. 따라서 4개의 6GB 카드는 naive MP를 사
앞에서는 그래디언트라고 하였기에 문서 내에서 같은 단어로 통일이 필요해 보입니다.

2023-07-26 07:00 UTC, sjlee-wise commented on docs/source/ko/perf_train_gpu_many.md
> +개념적으로 이는 그라디언트 누적 단계 (GAS)와 동일한 개념입니다. 파이토치에서는 `chunks`를 사용하고 DeepSpeed에서는 동일한 하이퍼파라미터를 GAS로 참조합니다.
여기도 그라디언트로 표기되어 있습니다.

2023-07-26 07:00 UTC, sjlee-wise commented on docs/source/ko/perf_train_gpu_many.md
> +다이어그램에서 보이는 것처럼 "dead" 시간의 버블이 존재하여 마지막 `forward` 단계가 `backward` 단계가 파이프라인을 완료하기를 기다려야 하는 상황이 발생하지만, `chunks`의 최적 값을 찾는 것의 목적은 모든 참여하는 GPU에서 동시에 고도로 활용되는 GPU 활용을 가능하게 하여 버블의 크기를 최소화하는 것입니다.
최적 값이란 말이 저는 최적해(optimal solution)로 읽히기도 합니다. 원문은 best value던데 최적의 값, 또는 가장 적절한 값 등으로 수정하면 어떨지 제안드립니다.

2023-07-26 07:00 UTC, sjlee-wise commented on docs/source/ko/perf_train_gpu_many.md
> +이론적으로는 ZeRO 단계 2(그라디언트 분할)를 파이프라인 병렬 처리와 함께 사용할 수도 있지만, 이는 성능에 나쁜 영향을 미칠 것입니다. 각 마이크로 배치마다 그라디언트를 샤딩하기 전에 추가적인 리듀스-스캐터 컬렉티브가 필요하며, 이는 잠재적으로 상당한 통신 오버헤드를 추가합니다. 파이프라인 병렬 처리의 특성상 작은 마이크로 배치가 사용되며, 산술 연
```suggestion
이론적으로는 ZeRO 단계 2(그라디언트 분할)를 파이프라인 병렬 처리와 함께 사용할 수도 있지만, 이는 성능에 나쁜 영향을 미칠 것입니다. 각 마이크로 배치마다 그라디언트를 샤딩하기 전에 추가적인 리듀스-스캐터 컬렉티브가 필요하며, 이는 잠재적으로 상당한 통신 오버헤드를 추가합니다. 파이프라인 병렬 처리의 특성상 작은 마이크로 배치가 사용되며, 산술 연산 강도(마이크로 배치 크기)를 균형 있게 유지하면서 파이프라인 버블(마이크로 배치 수)을 최소화하는 것에 중점을 둡니다. 따라서 해당 통신 비용은 문제가 될 것입니다.
```

2023-08-10 21:41 UTC, stevhliu reviewed
Very nice, thank you for your translation! If you can just update the `toctree`, I think it'll be ready to merge soon!

2023-09-21 08:03 UTC, closed without merging