[i18n-KO] Translated `big_models.md` to Korean
huggingface/transformers pull request #24985
Opened 2023-07-21 10:41 UTC by bolizabeth

# What does this PR do?

Translated the `big_models.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

May you please review this PR? @hyunhp @nuatmochoi @heuristicwave @mjk0618 @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-21 11:45 UTC, nuatmochoi requested changes

2023-07-21 11:45 UTC, nuatmochoi commented on docs/source/ko/big_models.md
> +만약 [`~PreTrainedModel.from_pretrained`]를 사용하지 않고 모델 내에서 이러한 샤드 체크포인트를 직접로드하려면 (전체 체크포인트를 위해 `model.load_state_dict()`를 수행하는 것처럼), [`~modeling_utils.load_sharded_checkpoint`]를 사용해야 합니다.
```suggestion
만약 [`~PreTrainedModel.from_pretrained`]를 사용하지 않고 모델 내에서 이러한 샤딩된 체크포인트를 직접 가져오려면 (전체 체크포인트를 위해 `model.load_state_dict()`를 수행하는 것처럼), [`~modeling_utils.load_sharded_checkpoint`]를 사용해야 합니다.
```
`sharded`를 번역할 때 `샤딩된`이 더 자연스러울 것 같아 수정하였습니다!

2023-07-21 11:45 UTC, nuatmochoi commented on docs/source/ko/big_models.md
> +샤드 체크포인트는 위에서 언급한 작업 흐름의 2단계에서 메모리 사용량을 줄이지만, 저(低)메모리 설정에서 모델을 사용하기 위해 우리의 Accelerate 라이브러리를 기반으로 한 도구를 활용하는 것이 좋습니다.
```suggestion
샤딩된 체크포인트는 위에서 언급한 작업 흐름의 2단계에서 메모리 사용량을 줄이지만, 저(低)메모리 설정에서 모델을 사용하기 위해 우리의 Accelerate 라이브러리를 기반으로 한 도구를 활용하는 것이 좋습니다.
```
동일한 항목 수정하였습니다.

2023-07-21 11:45 UTC, nuatmochoi commented on docs/source/ko/big_models.md
> +## 샤드 체크포인트 [[sharded-checkpoints]]
```suggestion
## 샤딩된 체크포인트 [[sharded-checkpoints]]
```
동일 항목이 소제목에도 있어 수정하였습니다.

2023-07-21 12:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_24985). All of your documentation changes will be reflected on that endpoint.

2023-07-24 06:17 UTC, heuristicwave commented on docs/source/ko/big_models.md
> +매우 큰 사전훈련된 모델을 사용하려면, RAM 사용을 최소화하는 것이 도전이 됩니다. 일반적인 PyTorch 작업 흐름은 다음과 같습니다:
```suggestion
매우 큰 사전훈련된 모델을 사용하려면, RAM 사용을 최소화해야 하는 과제가 있습니다. 일반적인 PyTorch 작업 흐름은 다음과 같습니다:
```
원문 25L Problem과의 관계를 고려하여 '도전' 대신에 '과제' 혹은 '문제'를 사용하는 것이 좋을것 같습니다.

2023-08-10 21:43 UTC, stevhliu reviewed
Great job! Feel free to mark this as ready for review once you've resolved the other reviewer's feedback and updated the `toctree` 😄

2023-08-18 14:44 UTC, wonhyeongseo requested changes
안녕하세요 @bolizabeth 님!
너무 리뷰가 늦어 정말 죄송합니다. 전반적으로 고민하신 흔적이 보여서 너무 좋았어요! 제안된 수정사항을 읽어보신후 반영 부탁드립니다!!

리뷰는 일방적인 수용이 아닌 서로간의 대화를 전제로 이루어집니다. 때문에 "어라, 이건 내가 맞아!"라고 주장해주시면 오히려 더 재밌는 리뷰 시간이 될 것입니다. 참여해주신 @heuristicwave 님, @nuatmochoi 님, 담당이셨던 @jungnerd 님도 모두 리뷰 자유롭게 올려주세요. 감사합니다. 💯 😆

2023-08-18 14:44 UTC, wonhyeongseo commented on docs/source/ko/_toctree.yml
> +      title: (번역중) 대형 모델을 인스턴스화
```suggestion
      title: 대형 모델을 인스턴스화
```

2023-08-18 14:44 UTC, wonhyeongseo commented on docs/source/ko/big_models.md
> +1단계와 2단계 모두 메모리에 모델의 전체 버전을 요구하며, 대부분의 경우에는 문제가 없지만 모델이 여러 기가바이트의 용량을 차지하기 시작하면 두 복사본은 RAM을 초과하여 메모리 부족 문제를 야기할 수 있습니다. 더 심각한 문제는 분산 학습을 위해 `torch.distributed`를 사용하는 경우, 각 프로세스가 사전훈련된 모델을 로드하고 이 두 복사
```suggestion
1단계와 2단계 모두 모델의 전체 버전을 메모리에 적재해야 하며, 대부분 문제가 없지만 모델이 기가바이트급의 용량을 차지하기 시작하면 복사본 2개가 RAM을 초과하여 메모리 부족 이슈를 야기할 수 있습니다. 더 심각한 문제는 분산 학습을 위해 `torch.distributed`를 사용하는 경우, 프로세스마다 사전훈련된 모델을 로드하고 복사본을 2개씩 RAM에 저장한다는 것입니다.
```

2023-08-18 14:44 UTC, wonhyeongseo commented on docs/source/ko/big_models.md
> +무작위로 생성된 모델은 "비어 있는" 텐서로 초기화되며 메모리 공간을 차지하지만 (무작위 값은 주어진 시간에 이 메모리 묶음에 있던 내용입니다), 적절한 분포를 따르는 무작위 초기화 (예: 정규 분포)는 오직 3단계에서 초기화되지 않은 가중치에 대해 수행되며 최대한 빠르게 수행됩니다!
```suggestion
무작위로 생성된 모델은 "비어 있는" (즉 그때 메모리에 있던 것으로 이뤄진) 텐서로 초기화되며 메모리 공간을 차지합니다. 초기화된 모델/파라미터의 종류에 적합한 분포(예: 정규 분포)에 따른 무작위 초기화는 가능한 한 빠르게 하기 위해 초기화되지 않은 가중치에 대해 3단계 이후에만 수행됩니다!
```

2023-08-18 14:44 UTC, wonhyeongseo commented on docs/source/ko/big_models.md
> +이 안내서에서는 Transformers가 이 문제를 해결하기 위해 제공하는 솔루션을 살펴봅니다. 주의할 점은 이는 활발히 개발 중인 분야이므로 여기서 설명하는 API가 앞으로 약간 변경될 수 있다는 것입니다.
```suggestion
이 안내서에서는 Transformers가 이 문제를 해결하기 위해 제공하는 솔루션을 살펴봅니다. 주의할 점은 아직 활발히 개발 중인 분야이므로 여기서 설명하는 API가 앞으로 약간 변경될 수 있다는 것입니다.
```

2023-08-18 14:44 UTC, wonhyeongseo commented on docs/source/ko/big_models.md
> +더 많은 정보를 위해 다음 가이드를 읽어보세요: [Large model loading using Accelerate](./main_classes/model#large-model-loading)
```suggestion
자세한 사항은 다음 가이드를 참조해주세요: [Accelerate로 대규모 모델 가져오기 (영문)](../en/main_classes/model#large-model-loading)
```

2023-09-21 08:03 UTC, closed without merging