🌐 [i18n-KO] Translated `add_tensorflow_model.md` to Korean
huggingface/transformers pull request #25017
Opened 2023-07-22 14:18 UTC by keonju2

# What does this PR do?

Translated the `add_tensorflow_model.md` file of the documentation to Korean 😄 
Thank you in advance for your review!

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)
@keonju2

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-24 13:27 UTC, sgugger commented
Please do not open and close four different PRs for the same file. You can update the original PR.

2023-07-24 15:12 UTC, junejae commented on docs/source/ko/add_tensorflow_model.md
> +그러나 이는 모델 별로 호환성을 추가해야한다는 것을 의미합니다. 좋은 소식은 기존 모델에 TensorFlow 호환성을 추가하는 것이 [처음부터 새로운 모델을 추가하는 것보다 간단하다는 것입니다](add_new_model)!
```suggestion
🤗 Transformers와 함께 사용할 수 있는 여러 가지 프레임워크를 활용할 수 있다는 것은, 응용 프로그램을 설계할 때 그들의 강점을 유연하게 이용할 수 있다는 것을 의미함과 동시에 모델 별로 호환성을 추가해야 한다는 것을 뜻합니다. 좋은 소식은 기존 모델에 TensorFlow 호환성을 추가하는 것이 [처음부터 새로운 모델을 추가하는 것보다 간단하다는 것입니다](add_new_model)! 
```

원문을 존중하면서도 한국적으로 바꿔보았습니다. 어떠신가요?

2023-07-25 08:57 UTC, harheem commented on docs/source/ko/add_tensorflow_model.md
> +가정하에 TensorFlow 모델 아키텍처가 🤗 Transformers에서 사용 가능하다고 가정하고, PyTorch 가중치를 TensorFlow 가중치로 변환하는 것은 쉽습니다!
```suggestion
TensorFlow 모델 아키텍처가 🤗 Transformers에서 사용 가능하다고 가정하면 PyTorch 가중치를 TensorFlow 가중치로 변환하는 것은 쉽습니다!
```

2023-07-25 08:57 UTC, harheem commented on docs/source/ko/add_tensorflow_model.md
> +가정하에 TensorFlow 모델 아키텍처가 🤗 Transformers에서 사용 가능하다고 가정하고, PyTorch 가중치를 TensorFlow 가중치로 변환하는 것은 쉽습니다!
가정하에 ~ 가정하고, 이 부분에서 '가정'이 반복되어 수정하면 좋을 것 같습니다! 🤗

2023-07-25 13:27 UTC, keonju2 commented on docs/source/ko/add_tensorflow_model.md
> +그러나 이는 모델 별로 호환성을 추가해야한다는 것을 의미합니다. 좋은 소식은 기존 모델에 TensorFlow 호환성을 추가하는 것이 [처음부터 새로운 모델을 추가하는 것보다 간단하다는 것입니다](add_new_model)!
오 너무 좋습니다!! 문장 문장에 집중하다보니 이렇게 표현을 변경하는 것을 놓쳤던 것 같습니다! 감사합니다:)

2023-07-25 13:28 UTC, keonju2 commented on docs/source/ko/add_tensorflow_model.md
> +가정하에 TensorFlow 모델 아키텍처가 🤗 Transformers에서 사용 가능하다고 가정하고, PyTorch 가중치를 TensorFlow 가중치로 변환하는 것은 쉽습니다!
이런 부분이 있었던 걸 놓쳤네요 감사합니다!

2023-07-28 02:37 UTC, wonhyeongseo requested changes
리뷰가 늦어져서 죄송합니다. ~L50 까지 간단한 약식 리뷰를 마쳤어요. 남은 부분도 내일까지 모두 살펴보고서 뵙겠습니다, 건주님!

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +그러나 이는 모델 별로 호환성을 추가해야한다는 것을 의미합니다. 좋은 소식은 기존 모델에 TensorFlow 호환성을 추가하는 것이 [처음부터 새로운 모델을 추가하는 것보다 간단하다는 것입니다](add_new_model)!
```suggestion
🤗 Transformers에서처럼 사용할 수 있는 여러 가지 프레임워크가 있다는 것은 애플리케이션을 설계할 때 그들의 강점을 유연하게 이용할 수 있다는 장점이 있지만, 모델 별로 호환성을 추가해야 한다는 단점 또한 존재한다는 것을 의미합니다. 좋은 소식은 기존 모델에 TensorFlow 호환성을 추가하는 것이 [처음부터 새로운 모델을 추가하는 것](add_new_model)보다도 간단하다는 것입니다! 
```
@junejae 님 정말 감사합니다! 앞부분만 살짝 고쳤습니다.

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +큰 TensorFlow 모델을 더 깊이 이해하거나, 주요 오픈 소스 기여를 수행하거나, 선택한 모델에 Tensorflow를 사용하려는 경우 이 안내서는 여러분을 위한 것입니다.
```suggestion
만약 대규모 TensorFlow 모델을 더 깊이 이해하려거나, 오픈 소스에 큰 기여를 하려거나, 선택한 모델에 Tensorflow를 활용하려한다면, 이 안내서는 여러분께 도움이 될 것입니다.
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +우리의 경험을 모아 활용하는 것은 이 프로세스를 점차적으로 더 쉽게 만드는 데 굉장히 중요하며, 따라서 이 가이드에 대한 개선 제안을 적극적으로 권장합니다!
```suggestion
모두의 경험을 모으는 것은 이 작업을 점차적으로 더 쉽게 만드는 데 굉장히 중요하기 때문에, 이 가이드를 개선시킬만한 제안이 떠오르면 공유하시는걸 적극적으로 권장합니다!
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +(add_new_model#general-overview-of-transformers)
```suggestion
- [🤗 Transformers의 일반 개요](add_new_model#general-overview-of-transformers)
```
마크다운 링크를 붙여줬어요!

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +<팁>
```suggestion
<Tip>
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +</팁>
```suggestion
</Tip>
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +큰 아키텍처 모델 설계하는 방법이 여러가지 있으며, 해당 설계를 구현하는 방법도 여러 가지 있습니다.
```suggestion
대규모 아키텍처를 가진 모델을 설계하는 방법에는 여러가지가 있으며, 해당 설계를 구현하는 방법도 여러 가지입니다. 
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +그러나 우리는 [🤗 Transformers 일반 개요](add_new_model#general-overview-of-transformers)에서 언급한 대로 일관된 설계 선택에 따라 🤗 Transformers 사용 편의성이 달려 있다는 확고한 의견을 가지고 있습니다.
```suggestion
그러나 우리는 [🤗 Transformers 일반 개요](add_new_model#general-overview-of-transformers)에서 언급한 대로 일관된 설계 선택에 따라야지만 🤗 Transformers를 사용하기 편할 것이라는 확고한 의견을 가지고 있습니다.
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +- 휠 패키지 파일을 다시 만들지 마세요! 대개 최소한 두 개의 참조 구현을 확인해야 합니다: 구현하려는 모델과 동일한 Pytorch 버전 및 동일한 문제 유형의 다른 TensorFlow 모델.
```suggestion
- 이미 있는걸 다시 개발하려 하지 마세요! 최소한 2개의 이미 구현된 모델을 대개 참조해야 합니다. 구현하려는 모델과 기능상 동일한 Pytorch 모델 하나와 같은 문제 유형을 풀고 있는 다른 TensorFlow 모델 하나를 살펴보세요.
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +- 우수한 모델 구현은 시간이 지나도 남아있습니다. 이것은 코드가 아름답다는 이유가 아니라 코드가 명확하고 디버깅 및 개선이 쉬워야 하기 때문입니다. TensorFlow 구현에서 동일한 패턴을 복제하고 Pytorch 구현과의 불일치를 최소화하여 유지 관리자의 업무를 쉽게 할 경우, 기여한 사항이 오래 유지됨을 보장할 수 있습니다.
```suggestion
- 우수한 모델 구현은 시간이 지나도 남아있습니다. 이것은 코드가 아름답다는 이유가 아니라 코드가 명확하고 디버깅 및 개선이 쉽기 때문입니다. TensorFlow 구현에서 다른 모델들과 패턴을 똑같이 하고 Pytorch 구현과의 불일치를 최소화하여 메인테이너의 업무를 쉽게 한다면, 기여한 코드가 오래도록 유지될 수 있습니다.
```

2023-07-28 02:37 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +- 도움이 필요한 경우 도움을 요청하세요! 🤗 Transformers 팀은 여러분을 돕기 위해 여기에 있으며, 여러분이 직면한 동일한 문제에 대한 해결책을 이미 찾은 경우도 있을 수 있습니다.
```suggestion
- 필요하다면 도움을 요청하세요! 🤗 Transformers 팀은 여러분을 돕기 위해 있으며, 여러분이 직면한 동일한 문제에 대한 해결책을 이미 찾은 경우도 있을 수 있습니다.
```

2023-07-28 12:49 UTC, wonhyeongseo requested changes
~L146 약식 리뷰이지만 다 하고나서 금방 설명을 추가하겠습니다. 고생 많으셨습니다. 건주님!

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +<팁>
```suggestion
<Tip>
```

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +</팁>
```suggestion
</Tip>
```

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +모델 아키텍처를 선택한 후, 관련 작업을 수행할 의도를 신호로 알리기 위해 draft PR을 엽니다. 환경을 설정하고 draft PR을 열려면 아래 지침을 따르세요.
```suggestion
모델 아키텍처를 선택한 후, 관련 작업을 수행할 의도를 미리 알리기 위해 Draft PR을 여세요. 아래 지침대로 하시면 환경을 설정하고 Draft PR을 열 수 있습니다.
```

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +1. 'Fork' 버튼을 클릭하여 [repository](https://github.com/huggingface/transformers)를 fork합니다. 이렇게 하면 GitHub 사용자 계정에 코드의 사본이 생성됩니다.
```suggestion
1. 'Fork' 버튼을 클릭하여 [리포지터리](https://github.com/huggingface/transformers)를 포크하세요. 이렇게 하면 GitHub 사용자 계정에 코드의 사본이 생성됩니다.
```

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +2. `transformers` 포크를 로컬 디스크에 클론하고 기본 repository를 원격 repository로 추가합니다.
```suggestion
2. `transformers` 포크를 로컬 디스크에 클론하고 원본 리포지터리를 원격 리포지터리로 추가하세요.
```

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +3. 개발 환경을 설정합니다. 예를 들어, 다음 명령을 실행하여 개발 환경을 설정할 수 있습니다.
```suggestion
3. 개발 환경을 설정하세요. 예를 들어, 다음 명령을 실행하여 개발 환경을 설정할 수 있습니다.
```

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +9. GitHub 풀 요청 웹 페이지 오른쪽에 있는 "Convert to draft"를 클릭하여 PR을 드래프트로 변경합니다.
```suggestion
9. GitHub Pull Requests 페이지의 오른쪽에 있는 "Convert to draft"를 클릭하여 PR을 초안으로 변경하세요.
```

2023-07-28 12:49 UTC, wonhyeongseo commented on docs/source/ko/add_tensorflow_model.md
> +설명 작업이 있는 경우, 시간을 내어 *BrandNewBert*의 논문을 읽어야 합니다. 이해하기 어려운 부분이 많을 수 있습니다. 그렇다고 해서 걱정하지 마세요! 목표는 논문의 심도있는 이론적 이해가 아니라 TensorFlow를 사용하여 🤗 Transformers에 모델을 효과적으로 다시 구현하는 데 필요한 필수 정보를 추출하는 것입니다. 많은 시간을
```suggestion
*BrandNewBert*처럼 자세한 글이 있다면 시간을 내어 논문을 읽는걸 추천드립니다. 이해하기 어려운 부분이 많을 수 있습니다. 그렇다고 해서 걱정하지 마세요! 목표는 논문의 심도있는 이론적 이해가 아니라 TensorFlow를 사용하여 🤗 Transformers에 모델을 효과적으로 다시 구현하는 데 필요한 필수 정보를 추출하는 것입니다. 많은 시간을 이론적 이해에 투자할 필요는 없지만 실용적인 측면에서 현재 존재하는 모델 문서 페이지(e.g. [model docs for BERT](model_doc/bert))에 집중하는 것이 좋습니다.
```

2023-08-02 03:57 UTC, HongB1 commented
공들여 번역 및 수정을 통해 훌륭한 결과물이 나오신 것 같네요! 전체적으로 잘 읽히는 것 같습니다~

2023-08-04 00:20 UTC, keonju2 reviewed
fix: resolve suggestions

2023-08-08 11:12 UTC, keonju2 commented
Could you review this PR? 😃
@sgugger, @ArthurZucker, @eunseojo

2023-08-08 11:56 UTC, sgugger approved these changes
Thanks for your contribution!

2023-08-08 11:56 UTC, merged