🌐 [i18n-KO] Translated `philosophy.md` to Korean
huggingface/transformers pull request #25010
Opened 2023-07-22 06:08 UTC by TaeYupNoh

# What does this PR do?

Translated the `philosophy.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)
@sronger, @TaeYupNoh, @kj021, @HanNayeoniee, @eenzeenee, @sim-so 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-07-25 03:16 UTC, eenzeenee commented on docs/source/ko/philosophy.md
> +🤗 Transformers는 다음과 같은 목적으로 만들어진 주관적인 라이브러리입니다:
```suggestion
🤗 Transformers는 다음과 같은 목적으로 만들어진 독자적인 라이브러리입니다:
```

원문의 opinionated가 '주관적인'보다는 '독자적인'이 더 잘 어울릴 것 같아 제안 드려봅니다..!

2023-07-25 03:16 UTC, eenzeenee commented on docs/source/ko/philosophy.md
> +- 전체 은닉 상태와 어텐션 가중치에 대한 액세스를 단일 API를 사용하여 제공합니다.
```suggestion
  - 전체 은닉 상태와 어텐션 가중치에 대한 액세스를 단일 API를 사용하여 제공합니다.
```

원문과 동일한 문서계층으로 수정해 보았습니다!

2023-07-25 03:16 UTC, eenzeenee commented on docs/source/ko/philosophy.md
> +- 전처리 클래스 및 기본 모델 API는 모델 간에 쉽게 전환할 수 있도록 표준화되어 있습니다.
```suggestion
  - 전처리 클래스 및 기본 모델 API는 모델 간에 쉽게 전환할 수 있도록 표준화되어 있습니다.
```
원문과 동일한 문서계층으로 수정해 보았습니다!

2023-07-25 03:16 UTC, eenzeenee commented on docs/source/ko/philosophy.md
> +- 미세 조정을 위해 어휘 및 임베딩에 새로운 토큰을 간단하고 일관된 방식으로 추가하는 방법을 제공합니다.
```suggestion
  - 미세 조정을 위해 어휘 및 임베딩에 새로운 토큰을 간단하고 일관된 방식으로 추가하는 방법을 제공합니다.
```
원문과 동일한 문서계층으로 수정해 보았습니다!

2023-07-25 03:16 UTC, eenzeenee commented on docs/source/ko/philosophy.md
> +- Transformer 헤드를 마스킹하고 가지치기하는 간단한 방법을 제공합니다.
```suggestion
  - Transformer 헤드를 마스킹하고 가지치기하는 간단한 방법을 제공합니다.
```
원문과 동일한 문서계층으로 수정해 보았습니다!

2023-07-28 12:31 UTC, sim-so requested changes
첫 PR 고생 많으셨습니다! 🥳
많이 늦었지만 리뷰를 보내 드려요!
glossary 참고하여 단어를 수정하고 한국어 표현을 제안 드립니다.
참고 부탁 드립니다!

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +- 이러한 클래스는 공통적인 `from_pretrained()` 메서드를 사용하여 미리 훈련된 인스턴스에서 간단하고 통일된 방식으로 초기화할 수 있습니다. 이 메서드는 미리 훈련된 체크포인트에서 관련 클래스 인스턴스와 관련 데이터(구성의 하이퍼파라미터, 토크나이저의 어휘, 모델의 가중치)를 다운로드(필요한 경우)하고 캐시하며 로드합니다. 체크포인트는 [H
```suggestion
- 이러한 클래스는 공통적인 `from_pretrained()` 메서드를 사용하여 미리 훈련된 인스턴스에서 간단하고 통일된 방식으로 초기화할 수 있습니다. 이 메소드는 미리 훈련된 체크포인트에서 관련 클래스 인스턴스와 관련 데이터(구성의 하이퍼파라미터, 토크나이저의 어휘, 모델의 가중치)를 (필요한 경우) 다운로드하고 캐시하며 가져옵니다. 체크포인트는 [Hugging Face Hub](https://huggingface.co/models)에서 제공되거나 사용자 자체의 저장된 체크포인트에서 제공됩니다.
```
glossary를 참고하여 수정 제안 드립니다.
(필요한 경우)는 앞에 두어도 자연스러울 것 같아서 옮겨봤어요. 참고 부탁 드립니다!

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +- **전처리 클래스**는 원시 데이터를 모델이 수용하는 형식으로 변환합니다. [Tokenizer](main_classes/tokenizer)는 각 모델의 어휘를 저장하고, 문자열을 토큰 임베딩 인덱스 리스트로 인코딩하고 디코딩하기 위한 메서드를 제공합니다. [Image processors](main_classes/image_processor)는 비전 입
```suggestion
- **전처리 클래스**는 원시 데이터를 모델이 수용하는 형식으로 변환합니다. [Tokenizer](main_classes/tokenizer)는 각 모델의 어휘를 저장하고, 문자열을 토큰 임베딩 인덱스 리스트로 인코딩하고 디코딩하기 위한 메소드를 제공합니다. [Image processors](main_classes/image_processor)는 비전 입력을 전처리하고, [feature extractors](main_classes/feature_extractor)는 오디오 입력을 전처리하며, [processor](main_classes/processors)는 멀티모달 입력을 처리합니다.
```
glossary를 참고하여 수정 제안 드립니다!

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +모든 이러한 클래스는 사전 훈련된 인스턴스에서 인스턴스화하고 로컬로 저장하며, 세 가지 메서드를 사용하여 Hub에서 공유할 수 있습니다:
```suggestion
모든 이러한 클래스는 사전 훈련된 인스턴스에서 인스턴스화하고 로컬로 저장하며, 세 가지 메소드를 사용하여 Hub에서 공유할 수 있습니다:
```
glossary를 참고하여 수정 제안 드립니다.

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +- `from_pretrained()` 메서드를 사용하면 라이브러리 자체에서 제공하는 사전 훈련된 버전(지원되는 모델은 [Model Hub](https://huggingface.co/models)에서 찾을 수 있음)이나 사용자가 로컬로 저장한 경우(또는 서버에 저장한 경우)의 모델, 구성 및 전처리 클래스를 인스턴스화할 수 있습니다.
```suggestion
- `from_pretrained()` 메소드를 사용하면 라이브러리 자체에서 제공하는 사전 훈련된 버전(지원되는 모델은 [Model Hub](https://huggingface.co/models)에서 찾을 수 있음)이나 사용자가 로컬로 저장한 경우(또는 서버에 저장한 경우)의 모델, 구성 및 전처리 클래스를 인스턴스화할 수 있습니다.
```
glossary를 참고하여 수정 제안 드립니다.

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +- `save_pretrained()` 메서드를 사용하면 모델, 구성 및 전처리 클래스를 로컬로 저장하여 `from_pretrained()`를 사용하여 다시로드할 수 있습니다.
```suggestion
- `save_pretrained()` 메소드를 사용하면 모델, 구성 및 전처리 클래스를 로컬로 저장하여 `from_pretrained()`를 사용하여 다시 가져올 수 있습니다.
```
glossary를 참고하여 수정 제안 드립니다.

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +- `push_to_hub()` 메서드를 사용하면 모델, 구성 및 전처리 클래스를 Hub에 공유하여 모두에게 쉽게 액세스할 수 있습니다.
```suggestion
- `push_to_hub()` 메소드를 사용하면 모델, 구성 및 전처리 클래스를 Hub에 공유하여 모두에게 쉽게 접근할 수 있습니다.
```
glossary를 참고하여 수정 제안 드립니다. ☺️

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +- **구성 클래스**는 모델을 구축하는 데 필요한 하이퍼파라미터(예: 레이어 수 및 은닉 크기)를 저장합니다. 구성 클래스를 직접 인스턴스화할 필요는 없습니다. 특히, 수정 없이 사전 훈련된 모델을 사용하는 경우 모델을 만들 때 구성을 자동으로 인스턴스화하는 것이 자동으로 처리됩니다.
```suggestion
- **구성 클래스**는 모델을 구축하는 데 필요한 하이퍼파라미터(예: 레이어 수 및 은닉 크기)를 저장합니다. 구성 클래스를 직접 인스턴스화할 필요는 없습니다. 특히, 수정 없이 고 사전 학습된 모델을 사용하는 경우 모델을 생성하면 모델의 일부인 구성을 자동으로 인스턴스화됩니다.
```
'자동으로'라는 부분이 반복된 것 같아 수정해보았습니다.

2023-07-28 12:31 UTC, sim-so commented on docs/source/ko/philosophy.md
> +- 사용자가 익히기 위해 사용자에게 노출되는 추상화의 수를 제한했습니다. 실제로 거의 추상화가 없으며, 각 모델을 사용하기 위해 필요한 세 가지 표준 클래스인 [configuration](main_classes/configuration), [models](main_classes/model) 및 전처리 클래스인 ([tokenizer](main_classes
```suggestion
- 학습해야 할 사용자 대상 추상화의 수를 제한했습니다. 실제로 거의 추상화가 없으며, 각 모델을 사용하기 위해 필요한 세 가지 표준 클래스인 [configuration](main_classes/configuration), [models](main_classes/model) 및 전처리 클래스인 ([tokenizer](main_classes/tokenizer)는 NLP용, [image processor](main_classes/image_processor)는 비전용, [feature extractor](main_classes/feature_extractor)는 오디오용, [processor](main_classes/processors)는 멀티모달 입력용)만 사용합니다.
```
`사용자에게 노출되는 추상화`가 무척 좋은데 `to learn`을 붙이기가 너무 어렵네요 🥲
`to learn`을 붙여보려고 바꾸어보았는데요, 제 제안일 뿐이오니 참고만 부탁 드려요!

2023-08-10 07:27 UTC, TaeYupNoh commented
May you please review this PR? :)  
@sgugger, @ArthurZucker, @eunseojo

2023-08-10 07:50 UTC, sgugger approved these changes
Thanks for your contribution!

2023-08-10 07:50 UTC, merged