Ko add new pipeline
huggingface/transformers pull request #25498
Opened 2023-08-14 13:35 UTC by heuristicwave

# What does this PR do?

Translated the `<your_file>.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

May you please review this PR? @nuatmochoi, @bolizabeth, @hyunhp, @mjk0618, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-08-14 14:56 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_25498). All of your documentation changes will be reflected on that endpoint.

2023-08-17 09:05 UTC, nuatmochoi requested changes

2023-08-17 09:05 UTC, nuatmochoi commented on docs/source/ko/add_new_pipeline.md
> +입/출력을 가능한한 간단하고 완전히 JSON 직렬화 가능한 형식으로 유지하려고 노력하십시오.
```suggestion
입/출력을 가능한 한 간단하고 완전히 JSON 직렬화 가능한 형식으로 유지하려고 노력하십시오.
```
맞춤법 수정하였습니다.

2023-08-18 14:52 UTC, wonhyeongseo requested changes
안녕하세요 @heuristicwave 님!

🔥 열정적으로 참여해주셔서 정말 감사드립니다. 전반적으로 고민하신 흔적이 보여서 너무 좋았어요! 아직 모두 리뷰를 못했지만 내일 OpenUP에서 마치겠습니다.

리뷰는 일방적인 수용이 아닌 서로간의 대화를 전제로 이루어집니다. 때문에 "어라, 이건 내가 맞아!"라고 주장해주시면 오히려 더 재밌는 리뷰 시간이 될 것입니다. 지금까지 최고의 리뷰를 꾸준히 올려주시는 @nuatmochoi 님 🥇 , 담당이신 @jungnerd 님도 모두 리뷰 자유롭게 올려주세요. 감사합니다. 💯 😆

2023-08-18 14:52 UTC, wonhyeongseo commented on docs/source/ko/_toctree.yml
> +      title: 다중 GPU에서 추론
고쳐주셔서 정말 감사합니다..! 👍

2023-08-18 14:52 UTC, wonhyeongseo commented on docs/source/ko/add_new_pipeline.md
> +먼저, 파이프라인이 수용할 수 있는 원시 입력을 결정해야 합니다.
```suggestion
먼저 파이프라인이 수용할 수 있는 원시 입력을 결정해야 합니다.
```

2023-08-18 14:52 UTC, wonhyeongseo commented on docs/source/ko/add_new_pipeline.md
> +이러한 것들이 파이프라인(전처리)의 `inputs`이 될 것입니다.
```suggestion
이 입력을 가능한 한 순수한 Python 형식으로 유지해야 (JSON을 통해 다른 언어와도) 호환성이 좋아집니다.
이것이 전처리(`preprocess`) 파이프라인의 입력(`inputs`)이 될 것입니다.
```

2023-08-18 14:52 UTC, wonhyeongseo commented on docs/source/ko/add_new_pipeline.md
> +이러한 것들이 `postprocess` 메소드의 출력이 될 것입니다.
```suggestion
그런 다음 `outputs`를 정의하세요.
`inputs`와 같은 정책을 따르고, 간단할수록 좋습니다.
이것이 후처리(`postprocess`) 메소드의 출력이 될 것입니다.
```

2023-08-18 14:52 UTC, wonhyeongseo commented on docs/source/ko/add_new_pipeline.md
> +## 허브에 파이프라인 공유하기 [[share-your-pipeline-on-the-hub]]
```suggestion
## Hub에 파이프라인 공유하기 [[share-your-pipeline-on-the-hub]]
```

2023-08-18 14:52 UTC, wonhyeongseo commented on docs/source/ko/add_new_pipeline.md
> +허브에 사용자 정의 파이프라인을 공유하려면 `Pipeline` 하위 클래스의 사용자 정의 코드를 Python 파일에 저장하기만 하면 됩니다.
```suggestion
Hub에 사용자 정의 파이프라인을 공유하려면 `Pipeline` 하위 클래스의 사용자 정의 코드를 Python 파일에 저장하기만 하면 됩니다.
```

2023-08-28 07:11 UTC, wonhyeongseo commented
May you please review this PR @stevhliu ? cc: @sgugger , @ArthurZucker, @eunseojo
Thank you so much for your help!

2023-08-29 13:19 UTC, stevhliu approved these changes
Awesome, thank you for your contribution!

2023-08-29 15:38 UTC, merged