🌐 [i18n-KO] Translated `visual_question_answering.md` to Korean
huggingface/transformers pull request #25679
Opened 2023-08-23 08:29 UTC by wonhyeongseo

# What does this PR do?

Translated the `<your_file>.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

Team OSSCA, may you please review this PR? @bolizabeth, @nuatmochoi, @heuristicwave, @mjk0618, @keonju2, @harheem, @HongB1, @junejae, @54data, @Sunmin0520, @seank021, @augustinLib, @sronger, @TaeYupNoh, @kj021, @eenzeenee

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-08-23 10:54 UTC, wonhyeongseo reviewed
Self correction with grammar checking.

2023-08-23 10:54 UTC, wonhyeongseo commented on docs/source/ko/tasks/visual_question_answering.md
> +보시다시피 `label` 특성은 같은 질문마다 답변이 여러개 있을 수 있습니다. 모두 다른 데이터 라벨러들로부터 수집되었기 때문인데요. 질문의 답변은 주관적일 수 있습니다. 이 경우 질문은 "그는 어디를 보고 있나요?" 였지만, 어떤 사람들은 "아래"로 레이블을 달았고, 다른 사람들은 "테이블" 또는 "스케이트보드" 등으로 주석을 달았습니다.
```suggestion
보시다시피 `label` 특성은 같은 질문마다 답변이 여러 개 있을 수 있습니다. 모두 다른 데이터 라벨러들로부터 수집되었기 때문인데요. 질문의 답변은 주관적일 수 있습니다. 이 경우 질문은 "그는 어디를 보고 있나요?" 였지만, 어떤 사람들은 "아래"로 레이블을 달았고, 다른 사람들은 "테이블" 또는 "스케이트보드" 등으로 주석을 달았습니다.
```

2023-08-23 10:54 UTC, wonhyeongseo commented on docs/source/ko/tasks/visual_question_answering.md
> +아래의 이미지를 보고 어떤 답변을 선택할 것인지 생각해보세요:
```suggestion
아래의 이미지를 보고 어떤 답변을 선택할 것인지 생각해 보세요:
```

2023-08-23 10:54 UTC, wonhyeongseo commented on docs/source/ko/tasks/visual_question_answering.md
> +2. 모델, 데이터셋, 프로세서, 데이터 콜레이터와 함께 훈련 인수를 [`Trainer`]에 전달하세요:
```suggestion
2. 모델, 데이터세트, 프로세서, 데이터 콜레이터와 함께 훈련 인수를 [`Trainer`]에 전달하세요:
```

2023-08-24 00:03 UTC, wonhyeongseo commented
안녕하세요!

🔥 번역에 참여해주신 모든 분들께 정말 감사드립니다. 이번 번역에서는 특정 이미지에 대해서 설명이 나와 보면서 번역이 알맞는지 확인해야했습니다. 오랜만에 번역하는 것이다보니 오류가 많을 것으로 예상되는데요. 어떤 부분이든 모두 주저없이 말씀해주세요 :)

리뷰는 일방적인 수용이 아닌 서로간의 대화를 전제로 이루어집니다. 때문에 "어라, 이건 내가 맞아!"라고 주장해주시면 오히려 더 재밌는 리뷰 시간이 될 것입니다. 지금까지 최고의 리뷰를 꾸준히 올려주시는 @nuatmochoi 님 🥇 , @heuristicwave 님 🥈 , @sim-so 님 🥉 도 모두 리뷰 자유롭게 올려주세요. 감사합니다. 💯 😆

2023-08-24 06:10 UTC, nuatmochoi requested changes

2023-08-24 06:10 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +시각적 질의응답(VQA)은 이미지를 기반으로 개방형 질문에 대응하는 태스크입니다. 이 태스크를 지원하는 모델의 입력은 대부분 이미지와 질문의 조합이며, 출력은 자연어로 된 답변입니다.
```suggestion
시각적 질의응답(VQA)은 이미지를 기반으로 개방형 질문에 대응하는 작업입니다. 이 작업을 지원하는 모델의 입력은 대부분 이미지와 질문의 조합이며, 출력은 자연어로 된 답변입니다.
```
glossary에 맞게 수정하였습니다.

2023-08-24 06:10 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +ViLT는 Vision Transformer (ViT) 내에 텍스트 임베딩을 포함하여 비전/자연어 사전 학습(VLP; Vision-and-Language Pretraining)을 위한 기본 디자인을 제공합니다.
```suggestion
ViLT는 Vision Transformer (ViT) 내에 텍스트 임베딩을 포함하여 비전/자연어 사전훈련(VLP; Vision-and-Language Pretraining)을 위한 기본 디자인을 제공합니다.
```
glossary에 맞게 수정하였습니다.

2023-08-24 06:10 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +최근의 BLIP, BLIP-2, InstructBLIP와 같은 모델들은 VQA를 생성형 태스크로 간주합니다. 가이드의 후반부에서는 이런 모델들을 사용하여 제로샷 VQA 추론을 하는 방법에 대해 설명하겠습니다.
```suggestion
최근의 BLIP, BLIP-2, InstructBLIP와 같은 모델들은 VQA를 생성형 작업으로 간주합니다. 가이드의 후반부에서는 이런 모델들을 사용하여 제로샷 VQA 추론을 하는 방법에 대해 설명하겠습니다.
```
glossary에 맞게 수정하였습니다.

2023-08-24 06:10 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +2. 모델, 데이터세트, 프로세서, 데이터 콜레이터와 함께 훈련 인수를 [`Trainer`]에 전달하세요:
```suggestion
2. 모델, 데이터세트, 프로세서, 데이터 수집기와 함께 훈련 인수를 [`Trainer`]에 전달하세요:
```
[문서](https://huggingface.co/docs/transformers/main_classes/data_collator)를 읽어보니 `데이터 수집기`로 해석해도 될 것 같아, 수정하였습니다.

2023-08-24 06:10 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +이전 모델은 VQA를 분류 문제로 처리했습니다. BLIP, BLIP-2 및 InstructBLIP와 같은 최근의 모델은 VQA를 생성 태스크로 접근합니다. [BLIP-2](../../en/model_doc/blip-2)를 예로 들어 보겠습니다. 이 모델은 사전 학습된 비전 인코더와 LLM의 모든 조합을 사용할 수 있는 새로운 비전-자연어 사전 학습 패러다
```suggestion
이전 모델은 VQA를 분류 문제로 처리했습니다. BLIP, BLIP-2 및 InstructBLIP와 같은 최근의 모델은 VQA를 생성 작업으로 접근합니다. [BLIP-2](../../en/model_doc/blip-2)를 예로 들어 보겠습니다. 이 모델은 사전훈련된 비전 인코더와 LLM의 모든 조합을 사용할 수 있는 새로운 비전-자연어 사전 학습 패러다임을 도입했습니다. ([BLIP-2 블로그 포스트](https://huggingface.co/blog/blip-2)를 통해 더 자세히 알아볼 수 있어요)
```
glossary에 맞게 수정하였습니다.

2023-08-24 06:10 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +이를 통해 시각적 질의응답을 포함한 여러 비전-자연어 태스크에서 SOTA를 달성할 수 있었습니다.
```suggestion
이를 통해 시각적 질의응답을 포함한 여러 비전-자연어 작업에서 SOTA를 달성할 수 있었습니다.
```
glossary에 맞게 수정하였습니다.

2023-08-24 06:10 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +BLIP-2를 시각적 질의응답 태스크에 사용하려면 텍스트 프롬프트가 `Question: {} Answer:` 형식을 따라야 합니다.
```suggestion
BLIP-2를 시각적 질의응답 작업에 사용하려면 텍스트 프롬프트가 `Question: {} Answer:` 형식을 따라야 합니다.
```
glossary에 맞게 수정하였습니다.

2023-08-24 15:14 UTC, wonhyeongseo commented on docs/source/ko/tasks/visual_question_answering.md
> +2. 모델, 데이터세트, 프로세서, 데이터 콜레이터와 함께 훈련 인수를 [`Trainer`]에 전달하세요:
이건 오해의 소지가 있기 때문에 glossary에 추가해둔후 미팅 때 논의해보아요 👍

2023-08-24 17:19 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_25679). All of your documentation changes will be reflected on that endpoint.

2023-08-24 18:14 UTC, stevhliu approved these changes
Great job! Thanks so much for your translation 🤗

2023-08-24 18:14 UTC, merged

2023-08-25 01:36 UTC, nuatmochoi commented on docs/source/ko/tasks/visual_question_answering.md
> +2. 모델, 데이터세트, 프로세서, 데이터 콜레이터와 함께 훈련 인수를 [`Trainer`]에 전달하세요:
저도 오인하였는데, `대조자`가 자연스러울 것 같긴합니다. glossary에는 추가해두었습니다:)