🌐 [i18n-KO] Translated `community.md` to Korean
huggingface/transformers pull request #25674
Opened 2023-08-23 00:58 UTC by sim-so

# What does this PR do?

Translated the `community.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-08-23 05:18 UTC, sim-so commented
리뷰 하실 때 참고하실 점 공유 드립니다.
  - [`Nlp`](https://huggingface.co/docs/datasets/v0.3.0/installation.html)는 `Datasets` 이전에 사용된 라이브러리 이름입니다. v1.0.0부터 `Datasets`로 바뀌었습니다. (현재 가장 최신 Datasets 버전은 v2.14입니다!) 모든 노트북에서 잘 실행되지는 않는 것 같지만 여전히 `Nlp` 이름으로 모듈을 다운로드 받을 수 있고, `Datasets`로 바꿀 때 관련 노트북도 수정이 필요할 것 같아 원문의 이름을 유지했습니다. 
  - 모델 이름인 `transformer`는 한글로, Hugging Face 라이브러리 이름인 `Transformers`는 영어로 옮겼습니다.
  - Hugging Face 라이브러리 앞에 쓰는 🤗 이모지는 원문에서 쓴 그대로 옮겼습니다. 원문에서도 일관되지 않게 붙이고 있는데요, 전부 붙일지 고민하다 일단 그대로 두었습니다.

위 내용 관련하여 의견 있으시면 편히 남겨주세요! 리뷰 잘 부탁 드립니다 😊

2023-08-23 06:22 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_25674). All of your documentation changes will be reflected on that endpoint.

2023-08-24 05:51 UTC, nuatmochoi requested changes

2023-08-24 05:51 UTC, nuatmochoi commented on docs/source/ko/community.md
> +| [요약을 위해 BART 미세 조정하기](https://github.com/ohmeow/ohmeow_website/blob/master/posts/2021-05-25-mbart-sequence-classification-with-blurr.ipynb) | blurr를 사용하여 fastai로 요약에 맞게 BART를 미세 조정하는 방법 | [Wayde Gi
```suggestion
| [요약을 위해 BART 미세 조정하기](https://github.com/ohmeow/ohmeow_website/blob/master/posts/2021-05-25-mbart-sequence-classification-with-blurr.ipynb) | blurr를 사용하여 fastai로 요약하기 위해 BART를 미세 조정하는 방법 | [Wayde Gilliam](https://ohmeow.com/) | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ohmeow/ohmeow_website/blob/master/posts/2021-05-25-mbart-sequence-classification-with-blurr.ipynb) |
```
문맥상 자연스럽게 수정하였습니다.

2023-08-24 05:51 UTC, nuatmochoi commented on docs/source/ko/community.md
> +| [Wav2Vec2를 사용하여 동영상 캡션 만들기](https://github.com/Muennighoff/ytclipcc/blob/main/wav2vec_youtube_captions.ipynb) | Wav2Vec으로 오디오를 전사하여 모든 동영상에서 YouTube 캡션 만드는 방법 | [Niklas Muennighoff](https://github.
```suggestion
| [Wav2Vec2를 사용하여 동영상 캡션 만들기](https://github.com/Muennighoff/ytclipcc/blob/main/wav2vec_youtube_captions.ipynb) | Wav2Vec으로 오디오를 텍스트로 변환하여 모든 동영상에서 YouTube 캡션 만드는 방법 | [Niklas Muennighoff](https://github.com/Muennighoff) |[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Muennighoff/ytclipcc/blob/main/wav2vec_youtube_captions.ipynb) |
```
`전사`라는 단어가 명확하긴 한데,  조금 더 이해하기 쉽게 `오디오를 텍스트로 변환`으로 풀어서 수정해보았습니다.

2023-08-24 09:52 UTC, sim-so commented on docs/source/ko/community.md
> +| [Wav2Vec2를 사용하여 동영상 캡션 만들기](https://github.com/Muennighoff/ytclipcc/blob/main/wav2vec_youtube_captions.ipynb) | Wav2Vec으로 오디오를 전사하여 모든 동영상에서 YouTube 캡션 만드는 방법 | [Niklas Muennighoff](https://github.
[자동 음성 인식](https://huggingface.co/docs/transformers/v4.32.0/ko/tasks/asr) 번역 때에는 제안 주신 것처럼 풀어서 썼다가, 오디오 관련 작업에서 `전사`라는 표현을 흔히 쓰고 있는 것 같아서 고민하다가 이번엔 그대로 옮겨봤어요. 
실습 자료를 소개하는 문서이니 쉬운 말로 쓰는 게 좋겠죠? 🤔 편히 의견 주시면 좋겠습니다!

2023-08-25 01:32 UTC, nuatmochoi commented on docs/source/ko/community.md
> +| [Wav2Vec2를 사용하여 동영상 캡션 만들기](https://github.com/Muennighoff/ytclipcc/blob/main/wav2vec_youtube_captions.ipynb) | Wav2Vec으로 오디오를 전사하여 모든 동영상에서 YouTube 캡션 만드는 방법 | [Niklas Muennighoff](https://github.
말씀하신대로 대상 독자를 고려해서 쉬운 말로 쓰는 것도 괜찮은 방향으로 보입니다!

2023-08-27 13:18 UTC, 0525hhgus requested changes
좋은 번역 감사합니다 😄 다양한 리소스에 대해 라이브러리와 모델을 고려하여 번역해주셔서 쉽게 이해할 수 있었습니다. 
아래 용어 관련하여 짧은 리뷰를 남깁니다!

2023-08-27 13:18 UTC, 0525hhgus commented on docs/source/ko/community.md
> +| [분류 및 객관식 작업을 위해 T5 미세 조정하기](https://github.com/patil-suraj/exploring-T5/blob/master/t5_fine_tuning.ipynb) | 분류 및 객관식 작업에 맞게 텍스트-텍스트 형식을 사용하여 PyTorch Lightning으로 T5를 미세 조정하는 방법 | [Suraj Patil](http
```suggestion
| [분류 및 객관식 문제를 위해 T5 미세 조정하기](https://github.com/patil-suraj/exploring-T5/blob/master/t5_fine_tuning.ipynb) | 분류 및 객관식 문제에 맞게 텍스트-텍스트 형식을 사용하여 PyTorch Lightning으로 T5를 미세 조정하는 방법 | [Suraj Patil](https://github.com/patil-suraj) | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/patil-suraj/exploring-T5/blob/master/t5_fine_tuning.ipynb) |
```
객관식 문제 문서에서 `객관식 문제`로 사용하고 있어서 제안드렸으나, `객관식 작업`이 더 잘 어울리는 것 같기도 해서 참고만 해주세요!

2023-08-27 13:18 UTC, 0525hhgus commented on docs/source/ko/community.md
> +| [사용자 지정 객체 감지 데이터 세트로 DETR 미세 조정하기](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/DETR/Fine_tuning_DetrForObjectDetection_on_custom_dataset_(balloon).ipynb) | 사용자 지정 객체 감지 데이터 세트
```suggestion
| [DETR로 이미지에서 객체 탐지하기](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/DETR/DETR_minimal_example_(with_DetrFeatureExtractor).ipynb) | 훈련된 *DetrForObjectDetection* 모델을 사용하여 이미지에서 객체를 탐지하고 어텐션을 시각화하는 방법 | [Niels Rogge](https://github.com/NielsRogge) | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/DETR/DETR_minimal_example_(with_DetrFeatureExtractor).ipynb) |
| [사용자 지정 객체 탐지 데이터 세트로 DETR 미세 조정하기](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/DETR/Fine_tuning_DetrForObjectDetection_on_custom_dataset_(balloon).ipynb) | 사용자 지정 객체 탐지 데이터 세트로 *DetrForObjectDetection*을 미세 조정하는 방법 | [Niels Rogge](https://github.com/NielsRogge) | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/DETR/Fine_tuning_DetrForObjectDetection_on_custom_dataset_(balloon).ipynb) |
```
Glossary와 다른 문서에서 `객체 탐지`로 되어 있어서 제안드립니다!

2023-08-29 07:35 UTC, sim-so reviewed
@nuatmochoi 님과 @0525hhgus 님께서 남겨주신 의견 반영했습니다. 리뷰 감사합니다! 🥰

2023-08-29 14:46 UTC, sim-so commented
@sgugger, @ArthurZucker, @stevhliu 
May you please review this PR? 😊

2023-08-29 15:47 UTC, stevhliu approved these changes
Looks good to me, thanks! 🎉

2023-08-29 15:47 UTC, merged