🌐 [i18n-KO] `model_memory_anatomy.md` to Korean
huggingface/transformers pull request #25755
Opened 2023-08-25 12:19 UTC by mjk0618

# What does this PR do?

Translated the `model_memory_anatomy.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-08-25 18:33 UTC, stevhliu reviewed
Thanks for the translation! Can you update your branch with the latest changes on `main`? I think that should fix the `Build PR Documentation` test :)

2023-08-28 13:45 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_25755). All of your documentation changes will be reflected on that endpoint.

2023-08-28 15:05 UTC, nuatmochoi requested changes

2023-08-28 15:05 UTC, nuatmochoi commented on docs/source/ko/model_memory_anatomy.md
> +**전방 활성화**
```suggestion
**순방향 활성화**
```
동일 내용 수정합니다.

2023-08-28 15:05 UTC, nuatmochoi commented on docs/source/ko/model_memory_anatomy.md
> +전방 및 후방 함수에서 전달 및 반환되는 입력과 출력이 있으며, 그라디언트 계산을 위해 저장된 전방 활성화가 있습니다.
```suggestion
순방향 및 역방향 함수에서 전달 및 반환되는 입력과 출력이 있으며, 그라디언트 계산을 위해 저장된 순방향 활성화가 있습니다.
```

2023-08-29 01:14 UTC, heuristicwave reviewed
@mjk0618 님 리뷰 완료했습니다!

2023-08-29 01:14 UTC, heuristicwave commented on docs/source/ko/model_memory_anatomy.md
> +좋습니다. 모델을 로드하기 전에는 예상대로 GPU 메모리가 점유되지 않았습니다. 그렇지 않다면 사용자의 기기에서 GPU 메모리를 사용하는 모든 프로세스를 중단해야 합니다. 그러나 사용자는 비어있는 모든 GPU 메모리를 사용할 수는 없습니다. 모델이 GPU에 로드될 때 커널도 로드되는데 이것은 1-2GB의 메모리를 차지할 수 있습니다. 얼마나 되는지 확인하
```suggestion
좋습니다. 모델을 로드하기 전에는 예상대로 GPU 메모리가 점유되지 않았습니다. 그렇지 않다면 사용자의 기기에서 GPU 메모리를 사용하는 모든 프로세스를 중단해야 합니다. 그러나 사용자는 모든 여유 GPU 메모리를 사용할 수는 없습니다. 모델이 GPU에 로드될 때 커널도 로드되므로 1-2GB의 메모리를 차지할 수 있습니다. 얼마나 되는지 확인하기 위해 GPU에 작은 텐서를 로드하여 커널이 로드되도록 트리거합니다.
```
피동 표현과 문맥상 흐름을 반영하여 수정했습니다.

2023-08-29 01:14 UTC, heuristicwave commented on docs/source/ko/model_memory_anatomy.md
> +소프트웨어에는 특별한 메모리 요구 사항이 있을 수 있습니다. 예를 들어, 빔 검색을 사용하여 텍스트를 생성할 때 소프트웨어는 입력과 출력의 여러 복사본을 유지해야 합니다.
```suggestion
소프트웨어에는 특별한 메모리 요구 사항이 있을 수 있습니다. 예를 들어, 빔 검색을 사용하여 텍스트를 생성할 때 소프트웨어는 여러 개의 입력 및 출력 사본을 유지해야 합니다.
```
이렇게 표현하는것은 어떨까요?

2023-08-29 07:16 UTC, mjk0618 commented on docs/source/ko/model_memory_anatomy.md
> +전방 및 후방 함수에서 전달 및 반환되는 입력과 출력이 있으며, 그라디언트 계산을 위해 저장된 전방 활성화가 있습니다.
리뷰 감사합니다! 의견주신 내용 모두 반영하여 commit하였습니다!

2023-08-29 07:17 UTC, mjk0618 commented on docs/source/ko/model_memory_anatomy.md
> +좋습니다. 모델을 로드하기 전에는 예상대로 GPU 메모리가 점유되지 않았습니다. 그렇지 않다면 사용자의 기기에서 GPU 메모리를 사용하는 모든 프로세스를 중단해야 합니다. 그러나 사용자는 비어있는 모든 GPU 메모리를 사용할 수는 없습니다. 모델이 GPU에 로드될 때 커널도 로드되는데 이것은 1-2GB의 메모리를 차지할 수 있습니다. 얼마나 되는지 확인하
감사합니다, 의견 주신 내용 반영하여 commit하였습니다!

2023-08-29 07:27 UTC, sim-so requested changes
이번 문서 번역하시느라 무척 고생 많으셨습니다! 문장마다 고민하신 흔적이 느껴집니다 🥲

서식이나 단어 사용에 틀린 부분이 거의 없어서 한국어 표현을 중심으로 리뷰를 해보았습니다. 
대부분 제 개인적인 의견으로 작성된 내용이오니 편히 생각하시고 원하시는 만큼 반영해주셔도 괜찮습니다!
제안 사항에 대해 의견이나 질문을 보내주셔도 좋습니다! 항상 감사합니다 😊

2023-08-29 07:27 UTC, sim-so commented on docs/source/ko/model_memory_anatomy.md
> +계산이 완료되면 곧바로 해제되는 모든 종류의 임시 변수가 있지만, 그 순간에는 추가 메모리가 필요할 수 있고, OOM이 발생할 수 있습니다. 따라서 코딩할 때 이러한 임시 변수에 대해 전략적으로 생각하고, 때로는 더 이상 필요하지 않은 즉시 명시적으로 빠르게 메모리에서 제거하는 것이 중요합니다.
```suggestion
더불어 모든 종류의 임시 변수는 계산이 완료되면 곧바로 해제되지만, 그 순간에는 추가 메모리가 필요할 수 있고 OOM을 유발할 수 있습니다. 따라서 코딩할 때 이러한 임시 변수에 대해 전략적으로 생각하고 때로는 더 이상 필요 없는 임시 변수를 즉시 명시적으로 메모리에서 제거하는 것이 중요합니다.
```
'필요하지 않은'과 '메모리에서 제거하는' 대상이 있으면 알기 쉬울 것 같아서 문장을 바꾸어 보았습니다.
편히 검토 부탁 드립니다!

2023-08-29 07:27 UTC, sim-so commented on docs/source/ko/model_memory_anatomy.md
> +그런 다음, 소프트웨어에는 특별한 메모리 요구 사항이 있을 수 있습니다. 예를 들어, 빔 검색을 사용하여 텍스트를 생성할 때 소프트웨어는 입력과 출력의 여러 복사본을 유지해야 합니다.
```suggestion
그런 다음, 소프트웨어에는 특별한 메모리 요구 사항이 있을 수 있습니다. 예를 들어, 빔 검색을 사용하여 텍스트를 생성할 때 소프트웨어는 입력과 출력 사본을 여러 개 유지해야 합니다.
```
수식이 많은 문장은 늘 번역하기 어렵습니다 ㅠ_ㅠ
'여러 입력과 출력 사본', '여러 개의 입력과 출력 사본', '입력과 출력 사본을 여러 개' 중에서 고민하다 3번째로 정하여 제안 드립니다!

2023-08-29 07:27 UTC, sim-so commented on docs/source/ko/model_memory_anatomy.md
> +합성곱과 선형 레이어의 경우 순방향에 비해 역방향에서는 2배의 플롭스가 필요하므로 일반적으로 2배 정도 느리게 변환됩니다(역방향의 경우 사이즈가 부자연스럽기 때문에, 때로는 더욱 느릴 수도 있습니다.). 활성화는 일반적으로 대역폭이 제한되어 있으며, 일반적으로 순방향보다 역방향에서 더 많은 데이터를 읽어야 합니다.(예를 들어, 순방향 활성화는 읽기를 한번
```suggestion
합성곱과 선형 레이어의 경우 순방향에 비해 역방향에서는 2배의 플롭스가 필요하므로 일반적으로 2배 정도 느리게 변환됩니다(역방향의 경우 사이즈가 부자연스럽기 때문에, 때로는 더욱 느릴 수도 있습니다). 활성화는 일반적으로 대역폭이 제한되어 있으며, 일반적으로 순방향보다 역방향에서 더 많은 데이터를 읽어야 합니다. (예를 들어, 순방향 활성화 시 한 번 씩 읽고 쓰지만, 역방향 활성화에서는 순방향 gradOutput과 출력에 대해 총 두 번 읽고 gradInput에 대해 한 번 씁니다.)
```
따로 질문하셨던 'awkward'도 있지만 전체적으로 번역하기 어려운 문장이었네요! 고민하신 흔적이 느껴집니다. 🥲
'1회'를 의미하는 '한 번'은 띄어쓰는 것이 맞아서 바꾸었고, 다른 부분은 제가 읽기 편한 대로 바꾼 것이니 참고 부탁 드립니다!

2023-08-29 10:38 UTC, mjk0618 commented on docs/source/ko/model_memory_anatomy.md
> +합성곱과 선형 레이어의 경우 순방향에 비해 역방향에서는 2배의 플롭스가 필요하므로 일반적으로 2배 정도 느리게 변환됩니다(역방향의 경우 사이즈가 부자연스럽기 때문에, 때로는 더욱 느릴 수도 있습니다.). 활성화는 일반적으로 대역폭이 제한되어 있으며, 일반적으로 순방향보다 역방향에서 더 많은 데이터를 읽어야 합니다.(예를 들어, 순방향 활성화는 읽기를 한번
리뷰해주셔서 감사합니다! 제안해주신 내용 참고해서 수정한 후 다시 커밋하였습니다!

2023-08-29 11:17 UTC, mjk0618 commented
May you please review this PR? @sgugger, @ArthurZucker, @eunseojo

2023-08-29 12:26 UTC, ArthurZucker approved these changes
LGTM! cc @stevhliu for a second look

2023-08-29 13:48 UTC, stevhliu approved these changes
Great job, thanks for the translation! 🤗

2023-08-29 13:48 UTC, merged