[i18n-KO] Translate `pipelines.md` to Korean
huggingface/transformers pull request #25772
Opened 2023-08-26 03:24 UTC by Sunmin0520

# What does this PR do?

Translated the `pipelines.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)
 @bolizabeth, @nuatmochoi, @heuristicwave, @mjk0618, @keonju2, @harheem, @HongB1, @junejae, @54data, @seank021, @augustinLib, @sronger, @TaeYupNoh, @kj021, @eenzeenee

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

2023-08-26 07:50 UTC, nuatmochoi requested changes

2023-08-26 07:50 UTC, nuatmochoi commented on docs/source/ko/main_classes/pipelines.md
> +- 가장 강력한 객체인 [파이프라인]은 다른 모든 파이프라인을 캡슐화합니다.
```suggestion
- 가장 강력한 객체인 [`pipeline`]은 다른 모든 파이프라인을 캡슐화합니다.
```
영문원본에서 pipeline() 함수로 링크 연결되고, 문서상에서는 wrapper로 이미 정의된 단어로 보여 원문 파일과 동일하게 수정해보았습니다.

2023-08-26 07:50 UTC, nuatmochoi commented on docs/source/ko/main_classes/pipelines.md
> +- 작업별 파이프라인은 오디오, 컴퓨터 비전, 자연어 처리, 멀티모달 작업을 위한 특정 작업에 사용할 수 있습니다.
```suggestion
- 작업별 파이프라인은 [오디오](#audio), [컴퓨터 비전](#computer-vision), [자연어 처리](#natural-language-processing), [멀티모달](#multimodal) 작업을 위한 특정 작업에 사용할 수 있습니다.
```
마크다운 문법에 따라 링크를 찾아가도록 영문원본 참고하여 수정하였습니다.

2023-08-27 01:03 UTC, Sunmin0520 commented on docs/source/ko/main_classes/pipelines.md
> +- 가장 강력한 객체인 [파이프라인]은 다른 모든 파이프라인을 캡슐화합니다.
꼼꼼하게 확인해주셔서 감사합니다! 알려주신 사항을 반영했습니다 :)

2023-08-27 01:03 UTC, Sunmin0520 commented on docs/source/ko/main_classes/pipelines.md
> +- 작업별 파이프라인은 오디오, 컴퓨터 비전, 자연어 처리, 멀티모달 작업을 위한 특정 작업에 사용할 수 있습니다.
이 부분 역시 꼼꼼하게 확인해주셔서 감사합니다! 알려주신 사항을 반영했습니다 :)

2023-08-27 12:48 UTC, 0525hhgus requested changes
좋은 번역 감사합니다! 첫 API 번역 문서입니다 🎉 
코드와 내용을 고려한 줄바꿈과 주석까지 정확히 번역해주셨군요 👍 
아래 약간의 리뷰를 남기니, 확인 부탁드립니다!

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +전체 데이터 세트를 반복하려면 `데이터셋`을 직접 사용하는 것이 좋습니다.
```suggestion
전체 데이터 세트를 반복하려면 `데이터 세트`을 직접 사용하는 것이 좋습니다. 
```
문장에서 데이터 세트로 번역하고 있어서, 맞춰서 수정하였습니다.

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +# 데이터셋의 *대상* 부분에는 관심이 없기 때문입니다. 문장 쌍의 경우 KeyPairDataset을 사용합니다.
```suggestion
# KeyDataset(*pt*만 해당)은 단순히 데이터 세트 항목이 반환한 딕셔너리의 항목을 반환합니다. 
# 데이터 세트의 *대상* 부분에는 관심이 없기 때문입니다. 문장 쌍의 경우 KeyPairDataset을 사용합니다.
```

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +- 지연 시간 제약이 있는 경우(추론을 수행하는 실시간 상품), 일괄 처리하지 마세요.
```suggestion
- 지연 시간에 제약이 있는 경우(추론을 수행하는 실시간 제품), 일괄 처리하지 마세요.
```

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +  - GPU가 클수록 일괄 처리 더 흥미롭게 보일 가능성이 큽니다.
```suggestion
  - 시퀀스 길이가 매우 규칙적이라면, 일괄 처리가 아주 효과적일 가능성이 큽니다. 
    OOM이 발생할 때까지 측정하고 푸시하세요.
  - GPU가 클수록 일괄 처리가 더 효과적일 가능성이 큽니다.
```
`효과적인`이 조금 더 와닿을 것 같아서, 리뷰드렸습니다.

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +그 결과 '트랜스포머'가 당신의 사용 사례를 지원할 수 있습니다.
```suggestion
그러면, 'transformers'는 당신의 사용 사례를 지원할 수 있습니다.
```
transformers 제품명을 의미하는 것으로 생각되어 `transformers`로 리뷰하였습니다.

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +## Computer vision [[Computer-vision]]
```suggestion
## 컴퓨터 비전 [[Computer-vision]]
```

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +## Natural Language Processing
```suggestion
## 자연어처리[[natural-language-processing]]
```

2023-08-27 12:48 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +## Multimodal
```suggestion
## 멀티모달[[multimodal]]
```

2023-08-28 05:49 UTC, nuatmochoi requested changes

2023-08-28 05:49 UTC, nuatmochoi commented on docs/source/ko/main_classes/pipelines.md
> +## Natural Language Processing
```suggestion
## 자연어 처리 [[natural-language-processing]]
```
@0525hhgus 원본과 대괄호부분은 띄어서 써야하지 않나요?! 잘몰라서 여쭤봅니다😅

2023-08-28 05:49 UTC, nuatmochoi commented on docs/source/ko/main_classes/pipelines.md
> +## Multimodal
```suggestion
## 멀티모달 [[multimodal]]
```
이 부분도 마크다운 문법으로 문서 내 링크 호출하는 line(27)과 연결되어 있어 띄어쓰기해야되는지 확인이 필요합니다.

2023-08-28 12:35 UTC, Sunmin0520 commented on docs/source/ko/main_classes/pipelines.md
> +감정 분석(Sentiment Analysis), 특징 추출(Feature Extraction), 질문 응답(Question Answering)과 같은 여러 작업을 위한 간단한 API를 제공합니다.
감사합니다! Glossary를 보면서 했으면서 이 부분들은 누락했네요🥹 꼼꼼히 확인해주셔서 감사합니다!

2023-08-28 12:42 UTC, Sunmin0520 commented on docs/source/ko/main_classes/pipelines.md
> +## Natural Language Processing
@nuatmochoi 저도 이 부분을 잘 모르겠어서 다른 분들의 PR을 살펴봤는데요! 헤더 텍스트와 대괄호가 띄워져 있는 PR도 있고, 아닌 PR도 있었습니다. 그래서 두 가지 버전의 차이점이 동작에는 영향을 미치지 않는 것으로 예상됩니다..!

2023-08-28 13:13 UTC, nuatmochoi commented on docs/source/ko/main_classes/pipelines.md
> +## 오디오 [[Audio]]
```suggestion
## 오디오 [[audio]]
```
preview 돌려봤는데 padding 안에 text로 링크가 연결되는 듯합니다. 이 부분만 수정하면 27라인 링크는 문제 없을 것으로 보입니다:)

2023-08-28 14:17 UTC, 0525hhgus commented on docs/source/ko/main_classes/pipelines.md
> +## Natural Language Processing
꼼꼼하게 확인해주셔서 감사합니다, @nuatmochoi님! 
Markdown 처리 툴에 따라 공백 유무는 처리되는 방식이 다른 것 같습니다.
@Sunmin0520 님께서 말씀주신 것처럼 다른 문서와 비교하여 보니, HuggingFace에서는 공백 유무 관계없이 가능한 것으로 생각됩니다 🤔 
[huggingface/doc-builder](https://github.com/huggingface/doc-builder/tree/main) 에서는 achor link 예시에 공백이 없지만, 내부적으로 두 가지 경우 모두 올바르게 처리되는 것 같습니다.

2023-08-29 23:41 UTC, Sunmin0520 commented
@0525hhgus 님, 혹시 위의 CI 테스트에서 첫번째 에러 부분에 대해 확인해주실 수 있을까요? 
에러 메세지를 보면 
`ValueError: There was an error when converting ../transformers/docs/source/ko/main_classes/pipelines.md to the MDX format.
Unable to find 파이프라인 in transformers. Make sure the path to that object is correct.` 라고 나옵니다.
API 문서에 대해서는 toctree.yml에 작성해야하는 방법이 조금 다른걸까요..?

2023-08-30 00:00 UTC, 0525hhgus commented
> @0525hhgus 님, 혹시 위의 CI 테스트에서 첫번째 에러 부분에 대해 확인해주실 수 있을까요? 에러 메세지를 보면 `ValueError: There was an error when converting ../transformers/docs/source/ko/main_classes/pipelines.md to the MDX format. Unable to find 파이프라인 in transformers. Make sure the path to that object is correct.` 라고 나옵니다. API 문서에 대해서는 toctree.yml에 작성해야하는 방법이 조금 다른걸까요..?

안녕하세요, @Sunmin0520 님!
pipelines.md 문서가 main_classes 폴더 아래 있다는 것이 나타나지 않아서 발생한 것으로 추정됩니다.
_toctree.yml에서 209 라인의 `pipelines`를 `main_classes/pipelines`로 수정하시면 될 것 같습니다! :smile:

2023-08-30 06:15 UTC, Sunmin0520 commented
@0525hhgus 님, 감사합니다! 알려주신 것처럼 수정 후 문제없이 CI 테스트 완료된 것 확인했습니다 :)

2023-10-12 08:05 UTC, closed without merging