🌐 [i18n-KO] `contributing.md` to Korean
huggingface/transformers pull request #25877
Opened 2023-08-30 16:43 UTC by mjk0618

# What does this PR do?

Translated the `contributing.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-08-30 17:18 UTC, seank021 commented on CONTRIBUTING_ko.md
> +🤗 Transformers를 널리 알리는 것도 큰 도움이 됩니다! 블로그 게시글에 멋진 프로젝트들이 가능하게 한 🤗 Transformers 라이브러리에 대해 언급하거나, 도움이 되었을 때마다 Twitter에 알리거나, 저장소에 ⭐️ 를 표시하여 감사 인사를 전해주세요.
멋진 프로젝트들'이' -> 멋진 프로젝트들'을' 이 조금 더 자연스러울 것 같아요!

또, 어순도 '멋진 프로젝트들을 가능하게 한 🤗 Transformers 라이브러리에 대해 블로그 게시글에 언급하거나'가 조금 더 자연스럽게 읽히는 것 같아 제안드려 봅니다!

2023-08-30 17:18 UTC, seank021 commented on CONTRIBUTING_ko.md
> +1. 이 기능이 필요한 *이유*는 무엇인가요? 라이브러리에 대한 문제나 불만과 관련이 있나요? 프로젝트에 필요한 기능인가요? 커뉴미니테 도움이 될 만한 기능인가요?
'커뮤니티에' 오타 있습니다!

2023-08-30 17:18 UTC, seank021 commented on CONTRIBUTING_ko.md
> +   여러분의 운영체제에 따라서, 그리고 🤗 Transformers의 선택적 의존성의 수가 증가하면서, 이 명령이 실패할 수도 있습니다. 그럴 경우 사용하려는 딥 러닝 프레임워크(PyTorch, TensorFlow, 그리고/또는 Flax)를 설치한 다음 다음 명령을 실행해주세요:
'설치한 다음 다음 명령을' 부분에서, 다음 다음이 연속되는 것이 자연스럽지 않은 것 같아서
첫 번째 '다음' 뒤에 쉼표를 두거나, 첫번째 '다음'을 '이후' 등의 어휘로 바꾸는 게 좋을 것 같습니다!

2023-08-31 01:40 UTC, 54data commented on CONTRIBUTING_ko.md
> +저장소의 루트 디렉토리에서도 같은 명령을 실행할 수 있습니다:
glossary에 따라 '디렉토리' -> '디렉터리'로 제안드립니다!
```suggestion
저장소의 루트 디렉터리에서도 같은 명령을 실행할 수 있습니다:
```

2023-08-31 01:40 UTC, 54data commented on CONTRIBUTING_ko.md
> +   저장소의 루트 디렉토리에서 다음 명령을 실행하세요:
```suggestion
   저장소의 루트 디렉터리에서 다음 명령을 실행하세요:
```

2023-08-31 01:40 UTC, 54data commented on CONTRIBUTING_ko.md
> +속도가 빠른 `pytest`와 `pytest-xdist`를 선호합니다. 저장소의 루트 디렉토리에서 테스트를 실행할 *하위 폴더 경로 또는 테스트 파일 경로*를 지정하세요.
```suggestion
속도가 빠른 `pytest`와 `pytest-xdist`를 선호합니다. 저장소의 루트 디렉터리에서 테스트를 실행할 *하위 폴더 경로 또는 테스트 파일 경로*를 지정하세요.
```

2023-08-31 01:40 UTC, 54data commented on CONTRIBUTING_ko.md
> +마찬가지로 `examples` 디렉토리에서도 *하위 폴더 경로 또는 테스트 파일 경로*를 지정하세요. 예를 들어, 다음 명령은 PyTorch `examples` 디렉토리의 텍스트 분류 하위 폴더를 테스트합니다:
```suggestion
마찬가지로 `examples` 디렉터리에서도 *하위 폴더 경로 또는 테스트 파일 경로*를 지정하세요. 예를 들어, 다음 명령은 PyTorch `examples` 디렉터리의 텍스트 분류 하위 폴더를 테스트합니다:
```

2023-08-31 01:40 UTC, 54data commented on CONTRIBUTING_ko.md
> +   여러분의 운영체제에 따라서, 그리고 🤗 Transformers의 선택적 의존성의 수가 증가하면서, 이 명령이 실패할 수도 있습니다. 그럴 경우 사용하려는 딥 러닝 프레임워크(PyTorch, TensorFlow, 그리고/또는 Flax)를 설치한 다음 다음 명령을 실행해주세요:
glossary에 따라 '딥 러닝' -> '딥러닝'으로 제안드립니다!
```suggestion
   여러분의 운영체제에 따라서, 그리고 🤗 Transformers의 선택적 의존성의 수가 증가하면서, 이 명령이 실패할 수도 있습니다. 그럴 경우 사용하려는 딥러닝 프레임워크(PyTorch, TensorFlow, 그리고/또는 Flax)를 설치한 다음 다음 명령을 실행해주세요:
```

2023-08-31 01:40 UTC, 54data commented on CONTRIBUTING_ko.md
> +☐ 모든 공개 메서드는 유용한 기술문서를 가져야 합니다 (예를 들어 [`modeling_bert.py`](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py) 참조).<br>
glossary에 따라 '메서드' -> '메소드'로 제안드립니다!
```suggestion
☐ 모든 공개 메소드는 유용한 기술문서를 가져야 합니다 (예를 들어 [`modeling_bert.py`](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py) 참조).<br>
```

2023-08-31 04:40 UTC, nuatmochoi requested changes

2023-08-31 04:40 UTC, nuatmochoi commented on CONTRIBUTING_ko.md
> +7. 관리자가 변경 사항을 요청해도 괜찮습니다. 숙련된 기여자들도 동일한 상황을 겪습니다! 모두가 변경 사항을 Pull Request에서 볼 수 있도록, 로컬 브랜치에서 작업하고 변경 사항을 포크한 저장소로 푸시하세요. 그러면 변경 사항이 자동으로 Pull Request에 나타납니다.
```suggestion
7. 관리자가 변경 사항을 요청해도 괜찮습니다. 핵심 기여자들도 동일한 상황을 겪습니다! 모두가 변경 사항을 Pull Request에서 볼 수 있도록, 로컬 브랜치에서 작업하고 변경 사항을 포크한 저장소로 푸시하세요. 그러면 변경 사항이 자동으로 Pull Request에 나타납니다.
```
원문(core)을 살려 `핵심`으로 수정하였습니다.

2023-08-31 04:40 UTC, nuatmochoi commented on CONTRIBUTING_ko.md
> +   - 새 토크나이저를 추가하는 경우, 테스트를 작성하고 다음 명령으로 테스트를 통과하는지 확인하세요: `RUN_SLOW=1 python -m pytest tests/models/{your_model_name}/test_tokenization_{your_model_name}.py`. CircleCI에서는 느린 테스트를 실행하지 않지만, GitHub Ac
```suggestion
   - 새 토크나이저를 추가하는 경우, 테스트를 작성하고 다음 명령으로 테스트를 통과하는지 확인하세요: `RUN_SLOW=1 python -m pytest tests/models/{your_model_name}/test_tokenization_{your_model_name}.py`. 
   - CircleCI에서는 느린 테스트를 실행하지 않지만, GitHub Actions에서는 매일 밤 실행됩니다!<br>
```
줄바뀜 누락된 부분 수정합니다.

2023-08-31 08:36 UTC, mjk0618 commented on CONTRIBUTING_ko.md
> +   여러분의 운영체제에 따라서, 그리고 🤗 Transformers의 선택적 의존성의 수가 증가하면서, 이 명령이 실패할 수도 있습니다. 그럴 경우 사용하려는 딥 러닝 프레임워크(PyTorch, TensorFlow, 그리고/또는 Flax)를 설치한 다음 다음 명령을 실행해주세요:
리뷰해주셔서 감사합니다! 말씀해주신 내용 반영해서 commit하였습니다!

2023-08-31 08:38 UTC, mjk0618 commented on CONTRIBUTING_ko.md
> +저장소의 루트 디렉토리에서도 같은 명령을 실행할 수 있습니다:
리뷰해주셔서 감사합니다. 말씀하신 내용 반영하여 커밋하였습니다!

2023-08-31 08:40 UTC, mjk0618 commented on CONTRIBUTING_ko.md
> +7. 관리자가 변경 사항을 요청해도 괜찮습니다. 숙련된 기여자들도 동일한 상황을 겪습니다! 모두가 변경 사항을 Pull Request에서 볼 수 있도록, 로컬 브랜치에서 작업하고 변경 사항을 포크한 저장소로 푸시하세요. 그러면 변경 사항이 자동으로 Pull Request에 나타납니다.
리뷰해주셔서 감사합니다! 말씀하신 내용 모두 반영해서 커밋하였습니다.

처음에 NMT Draft가 생성될 때 핵심 기여자로 되어 있었는데, 조금 더 이해가 쉽도록 숙련된으로 표현을 수정했었습니다. 다시 검토해보니 원문을 살리는 게 나을 거 같아서 반영해서 수정하였습니다!

2023-08-31 14:00 UTC, stevhliu reviewed
Thanks for the translation! 🤗 

Can you copy the contents of `CONTRIBUTING_ko.md` into `contributing.md`? We should just have one file for this.

2023-09-01 16:20 UTC, stevhliu commented
Oh nevermind, I see what you mean! You can feel free to mark the PR as ready for review and we can merge!

2023-09-02 14:14 UTC, mjk0618 commented
> Oh nevermind, I see what you mean! You can feel free to mark the PR as ready for review and we can merge!

Thank you for your help! I marked the PR as ready for review. Could you please review and merge it?

2023-09-05 05:44 UTC, mjk0618 commented
May you please review this PR? @sgugger, @ArthurZucker, @eunseojo

2023-09-05 18:38 UTC, stevhliu commented
@ArthurZucker, I think the `build_pr_documentation` test is failing because `docs/source/ko/contributing.md` is just a path to the actual docs and the [`generate_frontmatter_in_text`](https://github.com/huggingface/doc-builder/blob/c8152d4d1cb455e4b614dd34806f9c1345ad92b1/src/doc_builder/build_doc.py#L273) function is expecting a level 1 header. Would it still be ok to merge this PR?

2023-09-06 18:52 UTC, ArthurZucker commented
@stevhliu would be better if we find a fix! It's my first time seeing this so not really sure

2023-09-08 06:38 UTC, mjk0618 commented
@stevhliu Thank you for reviewing my PR! Then, should I try to fix something so that the error does not occur? I think I have to  try to find out the reason for the error, if I can help fixing the problem. If it's something I can't do, would it be better to wait while translating other documents?

2023-09-08 18:42 UTC, stevhliu commented
I think it's an issue with the test not recognizing the path to `contributing_ko.md` in the docs. We'll look into this issue, but in the meantime, feel free to keep up the good work translating other docs. This issue is probably only affecting this specific doc. 🙂

2023-09-12 02:03 UTC, mjk0618 commented on docs/source/ko/contributing.md
> +../../../CONTRIBUTING_ko.md
Before I make a new commit, I wanted to confirm if I unerstood correctly. Then, should I delete the `CONTRIBUTING_ko.md` file I added to the root directory, and copy all the contents to `docs/source/ko/contributing.md` file?

2023-09-12 15:09 UTC, mjk0618 commented on docs/source/ko/contributing.md
> +../../../CONTRIBUTING_ko.md
Thank you for your help! I've just finished what I should do.

2023-09-12 15:30 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_25877). All of your documentation changes will be reflected on that endpoint.

2023-09-12 15:35 UTC, stevhliu approved these changes
Great work! Thanks for being patient and working with us on this 😄

2023-09-12 15:35 UTC, stevhliu commented on docs/source/ko/contributing.md
> +../../../CONTRIBUTING_ko.md
Nothing left to do except merge! 🚀

2023-09-12 15:35 UTC, merged