🌐 [i18n-KO] Translated  `audio_classification.mdx` to Korean
huggingface/transformers pull request #26200
Opened 2023-09-16 13:21 UTC by gabrielwithappy

# What does this PR do?

Translated the `audio_classification.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-09-16 23:21 UTC, gabrielwithappy commented
Team PseudoLab, may you please review this PR? @0525hhgus, @kihoon71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

2023-09-17 05:01 UTC, wonhyeongseo requested changes
Section is complete, tysm @gabrielwithappy !

2023-09-17 05:01 UTC, wonhyeongseo commented on docs/source/ko/_toctree.yml
>      title: (번역중) 오디오
```suggestion
     title: 오디오
```

이 섹션은 완료되었으므로 번역중을 빼셔도 될 것 같아요. 좋은 번역 감사합니다, @gabrielwithappy 님!

2023-09-17 06:57 UTC, gabrielwithappy commented
@wonhyeongseo 
I updated your suggestion!
Thank you for your feedback. :-)

2023-09-21 23:10 UTC, 0525hhgus requested changes
좋은 번역 감사합니다 😀
오디오 관련 용어를 꼼꼼하게 번역해주셔서 수월하게 이해했습니다 👍
아래 리뷰를 남기니, 참고 부탁드립니다!

2023-09-21 23:10 UTC, 0525hhgus commented on docs/source/ko/tasks/audio_classification.md
> +1. 훈련 하이퍼파라미터를 [`TrainingArguments`]에 정의합니다. 유일한 필수 파라미터는 모델을 저장할 위치를 지정하는 `output_dir`입니다. `push_to_hub = True`를 설정하여 이 모델을 허브로 푸시합니다(모델을 업로드하려면 허깅 페이스에 로그인해야 합니다). 각 에포크가 끝날 때마다 [`Trainer`]가 정확도를 평
```suggestion
1. 훈련 하이퍼파라미터를 [`TrainingArguments`]에 정의합니다. 유일한 필수 매개변수는 모델을 저장할 위치를 지정하는 `output_dir`입니다. `push_to_hub = True`를 설정하여 이 모델을 허브로 푸시합니다(모델을 업로드하려면 허깅 페이스에 로그인해야 합니다). 각 에폭이 끝날 때마다 [`Trainer`]가 정확도를 평가하고 훈련 체크포인트를 저장합니다.
```

2023-09-21 23:10 UTC, 0525hhgus commented on docs/source/ko/tasks/audio_classification.md
> +2. 모델, 데이터 세트, 토큰화기, 데이터 콜레이터, `compute_metrics` 함수와 함께 훈련 인자를 [`Trainer`]에 전달합니다.
```suggestion
2. 모델, 데이터 세트, 토크나이저, 데이터 콜레이터, `compute_metrics` 함수와 함께 훈련 인자를 [`Trainer`]에 전달합니다.
```

2023-09-21 23:10 UTC, 0525hhgus commented on docs/source/ko/tasks/audio_classification.md
> +트레이닝이 완료되면 모든 사람이 모델을 사용할 수 있도록 [`~transformers.Trainer.push_to_hub`] 메서드를 사용하여 모델을 허브에 공유하세요:
```suggestion
훈련이 완료되면 모든 사람이 모델을 사용할 수 있도록 [`~transformers.Trainer.push_to_hub`] 메소드를 사용하여 모델을 허브에 공유하세요:
```

2023-09-21 23:10 UTC, 0525hhgus commented on docs/source/ko/tasks/audio_classification.md
> +추론을 실행할 오디오 파일을 로드합니다. 필요한 경우 오디오 파일의 샘플링 속도를 모델의 샘플링 속도와 일치하도록 리샘플링하는 것을 잊지 마세요!
```suggestion
이제 모델을 미세 조정했으니 추론에 사용할 수 있습니다!

추론을 실행할 오디오 파일을 가져옵니다. 필요한 경우 오디오 파일의 샘플링 속도를 모델의 샘플링 속도와 일치하도록 리샘플링하는 것을 잊지 마세요!
```

2023-09-21 23:10 UTC, 0525hhgus commented on docs/source/ko/tasks/audio_classification.md
> +특징 추출기를 로드하여 오디오 파일을 전처리하고 '입력'을 PyTorch 텐서로 반환합니다:
```suggestion
특징 추출기를 가져와서 오디오 파일을 전처리하고 `입력`을 PyTorch 텐서로 반환합니다:
```

2023-09-22 09:19 UTC, gabrielwithappy commented
> 좋은 번역 감사합니다 😀
> 오디오 관련 용어를 꼼꼼하게 번역해주셔서 수월하게 이해했습니다 👍
> 아래 리뷰를 남기니, 참고 부탁드립니다!

꼼꼼한 리뷰 너무감사 드립니다!!🤗

2023-09-25 08:01 UTC, gabrielwithappy reviewed
update review

2023-09-25 08:04 UTC, gabrielwithappy commented
@sgugger, @ArthurZucker, @eunseojo 
May you please review this PR?

2023-09-25 13:02 UTC, LysandreJik commented
cc @stevhliu for review :)

2023-09-25 17:03 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_26200). All of your documentation changes will be reflected on that endpoint.

2023-09-25 17:24 UTC, stevhliu approved these changes
Thanks for your translation! 😄

2023-09-25 17:24 UTC, merged