🌐 [i18n-KO] Translated `tokenizer_summary.md` to Korean
huggingface/transformers pull request #26243
Opened 2023-09-19 06:17 UTC by wonhyeongseo

# What does this PR do?

@HanNayeoniee translated the `tokenizer_summary.md` file of the documentation to Korean. I made sure hanging suggestions were resolved.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179
Moved from https://github.com/huggingface/transformers/pull/25023

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2023-09-21 10:06 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_26243). All of your documentation changes will be reflected on that endpoint.

2023-09-22 13:44 UTC, 0525hhgus requested changes
더 많은 인원이 검토할 수 있도록 PR를 옮겨주셔서 감사합니다 👍  
이전 번역과 리뷰가 모두 잘 이루어져 있어서, 아래 짧은 리뷰를 남깁니다 😄

2023-09-22 13:44 UTC, 0525hhgus commented on docs/source/ko/tokenizer_summary.md
> +단어 또는 서브워드를 아이디로 변환하는 것은 간단하기 때문에 이번 문서에서는 텍스트를 단어 또는 서브워드로 쪼개는 것(즉, 텍스트를 토큰화하는 것)에 중점을 두겠습니다.
```suggestion
단어 또는 서브워드를 id로 변환하는 것은 간단하기 때문에 이번 문서에서는 텍스트를 단어 또는 서브워드로 쪼개는 것(즉, 텍스트를 토큰화하는 것)에 중점을 두겠습니다.
```
이전 문장에서 id로 사용하고 있어서 영어로 수정했습니다!

2023-09-22 13:44 UTC, 0525hhgus commented on docs/source/ko/tokenizer_summary.md
> +예를 들어, 문자 `"t"`에 대한 의미 있는 문맥 독립적 표현을 배우는 것 보다 단어 `"today"`에 대한 의미 있는 문맥 독립적 표현을 배우는 것이 훨씬 더 어렵습니다.
```suggestion
*예를 들어*, 문자 `"t"`에 대한 의미 있는 문맥 독립적 표현을 배우는 것 보다 단어 `"today"`에 대한 의미 있는 문맥 독립적 표현을 배우는 것이 훨씬 더 어렵습니다.
```
원문에서 `*E.g.*`로 작성되어 `*예를 들어*`로 수정하였습니다. `*E.g.*`와 한국어에서의 형태가 달라서 해당 부분은 참고만 부탁드립니다!

2023-09-22 13:44 UTC, 0525hhgus commented on docs/source/ko/tokenizer_summary.md
> +예를 들어, [Transformer XL](model_doc/transformerxl)은 공백 및 구두점 토큰화를 사용해 어휘(vocabulary) 크기가 267,735입니다!
```suggestion
*예를 들어*, [Transformer XL](model_doc/transformerxl)은 공백 및 구두점 토큰화를 사용해 어휘(vocabulary) 크기가 267,735입니다!
```
원문에서 `*E.g.*`로 작성되어 `*예를 들어*`로 수정하였습니다. `*E.g.*`와 한국어에서의 형태가 달라서 해당 부분은 참고만 부탁드립니다!

2023-09-22 13:44 UTC, 0525hhgus commented on docs/source/ko/tokenizer_summary.md
> +각 훈련 단계에서 유니그램 알고리즘은 현재 어휘와 유니그램 언어 모델이 주어졌을 때 훈련 데이터에 대한 손실(흔히 로그 확률로 정의됨)을 정의합니다.
```suggestion
각 훈련 단계에서 유니그램 알고리즘은 현재 어휘와 유니그램 언어 모델이 주어졌을 때 훈련 데이터에 대한 손실(흔히 로그 우도로 정의됨)을 정의합니다.
```
워드피스 파트에서 `likelihood`를 `우도`로 언급되었고, `log-likelihood`도 `로그 우도`에 가까울 것 같습니다!

2023-09-25 16:29 UTC, stevhliu approved these changes
Thanks for carrying this over the finish line!

2023-10-02 16:55 UTC, merged