[Docs] PatchTST doc improvements
huggingface/transformers pull request #27476
Opened 2023-11-13 19:00 UTC by kashif

# What does this PR do?
updates the docs to the structure of #26876

2023-11-13 19:05 UTC, NielsRogge commented on docs/source/en/model_doc/patchtst.md
> +The PatchTST model was proposed in [A Time Series is Worth 64 Words: Long-term Forecasting with Transformers](https://arxiv.org/abs/2211.14730) by Yuqi Nie, Nam H. Nguyen, Phanwadee Sinthong and Jaya
would be great to add a one-line summary sentence here

2023-11-13 19:26 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_27476). All of your documentation changes will be reflected on that endpoint.

2023-11-13 19:34 UTC, amyeroberts approved these changes
Thanks for updating!

2023-11-14 11:49 UTC, amyeroberts requested changes
Please hold off on any merging as the model PR commit it being reverted

2023-11-18 18:53 UTC, closed without merging