translate deepspeed.md to chinese
huggingface/transformers pull request #27495
Opened 2023-11-14 17:14 UTC by jiaqiw09

# What does this PR do?

Part of  #26803 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? _not necessary_

## Who can review?
@stevhliu

2023-11-15 19:41 UTC, stevhliu approved these changes
LGTM! My Chinese isn't that great (its pretty basic 😅 ) so maybe @statelesshz, would you be interested in helping double check the translation?

2023-11-16 09:40 UTC, statelesshz commented
> LGTM! My Chinese isn't that great (its pretty basic 😅 ) so maybe @statelesshz, would you be interested in helping double check the translation?

My Pleasure!

2023-11-17 13:42 UTC, statelesshz requested changes

2023-11-17 13:42 UTC, statelesshz commented on docs/source/zh/main_classes/deepspeed.md
> +集成的内容是什么：
```suggestion
集成的内容：
```

2023-11-17 13:42 UTC, statelesshz commented on docs/source/zh/main_classes/deepspeed.md
> +1. DeepSpeed ZeRO推理支持使用ZeRO-Infinity的ZeRO stage 3。它使用与训练相同的ZeRO协议，但不使用优化器和学习率调度器，只与stage 3相关。更多详细信息请参阅：[zero-inference](#zero-inference)。
```suggestion
1. DeepSpeed ZeRO推理支持ZeRO stage 3和ZeRO-Infinity。它使用与训练相同的ZeRO协议，但不使用优化器和学习率调度器，只有stage 3与推理相关。更多详细信息请参阅：[zero-inference](#zero-inference)。
```

2023-11-17 16:21 UTC, jiaqiw09 commented
@statelesshz thanks for your reviw.

and @stevhliu would you mind having a check and finish the merge. I think I will update this file oneday I learn more about deepspeed.

Best

2023-11-17 21:39 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_27495). All of your documentation changes will be reflected on that endpoint.

2023-11-17 21:49 UTC, stevhliu commented
Great job and thanks again for tackling such a big and dense doc! 👏

2023-11-17 21:49 UTC, merged