[WIP] Adapt lm generate fn for seq 2 seq models
huggingface/transformers pull request #2888
Opened 2020-02-18 14:55 UTC by patrickvonplaten

From looking at the soon-to-be-added Bart model, I though the language generation could be conceptually adapted as shown below to be able to produce language from seq-to-seq models (Bart & T5). 

So far this is not tested at all and only adapted for the `_generate_no_beam_search()` function. Also it still has to be checked whether this is compatible with T5.

Would be happy about feedback @sshleifer, @thomwolf

2020-02-18 15:10 UTC, sshleifer commented
Excited for this!

A little early for me to have an opinion, but I'd start by adding a bunch of failing tests (e.g. for t5.generate), and some slow tests that verify that T5.generate/another non seq2seq model generate reasonable results. (You have to run those locally). 

Stylistically, I'd say `is_seq_to_seq` should probably not be a function, just an attribute. But I think style here much less important than test coverage :)

Bon Chance!

2020-02-18 15:13 UTC, sshleifer requested changes

2020-02-18 15:13 UTC, sshleifer commented on src/transformers/modeling_utils.py
> +        cur_len = 0 if self._is_seq_to_seq() else input_ids.shape[0]
_is_seq_to_seq should probably not start with `_`.
There is also `is_encoder_decoder` in the ModelTester, and I feel like it should be one param :)

2020-02-18 15:13 UTC, sshleifer commented on src/transformers/modeling_utils.py
> +                next_token_logits, past, encoder_outputs = self.postprocess_outputs_for_generatio(outputs)
typ: postprocess_outputs_for_generatio(n)

2020-02-18 15:14 UTC, sshleifer commented
Meant to just comment, sorry!

2020-02-21 13:52 UTC, patrickvonplaten commented on src/transformers/modeling_bart.py
> +    def prepare_inputs_for_generation(decoder_input_ids, past, encoder_inputs, encoder_outputs, **wwargs):
This is how I would implement the `prepare_inputs_for_generation` fn for Bart. What do you think? @sshleifer

2020-02-21 13:53 UTC, patrickvonplaten commented on src/transformers/modeling_bart.py
> +    def postprocess_outputs_for_generation(self, outputs):
This function in general is very hacky and should be removed when changing to named tuples as the preferred output for all models.

2020-02-21 13:58 UTC, patrickvonplaten commented
I adapted the language generation according to the newly added Bart file. This is still very much work in progress that's why I left a lot of comments in all files. Would be very happy about some feedback! @sshleifer

2020-02-21 15:11 UTC, sshleifer requested changes
TLDR: I think it doesn't make that much sense to iterate on the abstractions until we know how to generate high quality stuff from seq2seq models. 

I would figure out how to get reasonable generations with the fairseq bart-large (not CNN) model, (might need to ask authors), then see if you can get the huggingface code producing the same generations.

I figured out how to do it for summarization and made a gist: 
https://gist.github.com/sshleifer/92e26dc54ce937de9b757a17797fbaa2

In the meantime, I'm going to try to get summarization working for bart-large-cnn.

2020-02-24 14:05 UTC, patrickvonplaten commented on src/transformers/modeling_utils.py
> +        if self.config.is_encoder_decoder:
I thought about it, but I think some ifs are going to be unavoidable. For a seq-2-seq model the input_ids always represent the encoder_input_ids which will not be at the begging of the output, whereas for a "decoder-only" model (such as gpt2) the input ids will always present the beginning of the output. So the `cur_len` and `input_ids` variables have to rely on an if-statement in my opinion. One other option would be to (again) introduce a generic function that could be overwritten by each class, but I prefer the first option. Open to other design ideas though! @sshleifer

2020-02-24 14:05 UTC, patrickvonplaten commented on src/transformers/modeling_utils.py
> +            input_ids = torch.full(
True, I think we should discuss this more in detail!

2020-03-05 22:30 UTC, closed without merging