[ Docs] translated peft (ES) and toctree.yml add
huggingface/transformers pull request #30554
Opened 2024-04-29 19:00 UTC by njackman-2344

Add the Spanish version of `peft.md` to `transformers/docs/source/es` 

#28936

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@stevhliu @aaronjimv  If you don't mind reviewing, thanks!! :)

2024-04-29 19:46 UTC, stevhliu reviewed
Thanks for adding! 🤗

2024-04-29 19:46 UTC, stevhliu commented on docs/source/es/_toctree.yml
> +    local: peft
This should be in the "Tutorial" section.

```suggestion
   - local: peft
```

2024-04-29 19:46 UTC, stevhliu commented on docs/source/es/peft.md
> +  <figcaption class="text-center">The adapter weights for a OPTForCausalLM model stored on the Hub are only ~6MB compared to the full size of the model weights, which can be ~700MB.</figcaption>
Would be nice to also translate the caption 🙂

2024-04-29 19:46 UTC, stevhliu commented on docs/source/es/peft.md
> + guarda memoria (mira la [guia](./quantization#bitsandbytes-integration) de `bitsandbytes` para aprender mas). Agrega el parametro `load_in_8bit` o el parametro `load_in_4bit` al [`~PreTrainedModel.f
The "Quantization" doc doesn't exist in Spanish yet so let's link to the English one for now

```suggestion
 guarda memoria (mira la [guia](https://huggingface.co/docs/transformers/quantization#bitsandbyes) de `bitsandbytes` para aprender mas). Agrega el parametro `load_in_8bit` o el parametro `load_in_4bit` al [`~PreTrainedModel.from_pretrained`] y coloca `device_map="auto"` para effectivamente distribuir el modelo tu hardware:
```

2024-04-29 20:51 UTC, aaronjimv reviewed
Hi, thanks for adding! The translation in general is good, but I have to point out that it presents several issues with fluency (making it sound natural) and coherence (making it reflect the original content).

2024-05-21 18:42 UTC, aaronjimv requested changes
Hi @njackman-2344, I appreciate you asking me to review again. However, I still have some concerns about the fluency and coherence of the translation. Would you mind taking another look at all the comments made [here](https://github.com/huggingface/transformers/pull/30554/commits/03a1a7d2c0b00ecfde6f4b9c3c19b68ae341b5d7) and addressing those issues? I think it would really make a big difference. Additionally, I wanted to suggest you to use tools like [HuggingChat](https://huggingface.co/chat/) to assist you in the translations and improving their fluency and coherence. Once you've made the necessary changes, I'll be happy to review again.

2024-05-21 18:50 UTC, njackman-2344 commented
> Hi @njackman-2344, I appreciate you asking me to review again. However, I still have some concerns about the fluency and coherence of the translation. Would you mind taking another look at all the comments made [here](https://github.com/huggingface/transformers/pull/30554/commits/03a1a7d2c0b00ecfde6f4b9c3c19b68ae341b5d7) and addressing those issues? I think it would really make a big difference. Additionally, I wanted to suggest you to use tools like [HuggingChat](https://huggingface.co/chat/) to assist you in the translations and improving their fluency and coherence. Once you've made the necessary changes, I'll be happy to review again.

Ok! Thank you! I didn't see the corrections. I will do that.

2024-07-11 08:05 UTC, closed without merging