Add BartForSummarization alias with better docstring
huggingface/transformers pull request #3114
Opened 2020-03-03 22:42 UTC by sshleifer

2020-03-04 10:10 UTC, thomwolf requested changes
Up to now, model classes have been named from the generic task they can handle (ex. `BertForSequenceClassification`  instead of `BertForNLI`)

We should do the same here and keep task specific names for `pipelines` which are intended for this.

IMO the generic name here is something like `BartForConditionalGeneration`

2020-03-04 20:49 UTC, sshleifer commented
Docs:
![image](https://user-images.githubusercontent.com/6045025/75921740-a3a20680-5e2f-11ea-983c-af02dbe1f84f.png)

2020-03-04 20:50 UTC, sshleifer commented on tests/test_modeling_bart.py
> +        lm_model = BartForConditionalGeneration(config).to(torch_device)
This fix should be in a separate PR

2020-03-05 12:21 UTC, thomwolf commented on docs/source/model_doc/bart.rst
> +- ``BartModel.forward`` will create decoder inputs (using the helper function ``transformers.modeling_bart._prepare_bart_decoder_inputs``)  if they are not passed. This is different than some other m
"The forward pass of `BartModel`" we don't want to encourage people to use `model.forward()`, it's a bad PyTorch practice.

2020-03-05 12:21 UTC, thomwolf commented on docs/source/model_doc/bart.rst
> +- ``BartForConditionalGeneration.generate`` should be used for summarization, see the example in that docstrings
"for conditional generation tasks like summarization"

2020-03-05 12:21 UTC, thomwolf commented on src/transformers/__init__.py
> +        BartForConditionalGeneration,
duplicate

2020-03-05 12:21 UTC, thomwolf commented on src/transformers/convert_bart_original_pytorch_checkpoint_to_pytorch.py
>      if checkpoint_path == "bart.large.cnn":  # generate doesnt work yet
Remove this "generate doesnt work yet" comment?

2020-03-05 12:21 UTC, thomwolf commented on src/transformers/convert_bart_original_pytorch_checkpoint_to_pytorch.py
> +        model = BartForConditionalGeneration(config, base_model=model)
Can you also fix all the `model.forward()` calls in this script?

2020-03-05 22:07 UTC, thomwolf approved these changes
Ok LGTM, thanks @sshleifer

2020-03-05 22:41 UTC, merged