🌐 [i18n-KO] Translated `trainer.md` to Korean
huggingface/transformers pull request #32260
Opened 2024-07-27 08:15 UTC by cjfghk5697

# What does this PR do?

Translated the `trainer.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@mjk0618, @cjfghk5697, @ahnjj, @JinukHong, @nuatmochoi

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-08-03 07:29 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`]는 Transformers 라이브러리에 구현된 PyTorch 모델 훈련 및 평가 루프입니다. 훈련에 필요한 요소(모델, 토크나이저, 데이터셋, 평가 함수, 훈련 하이퍼파라미터 등)만 제공하면 [`Trainer`]가 필요한 나머지 작업을 처리합니다. 이를 통해 직접 훈련 루프를 작성하지 않고도 빠르게 훈련을 시작할 수 있습니다. 또한 [
```suggestion
[Trainer]는 Transformers 라이브러리에 구현된 PyTorch 모델 훈련 및 평가 루프입니다. 훈련에 필요한 요소(모델, 토크나이저, 데이터셋, 평가 함수, 훈련 하이퍼파라미터 등)만 제공하면 [Trainer]가 나머지 필요한 작업을 처리합니다. 이를 통해 직접 훈련 루프를 작성하지 않고도 쉽고 빠르게 훈련을 시작할 수 있습니다. 또한 [Trainer]는 강력한 맞춤 설정과 다양한 훈련 옵션을 제공하여 사용자 맞춤 훈련이 가능합니다.
```

2024-08-03 07:38 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스 외에도 번역이나 요약과 같은 시퀀스-투-시퀀스 작업을 위한 [`Seq2SeqTrainer`] 클래스도 Transformers에서 제공합니다. 또한 [TRL](https://hf.co/docs/trl) 라이브러리에서 [`Trainer`] 클래스를 래핑하여 Llama-2 및 Mistral과 같은 언어 모델을 자동 회귀 기법으로 훈
```suggestion
Transformers는 [`Trainer`] 클래스 외에도 번역이나 요약과 같은 시퀀스-투-시퀀스 작업을 위한 [`Seq2SeqTrainer`] 클래스도 제공합니다. 또한 [TRL](https://hf.co/docs/trl) 라이브러리에는 [`Trainer`] 클래스를 감싸고 Llama-2 및 Mistral과 같은 언어 모델을 자동 회귀 기법으로 훈련하는 데 최적화된 [`~trl.SFTTrainer`] 클래스도 있습니다. [`~trl.SFTTrainer`]는 시퀀스 패킹, LoRA, 양자화 및 DeepSpeed와 같은 기능을 지원하여 크기 상관없이 모델 효율적으로 확장할 수 있습니다.
```

2024-08-03 07:39 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스 외에도 번역이나 요약과 같은 시퀀스-투-시퀀스 작업을 위한 [`Seq2SeqTrainer`] 클래스도 Transformers에서 제공합니다. 또한 [TRL](https://hf.co/docs/trl) 라이브러리에서 [`Trainer`] 클래스를 래핑하여 Llama-2 및 Mistral과 같은 언어 모델을 자동 회귀 기법으로 훈
```suggestion
```

2024-08-03 07:43 UTC, JinukHong commented on docs/source/ko/trainer.md
> +이들 [`Trainer`] 유형 클래스에 대해 더 알고 싶다면 [API 참조](./main_classes/trainer)를 확인하여 언제 어떤 클래스가 적합할지 확인하세요. 일반적으로 [`Trainer`]는 가장 다재다능한 옵션으로, 다양한 작업에 적합합니다. [`Seq2SeqTrainer`]는 시퀀스-투-시퀀스 작업을 위해 설계되었고, [`~trl.SF
```suggestion
이들 다른 [`Trainer`] 유형 클래스에 대해 더 알고 싶다면 [API 참조](./main_classes/trainer)를 확인하여 언제 어떤 클래스가 적합할지 확인하세요. 일반적으로 [`Trainer`]는 가장 다재다능한 옵션으로, 다양한 작업에 적합합니다. [`Seq2SeqTrainer`]는 시퀀스-투-시퀀스 작업을 위해 설계되었고, [`~trl.SFTTrainer`]는 언어 모델 훈련을 위해 설계되었습니다.
```

2024-08-03 07:46 UTC, JinukHong commented on docs/source/ko/trainer.md
> +시작하기 전에, 분산 환경에서 PyTorch 훈련과 실행을 할 수 있게 [Accelerate](https://hf.co/docs/accelerate)를 설치하세요.
```suggestion
시작하기 전에, 분산 환경에서 PyTorch 훈련과 실행을 할 수 있게 [Accelerate](https://hf.co/docs/accelerate) 라이브러리를 설치하세요.
```

2024-08-03 07:52 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스는 이 과정에 필요한 모든 코드를 추상화하여, PyTorch와 훈련에 익숙하지 않거나 막 시작한 경우에도 훈련이 가능합니다. 훈련에 필요한 모델과 데이터셋 같은 필수 구성 요소만 제공하면, [Trainer] 클래스가 나머지를 처리합니다.
```suggestion
[`Trainer`] 클래스는 이 과정에 필요한 모든 코드를 추상화하여, PyTorch와 훈련 과정에 익숙하지 않거나 막 시작한 경우에도 훈련이 가능합니다. 또한 매번 훈련 루프를 손수 작성하지 않아도 되며, 훈련에 필요한 모델과 데이터셋 같은 필수 구성 요소만 제공하면 [Trainer] 클래스가 나머지를 처리합니다.
```

2024-08-03 07:53 UTC, JinukHong commented on docs/source/ko/trainer.md
> +훈련 옵션이나 하이퍼파라미터를 지정하려면, [`TrainingArguments`] 클래스에서 확인 할 수 있습니다. 예를 들어, 모델을 저장할 디렉토리를 `output_dir`에 정의하고, 훈련 후에 Hub로 모델을 푸시하려면 `push_to_hub=True`로 설정합니다.
```suggestion
```

2024-08-03 07:55 UTC, JinukHong commented on docs/source/ko/trainer.md
> +`training_args`를 [`Trainer`]에 모델, 데이터셋, 데이터셋을 전처리할 수 있는 도구(데이터 유형에 따라 토크나이저, 특징 추출기 또는 이미지 프로세서일 수 있음), 데이터 수집기 및 훈련 중 확인할 지표를 계산할 함수를 함께 전달하세요.
```suggestion
`training_args`를 [`Trainer`]에 모델, 데이터셋, 데이터셋 전처리 도구(데이터 유형에 따라 토크나이저, 특징 추출기 또는 이미지 프로세서일 수 있음), 데이터 수집기 및 훈련 중 확인할 지표를 계산할 함수를 함께 전달하세요.
```

2024-08-03 07:55 UTC, JinukHong commented on docs/source/ko/trainer.md
> +마지막으로, [`~Trainer.train`]를 호출하여 훈련을 시작하세요.
```suggestion
마지막으로, [`~Trainer.train`]를 호출하여 훈련을 시작하세요!
```

2024-08-03 07:56 UTC, JinukHong commented on docs/source/ko/trainer.md
> +체크포인트를 Hub에 푸시하려면 [`TrainingArguments`]에서 `push_to_hub=True`로 설정하여 커밋하고 푸시할 수 있습니다. 체크포인트를 저장하는 방법을 결정하는 다른 옵션은 [`hub_strategy`](https://huggingface.co/docs/transformers/main_classes/trainer#transfor
```suggestion
```

2024-08-03 07:57 UTC, JinukHong commented on docs/source/ko/trainer.md
> +체크포인트를 Hub에 푸시하려면 [`TrainingArguments`]에서 `push_to_hub=True`로 설정하여 커밋하고 푸시할 수 있습니다. 체크포인트를 저장하는 방법을 결정하는 다른 옵션은 [`hub_strategy`](https://huggingface.co/docs/transformers/main_classes/trainer#transfor
```suggestion
체크포인트를 Hub에 푸시하려면 [`TrainingArguments`]에서 `push_to_hub=True`로 설정하여 커밋하고 푸시할 수 있습니다. 체크포인트 저장 방법을 결정하는 다른 옵션은 [`hub_strategy`](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.hub_strategy) 매개변수에서 설정합니다:
```

2024-08-03 07:58 UTC, JinukHong commented on docs/source/ko/trainer.md
> +예를 들어, [`~Trainer.compute_loss`] 메소드를 맞춤 설정하여 가중 손실을 사용하려는 경우:
```suggestion
```

2024-08-03 07:59 UTC, JinukHong commented on docs/source/ko/trainer.md
> +로깅 API에 대한 자세한 내용은 [로깅](./main_classes/logging) API 레퍼런스를 확인하세요.
```suggestion
```

2024-08-03 07:59 UTC, JinukHong commented on docs/source/ko/trainer.md
> +각 노드의 로그 레벨 설정을 구성하려면 [`log_on_each_node`](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.TrainingArguments.log_on_each_node) 매개변수를 사용하여 각 노드에서 로그 레벨을 사용할지 아니면 주 노
```suggestion
```

2024-08-03 07:59 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`]는 기본적으로 `logging.INFO`로 설정되어 있어 오류, 경고 및 기타 기본 정보를 보고합니다. 분산 환경에서는 [`Trainer`] 복제본이 `logging.WARNING`으로 설정되어 오류와 경고만 보고합니다. [`TrainingArguments`]의 [`log_level`](https://huggingface.co/docs
```suggestion
```

2024-08-03 07:59 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`]는 [`Trainer.__init__`] 메소드에서 각 노드에 대해 로그 레벨을 별도로 설정하므로, [`Trainer`] 객체를 생성하기 전에 다른 Transformers 기능을 사용할 경우 이를 미리 설정하는 것이 좋습니다.
```suggestion
```

2024-08-03 07:59 UTC, JinukHong commented on docs/source/ko/trainer.md
> +예를 들어, 메인 코드와 모듈을 각 노드에 따라 동일한 로그 레벨을 사용하도록 설정하려면 다음과 같이 합니다.
```suggestion
```

2024-08-03 08:05 UTC, JinukHong commented on docs/source/ko/trainer.md
> +이 두 옵티마이저는 메모리 사용량을 줄이기 위해 그레디언트 계산과 매개변수 업데이트를 하나의 단계로 융합하는 효율적인 전체 매개변수 미세 조정 방법입니다. LOMO를 지원하는 옵티마이저는 `"lomo"`와 `"adalomo"`입니다. 먼저 pypi에서 `lomo`를 설치하거나 소스에서 `git+https://github.com/OpenLMLab/LOMO.
```suggestion
```

2024-08-03 08:05 UTC, JinukHong commented on docs/source/ko/trainer.md
> +현재 Linear 레이어만 GaLore 레이어로 간주되며, 저계수 분해를 사용하여 훈련되고 나머지 레이어는 기존 방식으로 최적화됩니다.
```suggestion
```

2024-08-03 08:05 UTC, JinukHong commented on docs/source/ko/trainer.md
> +해당 방법에 대한 자세한 내용은 [원본 리포지토리](https://github.com/jiaweizzhao/GaLore) 또는 [논문](https://arxiv.org/abs/2403.03507)을 참고하세요.
```suggestion
```

2024-08-03 08:05 UTC, JinukHong commented on docs/source/ko/trainer.md
> +Gradient Low-Rank Projection (GaLore)은 전체 매개변수를 학습하면서도 LoRA와 같은 일반적인 저계수 적응 방법보다 더 메모리 효율적인 저계수 학습 전략입니다.
```suggestion
```

2024-08-03 08:10 UTC, JinukHong commented on docs/source/ko/trainer.md
> +체크포인트에서 훈련을 재개할 때, [`Trainer`]는 체크포인트가 저장될 때와 동일한 Python, NumPy 및 PyTorch RNG 상태를 유지하려고 합니다. 하지만 PyTorch는 다양한 일관된 결과를 보장되지 않게 기본 설정이 되어 있기 때문에, RNG 상태가 동일할 것이라고 보장할 수는 없습니다. 따라서, 일관된 결과를 보장 되도록 활성화하려
```suggestion
체크포인트에서 훈련을 재개할 때, [`Trainer`]는 체크포인트가 저장될 때와 동일한 Python, NumPy 및 PyTorch RNG 상태를 유지하려고 합니다. 하지만 PyTorch는 다양한 비결정적 기본 설정을 갖기 때문에, RNG 상태가 동일할 것이라고 보장할 수는 없습니다. 따라서, 일관된 결과 보장을 가능하게 하려면, [랜덤성 제어](https://pytorch.org/docs/stable/notes/randomness#controlling-sources-of-randomness) 가이드를 참고하여 훈련을 완전하게 결정적으로 만들기 위해 활성화할 수 있는 항목을 확인하세요. 다만, 특정 설정을 결정적으로 만들면 훈련이 느려질 수 있습니다.
```

2024-08-03 08:22 UTC, ahnjj requested changes
1차 코드리뷰! (~160 콜백전)

2024-08-03 08:22 UTC, ahnjj commented on docs/source/ko/trainer.md
> +체크포인트를 Hub에 푸시하려면 [`TrainingArguments`]에서 `push_to_hub=True`로 설정하여 커밋하고 푸시할 수 있습니다. 체크포인트를 저장하는 방법을 결정하는 다른 옵션은 [`hub_strategy`](https://huggingface.co/docs/transformers/main_classes/trainer#transfor
109번 라인이 중복된것 같아요!

2024-08-03 08:22 UTC, ahnjj commented on docs/source/ko/trainer.md
> +## Trainer 맞춤 설정 [[customize-the-trainer]]
117번라인 중복된것 같아요!

2024-08-03 08:22 UTC, ahnjj commented on docs/source/ko/trainer.md
> +체크포인트에서 훈련을 재개할 때, [`Trainer`]는 체크포인트가 저장될 때와 동일한 Python, NumPy 및 PyTorch RNG 상태를 유지하려고 합니다. 하지만 PyTorch는 다양한 일관된 결과를 보장되지 않게 기본 설정이 되어 있기 때문에, RNG 상태가 동일할 것이라고 보장할 수는 없습니다. 따라서, 일관된 결과를 보장 되도록 활성화하려
하지만 PyTorch는 기본 설정으로 '일관된 결과를 보장하지 않음'으로 많이 되어있기 때문에, RNG 상태가 동일할 것이라고 보장할 수 없습니다. 
따라서, 일관된 결과가 보장되도록 활성화 하려면, [랜덤성 제어](https://pytorch.org/docs/stable/notes/randomness#controlling-sources-of-randomness) 가이드를 참고하여 훈련이 완전히 일관된 결과를 보장 받도록 만들기 위해 활성화할 수 있는 항목을 확인하세요.

2024-08-03 08:22 UTC, ahnjj commented on docs/source/ko/trainer.md
> +이 두 옵티마이저는 메모리 사용량을 줄이기 위해 그레디언트 계산과 매개변수 업데이트를 하나의 단계로 융합하는 효율적인 전체 매개변수 미세 조정 방법입니다. LOMO를 지원하는 옵티마이저는 `"lomo"`와 `"adalomo"`입니다. 먼저 pypi에서 `lomo`를 설치하거나 소스에서 `git+https://github.com/OpenLMLab/LOMO.
413라인 중복된것 같아요ㅠㅠ

2024-08-03 08:22 UTC, ahnjj commented on docs/source/ko/trainer.md
> +* [`~Trainer.log`]는 훈련을 모니터링하는 다양한 객체에 대한 정보를 로그합니다.
훈련을 모니터링하는 다양한 객체에 대한 정보를 로그로 남깁니다.

2024-08-03 08:22 UTC, ahnjj commented on docs/source/ko/trainer.md
> +예를 들어, [`~Trainer.compute_loss`] 메소드를 맞춤 설정하여 가중 손실을 사용하려는 경우:
136라인 중복된것 같아요!

2024-08-03 08:22 UTC, ahnjj commented on docs/source/ko/trainer.md
> +        # 서로 다른 가중치로 3개의 레이블에 대한 사용자 정의 손실을 계산
151라인 중복된것 같아요!

2024-08-03 10:28 UTC, JinukHong commented on docs/source/ko/trainer.md
> +* [`~Trainer.create_optimizer_and_scheduler`]는 `__init__`에서 전달되지 않은 경우 옵티마이저와 학습률 스케줄러를 생성합니다. 이들은 각각 [`~Trainer.create_optimizer`] 및 [`~Trainer.create_scheduler`]로 별도로 맞춤 설정 할 수 있습니다.
```suggestion
```

2024-08-03 11:07 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`]를 맞춤 설정하는 또 다른 방법은 [콜백](callbacks)을 사용하는 것입니다. 콜백은 훈련 루프의 상태를 검사한 후 상태에 따라 일부 작업(조기 종료, 결과 로그 등)을 실행합니다. 즉, 콜백은 사용자 정의 손실 함수와 같은 것을 구현하는 데 사용할 수 없으며, 이를 위해서는 [`~Trainer.compute_loss`] 메소드를
```suggestion
```

2024-08-03 11:22 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[NEFTune](https://hf.co/papers/2310.05914)은 훈련 중 임베딩 벡터에 노이즈를 추가하여 성능을 향상시킬 수 있는 기술입니다. [`Trainer`]에서 이를 활성화하려면 [`TrainingArguments`]의 `neftune_noise_alpha` 매개변수를 설정하여 노이즈의 양을 조절합니다.
```suggestion
```

2024-08-03 11:36 UTC, JinukHong commented on docs/source/ko/trainer.md
> +NEFTune은 예상치 못한 동작을 피하기 위해 훈련 후에 처음 임베딩 레이어로 복원합니다.
```suggestion
```

2024-08-03 16:05 UTC, nuatmochoi requested changes

2024-08-03 16:05 UTC, nuatmochoi commented on docs/source/ko/trainer.md
> +이 두 옵티마이저는 메모리 사용량을 줄이기 위해 그레디언트 계산과 매개변수 업데이트를 하나의 단계로 융합하는 효율적인 전체 매개변수 미세 조정 방법입니다. LOMO를 지원하는 옵티마이저는 `"lomo"`와 `"adalomo"`입니다. 먼저 pypi에서 `lomo`를 설치하거나 소스에서 `git+https://github.com/OpenLMLab/LOMO.
```suggestion
이들은 모두 효율적인 전체 매개변수 미세 조정 방법으로 구성되어 있습니다. 이러한 옵티마이저들은 메모리 사용량을 줄이기 위해 그레이디언트 계산과 매개변수 업데이트를 하나의 단계로 융합합니다. LOMO에서 지원되는 옵티마이저는 `"lomo"`와 `"adalomo"`입니다. 먼저 pypi에서 `pip install lomo-optim`를 통해 `lomo`를 설치하거나, GitHub 소스에서 `pip install git+https://github.com/OpenLMLab/LOMO.git`로 설치하세요.
```
문장을 풀어서 이해하기 쉽게 바꾸어보았습니다. glossary 참고하여 gradient를 수정하고, 원문에서 일부 빠진 설치 커맨드도 추가해보았어요 ㅎㅎ

2024-08-03 16:05 UTC, nuatmochoi commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스는 [Accelerate](https://hf.co/docs/accelerate)로 구동되며, 이는 [FullyShardedDataParallel (FSDP)](https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/) 및 [DeepSpeed](h
```suggestion
```

2024-08-03 23:54 UTC, JinukHong commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스는 [Accelerate](https://hf.co/docs/accelerate)로 구동되며, 이는 [FullyShardedDataParallel (FSDP)](https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/) 및 [DeepSpeed](h
```suggestion
```

2024-08-05 14:00 UTC, ahnjj requested changes

2024-08-05 14:00 UTC, ahnjj commented on docs/source/ko/trainer.md
> +레이어별 최적화는 다소 실험적이며 DDP(분산 데이터 병렬)를 지원하지 않으므로, 1개의 GPU에서만 훈련 스크립트를 실행할 수 있습니다. 자세한 내용은 [이 문서를](https://github.com/jiaweizzhao/GaLore?tab=readme-ov-file#train-7b-model-with-a-single-gpu-with-24gb-memor
1개의 GPU -> 단일 GPU (single GPU)

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`]는 Transformers 라이브러리에 구현된 PyTorch 모델 훈련 및 평가 루프입니다. 훈련에 필요한 요소(모델, 토크나이저, 데이터셋, 평가 함수, 훈련 하이퍼파라미터 등)만 제공하면 [`Trainer`]가 필요한 나머지 작업을 처리합니다. 이를 통해 직접 훈련 루프를 작성하지 않고도 빠르게 훈련을 시작할 수 있습니다. 또한 [
제가 원문 확인해본 결과 [`Trainer`]는 넣어져있어서, 다시 확인해보겠습니다!

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`]는 Transformers 라이브러리에 구현된 PyTorch 모델 훈련 및 평가 루프입니다. 훈련에 필요한 요소(모델, 토크나이저, 데이터셋, 평가 함수, 훈련 하이퍼파라미터 등)만 제공하면 [`Trainer`]가 필요한 나머지 작업을 처리합니다. 이를 통해 직접 훈련 루프를 작성하지 않고도 빠르게 훈련을 시작할 수 있습니다. 또한 [
저도 이게 많이 고민되는데, "반복적인 훈련"이나 "순환하는 훈련"도 나쁘지 않을거 같아요. 이렇게 수정해볼게요!
```suggestion
[`Trainer`]는 Transformers 라이브러리에 구현된 PyTorch 모델을 반복하여 훈련 및 평가 과정입니다. 훈련에 필요한 요소(모델, 토크나이저, 데이터셋, 평가 함수, 훈련 하이퍼파라미터 등)만 제공하면 [`Trainer`]가 필요한 나머지 작업을 처리합니다. 이를 통해 직접 훈련 루프를 작성하지 않고도 빠르게 훈련을 시작할 수 있습니다. 또한 [`Trainer`]는 강력한 맞춤 설정과 다양한 훈련 옵션을 제공하여 사용자 맞춤 훈련이 가능합니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`]는 기본적인 훈련 루프에 포함된 모든 코드를 포함합니다:
```suggestion
[`Trainer`]는 기본적인 훈련 루프에 필요한 모든 코드를 포함하고 있습니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스는 이 과정에 필요한 모든 코드를 추상화하여, PyTorch와 훈련에 익숙하지 않거나 막 시작한 경우에도 훈련이 가능합니다. 훈련에 필요한 모델과 데이터셋 같은 필수 구성 요소만 제공하면, [Trainer] 클래스가 나머지를 처리합니다.
```suggestion
[`Trainer`] 클래스는 PyTorch와 훈련에 익숙하지 않거나 막 시작한 경우에도 훈련이 가능하도록 필요한 모든 코드를 추상화하였습니다. 훈련에 필요한 모델과 데이터셋 같은 필수 구성 요소만 제공하면, [Trainer] 클래스가 나머지를 처리합니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +## Trainer 맞춤 설정 [[customize-the-trainer]]
```suggestion
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스 외에도 번역이나 요약과 같은 시퀀스-투-시퀀스 작업을 위한 [`Seq2SeqTrainer`] 클래스도 Transformers에서 제공합니다. 또한 [TRL](https://hf.co/docs/trl) 라이브러리에서 [`Trainer`] 클래스를 래핑하여 Llama-2 및 Mistral과 같은 언어 모델을 자동 회귀 기법으로 훈
```suggestion
Transformers는 [`Trainer`] 클래스 외에도 번역이나 요약과 같은 시퀀스-투-시퀀스 작업을 위한 [`Seq2SeqTrainer`] 클래스도 제공합니다. 또한 [TRL](https://hf.co/docs/trl) 라이브러리에는 [`Trainer`] 클래스를 래핑하여 Llama-2 및 Mistral과 같은 언어 모델을 자동 회귀 기법으로 훈련하는 데 최적화된 [`~trl.SFTTrainer`] 클래스 입니다. [`~trl.SFTTrainer`]는 시퀀스 패킹, LoRA, 양자화 및 DeepSpeed와 같은 기능을 지원하여 크기 상관없이 모델 효율적으로 확장할 수 있습니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`]는 기본적인 훈련 루프에 포함된 모든 코드를 포함합니다:
```suggestion
[`Trainer`]는 기본적인 훈련 루프에 필요한 모든 코드를 포함하고 있습니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`] 클래스는 이 과정에 필요한 모든 코드를 추상화하여, PyTorch와 훈련에 익숙하지 않거나 막 시작한 경우에도 훈련이 가능합니다. 훈련에 필요한 모델과 데이터셋 같은 필수 구성 요소만 제공하면, [Trainer] 클래스가 나머지를 처리합니다.
```suggestion
[`Trainer`] 클래스는 PyTorch와 훈련에 익숙하지 않거나 막 시작한 경우에도 훈련이 가능하도록 필요한 모든 코드를 추상화하였습니다. 훈련에 필요한 모델과 데이터셋 같은 필수 구성 요소만 제공하면, [Trainer] 클래스가 나머지를 처리합니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +체크포인트에서 훈련을 재개할 때, [`Trainer`]는 체크포인트가 저장될 때와 동일한 Python, NumPy 및 PyTorch RNG 상태를 유지하려고 합니다. 하지만 PyTorch는 다양한 일관된 결과를 보장되지 않게 기본 설정이 되어 있기 때문에, RNG 상태가 동일할 것이라고 보장할 수는 없습니다. 따라서, 일관된 결과를 보장 되도록 활성화하려
```suggestion
체크포인트에서 훈련을 재개할 때, [`Trainer`]는 체크포인트가 저장될 때와 동일한 Python, NumPy 및 PyTorch RNG 상태를 유지하려고 합니다. 하지만 PyTorch는 기본 설정으로 '일관된 결과를 보장하지 않음'으로 많이 되어있기 때문에, RNG 상태가 동일할 것이라고 보장할 수 없습니다. 따라서, 일관된 결과가 보장되도록 활성화 하려면, [랜덤성 제어](https://pytorch.org/docs/stable/notes/randomness#controlling-sources-of-randomness) 가이드를 참고하여 훈련을 완전히 일관된 결과를 보장 받도록 만들기 위해 활성화할 수 있는 항목을 확인하세요. 다만, 특정 설정을 결정적으로 만들면 훈련이 느려질 수 있습니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +* [`~Trainer.log`]는 훈련을 모니터링하는 다양한 객체에 대한 정보를 로그합니다.
```suggestion
* [`~Trainer.log`]는 훈련을 모니터링하는 다양한 객체에 대한 정보를 로그로 남깁니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +        # 서로 다른 가중치로 3개의 레이블에 대한 사용자 정의 손실을 계산
```suggestion
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`]를 맞춤 설정하는 또 다른 방법은 [콜백](callbacks)을 사용하는 것입니다. 콜백은 훈련 루프의 상태를 검사한 후 상태에 따라 일부 작업(조기 종료, 결과 로그 등)을 실행합니다. 즉, 콜백은 사용자 정의 손실 함수와 같은 것을 구현하는 데 사용할 수 없으며, 이를 위해서는 [`~Trainer.compute_loss`] 메소드를
```suggestion
[`Trainer`]를 맞춤 설정하는 또 다른 방법은 [콜백](callbacks)을 사용하는 것입니다. 콜백은 훈련 루프에서 *변화를 주지 않습니다*. 훈련 루프의 상태를 검사한 후 상태에 따라 일부 작업(조기 종료, 결과 로그 등)을 실행합니다. 즉, 콜백은 사용자 정의 손실 함수와 같은 것을 구현하는 데 사용할 수 없으며, 이를 위해서는 [`~Trainer.compute_loss`] 메소드를 서브클래스화하고 오버라이드해야 합니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`]는 [`Trainer.__init__`] 메소드에서 각 노드에 대해 로그 레벨을 별도로 설정하므로, [`Trainer`] 객체를 생성하기 전에 다른 Transformers 기능을 사용할 경우 이를 미리 설정하는 것이 좋습니다.
```suggestion
[`Trainer`]는 [`Trainer.__init__`] 메소드에서 각 노드에 대해 로그 레벨을 별도로 설정하므로, 다른 Transformers 기능을 사용할 경우 [`Trainer`] 객체를 생성하기 전에 이를 미리 설정하는 것이 좋습니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +`log_level`과 `log_level_replica`를 다양한 조합으로 사용하여, 각 노드에서 기록되는 내용을 구성하세요.
```suggestion
각 노드에서 기록될 내용을 구성하기 위해 `log_level`과 `log_level_replica`를 다양한 조합으로 사용해보세요.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +NEFTune은 예상치 못한 동작을 피하기 위해 훈련 후에 처음 임베딩 레이어로 복원합니다.
```suggestion
NEFTune은 예상치 못한 동작을 피할 목적으로 처음 임베딩 레이어로 복원하기 위해 훈련 후 비활성화 됩니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +현재 Linear 레이어만 GaLore 레이어로 간주되며, 저계수 분해를 사용하여 훈련되고 나머지 레이어는 기존 방식으로 최적화됩니다.
```suggestion
현재 GaLore 레이어로 간주되는 Linear 레이어만 훈련 할수 있으며, 저계수 분해를 사용하여 훈련되고 나머지 레이어는 기존 방식으로 최적화됩니다.
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +레이어별 최적화는 다소 실험적이며 DDP(분산 데이터 병렬)를 지원하지 않으므로, 1개의 GPU에서만 훈련 스크립트를 실행할 수 있습니다. 자세한 내용은 [이 문서를](https://github.com/jiaweizzhao/GaLore?tab=readme-ov-file#train-7b-model-with-a-single-gpu-with-24gb-memor
```suggestion
레이어별 최적화는 다소 실험적이며 DDP(분산 데이터 병렬)를 지원하지 않으므로, 단일 GPU에서만 훈련 스크립트를 실행할 수 있습니다. 자세한 내용은 [이 문서를](https://github.com/jiaweizzhao/GaLore?tab=readme-ov-file#train-7b-model-with-a-single-gpu-with-24gb-memory)을 참조하세요. gradient clipping, DeepSpeed 등 다른 기능은 기본적으로 지원되지 않을 수 있습니다. 이러한 문제가 발생하면 [GitHub에 이슈를 올려주세요](https://github.com/huggingface/transformers/issues).
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +다음은 IMDB 데이터셋에서 [google/gemma-2b](https://huggingface.co/google/gemma-2b)를 완 정밀도로 미세 조정하는 간단한 스크립트입니다:
```suggestion
다음은 IMDB 데이터셋에서 [google/gemma-2b](https://huggingface.co/google/gemma-2b)를 최대 정밀도로 미세 조정하는 간단한 스크립트입니다:
```

2024-08-06 13:56 UTC, cjfghk5697 commented on docs/source/ko/trainer.md
> +[`Trainer`]와 Accelerate를 사용하려면 [`accelerate.config`](https://huggingface.co/docs/accelerate/package_reference/cli#accelerate-config) 명령을 실행하여 훈련 환경을 설정하세요. 이 명령은 훈련 스크립트를 실행할 때 사용할 `config_file.yaml`
```suggestion
[`Trainer`]와 Accelerate를 사용하려면 [`accelerate.config`](https://huggingface.co/docs/accelerate/package_reference/cli#accelerate-config) 명령을 실행하여 훈련 환경을 설정하세요. 이 명령은 훈련 스크립트를 실행할 때 사용할 `config_file.yaml`을 생성합니다. 예를 들어, 다음 예시는 설정할 수 있는 일부 구성 예입니다.
```

2024-08-07 19:01 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_32260). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-07 21:42 UTC, stevhliu approved these changes
Thanks for translating this doc! Can you run `make style` and resolve the conflict? Then we'll be good to merge 🤗

2024-08-08 16:38 UTC, merged