🌐 [i18n-KO] Translated `quantization/quanto.md` to Korean
huggingface/transformers pull request #32281
Opened 2024-07-29 06:20 UTC by fabxoe

# What does this PR do?

Translated the `quantization/quanto.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@win2dvp21, @enchantee00, @fabxoe, @1kmmk1, @junejae

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-08-01 12:18 UTC, junejae commented on docs/source/ko/quantization/quanto.md
> +[🤗 Quanto](https://github.com/huggingface/optimum-quanto) 라이브러리는 다목적의 파이토치 양자화 툴킷입니다. 양자화 방법으로 선형 양자화를 사용하고 다음과 같은 몇 가지 고유한 기능을 제공합니다:
```suggestion
[🤗 Quanto](https://github.com/huggingface/optimum-quanto) 라이브러리는 다목적 파이토치 양자화 툴킷입니다. 양자화 방법으로 선형 양자화를 사용하고 다음과 같은 몇 가지 고유한 기능을 제공합니다:
```

2024-08-01 12:18 UTC, junejae commented on docs/source/ko/quantization/quanto.md
> +시작하기 전에 다음 라이브러리가 설치되어 있는지 확인하세요:
```suggestion
시작하기 전에 다음 라이브러리가 설치되어 있는지 확인해 주세요:
```

2024-08-03 07:31 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +이 라이브러리는 대부분의 PTQ 최적화 알고리즘과 호환될 만큼 충분히 유연합니다. 앞으로의 계획은 가장 인기 있는 알고리즘(AWQ, Smoothquant)을 가능한 한 매끄럽게 통합하는 것입니다.
```suggestion
이 라이브러리는 대부분의 PTQ 최적화 알고리즘과 호환될 만큼 충분히 유연합니다. 앞으로의 계획은 가장 인기 있는 알고리즘(AWQ, Smoothquant)을 최대한 매끄럽게 통합하는 것입니다.
```

2024-08-03 07:36 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +- 모달리티 독립성 (e.g CV,LLM)
```suggestion
- 모달리티 비종속성(e.g CV,LLM)
```

2024-08-03 07:36 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +- 장치 독립성 (e.g CUDA,MPS,CPU)
```suggestion
- 장치 비종속성 (e.g CUDA,MPS,CPU)
```

2024-08-03 07:36 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +- 특정 장치에 대한 사용자 지정 커널의 쉬운 추가
```suggestion
- 특정 장치에 대한 사용자 정의 커널의 쉬운 추가
```

2024-08-03 07:41 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +Quanto 라이브러리는 양자화를 위해 선형 양자화 알고리즘을 사용합니다. 비록 기본적인 양자화 기술이지만, 좋은 결과를 얻는데 아주 큰 도움이 됩니다! 바로 아래에 있는 벤치마크(llama-2-7b의 perplexity 지표)를 확인해 보세요. 더 많은 벤치마크는 [여기](https://github.com/huggingface/quanto/tree/ma
```suggestion
Quanto 라이브러리는 양자화를 위해 선형 양자화 알고리즘을 사용합니다. 비록 기본적인 양자화 기술이지만, 좋은 결과를 얻는데 아주 큰 도움이 됩니다! 바로 아래에 있는 벤치마크(llama-2-7b의 펄플렉서티 지표)를 확인해 보세요. 더 많은 벤치마크는 [여기](https://github.com/huggingface/quanto/tree/main/bench/generation) 에서 찾을 수 있습니다.
```

2024-08-03 08:14 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +허깅페이스의 transformers 라이브러리는 개발자 편의를 위해 quanto의 인터페이스를 일부 통합하여 지원하고 있으며, 이 방식으로는 가중치 양자화만 지원합니다. 활성화 양자화, 캘리브레이션, QAT 같은 더 복잡한 기능을 수행하기 위해서는 [quanto](https://github.com/huggingface/optimum-quanto) 라이브러
> The integration with transformers only supports weights quantization. For the more complex use case such as activation quantization, calibration and quantization aware training, you should use [quanto](https://github.com/huggingface/quanto) library instead. 

해당 부분 번역과 약간 다른 것 같아서요. 제가 보는 문서 버전이 달라서 그런건걸까요?([source](https://huggingface.co/docs/transformers/main/en/quantization/quanto))

2024-08-03 08:22 UTC, fabxoe commented on docs/source/ko/quantization/quanto.md
> +허깅페이스의 transformers 라이브러리는 개발자 편의를 위해 quanto의 인터페이스를 일부 통합하여 지원하고 있으며, 이 방식으로는 가중치 양자화만 지원합니다. 활성화 양자화, 캘리브레이션, QAT 같은 더 복잡한 기능을 수행하기 위해서는 [quanto](https://github.com/huggingface/optimum-quanto) 라이브러
integration 이라는 단어가 한글로는 '통합'으로 번역하기 좋은데, '통합'이 영어에서 주는 software integration의 느낌처럼 전혀 익숙한 느낌을 주지 않아서 한국 개발자들에게 갑작스럽지 않고 이해 시킬 수 있을 문장을 추가했어요.
인터페이스 통합으로 번역해서 제공해도 되는데 1:1의 느낌이 강해서 그보다는 새 문장을 추가 했습니다.

2024-08-03 09:01 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +허깅페이스의 transformers 라이브러리는 개발자 편의를 위해 quanto의 인터페이스를 일부 통합하여 지원하고 있으며, 이 방식으로는 가중치 양자화만 지원합니다. 활성화 양자화, 캘리브레이션, QAT 같은 더 복잡한 기능을 수행하기 위해서는 [quanto](https://github.com/huggingface/optimum-quanto) 라이브러
> integration 이라는 단어가 한글로는 '통합'으로 번역하기 좋은데, '통합'이 영어에서 주는 software integration의 느낌처럼 전혀 익숙한 느낌을 주지 않아서 한국 개발자들에게 갑작스럽지 않고 이해 시킬 수 있을 문장을 추가했어요. 인터페이스 통합으로 번역해서 제공해도 되는데 1:1의 느낌이 강해서 그보다는 새 문장을 추가 했습니다.

그런 깊은 뜻이 있으셨군요!
읽는데는 전혀 문제가 없는 깔끔한 문장인 것 같습니다ㅎ

2024-08-03 14:06 UTC, win2dvp21 requested changes

2024-08-03 14:06 UTC, win2dvp21 commented on docs/source/ko/quantization/quanto.md
> +[🤗 Quanto](https://github.com/huggingface/optimum-quanto) 라이브러리는 다목적의 파이토치 양자화 툴킷입니다. 양자화 방법으로 선형 양자화를 사용하고 다음과 같은 몇 가지 고유한 기능을 제공합니다:
```suggestion
[🤗 Quanto](https://github.com/huggingface/optimum-quanto) 라이브러리는 다목적 파이토치 양자화 툴킷입니다. 이 라이브러리에서 사용되는 양자화 방법은 선형 양자화입니다. Quanto는 다음과 같은 여러 가지 기능을 제공합니다:
```

2024-08-03 14:06 UTC, win2dvp21 commented on docs/source/ko/quantization/quanto.md
> +- 모달리티 독립성 (e.g CV,LLM)
```suggestion
- 모달리티에 구애받지 않음 (e.g CV,LLM)
```

2024-08-03 14:06 UTC, win2dvp21 commented on docs/source/ko/quantization/quanto.md
> +- 장치 독립성 (e.g CUDA,MPS,CPU)
```suggestion
- 장치에 구애받지 않음 (e.g CUDA,MPS,CPU)
```

2024-08-03 14:06 UTC, win2dvp21 commented on docs/source/ko/quantization/quanto.md
> +- 특정 장치에 대한 사용자 지정 커널의 쉬운 추가
```suggestion
- 특정 장치에 대한 사용자 정의 커널을 쉽게 추가 가능
```

2024-08-03 14:18 UTC, junejae reviewed
독자를 고려한 훌륭한 번역에 감명받았어요! 너무 좋습니다!

2024-08-03 14:18 UTC, junejae commented on docs/source/ko/quantization/quanto.md
> +이제 [`~PreTrainedModel.from_pretrained`] 메소드에 [`QuantoConfig`] 객체를 전달하여 모델을 양자화할 수 있습니다. 이 방식은 `torch.nn.Linear` 레이어를 포함하는 한해서, 어떤 모달리티의 어떤 모델에 대해서든 잘 작동합니다.
```suggestion
이제 [`~PreTrainedModel.from_pretrained`] 메소드에 [`QuantoConfig`] 객체를 전달하여 모델을 양자화할 수 있습니다. 이 방식은 `torch.nn.Linear` 레이어를 포함하는 모든 모달리티의 모든 모델에서 잘 작동합니다.
```
문장 간소화로 가독성을 늘려봤습니다.

2024-08-03 15:24 UTC, fabxoe commented on docs/source/ko/quantization/quanto.md
> +Quanto 라이브러리는 양자화를 위해 선형 양자화 알고리즘을 사용합니다. 비록 기본적인 양자화 기술이지만, 좋은 결과를 얻는데 아주 큰 도움이 됩니다! 바로 아래에 있는 벤치마크(llama-2-7b의 perplexity 지표)를 확인해 보세요. 더 많은 벤치마크는 [여기](https://github.com/huggingface/quanto/tree/ma
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/ae8c94e9-ce6d-4786-b11c-65be8756397b">
피드백 감사합니다! glossary를 따르면 펄플렉서티 군요. 링크한 자료로 가서 참고할 지표 이름을 알려주는 것이기도해서 편의를 위해 '펄플렉서티(perplexity)'로 병기 하는 것도 좋겠다고 생각했는데 이미 괄호를 사용해서 안되겠네요. 고쳐주신 그대로 변경하겠습니다!

2024-08-03 15:30 UTC, fabxoe commented on docs/source/ko/quantization/quanto.md
> +참고로, transformers에서는 아직 직렬화가 지원되지 않지만 곧 지원될 예정입니다!
두 문장이 서로 연관성이 없는 별개의 정보를 전달하기 때문에 이것은 따로 두는 것이 좋아 보입니다.

2024-08-03 15:34 UTC, fabxoe commented on docs/source/ko/quantization/quanto.md
> +- 특정 장치에 대한 사용자 지정 커널의 쉬운 추가
감사합니다. 제가 nmt 적용 후에 놓쳤네요!

2024-08-03 15:43 UTC, fabxoe commented on docs/source/ko/quantization/quanto.md
> +- 장치 독립성 (e.g CUDA,MPS,CPU)
리뷰 감사합니다. 저는 줄이거나 요약해서 전달하는 bullet point 표현에 agnostic 이란 단어가 등장해서, 
앞으로 일관된 한글 단어를 정해주는 주는 방법이 있다고만 생각했었어요.
그런데 구애받지 않음이라고 풀어서 전달하는 것이 한국 개발자들에게 전달력이 아주 더 좋아 보입니다.

2024-08-05 12:05 UTC, 1kmmk1 commented on docs/source/ko/quantization/quanto.md
> +- 장치 독립성 (e.g CUDA,MPS,CPU)
저는 agnostic을 '비종속성'으로 번역하는걸 제안드렸었는데, '구애받지 않음'이 조금 더 직관적으로 받아들일 수 있을 것 같아요!👍

2024-08-07 02:30 UTC, fabxoe commented on docs/source/ko/quantization/quanto.md
> +- 장치 독립성 (e.g CUDA,MPS,CPU)
비종속성은 독립성과 어느정도 같은 레벨의 번역으로 느껴졌었어요.
하지만 민기님 리뷰 감사드려요! 일단 그러면 의견 반영해서 적용하겠습니다.

2024-08-07 16:09 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_32281). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-07 16:52 UTC, stevhliu approved these changes
Nice work, thanks for contributing! 🤗

2024-08-07 16:52 UTC, merged