🌐 [i18n-KO] Translated `llm_optims.md` to Korean
huggingface/transformers pull request #32325
Opened 2024-07-30 13:32 UTC by yijun-lee

# What does this PR do?

Translated the `llm_optims.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@jun048098, @yijun-lee, @mreraser, @shinhyunji36, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-08-04 16:54 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +기본적인 추론은 느립니다. LLM이 다음 토큰을 생성하기 위해 반복적으로 호출되어야 하기 때문입니다. 생성이 진행됨에 따라 입력 시퀀스가 길어져 처리 시간이 점점 길어집니다. 또한, LLM은 수십억 개의 매개변수를 가지고 있어 모든 가중치를 메모리에 저장하고 처리하는 데 어려움이 있습니다.
```suggestion
기본적인 추론은 느립니다, 왜냐하면 LLM이 다음 토큰을 생성하기 위해 반복적으로 호출되어야 하기 때문입니다. 생성이 진행됨에 따라 입력 시퀀스가 길어져 처리 시간이 점점 길어집니다. 또한, LLM은 수십억 개의 매개변수를 가지고 있어 모든 가중치를 메모리에 저장하고 처리하는 데 어려움이 있습니다.
```

원문을 고려하여 왜냐하면을 추가해보았습니다.

2024-08-04 16:56 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +이 가이드는 LLM 추론을 가속화하기 위해 Transformers에서 사용할 수 있는 최적화 기술을 사용하는 방법을 보여줍니다.
```suggestion
이 가이드는 LLM 추론을 가속하기 위해 Transformers에서 사용할 수 있는 최적화 기술을 사용하는 방법을 보여줍니다.
```

 '가속하다.'로 쓰면 충분한데 한자 접미사 '-화'를 붙여 '가속화하다.'나 '가속화시키다.'로 쓰는 것은 불필요한 것 같습니다.

2024-08-04 17:05 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +*정적 kv-cache*는 최대 값을 미리 할당하여 이 문제를 해결하여 torch.compile과 결합할 수 있게 합니다. 이를 통해 최대 4배의 속도 향상이 가능합니다.
```suggestion
*정적 kv-cache*는 최댓값을 미리 할당하여 이 문제를 해결하여 torch.compile과 결합할 수 있게 합니다. 이를 통해 최대 4배의 속도 향상이 가능합니다.
```
사이시옷 규정에 따라 최댓값이 올바른 한국어 표기라 고쳤습니다.
-> [참조](https://ko.dict.naver.com/#/correct/korean/info?seq=5020)

2024-08-04 17:09 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +내부적으로, 'generate'는 동일한 캐시 객체를 재사용하려고 시도하여 각 호출에서 다시 컴파일할 필요가 없도록 합니다. 그러나 배치 크기 또는 최대 출력 길이가 호출 간에 증가하면 캐시를 다시 초기화해야 하므로 새로 컴파일 해야합니다.
```suggestion
내부적으로, 'generate'는 동일한 캐시 객체를 재사용하려고 시도하여 각 호출에서 다시 컴파일할 필요가 없도록 합니다. 그러나 배치 크기 또는 최대 출력 길이가 호출 간에 증가하면 캐시를 다시 초기화해야 하므로 새로 컴파일해야 합니다.
```

[해당 문서](https://wikidocs.net/67213#google_vignette)를 참조하여 '해야 하다'가 적절한 띄어쓰기라 고쳤습니다.

2024-08-04 17:25 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +3. [torch.backends.cuda.sdp_kernel](https://pytorch.org/docs/master/generated/torch.nn.functional.scaled_dot_product_attention.html) 컨텍스트 관리자에서 `enable_math=True`를 설정하여 네이티브 PyTorch C++ 구현된 스케일된 dot
```suggestion
3. [torch.backends.cuda.sdp_kernel](https://pytorch.org/docs/master/generated/torch.nn.functional.scaled_dot_product_attention.html) 컨텍스트 관리자에서 `enable_math=True`를 설정하여 네이티브 PyTorch C++ 구현된 scaled dot product attention를 활성화하여 추론 속도를 더욱 높입니다.
```

원문에서 implementation of 'scaled dot product attention'이니 scaled를 굳이 스케일된이라고 표기하기 보다는, 위처럼 고치면 어떨까합니다.

2024-08-04 17:31 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +추정 샘플링 디코딩을 위해, 보조 모델 외에도 [`~GenerationMixin.generate`] 메서드에 `do_sample` 및 `temperature` 매개변수를 추가하십시오.
```suggestion
추정 샘플링 디코딩(speculative sampling decoding)을 위해, 보조 모델 외에도 [`~GenerationMixin.generate`] 메서드에 `do_sample` 및 `temperature` 매개변수를 추가하십시오.
```

이해를 위해 영어 원문을 같이 병기하면 어떨까 합니다.

2024-08-05 06:18 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +트랜스포머 모델의 알려진 문제는 셀프 어텐션 메커니즘이 입력 토큰 수와 함께 계산 및 메모리가 제곱으로 증가한다는 것입니다. 이 제한은 훨씬 더 긴 시퀀스를 처리하는 LLM에서는 더욱 커집니다. 이를 해결하기 위해 FlashAttention2 또는 PyTorch의 스케일된 점곱 어텐션를 사용해 보십시오. 이들은 더 메모리 효율적인 어텐션 구현으로 추론을
```suggestion
트랜스포머 모델의 알려진 문제는 셀프 어텐션 메커니즘이 입력 토큰 수와 함께 계산 및 메모리가 제곱으로 증가한다는 것입니다. 이 제한은 훨씬 더 긴 시퀀스를 처리하는 LLM에서는 더욱 커집니다. 이를 해결하기 위해 FlashAttention2 또는 PyTorch의 scaled dot product attention를 사용해 보십시오. 이들은 더 메모리 효율적인 어텐션 구현으로 추론을 가속화할 수 있습니다.
```

통일성을 위해 위의 표현을 그대로 작성하였습니다.

2024-08-06 02:38 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +### PyTorch 스케일된 점곱 어텐션 [[pytorch-scaled-dot-product-attention]]
```suggestion
### PyTorch 스케일된 점곱 어텐션(scaled dot product attention) [[pytorch-scaled-dot-product-attention]]
```

밑에서 `스케일된 점곱 어텐션` , `SDPA` 등 다양한 형태로 나오니 최소한 제목에 원 용어를 병기하면 어떨까 합니다.

2024-08-06 02:42 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +### PyTorch 스케일된 점곱 어텐션 [[pytorch-scaled-dot-product-attention]]
번역하느라 고생하셨습니다 😄

2024-08-06 08:49 UTC, jun048098 commented on docs/source/ko/llm_optims.md
> +*정적 kv-cache*는 최대 값을 미리 할당하여 이 문제를 해결하여 torch.compile과 결합할 수 있게 합니다. 이를 통해 최대 4배의 속도 향상이 가능합니다.
```suggestion
*정적 kv-cache*는 최대 값을 미리 할당하여 이 문제를 해결하여 torch.compile과 결합할 수 있게 합니다. 이를 통해 최대 4배의 속도 향상이 가능합니다. 속도 향상은 모델 크기(모델이 클수록 속도 향상이 더 작음) 및 하드웨어에 따라 달라질 수 있습니다.
```
원문 line29  Your speed up may vary depending on the model size (larger models have a smaller speed up) and hardware. 문장의 해석이 누락된 것 같습니다.

2024-08-06 11:03 UTC, jun048098 commented
원문의 내용이 새로운 commit으로 변경되었습니다.

2024-08-06 11:08 UTC, shinhyunji36 requested changes

2024-08-06 11:08 UTC, shinhyunji36 commented on docs/source/ko/llm_optims.md
> +자기 회귀의 또 다른 문제는 각 입력 토큰에 대해 순전파 중에 모델 가중치를 매번 로드해야 한다는 점입니다. 이는 수십억 개의 매개변수를 가진 LLM에는 느리고 번거롭습니다. 추정 디코딩은 더 작고 빠른 보조 모델을 사용하여 후보 토큰을 생성하고, 이를 큰 LLM이 단일 순전파에서 검증하여 이 속도 저하를 완화합니다. 검증된 토큰이 정확하다면, LLM은
```suggestion
자기 회귀의 또 다른 문제는 각 입력 토큰에 대해 순전파 중에 모델 가중치를 매번 로드해야 한다는 점입니다. 이는 수십억 개의 매개변수를 가진 LLM에는 느리고 번거롭습니다. 추정 디코딩은 더 작고 빠른 보조 모델을 사용하여 후보 토큰을 생성하고, 이를 큰 LLM이 단일 순전파에서 검증하여 이 속도 저하를 완화합니다. 검증된 토큰이 정확하다면, LLM은 이를 추가적인 연산 없이 획득하게 됩니다. 검증 순전파를 통해 LLM이 자체적으로 생성한 것과 동일한 출력이 생성되기 때문에 정확도가 저하되지 않습니다.
```

2024-08-06 11:08 UTC, shinhyunji36 commented on docs/source/ko/llm_optims.md
> +자기 회귀의 또 다른 문제는 각 입력 토큰에 대해 순전파 중에 모델 가중치를 매번 로드해야 한다는 점입니다. 이는 수십억 개의 매개변수를 가진 LLM에는 느리고 번거롭습니다. 추정 디코딩은 더 작고 빠른 보조 모델을 사용하여 후보 토큰을 생성하고, 이를 큰 LLM이 단일 순전파에서 검증하여 이 속도 저하를 완화합니다. 검증된 토큰이 정확하다면, LLM은
자체적으로 생성하는 것과 동일한 토큰을 연산없이 얻는다는 의미를 좀 더 강조해서 수정해봤습니다.

2024-08-06 11:09 UTC, shinhyunji36 commented
긴 문서인데, 번역하느라 고생 많으셨습니다! 😄 @yijun-lee

2024-08-06 16:17 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_32325). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-06 18:27 UTC, stevhliu reviewed
Thanks for translating this! 🤗

2024-08-06 18:27 UTC, stevhliu commented on docs/source/ko/llm_optims.md
> +이 예제에서는 [Gemma](https://hf.co/google/gemma-2b) 모델을 로드해 보겠습니다.
I think we're missing some content here about the 3 types of static kv usage.

2024-08-28 16:37 UTC, stevhliu reviewed
Fantastic, LGTM! Thanks for adding those additional sections!

@mreraser @shinhyunji36 would you mind reviewing these new sections?

2024-08-28 16:40 UTC, mreraser commented
> Fantastic, LGTM! Thanks for adding those additional sections!
> 
> @mreraser @shinhyunji36 would you mind reviewing these new sections?

Hello @stevhliu! Yes, I will review the newly added sections. Thank you 😄

2024-08-28 17:02 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +mport torch
```suggestion
import torch
```
typo fix

2024-08-28 17:09 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +1. 배치 크기가 변경되거나 호출 간 최대 출력 길이가 증가하면 캐시를 다시 초기화해야 하며, 이로 인해 새로운 컴파일이 발생합니다;
```suggestion
1. 배치 크기가 변경되거나 호출 간 최대 출력 길이가 증가하면 캐시를 다시 초기화해야 하며, 이로 인해 새로 컴파일을 해야 합니다;
```
조금 자연스러운 느낌으로 바꿔보았습니다.

2024-08-28 17:17 UTC, mreraser commented on docs/source/ko/llm_optims.md
> +3. 많은 경고와 예외가 억제됩니다. -- 먼저 비컴파일 형태로 테스트하는 것을 권장합니다;
```suggestion
3. 많은 경고와 예외가 억제됩니다. -- 먼저 컴파일 되지 않은 형태로 테스트하는 것을 권장합니다;
```
`비컴파일` 보다는 `컴파일 되지 않은`이 자연스러운 표현인 것 같아 작성합니다.

2024-08-29 01:58 UTC, mreraser approved these changes
LGTM 😄

2024-08-30 16:52 UTC, stevhliu approved these changes

2024-08-30 16:52 UTC, merged