🌐 [i18n-KO] Translated `eetq.md` to Korean
huggingface/transformers pull request #32352
Opened 2024-07-31 10:32 UTC by jun048098

# What does this PR do?

Translated the `eetq.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@jun048098, @yijun-lee, @mreraser, @shinhyunji36, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-08-03 12:50 UTC, junejae requested changes
@jun048098 
아직 OSSCA 팀원들에게 리뷰/검토되지 않은 PR입니다. PR의 상태를 Draft로 변경 부탁드립니다.

This PR has never been reviewed by OSSCA members, Please change your PR's status to Draft.

2024-08-04 02:58 UTC, heuristicwave commented on docs/source/ko/quantization/eetq.md
> +[EETQ](https://github.com/NetEase-FuXi/EETQ) 라이브러리는 NVIDIA GPU에 대해 int8 채널별(per-channel) weight-only quantization을 지원합니다. 고성능 GEMM 및 GEMV 커널은 FasterTransformer 및 TensorRT-LLM에서 가져왔습니다. 캘리브레이션 데이터셋이 필
```suggestion
[EETQ](https://github.com/NetEase-FuXi/EETQ) 라이브러리는 NVIDIA GPU에 대해 int8 채널별(per-channel) 가중치 전용 양자화(weight-only quantization)를 지원합니다.
고성능 GEMM 및 GEMV 커널은 FasterTransformer 및 TensorRT-LLM에서 가져왔습니다. 보정(calibration) 데이터셋이 필요 없으며, 모델을 사전에 양자화할 필요도 없습니다. 또한, 채널별 양자화(per-channel quantization) 덕분에 정확도 저하가 미미합니다.
```
개행과 calibration datasets에 대한 의견을 남겨두었습니다.

2024-08-04 03:03 UTC, heuristicwave commented
@jun048098 Before reviewing 체크리스트도 체크 부탁드려요~

2024-08-04 09:53 UTC, mreraser commented on docs/source/ko/quantization/eetq.md
> +[EETQ 릴리스 페이지](https://github.com/NetEase-FuXi/EETQ/releases)에서 EETQ를 설치했는지 확인하십시오.
```suggestion
[릴리스 페이지](https://github.com/NetEase-FuXi/EETQ/releases)에서 eetq를 설치했는지 확인하세요.
```
사소한 차이이긴 하나 원문을 그대로 번역하는 것이 좋지 않을까 하여 제안드립니다.

2024-08-04 10:06 UTC, mreraser commented on docs/source/ko/quantization/eetq.md
> +[EETQ 릴리스 페이지](https://github.com/NetEase-FuXi/EETQ/releases)에서 EETQ를 설치했는지 확인하십시오.
이외의 특별한 리뷰 사항은 없는 것 같습니다! 고생하셨습니다 😄 @jun048098

2024-08-06 09:06 UTC, jun048098 commented on docs/source/ko/quantization/eetq.md
> +[EETQ](https://github.com/NetEase-FuXi/EETQ) 라이브러리는 NVIDIA GPU에 대해 int8 채널별(per-channel) weight-only quantization을 지원합니다. 고성능 GEMM 및 GEMV 커널은 FasterTransformer 및 TensorRT-LLM에서 가져왔습니다. 캘리브레이션 데이터셋이 필
weight-only quantization 은 intel에서 제공하는 extension이라 번역이 적절한지 고민하고 있었습니다

https://www.intel.com/content/www/us/en/developer/articles/technical/weight-only-quantization-in-llm-inference.html

2024-08-06 09:57 UTC, shinhyunji36 reviewed
다른 분들이 리뷰해주신 부분 외에 특별한 리뷰 사항을 발견하지 못했습니다! 고생 하셨습니다 😃

2024-08-06 11:01 UTC, jun048098 commented on docs/source/ko/quantization/eetq.md
> +[EETQ](https://github.com/NetEase-FuXi/EETQ) 라이브러리는 NVIDIA GPU에 대해 int8 채널별(per-channel) weight-only quantization을 지원합니다. 고성능 GEMM 및 GEMV 커널은 FasterTransformer 및 TensorRT-LLM에서 가져왔습니다. 캘리브레이션 데이터셋이 필
```suggestion
[EETQ](https://github.com/NetEase-FuXi/EETQ) 라이브러리는 NVIDIA GPU에 대해 int8 채널별(per-channel) weight-only quantization을 지원합니다. 고성능 GEMM 및 GEMV 커널은 FasterTransformer 및 TensorRT-LLM에서 가져왔습니다. 교정(calibration) 데이터셋이 필요 없으며, 모델을 사전에 양자화할 필요도 없습니다. 또한, 채널별 양자화(per-channel quantization) 덕분에 정확도 저하가 미미합니다.
```

2024-08-06 11:10 UTC, yijun-lee requested changes
이외에는 딱히 수정할 곳이 없어보입니다! 수고하셨습니다.

2024-08-06 11:10 UTC, yijun-lee commented on docs/source/ko/quantization/eetq.md
> +
22, 26, 28, 37번 라인에 원문과 다른 개행이 있는 것 같습니다.

2024-08-06 11:10 UTC, yijun-lee commented on docs/source/ko/quantization/eetq.md
> +
22, 26, 28, 37번 라인에 원문과 다른 개행이 있는 것 같습니다.

2024-08-06 11:10 UTC, yijun-lee commented on docs/source/ko/quantization/eetq.md
> +
22, 26, 28, 37번 라인에 원문과 다른 개행이 있는 것 같습니다.

2024-08-06 11:10 UTC, yijun-lee commented on docs/source/ko/quantization/eetq.md
> +
```suggestion
# suggestion: remove this line
```
22, 26, 28, 37번 라인에 원문과 다른 개행이 있는 것 같습니다.

2024-08-06 12:50 UTC, jun048098 reviewed
개행 제거

2024-08-06 12:50 UTC, jun048098 commented on docs/source/ko/quantization/eetq.md
> +
```suggestion
```

2024-08-06 12:50 UTC, jun048098 commented on docs/source/ko/quantization/eetq.md
> +
```suggestion
```

2024-08-06 12:50 UTC, jun048098 commented on docs/source/ko/quantization/eetq.md
> +
```suggestion
```

2024-08-06 12:50 UTC, jun048098 commented on docs/source/ko/quantization/eetq.md
> +
```suggestion
```

2024-08-07 16:14 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_32352). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-07 16:58 UTC, stevhliu approved these changes
Nice job! Once we resolve the conflict, we can merge 🤗

2024-08-08 16:39 UTC, merged