🌐 [i18n-KO] Translated `bitsandbytes.md` to Korean
huggingface/transformers pull request #32408
Opened 2024-08-04 07:19 UTC by SeungAhSon

<!— PR의 제목은 "🌐 [i18n-KO] Translated `<your_file>.md` to Korean" 으로 부탁드립니다 —>
# What does this PR do?

Translated the `<your_file>.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@SeungAhSon, @Jwaminju, @thsamajiki, @4N3MONE, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-08-04 07:37 UTC, thsamajiki commented on docs/source/ko/quantization/bitsandbytes.md
> +중첩 양자화는 추가적인 성능 손실 없이 추가적인 메모리를 절약할 수 있는 기술입니다. 이 기능은 이미 양자화된 가중치의 2차 양자화를 수행하여 매개변수당 추가로 0.4비트를 절약합니다. 예를 들어, 중첩 양자화를 통해 16GB NVIDIA T4 GPU에서 시퀀스 길이 1024, 배치 크기 1, 그라디언트 누적 4단계를 사용하여 [Llama-13b](htt
@SeungAhSon 안녕하세요.
Glossary 가이드에 따라 gradient는 그라디언트 -> 그레이디언트로 번역하는게 적절한 것으로 생각합니다!

2024-08-04 14:42 UTC, junejae requested changes
아직 OSSCA 팀원들에게 충분히 리뷰/검토되지 않은 PR입니다. PR의 상태를 Draft로 변경 부탁드립니다.

This PR hasn't been sufficiently reviewed by OSSCA members, Please change your PR's status to Draft.

2024-08-05 00:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +[bitsandbytes](https://github.com/TimDettmers/bitsandbytes)는 모델을 8비트 및 4비트로 양자화하는 가장 쉬운 방법입니다. 8비트 양자화는 fp16에서 이상치를 제외한 값을 int8로 변환한 후, 이상치 값을 fp16으로 다시 변환하고 이들을 합산하여 fp16으로 가중치를 반환합니다. 이렇게 하면 이상치 값이
```suggestion
[bitsandbytes](https://github.com/TimDettmers/bitsandbytes)는 모델을 8비트 및 4비트로 양자화하는 가장 쉬운 방법입니다. 8비트 양자화는 fp16의 이상치와 int8의 비이상치를 곱한 후, 비이상치 값을 fp16으로 다시 변환하고, 이들을 합산하여 fp16으로 가중치를 반환합니다. 이렇게 하면 이상치 값이 모델 성능에 미치는 저하 효과를 줄일 수 있습니다. 4비트 양자화는 모델을 더욱 압축하며, [QLoRA](https://hf.co/papers/2305.14314)와 함께 사용하여 양자화된 대규모 언어 모델을 미세 조정하는 데 흔히 사용됩니다.
```
1. 원문의 multiplies 의미가 더 담기도록 수정해보았습니다.
> multiplies outliers in fp16 with non-outliers in int8
2. LLM은 glossary에 따르면 대규모 언어 모델로 번역하는 것 같습니다!

2024-08-05 00:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +이제 `BitsAndBytesConfig`를 [`~PreTrainedModel.from_pretrained`] 메서드에 전달하여 모델을 양자화할 수 있습니다. 이는 Accelerate와 함께 로드할 수 있고 `torch.nn.Linear` 레이어가 포함된 모든 모델에서 작동합니다.
```suggestion
이제 `BitsAndBytesConfig`를 [`~PreTrainedModel.from_pretrained`] 메소드에 전달하여 모델을 양자화할 수 있습니다. 이는 Accelerate 가져오기를 지원하고 `torch.nn.Linear` 레이어가 포함된 모든 모델에서 작동합니다.
```

1. Glossary에서는 method는 메소드라고 번역되어있었네요!
2. Accelerate은 논의중인 용어인 것 같네요! 
3. load는 gloassary에서 가져오다로 번역되어 있어서 문장을 수정해보았습니다.

2024-08-05 00:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +모델을 8비트로 양자화하면 메모리 사용량이 절반으로 줄어들며, 대형 모델의 경우  `device_map="auto"`를 설정하여 사용 가능한 GPU를 효율적으로 활용할 수 있습니다:
```suggestion
모델을 8비트로 양자화하면 메모리 사용량이 절반으로 줄어들며, 대규모 모델의 경우  `device_map="auto"`를 설정하여 사용 가능한 GPU를 효율적으로 활용할 수 있습니다:
```

llm을 대규모 언어 모델로 번역하는 걸 보면, large도 대규모로 통일하면 어떨까 싶습니다.

2024-08-05 00:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +모델을 8비트로 양자화하면 메모리 사용량이 절반으로 줄어들며, 대형 모델의 경우  `device_map="auto"`를 설정하여 사용 가능한 GPU를 효율적으로 활용할 수 있습니다:
```suggestion
모델을 8비트로 양자화하면 메모리 사용량이 절반으로 줄어들며, 대규모 모델의 경우  사용 가능한 GPU를 효율적으로 활용하려면 `device_map="auto"`를 설정하세요. 
```
원문에서 set ~ 으로 시작하는 것이 명령형으로 번역되는 것 같아서, 수정해보았습니다.
> set device_map="auto" to efficiently use the GPUs available:

이 부분은 참고만 해주세요!

2024-08-05 00:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +기본적으로 `torch.nn.LayerNorm`과 같은 다른 모듈은 `torch.float16`으로 변환됩니다. 원하면 `torch_dtype` 매개변수로 이 모듈의 데이터 유형을 변경할 수 있습니다:
```suggestion
기본적으로 `torch.nn.LayerNorm`과 같은 다른 모듈은 `torch.float16`으로 변환됩니다. 원한다면 `torch_dtype` 매개변수로 이들 모듈의 데이터 유형을 변경할 수 있습니다:
```
1. By defualt는 논의중인 glossary 용어네요! '기본값으로' 라고도 해석될 수 있을 것 같네요!
2. '원한다면'이 조금 매끄러워 보여서 제안드립니다.
3. 원문의 these models 복수형을 살려보았습니다.

2024-08-05 00:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +모델이 8비트로 양자화되면 최신 버전의 Transformers와 bitsandbytes를 사용하지 않는 한 양자화된 가중치를 Hub에 푸시할 수 없습니다. 최신 버전을 사용하는 경우, [`~PreTrainedModel.push_to_hub`] 방법을 사용하여 8비트 모델을 Hub에 푸시할 수 있습니다. 양자화 구성 파일(config.json)이 먼저 푸시
```suggestion
모델이 8비트로 양자화되면 최신 버전의 Transformers와 bitsandbytes를 사용하지 않는 한 양자화된 가중치를 Hub에 푸시할 수 없습니다. 최신 버전을 사용하는 경우, [`~PreTrainedModel.push_to_hub`] 메소드를 사용하여 8비트 모델을 Hub에 푸시할 수 있습니다. 양자화 구성 파일(config.json)이 먼저 푸시되고, 그 다음 양자화된 모델 가중치가 푸시됩니다.
```
glossary에 method는 메소드라고 번역되어 있네요!

2024-08-05 00:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +모델이 8비트로 양자화되면 최신 버전의 Transformers와 bitsandbytes를 사용하지 않는 한 양자화된 가중치를 Hub에 푸시할 수 없습니다. 최신 버전을 사용하는 경우, [`~PreTrainedModel.push_to_hub`] 방법을 사용하여 8비트 모델을 Hub에 푸시할 수 있습니다. 양자화 구성 파일(config.json)이 먼저 푸시
```suggestion
모델이 8비트로 양자화되면 최신 버전의 Transformers와 bitsandbytes를 사용하지 않는 한 양자화된 가중치를 Hub에 푸시할 수 없습니다. 최신 버전을 사용하는 경우, [`~PreTrainedModel.push_to_hub`] 방법을 사용하여 8비트 모델을 Hub에 푸시할 수 있습니다. 양자화 config.json 파일이 먼저 푸시되고, 그 다음 양자화된 모델 가중치가 푸시됩니다.
```
config.json은 파일명인 것 같아서, 번역을 해야할지 고민되어서 제안드려봅니다.

2024-08-05 14:13 UTC, 4N3MONE commented on docs/source/ko/quantization/bitsandbytes.md
> +`bitsandbytes>=0.41.3`을 사용하는 경우 4비트 모델을 직렬화하고 Hugging Face Hub에 푸시할 수 있습니다. 모델을 4비트 정밀도로 로드한 후 `model.push_to_hub()`를 호출하면 됩니다. 또한 `model.save_pretrained()` 명령어로 로컬에 직렬화된 4비트 모델을 저장할 수도 있습니다.
```suggestion
`bitsandbytes>=0.41.3`을 사용하는 경우 4비트 모델을 직렬화하고 Hugging Face Hub에 푸시할 수 있습니다. 모델을 4비트 정밀도로 가져온 후 `model.push_to_hub()`를 호출하면 됩니다. 또한 `model.save_pretrained()` 명령어로 로컬에 직렬화된 4비트 모델을 저장할 수도 있습니다.
```

글로서리 기준으로 수정했습니다. (개인적인 의견으로는 후보군에 '로드하다'가 있으니 그쪽으로 통일하는것도 자연스럽지 않나 싶습니다)

2024-08-05 14:13 UTC, 4N3MONE commented on docs/source/ko/quantization/bitsandbytes.md
> +양자화된 모델은 [`~PreTrainedModel.from_pretrained`]를 사용하여 `load_in_8bit` 또는 `load_in_4bit` 매개변수를 지정하지 않고도 로드할 수 있습니다:
```suggestion
양자화된 모델은 [`~PreTrainedModel.from_pretrained`]를 사용하여 `load_in_8bit` 또는 `load_in_4bit` 매개변수를 지정하지 않고도 가져올 수 있습니다:
```
글로서리 기반 수정입니다.

2024-08-05 14:13 UTC, 4N3MONE commented on docs/source/ko/quantization/bitsandbytes.md
> +이제 사용자 정의 `device_map`과 `quantization_config`을 사용하여 모델을 로드합니다:
```suggestion
이제 사용자 정의 `device_map`과 `quantization_config`을 사용하여 모델을 가져옵니다:
```
글로서리 기반 수정입니다.

2024-08-05 14:13 UTC, 4N3MONE commented on docs/source/ko/quantization/bitsandbytes.md
> +[PEFT](https://github.com/huggingface/peft) 라이브러리를 사용하면 [flan-t5-large](https://huggingface.co/google/flan-t5-large) 및 [facebook/opt-6.7b](https://huggingface.co/facebook/opt-6.7b)와 같은 대형 모델을 8비트 양자화
```suggestion
[PEFT](https://github.com/huggingface/peft) 라이브러리를 사용하면 [flan-t5-large](https://huggingface.co/google/flan-t5-large) 및 [facebook/opt-6.7b](https://huggingface.co/facebook/opt-6.7b)와 같은 대형 모델을 8비트 양자화로 미세 조정할 수 있습니다. 훈련 시 `device_map` 매개변수를 전달할 필요가 없으며, 모델을 자동으로 GPU에 가져옵니다. 그러나 원하는 경우 `device_map` 매개변수로 장치 맵을 사용자 정의할 수 있습니다 (`device_map="auto"`는 추론에만 사용해야 합니다).
```
글로서리 기반 수정입니다.

2024-08-05 14:13 UTC, 4N3MONE commented on docs/source/ko/quantization/bitsandbytes.md
> +양자화된 후에는 모델을 원래의 정밀도로 비양자화할 수 있지만, 이는 모델의 작은 품질 손실을 초래할 수 있습니다. 비양자화된 모델을 맞추기 위해 충분한 GPU RAM이 있는지 확인하세요.
```suggestion
양자화된 후에는 모델을 원래의 정밀도로 비양자화할 수 있지만, 이는 모델의 품질이 약간 저하될 수 있습니다. 비양자화된 모델을 맞추기 위해 충분한 GPU RAM이 있는지 확인하세요.
```

자연스러운 어감으로 수정해 보았습니다.

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +모델을 4비트로 양자화하면 메모리 사용량이 4배 줄어들며, 대형 모델의 경우 `device_map="auto"`를 설정하여 사용 가능한 GPU를 효율적으로 활용할 수 있습니다:
```suggestion
모델을 4비트로 양자화하면 메모리 사용량이 4배 줄어들며, 대규모 모델의 경우 `device_map="auto"`를 설정하여 사용 가능한 GPU를 효율적으로 활용할 수 있습니다:
```
glossary에서 llm을 대규모 언어 모델로 번역해서, large를 대규모로 번역해보았습니다.

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +모델을 4비트로 양자화하면 메모리 사용량이 4배 줄어들며, 대형 모델의 경우 `device_map="auto"`를 설정하여 사용 가능한 GPU를 효율적으로 활용할 수 있습니다:
```suggestion
모델을 4비트로 양자화하면 메모리 사용량이 4배 줄어들며, 대형 모델의 경우 사용 가능한 GPU를 효율적으로 활용하려면 `device_map="auto"`를 설정하세요:
```
위의 46 line과 마찬가지로 suggestion 입니다.

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +기본적으로 torch.nn.LayerNorm과 같은 다른 모듈은 `torch.float16`으로 변환됩니다. 원하면 `torch_dtype` 매개변수로 이 모듈의 데이터 유형을 변경할 수 있습니다:
https://github.com/huggingface/transformers/pull/32408/files#r1703434051

FYI, 나중에 윗 부분이 결정된다면, 통일되면 좋을 것 같네요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +기본적으로 torch.nn.LayerNorm과 같은 다른 모듈은 `torch.float16`으로 변환됩니다. 원하면 `torch_dtype` 매개변수로 이 모듈의 데이터 유형을 변경할 수 있습니다:
```suggestion
기본적으로 `torch.nn.LayerNorm`과 같은 다른 모듈은 `torch.float16`으로 변환됩니다. 원한다면 `torch_dtype` 매개변수로 이들 모듈의 데이터 유형을 변경할 수 있습니다:
```

markdown 문법이 빠져있었네요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +
```suggestion
```
이 공백 라인이 추가로 들어가서, line 숫자가 원문이랑 다른 것 같네요! 삭제되면 좋을 것 같아요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +
```suggestion
```
2라인이 추가되었었네요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +
```suggestion
```
공백 라인이 추가되어서, line 수가 원문이랑 달라 삭제되면 좋을 것 같아요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +
```suggestion
```
공백 라인이 추가되어서, line 수가 원문이랑 달라 삭제되면 좋을 것 같아요! 
(생각보다 기계번역에 의한 공백 라인 추가가 많아서,, 제가 잘 리뷰하는건지 더블 체크 부탁드립니다!)

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +양자화된 모델은 [`~PreTrainedModel.from_pretrained`]를 사용하여 `load_in_8bit` 또는 `load_in_4bit` 매개변수를 지정하지 않고도 로드할 수 있습니다:
```suggestion
양자화된 모델은 [`~PreTrainedModel.from_pretrained`] 메소드를 사용하여 `load_in_8bit` 또는 `load_in_4bit` 매개변수를 지정하지 않고도 로드할 수 있습니다:
```

원문의 method가 빠져서 추가합니다!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +
```suggestion
```

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +# bitsandbytes[[bitsandbytes]]
```suggestion
# bitsandbytes [[bitsandbytes]]
```

문서 전체적으로, 제목이랑 [[]] 옆에 띄어쓰기가 하나 없네요!
다른 번역 완료된 문서들을 보면 띄어쓰기가 하나 있어서, 일단 코멘트 남겨둡니다! 
live-preview 때 링크가 잘 달리는지 확인해보면 좋을 거 같아요!
e.g. 큰 모델 인스턴스화 [[instantiating-a-big-model]]

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +이 섹션에서는 오프로드, 이상치 임곗값, 모듈 변환 건너뛰기 및 미세 조정과 같은 8비트 모델의 특정 기능을 살펴봅니다.
```suggestion
이 섹션에서는 오프로딩, 이상치 임곗값, 모듈 변환 건너뛰기 및 미세 조정과 같은 8비트 모델의 특정 기능을 살펴봅니다.
```
원문: offloading

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +### 오프로드[[offloading]]
```suggestion
### 오프로딩 [[offloading]]
```
발음되는 대로 적어보았습니다!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +"이상값"은 특정 임곗값을 초과하는 히든 상태 값을 의미하며, 이러한 값은 fp16으로 계산됩니다. 값은 일반적으로 정규 분포([-3.5, 3.5])를 따르지만, 대형 모델의 경우 이 분포는 매우 다를 수 있습니다([-60, 6] 또는 [6, 60]). 8비트 양자화는 ~5 정도의 값에서 잘 작동하지만, 그 이상에서는 상당한 성능 저하가 발생합니다. 좋은
```suggestion
"이상치"는 특정 임곗값을 초과하는 은닉 상태 값을 의미하며, 이러한 값은 fp16으로 계산됩니다. 값은 일반적으로 정규 분포 ([-3.5, 3.5])를 따르지만, 대규모 모델의 경우 이 분포는 매우 다를 수 있습니다 ([-60, 6] 또는 [6, 60]). 8비트 양자화는 ~5 정도의 값에서 잘 작동하지만, 그 이상에서는 상당한 성능 저하가 발생합니다. 좋은 기본 임곗값 값은 6이지만, 더 불안정한 모델 (소형 모델 또는 미세 조정)에는 더 낮은 임곗값이 필요할 수 있습니다.
```

1. 제목의 이상치와 통일하면 좋을 것 같네요!
2. glossary에서 참조했습니다.
3. 띄어쓰기는 원문을 따라했어요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +"이상값"은 특정 임곗값을 초과하는 히든 상태 값을 의미하며, 이러한 값은 fp16으로 계산됩니다. 값은 일반적으로 정규 분포([-3.5, 3.5])를 따르지만, 대형 모델의 경우 이 분포는 매우 다를 수 있습니다([-60, 6] 또는 [6, 60]). 8비트 양자화는 ~5 정도의 값에서 잘 작동하지만, 그 이상에서는 상당한 성능 저하가 발생합니다. 좋은
```suggestion
"이상값"은 특정 임곗값을 초과하는 히든 상태 값을 의미하며, 이러한 값은 fp16으로 계산됩니다. 값은 일반적으로 정규 분포([-3.5, 3.5])를 따르지만, 대형 모델의 경우 이 분포는 매우 다를 수 있습니다([-60, 6] 또는 [6, 60]). 8-비트 양자화는 ~5 정도의 값에서 잘 작동하지만, 그 이상에서는 상당한 성능 저하가 발생합니다. 좋은 기본 임곗값 값은 6이지만, 더 불안정한 모델(소형 모델 또는 미세 조정)에는 더 낮은 임곗값이 필요할 수 있습니다.
```

지금 발견했는데, 8-bit를 8비트라고 해야할지 8-bit 라고 그대로 해야할지,, 중간에 -가 신경쓰이네요! 
👀작은 거라,, 어디까지 디테일해야할지 모르겠네요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +[PEFT](https://github.com/huggingface/peft) 라이브러리를 사용하면 [flan-t5-large](https://huggingface.co/google/flan-t5-large) 및 [facebook/opt-6.7b](https://huggingface.co/facebook/opt-6.7b)와 같은 대형 모델을 8비트 양자화
```suggestion
[PEFT](https://github.com/huggingface/peft) 라이브러리를 사용하면 [flan-t5-large](https://huggingface.co/google/flan-t5-large) 및 [facebook/opt-6.7b](https://huggingface.co/facebook/opt-6.7b)와 같은 대규모 모델을 8비트 양자화로 미세 조정할 수 있습니다. 훈련 시 `device_map` 매개변수를 전달할 필요가 없으며, 모델이 자동으로 GPU에 로드됩니다. 그러나 원하는 경우 `device_map` 매개변수로 장치 맵을 사용자 정의할 수 있습니다 (`device_map="auto"`는 추론에만 사용해야 합니다).
```

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +
```suggestion
```

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +이 [노트북](https://colab.research.google.com/drive/1ge2F1QSK8Q7h0hn3YKuBCOAS0bK8E0wf)에서 4비트 양자화를 시도하고 자세한 내용은 이 [블로그 게시물](https://huggingface.co/blog/4bit-transformers-bitsandbytes)에서 확인하세요.
```suggestion
이 [노트북](https://colab.research.google.com/drive/1ge2F1QSK8Q7h0hn3YKuBCOAS0bK8E0wf)에서 4비트 양자화를 시도해보고 자세한 내용은 이 [블로그 게시물](https://huggingface.co/blog/4bit-transformers-bitsandbytes)에서 확인하세요.
```

좀 더 자연스럽게 수정해보았어요!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +이 섹션에서는 계산 데이터 유형 변경, Normal Float 4 (NF4) 데이터 유형 사용, 중첩 양자화와 같은 4비트 모델의 특정 기능을 탐구합니다.
```suggestion
이 섹션에서는 계산 데이터 유형 변경, Normal Float 4 (NF4) 데이터 유형 사용, 중첩 양자화 사용과 같은 4비트 모델의 특정 기능 일부를 탐구합니다.
```

원문에 맞춰보았습니다!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +계산 속도를 높이기 위해 [`BitsAndBytesConfig`]에서 `bnb_4bit_compute_dtype` 매개변수를 사용하여 데이터 유형을 float32(기본값)에서 bf16으로 변경할 수 있습니다:
```suggestion
계산 속도를 높이기 위해 [`BitsAndBytesConfig`]에서 `bnb_4bit_compute_dtype` 매개변수를 사용하여 데이터 유형을 float32 (기본값) 에서 bf16으로 변경할 수 있습니다:
```
원문 띄어쓰기를 따라했습니다.

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +
```suggestion
```

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +양자화된 후에는 모델을 원래의 정밀도로 비양자화할 수 있지만, 이는 모델의 작은 품질 손실을 초래할 수 있습니다. 비양자화된 모델을 맞추기 위해 충분한 GPU RAM이 있는지 확인하세요.
```suggestion
양자화된 후에는 모델을 원래의 정밀도로 비양자화할 수 있지만, 이는 모델의 작은 품질 손실을 초래할 수 있습니다. 비양자화된 모델에 맞출 수 있는 충분한 GPU RAM이 있는지 확인하세요.
```
저도 자연스러운 어감으로 수정해 보았습니다!

2024-08-05 15:59 UTC, Jwaminju commented on docs/source/ko/quantization/bitsandbytes.md
> +양자화된 후에는 모델을 원래의 정밀도로 비양자화할 수 있지만, 이는 모델의 작은 품질 손실을 초래할 수 있습니다. 비양자화된 모델을 맞추기 위해 충분한 GPU RAM이 있는지 확인하세요.
긴 글 번역하시느라 넘 고생많으셨어요 🥹

2024-08-06 08:06 UTC, jungnerd commented on docs/source/ko/quantization/bitsandbytes.md
> +CPU에 전달할 `lm_head`를 제외한 모든 것을 GPU에 적재할 수 있도록 사용자 정의 장치 맵을 설계합니다:
```suggestion
CPU에 전달할 `lm_head`를 제외한 모든 것을 GPU에 적재할 수 있도록 사용자 정의 디바이스 맵을 설계합니다:
```
'장치 맵' 보다 '디바이스 맵'이 독자들이 이해하기 쉬울 것 같아서 수정해봤습니다. 
Glossary 확정하고 아래도 수정하면 될 것 같습니다!

2024-08-06 08:10 UTC, jungnerd commented on docs/source/ko/quantization/bitsandbytes.md
> +계산 속도를 높이기 위해 [`BitsAndBytesConfig`]에서 `bnb_4bit_compute_dtype` 매개변수를 사용하여 데이터 유형을 float32(기본값)에서 bf16으로 변경할 수 있습니다:
한국어에선 붙여서 쓰는 게 자연스러울 것 같아요! 🤔

2024-08-06 08:13 UTC, jungnerd commented on docs/source/ko/quantization/bitsandbytes.md
> +"이상값"은 특정 임곗값을 초과하는 히든 상태 값을 의미하며, 이러한 값은 fp16으로 계산됩니다. 값은 일반적으로 정규 분포([-3.5, 3.5])를 따르지만, 대형 모델의 경우 이 분포는 매우 다를 수 있습니다([-60, 6] 또는 [6, 60]). 8비트 양자화는 ~5 정도의 값에서 잘 작동하지만, 그 이상에서는 상당한 성능 저하가 발생합니다. 좋은
한국어에선 `-`를 빼고 `8비트`라고 하는 게 자연스러운 표현이라고 생각해요!

2024-08-06 08:16 UTC, jungnerd commented
좋은 번역 감사합니다! 
PR 서식 맨 첫 줄 `Translated the <your_file>.md file of the documentation to Korean.` 부분의 `<your_file>.md`를 번역하신 문서로 수정해주세요!

2024-08-06 16:25 UTC, SeungAhSon commented on docs/source/ko/quantization/bitsandbytes.md
> +중첩 양자화는 추가적인 성능 손실 없이 추가적인 메모리를 절약할 수 있는 기술입니다. 이 기능은 이미 양자화된 가중치의 2차 양자화를 수행하여 매개변수당 추가로 0.4비트를 절약합니다. 예를 들어, 중첩 양자화를 통해 16GB NVIDIA T4 GPU에서 시퀀스 길이 1024, 배치 크기 1, 그라디언트 누적 4단계를 사용하여 [Llama-13b](htt
```suggestion
중첩 양자화는 추가적인 성능 손실 없이 추가적인 메모리를 절약할 수 있는 기술입니다. 이 기능은 이미 양자화된 가중치의 2차 양자화를 수행하여 매개변수당 추가로 0.4비트를 절약합니다. 예를 들어, 중첩 양자화를 통해 16GB NVIDIA T4 GPU에서 시퀀스 길이 1024, 배치 크기 1, 그레이디언트 누적 4단계를 사용하여 [Llama-13b](https://huggingface.co/meta-llama/Llama-2-13b) 모델을 미세 조정할 수 있습니다.
```
넵 반영하겠습니다

2024-08-06 16:33 UTC, SeungAhSon commented on docs/source/ko/quantization/bitsandbytes.md
> +양자화된 후에는 모델을 원래의 정밀도로 비양자화할 수 있지만, 이는 모델의 작은 품질 손실을 초래할 수 있습니다. 비양자화된 모델을 맞추기 위해 충분한 GPU RAM이 있는지 확인하세요.
```suggestion
양자화된 후에는 모델을 원래의 정밀도로 비양자화할 수 있지만, 이는 모델의 품질이 약간 저하될 수 있습니다. 비양자화된 모델에 맞출 수 있는 충분한 GPU RAM이 있는지 확인하세요.
```
두분 의견 반영해서 수정하겠습니다!

2024-08-06 16:35 UTC, SeungAhSon commented on docs/source/ko/quantization/bitsandbytes.md
> +양자화된 모델은 [`~PreTrainedModel.from_pretrained`]를 사용하여 `load_in_8bit` 또는 `load_in_4bit` 매개변수를 지정하지 않고도 로드할 수 있습니다:
```suggestion
양자화된 모델은 [`~PreTrainedModel.from_pretrained`] 메소드를 사용하여 `load_in_8bit` 또는 `load_in_4bit` 매개변수를 지정하지 않고도 가져올 수 있습니다:
```

2024-08-06 16:36 UTC, SeungAhSon commented on docs/source/ko/quantization/bitsandbytes.md
> +모델을 4비트로 양자화하면 메모리 사용량이 4배 줄어들며, 대형 모델의 경우 `device_map="auto"`를 설정하여 사용 가능한 GPU를 효율적으로 활용할 수 있습니다:
```suggestion
모델을 4비트로 양자화하면 메모리 사용량이 4배 줄어들며, 대규모 모델의 경우 사용 가능한 GPU를 효율적으로 활용하려면 `device_map="auto"`를 설정하세요:
```

2024-08-06 16:41 UTC, SeungAhSon commented on docs/source/ko/quantization/bitsandbytes.md
> +모델이 8비트로 양자화되면 최신 버전의 Transformers와 bitsandbytes를 사용하지 않는 한 양자화된 가중치를 Hub에 푸시할 수 없습니다. 최신 버전을 사용하는 경우, [`~PreTrainedModel.push_to_hub`] 방법을 사용하여 8비트 모델을 Hub에 푸시할 수 있습니다. 양자화 구성 파일(config.json)이 먼저 푸시
```suggestion
모델이 8비트로 양자화되면 최신 버전의 Transformers와 bitsandbytes를 사용하지 않는 한 양자화된 가중치를 Hub에 푸시할 수 없습니다. 최신 버전을 사용하는 경우, [`~PreTrainedModel.push_to_hub`] 메소드를 사용하여 8비트 모델을 Hub에 푸시할 수 있습니다. 양자화 config.json 파일이 먼저 푸시되고, 그 다음 양자화된 모델 가중치가 푸시됩니다.
```

2024-08-06 16:43 UTC, SeungAhSon commented on docs/source/ko/quantization/bitsandbytes.md
> +[PEFT](https://github.com/huggingface/peft) 라이브러리를 사용하면 [flan-t5-large](https://huggingface.co/google/flan-t5-large) 및 [facebook/opt-6.7b](https://huggingface.co/facebook/opt-6.7b)와 같은 대형 모델을 8비트 양자화
```suggestion
[PEFT](https://github.com/huggingface/peft) 라이브러리를 사용하면 [flan-t5-large](https://huggingface.co/google/flan-t5-large) 및 [facebook/opt-6.7b](https://huggingface.co/facebook/opt-6.7b)와 같은 대규모 모델을 8비트 양자화로 미세 조정할 수 있습니다. 훈련 시 `device_map` 매개변수를 전달할 필요가 없으며, 모델을 자동으로 GPU에 가져옵니다. 그러나 원하는 경우 `device_map` 매개변수로 장치 맵을 사용자 정의할 수 있습니다 (`device_map="auto"`는 추론에만 사용해야 합니다).
```

2024-08-06 19:19 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_32408). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-06 19:40 UTC, stevhliu reviewed
Nice job, thanks for the translation! Can you check if whether removing the "?" in some of the sentences alters the meaning? Thanks! 🤗

2024-08-06 19:40 UTC, stevhliu commented on docs/source/ko/quantization/bitsandbytes.md
> +모델에 가장 적합한 임곗값을 찾으려면 [BitsAndBytesConfig]에서 `llm_int8_threshold` 매개변수를 실험해보는 것이 좋습니다:
```suggestion
모델에 가장 적합한 임곗값을 찾으려면 [`BitsAndBytesConfig`]에서 `llm_int8_threshold` 매개변수를 실험해보는 것이 좋습니다:
```

2024-08-06 19:40 UTC, stevhliu commented on docs/source/ko/quantization/bitsandbytes.md
> +[bitsandbytes](https://github.com/TimDettmers/bitsandbytes)는 모델을 8비트 및 4비트로 양자화하는 가장 쉬운 방법입니다. 8비트 양자화는 fp16의 이상치와 int8의 비이상치�를 곱한 후, 비이상치 값을 fp16으로 다시 변환하고, 이들을 합산하여 fp16으로 가중치를 반환합니다. 이렇게 하면 이상치 값이
Not sure why there is a "?" in there so I removed it. Can you check if the translation is still the same please?

```suggestion
[bitsandbytes](https://github.com/TimDettmers/bitsandbytes)는 모델을 8비트 및 4비트로 양자화하는 가장 쉬운 방법입니다. 8비트 양자화는 fp16의 이상치와 int8의 비이상치를 곱한 후, 비이상치 값을 fp16으로 다시 변환하고, 이들을 합산하여 fp16으로 가중치를 반환합니다. 이렇게 하면 이상치 값이 모델 성능에 미치는 저하 효과를 줄일 수 있습니다. 4비트 양자화는 모델을 더욱 압축하며, [QLoRA](https://hf.co/papers/2305.14314)와 함께 사용하여 양자화된 대규모 언어 모델을 미세 조정하는 데 흔히 사용됩니다.
```

2024-08-06 19:40 UTC, stevhliu commented on docs/source/ko/quantization/bitsandbytes.md
> +이제 `BitsAndBytesConfig`를 [`~PreTrainedModel.from_pretrained`] 메소드에 전달하여 모델을 양자화할 수 있습니다. 이는 Accelerate 가져오기를 지원�하고 `torch.nn.Linear` 레이어가 포함된 모든 모델에서 작동합니다.
There's also a "?" here so I removed it.

```suggestion
이제 `BitsAndBytesConfig`를 [`~PreTrainedModel.from_pretrained`] 메소드에 전달하여 모델을 양자화할 수 있습니다. 이는 Accelerate 가져오기를 지원하고 `torch.nn.Linear` 레이어가 포함된 모든 모델에서 작동합니다.
```

2024-08-08 12:07 UTC, SeungAhSon commented
> Nice job, thanks for the translation! Can you check if whether removing the "?" in some of the sentences alters the meaning? Thanks! 🤗

Thank you so much for checking! Your suggestion was spot on, so I've made the changes accordingly.

2024-08-08 16:40 UTC, stevhliu approved these changes
Thanks again!

2024-08-08 16:40 UTC, merged