[i18n-ar] Translated file `README.md` into Arabic
huggingface/transformers pull request #32583
Opened 2024-08-11 01:50 UTC by AhmedAlmaghz

# What does this PR do? 
 Translate docs into Arabic issue-number #32435 
 @stevhliu , @MKhalusova , @abodacs 
 This pull request contains changes [**for file : README.md**](https://github.com/AhmedAlmaghz/transformers/blob/Update_README_md/README.md)

2024-08-11 17:49 UTC, abodacs requested changes
@AhmedAlmaghz 
Can you change the title to reflect the commit content?

I recommend renaming it to  "add README_ar.md to README.md"

2024-08-11 17:49 UTC, abodacs commented on README.md
> +		<a href="https://github.com/huggingface/transformers/blob/main/i18n/README_ar.md">العربية</a> |
@AhmedAlmaghz 
Please keep the same indent .

2024-08-12 17:15 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_32583). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-16 14:40 UTC, abodacs commented
LGTM 

Thanks @AhmedAlmaghz

2024-08-19 17:02 UTC, stevhliu reviewed
Thanks! I would double-check the Markdown links are correctly formatted. Some of the bracketed items are separated from the parentheses kind of like below:

```md
[some text] more text more text (link)
```

2024-08-19 17:02 UTC, stevhliu commented on i18n/README_ar.md
> +# قم بتنزيل صورة بها قطط لطيفة
Nice, thanks for translating the code comments too!

2024-08-20 16:09 UTC, DSYemen commented on i18n/README_ar.md
> +يوفر 🤗 Transformers واجهات برمجة التطبيقات (APIs) لتحميل تلك النماذج المُدربة مسبقًا واستخدامها على نص معين، وضبطها بدقة على مجموعات البيانات الخاصة بك، ثم مشاركتها مع المجتمع على [مركز النماذج](http
Yes!

2024-08-20 23:10 UTC, stevhliu commented on i18n/README_ar.md
> +يوفر 🤗 Transformers واجهات برمجة التطبيقات (APIs) لتحميل تلك النماذج المُدربة مسبقًا واستخدامها على نص معين، وضبطها بدقة على مجموعات البيانات الخاصة بك، ثم مشاركتها مع المجتمع على [مركز النماذج](http
Great, thanks!

2024-08-20 23:11 UTC, stevhliu approved these changes
Thanks for translating to Arabic, and thanks to all the reviewers as well 🤗

2024-08-20 23:11 UTC, merged

2024-08-21 21:49 UTC, AhmedAlmaghz commented
Thank you @stevhliu  on merged