Fix all_special_tokens to have special tokens from added_tokens
huggingface/transformers pull request #32688
Opened 2024-08-14 16:06 UTC by ita9naiwa

# What does this PR do?

for phi-3 models,
![image](https://github.com/user-attachments/assets/0d89f2e5-d8b3-42a9-b33c-5413b72de1d0)

some important special tokens (such as template tokens `<|assistant|>`) are not in Tokenizer.all_special_tokens

but they re in added_vocab
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/9af81b21-8af1-4d23-a8ba-706841b6d959">

 This PR adds those special tokens in added vocab into special tokens.

if I ran correctly, rust tokenizer implementation find special tokens well.

```rust
eprintln!("{:?}", self.special_tokens_set.iter().collect::<Vec<_>>());

> ["<|placeholder15|>", "<|endoftext|>", "<|placeholder13|>", "<|placeholder16|>", "<|placeholder11|>", "<|placeholder10|>", "<|system|>", "<|placeholder18|>", "<|placeholder23|>", "<|placeholder36|>", "<|image|>", "<|placeholder28|>", "<|placeholder29|>", "<|user|>", "<|placeholder3|>", "<|placeholder7|>", "<|placeholder20|>", "<unk>", "<|placeholder24|>", "<|placeholder25|>", "<|placeholder26|>", "<|placeholder1|>", "<|placeholder33|>", "<|placeholder37|>", "<|placeholder12|>", "<|placeholder32|>", "<|placeholder39|>", "<|placeholder27|>", "<|placeholder5|>", "<s>", "<|assistant|>", "<|placeholder38|>", "<|end|>", "<|placeholder14|>", "<|placeholder4|>", "<|placeholder9|>", "<|placeholder2|>", "<|placeholder22|>", "<|placeholder31|>", "<|placeholder34|>", "<|placeholder21|>", "<|placeholder8|>", "<|placeholder6|>", "<|placeholder17|>", "<|placeholder19|>", "<|placeholder30|>", "<|placeholder35|>"]
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

2024-08-14 16:06 UTC, ita9naiwa commented
not sure it's intended behavior tho.

2024-08-15 11:11 UTC, amyeroberts commented
cc @ArthurZucker @itazap

2024-08-19 14:06 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_32688). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-20 15:14 UTC, itazap requested changes
Thank you for this addition! 🚀  Would you be able to please add a small test to test that all special tokens are present? 

As well, can you please try rebasing to main to merge the latest changes? It should fix the failing unrelated tests. Also feel free to update the docstring of this function to inform that special added tokens are included. Thanks! 🤗

2024-08-22 10:41 UTC, itazap approved these changes
great addition, thank you! 🚀 will wait for CI test and then ready to merge!

2024-08-26 06:29 UTC, ita9naiwa commented
Hi, no updates? @itazap

2024-08-26 11:42 UTC, itazap commented
Awesome, thanks @ita9naiwa ! @ArthurZucker good to merge? 🚀

2024-08-27 13:26 UTC, ArthurZucker reviewed
Hey! Yeah but we should probably be more efficient and make sure they are added to `special_tokens_map_extended` when we add tokens no? (can make a difference in terms of performances for models like whisper )

2024-08-28 08:07 UTC, ArthurZucker commented
I think it should only be done for tokenizer_utils (not fast)!

2024-08-29 09:38 UTC, ArthurZucker commented
OVerall we should:
> make sure they are added to special_tokens_map_extended when we add tokens no? (can make a difference in terms of performances for models like whisper )

so instead of computing the set of special added tokens every time youcall special tokens extended, we ought add the tokens to the list, when we do  `add_token` . It's alright if we don't, but it's important to measure the performances as this can affect other applications

2025-01-20 22:52 UTC, closed without merging