[i18n-ar] Translated file : `docs/source/ar/accelerate.md` into Arabic
huggingface/transformers pull request #33016
Opened 2024-08-22 20:18 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/accelerate.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-08-22 20:26 UTC, stevhliu commented
Hi, when opening PRs, it is generally good not to open a ton at once. This gives reviewers time to review them without being overwhelmed. I recommend opening one or just a few PRs at once (you can even bundle them into one), waiting for them to be reviewed and merged, and then opening the next set of PRs.

2024-08-22 20:40 UTC, AhmedAlmaghz commented
Thank you very much for your valuable comments - @stevhliu 
I took @abodacs comments and modified the previous pull requests to make the translation better.

2024-09-03 22:10 UTC, abodacs requested changes
السﻻم عليكم
@AhmedAlmaghz 
جزيل الشكر
تمت المراجعة

2024-09-03 22:10 UTC, abodacs commented on docs/source/ar/accelerate.md
> +ثم قم باستيراد وإنشاء كائن [`~accelerate.Accelerator`]. سيقوم [`~accelerate.Accelerator`] تلقائيًا بالكشف عن نوع الإعداد الموزع الخاص بك وتهيئة جميع المكونات اللازمة للتدريب. لا تحتاج إلى وضع نموذجك
```suggestion
ثم قم باستيراد وإنشاء كائن [`~accelerate.Accelerator`]. سيقوم [`~accelerate.Accelerator`] تلقائيًا باكتشاف نوع الإعداد الموزع الخاص بك وتهيئة جميع المكونات اللازمة للتدريب. لن تحتاج إلى وضع نموذجك على جهاز بشكل معين.
```

2024-09-03 22:10 UTC, abodacs commented on docs/source/ar/accelerate.md
> +الخطوة التالية هي تمرير جميع كائنات التدريب ذات الصلة إلى طريقة [`~accelerate.Accelerator.prepare`]. ويشمل ذلك DataLoaders للتدريب والتقييم، ونموذجًا ومُحَسِّنًا:
```suggestion
الخطوة التالية هي تمرير جميع كائنات التدريب ذات الصلة إلى دالة الإعداد [`~accelerate.Accelerator.prepare`]. ويشمل ذلك DataLoaders للتدريب والتقييم، ونموذجًا ومُحَسِّنً المعاملات (optimizer):
```

2024-09-03 22:10 UTC, abodacs commented on docs/source/ar/accelerate.md
> +الإضافة الأخيرة هي استبدال `loss.backward()` النموذجي في حلقة التدريب الخاصة بك بأسلوب [`~accelerate.Accelerator.backward`] في 🤗 Accelerate:
```suggestion
الإضافة الأخيرة هي استبدال الدالة المعتادة `loss.backward()` في حلقة التدريب الخاصة بك بدالة [`~accelerate.Accelerator.backward`] في 🤗 Accelerate:
```

2024-09-03 22:10 UTC, abodacs commented on docs/source/ar/accelerate.md
> +## الخلفي
```suggestion
## الخلفي Backward
```

2024-09-03 22:10 UTC, abodacs commented on docs/source/ar/accelerate.md
> +يمكن أيضًا تشغيل 🤗 Accelerate في دفتر ملاحظات إذا كنت تخطط لاستخدام وحدات معالجة الرسوميات (TPUs) في Colaboratory. قم بتغليف كل الكود المسؤول عن التدريب في دالة، ومررها إلى [`~accelerate.notebook_lau
```suggestion
يمكن أيضًا تشغيل 🤗 Accelerate في دفاتر إذا كنت تخطط لاستخدام وحدات معالجة الرسوميات (TPUs) في Colaboratory. قم بتغليف كل الكود المسؤول عن التدريب في دالة، ومررها إلى [`~accelerate.notebook_launcher`]:
```

2024-09-04 04:45 UTC, AhmedAlmaghz commented
أشكرك من اعماق قلبي أخي/ عبدالله
الله يبارك فيك 
@abodacs

2024-09-04 07:55 UTC, abodacs approved these changes

2024-09-04 08:23 UTC, abodacs commented
@AhmedAlmaghz 
جزاك الله خيرا

ممكن تجول الحالة من draft to open

2024-09-13 03:29 UTC, closed without merging