[i18n-ar] Translated file : `docs/source/ar/autoclass_tutorial.md` into Arabic
huggingface/transformers pull request #33022
Opened 2024-08-22 20:19 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/autoclass_tutorial.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-09-01 21:22 UTC, abodacs requested changes
سﻻم عليكم
@AhmedAlmaghz 
شكرا لمجهودك

تم اضافة بعض المﻻحظات

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +تذكر أن البنية تشير إلى هيكل النموذج، ونقاط التفتيش هي الأوزان لبنية معينة. على سبيل المثال، [BERT](https://huggingface.co/google-bert/bert-base-uncased) هي بنية، في حين أن `google-bert/bert-base-unc
```suggestion
تذكر أن البنية تشير إلى هيكل النموذج، والنسخ هي الأوزان لبنية معمارية معينة. على سبيل المثال، [BERT](https://huggingface.co/google-bert/bert-base-uncased) هي بنية معمارية، في حين أن `google-bert/bert-base-uncased` هي نسخة. "النموذج" هو مصطلح عام يمكن أن يعني إما البنية أو نالنسخة.
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +* تحميل محدد مُدرب مسبقًا
```suggestion
* تحميل مُجزّئ الرموز مُدرب مسبقًا
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +تبدأ كل مهمة NLP تقريبًا بمحدد. يقوم المحلل اللغوي بتحويل إدخالك إلى تنسيق يمكن للنموذج معالجته.
```suggestion
تبدأ كل مهمة NLP تقريبًا بمُجزّئ للرموز. يقوم المُجزّئ بتحويل النص إلى شكل يمكن للنموذج معالجته.
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +قم بتحميل محلل باستخدام [`AutoTokenizer.from_pretrained`]:
```suggestion
قم بتحميل المُجزّئ باستخدام [`AutoTokenizer.from_pretrained`]:
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +## AutoImageProcessor
```suggestion
## معالج الصور التلقائي (AutoImageProcessor)
 
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +    <figcaption class="mt-2 text-center text-sm text-gray-500">A Swin backbone with multiple stages for outputting a feature map.</figcaption>
```suggestion
    <figcaption class="mt-2 text-center text-sm text-gray-500">الصورة توضح مخطط مراحل نموذج Swin.</figcaption>
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +    <figcaption class="mt-2 text-center text-sm text-gray-500">A feature map from the first stage of the backbone. The patch partition refers to the model stem.</figcaption>
```suggestion
    <figcaption class="mt-2 text-center text-sm text-gray-500">صورة توضح خريطة ميزات من المرحلة الأولى للعمود الفقري.</figcaption>
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +## AutoFeatureExtractor
```suggestion
## مستخرج الميزات التلقائي (AutoFeatureExtractor)
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +## AutoProcessor
```suggestion
## المعالج التلقائي (AutoProcessor)
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +تتطلب المهام متعددة الوسائط معالجًا يجمع بين نوعين من أدوات المعالجة المسبقة. على سبيل المثال، يتطلب نموذج [LayoutLMV2](model_doc/layoutlmv2) معالج صور لمعالجة الصور ومحلل لغوي لمعالجة النص؛ يجمع الم
```suggestion
تتطلب المهام متعددة الوسائط معالجًا يجمع بين نوعين من أدوات المعالجة المسبقة. على سبيل المثال، يتطلب نموذج [LayoutLMV2](model_doc/layoutlmv2) معالج صور لمعالجة الصور ومُجزّئ لمعالجة النص؛ يجمع المعالج كليهما.
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +## AutoModel
```suggestion
## النموذج التلقائي (AutoModel)
```

2024-09-01 21:22 UTC, abodacs commented on docs/source/ar/autoclass_tutorial.md
> +بشكل عام، نوصي باستخدام فئة `AutoTokenizer` وفئة `TFAutoModelFor` لتحميل مثيلات مُدربة مسبقًا من النماذج. سيساعدك هذا في تحميل البنية الصحيحة في كل مرة. في البرنامج التعليمي التالي، تعرف على كيفية اس
```suggestion
بشكل عام، نوصي باستخدام فئة `AutoTokenizer` وفئة `TFAutoModelFor` لتحميل نسخ لنماذج مُدربة مسبقًا. سيساعدك هذا في تحميل البنية الصحيحة في كل مرة. في البرنامج التعليمي التالي، ستتعرف على كيفية استخدام المُجزّئ اللغوي ومعالج الصور ومستخرج الميزات والمعالج الذي تم تحميله حديثًا لمعالجة مجموعة بيانات للضبط الدقيق.
```

2024-09-04 04:18 UTC, AhmedAlmaghz commented
Thank you @abidlabs

2024-09-04 08:22 UTC, abodacs approved these changes
Ready to merge

2024-09-13 03:28 UTC, closed without merging