[i18n-ar] Translated file : `docs/source/ar/community.md` into Arabic
huggingface/transformers pull request #33027
Opened 2024-08-22 20:19 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/community.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-12-03 01:09 UTC, AhmedAlmaghz commented
أخي عبدالله @abodacs  هذا ما تم إنجازه في هذا القسم 
إلى الامام إن شاء الله
هذا آخر ملف في هذا القسم



# DEVELOPER GUIDES

- [x]  Use fast tokenizers from 🤗 Tokenizers #33034
- [x]  Run inference with multilingual models #33048
- [x]  Use model-specific APIs #33030
- [x]  Share a custom model #33031
- [x]  Templates for chat models #33026
- [x]  Trainer #33080
- [x]  Run training on Amazon SageMaker #33071
- [x]  Export to ONNX #33072
- [x]  Export to TFLite #33077
- [ ]  Export to TorchScript #33079
- [ ]  Benchmarks #33023
- [ ]  Notebooks with examples #33049
- [ ]  Community resources #33027
- [ ]  Troubleshoot #33017
- [x]  Interoperability with GGUF files #33037

2024-12-03 19:57 UTC, abodacs commented
@AhmedAlmaghz 
تسلم
 ممكن تلقى نظرة على
 
https://huggingface.co/docs/transformers/main/en/tiktoken
https://huggingface.co/docs/transformers/main/en/modular_transformers
https://huggingface.co/docs/transformers/main/en/how_to_hack_models

اعتقد انهم ليس لهم ترجمة

2024-12-03 19:59 UTC, abodacs approved these changes

2024-12-03 22:42 UTC, AhmedAlmaghz commented
> @AhmedAlmaghz تسلم ممكن تلقى نظرة على
> 
> https://huggingface.co/docs/transformers/main/en/tiktoken https://huggingface.co/docs/transformers/main/en/modular_transformers https://huggingface.co/docs/transformers/main/en/how_to_hack_models
> 
> اعتقد انهم ليس لهم ترجمة

تم إضافة ترجمة الملفات 
هذه الملفات جديدة تم إضافتها حديثاً

اشكري اخي عبدالله @abodacs على ملاحظاتك  القيمة.

اتمنى لك التوفيق

2024-12-07 21:08 UTC, abodacs requested changes
السﻻم عليكم

تمت المراجعة جزاك الله خير

@AhmedAlmaghz

2024-12-07 21:08 UTC, abodacs commented on docs/source/ar/modular_transformers.md
> +
```suggestion
هنا مثال سريع باستخدام BERT و RoBERTa. النموذجان مرتبطان ارتباطًا وثيقًا: يختلف تنفيذهما النموذجي في طبقة تضمين.

بدلاً من إعادة تعريف النموذج بالكامل، إليك كيف يبدو ملف `modular_roberta.py` لفئات النمذجة والتكوين (لأغراض المثال، يتم تجاهل المجزىء اللغوي في هذا الوقت حيث أنه مختلف جدًا).

```

2024-12-07 21:08 UTC, abodacs commented on docs/source/ar/tiktoken.md
> +من أجل تحميل ملفات `tiktoken` في `transformers`، تأكد من أن ملف `tokenizer.model` هو ملف tiktoken وسيتم تحميله تلقائيًا عند التحميل `from_pretrained`. إليك كيفية تحميل محلل لغوي ونموذج، والذي
```suggestion
من أجل تحميل ملفات `tiktoken` في `transformers`، تأكد من أن ملف `tokenizer.model` هو ملف tiktoken وسيتم تحميله تلقائيًا عند التحميل `from_pretrained`. إليك كيفية تحميل مجزىء لغوي ونموذج، والذي
```

2024-12-07 21:08 UTC, abodacs commented on docs/source/ar/tiktoken.md
> +## إنشاء محلل لغوي tiktoken
```suggestion
## إنشاء مجزىء لغوي tiktoken
```

2024-12-10 15:25 UTC, AhmedAlmaghz commented
Thank you @abodacs

2024-12-10 16:56 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33027). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-12-10 17:08 UTC, stevhliu approved these changes
LGTM, thanks!

2024-12-10 17:08 UTC, merged