[i18n-ar] Translated file : `docs/source/ar/glossary.md` into Arabic
huggingface/transformers pull request #33038
Opened 2024-08-22 20:20 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/glossary.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-08-27 22:30 UTC, abodacs reviewed
@AhmedAlmaghz 
بدأت فى المراحعة

2024-08-27 22:30 UTC, abodacs commented on docs/source/ar/glossary.md
> +### التغذية الأمامية للتشويك
تجزئة التغذية الأمامية  (feed forward chunking)

في كل وحدة الانتباه الباقية في المحولات، تلي طبقة الاهتمام الانتباه عادة طبقتان للتغذية الأمامية.
حجم تضمين الطبقة الأمامية الوسيطة أكبر عادة من حجم المخفي للنموذج (على سبيل المثال، لـ
`google-bert/bert-base-uncased`).
بالنسبة لإدخال بحجم `[batch_size، sequence_length]`، يمكن أن تمثل الذاكرة المطلوبة لتخزين التضمينات الأمامية الوسيطة `[batch_size، sequence_length، config.intermediate_size]` جزءًا كبيرًا من استخدام الذاكرة. لاحظ مؤلفو [Reformer: The Efficient Transformer](https://arxiv.org/abs/2001.04451) أنه نظرًا لأن الحساب مستقل عن بعد `sequence_length`، فإنه من المكافئ رياضيًا حساب تضمينات الإخراج الأمامية `[batch_size، config.hidden_size]_0، ...، [batch_size، config_size]_n`
فردياً والتوصيل بها لاحقًا إلى `[batch_size، sequence_length، config.hidden_size]` مع `n = sequence_length`، والذي يتداول زيادة وقت الحساب مقابل تقليل استخدام الذاكرة، ولكنه ينتج عنه نتيجة مكافئة رياضيا.

بالنسبة للنماذج التي تستخدم الدالة [`apply_chunking_to_forward`]`، يحدد `chunk_size` عدد التضمينات
يتم حساب الإخراج بالتوازي وبالتالي يحدد المقايضة بين حجم الذاكرة والتعقيد الوقت. إذا تم تعيين `chunk_size` إلى 0، فلن يتم إجراء تجزئة التغذية الأمامية.

2024-08-27 22:30 UTC, abodacs commented on docs/source/ar/glossary.md
> +
النماذج المضبوطة (finetuned models)

الضبط الدقيق هو شكل من أشكال نقل التعلم، يتضمن أخذ نموذج مُدرّب مسبقًا، وتجميد أوزانه، واستبدال طبقة الإخراج برأس نموذج مُضاف حديثًا. يتم تدريب رأس النموذج على مجموعة البيانات المستهدفة.

2024-08-27 22:30 UTC, abodacs commented on docs/source/ar/glossary.md
> +يشير رأس النموذج إلى الطبقة الأخيرة من الشبكة العصبية التي تقبل الحالات المخفية الخام وتسقطها إلى بعد مختلف. هناك رأس نموذج مختلف لكل مهمة. على سبيل المثال:
رأس النموذج (head)

يشير رأس النموذج إلى الطبقة الأخيرة من الشبكة العصبية التي تقبل الحالات المخفية الخام/الأولية وتُسقطها على بُعد مختلف. يوجد رأس نموذج مختلف لكل مهمة.

2024-08-28 20:48 UTC, abodacs requested changes
@AhmedAlmaghz 
شكرا على مجهودك ومبادرتك
تتم المراجعة الPR

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +العلامات هي حجة اختيارية يمكن تمريرها حتى يتمكن النموذج من حساب الخسارة بنفسه. هذه العلامات
نماذج تصنيف التسلسل: ([`BertForSequenceClassification`])  يتوقع النموذج مصفوفة ذات بعد (batch_size) حيث تتوافق كل قيمة من المجموعة مع الملصق المتوقع للتسلسل بأكمله.
نماذج تصنيف الرمز:  ([`BertForTokenClassification`]) يتوقع النموذج مصفوفة ذات بعد (batch_size, seq_length) حيث تتوافق كل قيمة مع الملصق المتوقع لكل رمز فردي.
نماذج النمذجة اللغوية المقنعة:([`BertForMaskedLM`])  يتوقع النموذج مصفوفة ذات بعد (batch_size, seq_length) حيث تتوافق كل قيمة مع الملصق المتوقع لكل رمز فردي: تكون الملصقات هي معرف رمز الكلمة المقنعة، والقيم الأخرى يتم تجاهلها (عادةً -100).
مهام التسلسل إلى التسلسل:  ([`BartForConditionalGeneration`], [`MBartForConditionalGeneration`]) يتوقع النموذج مصفوفة ذات بعد (batch_size, tgt_seq_length) حيث تتوافق كل قيمة مع التسلسل الهدف المرتبط بكل تسلسل مدخل. أثناء التدريب، سيقوم كل من BART و T5 بإنشاء decoder_input_ids و decoder attention masks داخليًا. عادةً لا يلزم توفيرها. هذا لا ينطبق على النماذج التي تستخدم إطار العمل Encoder-Decoder.
نماذج تصنيف الصور: ([`ViTForImageClassification`])  يتوقع النموذج مصفوفة ذات بعد (batch_size) حيث تتوافق كل قيمة من المجموعة مع الملصق المتوقع لكل صورة فردية.
نماذج التقسيم الدلالي: ([`SegformerForSemanticSegmentation`])  يتوقع النموذج مصفوفة ذات بعد (batch_size, height, width) حيث تتوافق كل قيمة من المجموعة مع الملصق المتوقع لكل بكسل فردي.
نماذج اكتشاف الأجسام: ([`DetrForObjectDetection`])  يتوقع النموذج قائمة من القواميس تحتوي على مفتاح class_labels و boxes حيث تتوافق كل قيمة من المجموعة مع الملصق المتوقع وعدد المربعات المحيطة بكل صورة فردية.
نماذج التعرف التلقائي على الكلام:  ([`Wav2Vec2ForCTC`]) يتوقع النموذج مصفوفة ذات بعد (batch_size, target_length) حيث تتوافق كل قيمة مع الملصق المتوقع لكل رمز فردي.

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +مهمة تدريب مسبق يرى فيها النموذج إصدارًا مشوهًا من النصوص، ويتم ذلك عادةً عن طريق قناع بعض الرموز بشكل عشوائي، ويجب عليه التنبؤ بالنص الأصلي.
مهمة تدريب مسبق حيث يرى النموذج نسخة تالفة من النصوص، وعادة ما يتم ذلك عن طريق حجب بعض الرموز بشكل عشوائي، ويتعين على النموذج التنبؤ بالنص الأصلي.

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +مهمة تجمع بين النصوص مع نوع آخر من الإدخالات (على سبيل المثال، الصور).
* المدخلات *

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### إنشاء اللغة الطبيعية (NLG)
توليد اللغة الطبيعية (NLG)

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +خط أنابيب في 🤗 المحولات هو تجريد يشير إلى سلسلة من الخطوات التي يتم تنفيذها بترتيب محدد لمعالجة البيانات وتحويلها وإرجاع تنبؤ من نموذج. قد تكون بعض المراحل الموجودة في خط الأنابيب هي معالجة البيانات
خط الأنابيب (pipeline)

في مكتبة Transformers، يُشير مصطلح "خط الأنابيب" إلى سلسلة من الخطوات التي يتم تنفيذها بترتيب محدد لمعالجة البيانات وتحويلها وإرجاع تنبؤ من نموذج. بعض المراحل الشائعة في خط الأنابيب قد تشمل معالجة البيانات الأولية، واستخراج الميزات، والتوحيد.

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +تقنية توازي يتم فيها تقسيم النموذج رأسياً (على مستوى الطبقة) عبر وحدات معالجة الرسومات (GPU) متعددة، بحيث توجد طبقة واحدة أو عدة طبقات من النموذج على وحدة معالجة الرسومات (GPU) واحدة فقط. تقوم كل وحد
التوازي على مستوى خط الأنابيب (PipelineParallel)

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +عملية تقلل مصفوفة إلى مصفوفة أصغر، إما عن طريق أخذ الحد الأقصى أو المتوسط للأبعاد المجمعة. طبقات التجميع شائعة بين الطبقات التلافيفية لتصغير تمثيل الميزة.
التجميع (Pooling)

هي عملية تقوم بتقليص مصفوفة إلى مصفوفة أصغر، إما عن طريق أخذ القيمة القصوى أو المتوسط الحسابي للأبعاد التي يتم تجميعها. توجد طبقات التجميع بشكل شائع بين الطبقات التلافيفية convolutional layers لتقليل حجم تمثيل الميزات.

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### معرفات الموضع
معرفات الموضع (position IDs)

على عكس الشبكات العصبية المتكررة (RNNs) التي تتضمن موضع كل رمز (token) ضمن بنيتها،

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +نموذج تم تدريبه مسبقًا على بعض البيانات (على سبيل المثال، كل Wikipedia). تنطوي طرق التدريب المسبق على هدف ذاتي الإشراف، والذي يمكن أن يكون قراءة النص ومحاولة التنبؤ بالكلمة التالية (راجع [نمذجة اللغة
الاشارة إلى نمذجة اللغة السببية و نمذجة اللغة المقنعة 
ﻻ تعمل

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +نوع من النماذج التي تستخدم حلقة عبر طبقة لمعالجة النصوص.
هي نوع من النماذج التي تستخدم حلقة متكررة فوق طبقة معينة لمعالجة النصوص.

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### تعلم التمثيل
التعلم التمثيلي (representation learning)

هو فرع من فروع تعلم الآلة يركز على تعلم تمثيلات ذات معنى للبيانات الخام. بعض الأمثلة على تقنيات التعلم التمثيلي تشمل تضمين الكلمات، والمشفرات ذاتية، وشبكات التنافس التوليدية(GANs).

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### الاهتمام الذاتي
الانتباه الذاتي (Self-Attention)
هو آلية تتيح لكل عنصر في المدخل أن يحدد أي العناصر الأخرى في نفس المدخل يجب أن ينتبه إليها.

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +نماذج تولد تسلسلًا جديدًا من إدخال، مثل نماذج الترجمة، أو نماذج الملخص (مثل [Bart](model_doc/bart) أو [T5](model_doc/t5)).
نماذج التلخيص *

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### خطوة
الخطوة (Stride)

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +
في العمليات التلافيفية أو التجميعية، تشير الخطوة إلى المسافة التي يتحرك بها النواة (kernel) فوق المصفوفة. خطوة تساوي 1 تعني أن النواة تتحرك بكسل واحد في كل مرة

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +شكل من أشكال تدريب النماذج التي تستخدم البيانات الموسومة مباشرة لتصحيح أداء النموذج وتوجيهه. يتم تغذية البيانات في النموذج الذي يتم تدريبه، ويتم مقارنة تنبؤاته بالتسميات المعروفة. يقوم النموذج بتحديث
هو نوع من تدريب النماذج التي تستخدم بيانات مُعلَّمة بشكل مباشر لتصحيح أداء النموذج وتوجيهه. يتم تغذية البيانات إلى النموذج قيد التدريب، ويتم مقارنة تنبؤاته بالنتائج الصحيحة المعروفة. يقوم النموذج بتعديل أوزانه بناءً على مدى خطأ تنبؤاته، وتتكرر هذه العملية لتحسين أداء النموذج.

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### رمز
الرمز اللغوي (Token)

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +جزء من جملة، عادة ما يكون كلمة، ولكن يمكن أن يكون أيضًا كلمة فرعية (غالبًا ما يتم تقسيم الكلمات غير الشائعة إلى كلمات فرعية) أو رمز ترقيم.
علامة ترقيم*

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +يمكننا استخدام برنامجنا للتمييز لإنشاء مثل هذه الجملة تلقائيًا عن طريق تمرير التسلسلين إلى `tokenizer` كحجتين (وليس قائمة، كما كان من قبل) مثل هذا:
```suggestion
يمكننا استخدام برنامجنا للتمييز لإنشاء مثل هذه الجملة تلقائيًا عن طريق تمرير التسلسلين إلى `tokenizer` كمعاملين (وليس قائمة، كما كان من قبل) مثل هذا:
```

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### التعلم بالنقل
التعلم الانتقالي (Transfer Learning)

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +هندسة نموذج التعلم العميق القائمة على الاهتمام الذاتي.
```suggestion
هو بنية لنموذج تعلم عميق يعتمد على الانتباه الذاتي.


```

2024-08-28 20:48 UTC, abodacs commented on docs/source/ar/glossary.md
> +### محسن Zero Redundancy (ZeRO)
محسن التكرار الصفري (ZeRO)

2024-08-29 18:04 UTC, AhmedAlmaghz commented
التالي :
🤗 Transformers #33040
 Quick tour #33069
 Installation #33041

2024-08-30 15:00 UTC, abodacs approved these changes

2024-08-30 17:00 UTC, stevhliu reviewed
Cool thanks, there are just a few missing things

2024-08-30 17:00 UTC, stevhliu commented on docs/source/ar/glossary.md
> +### التعلم غير الخاضع للإشراف
```suggestion
### التعلم غير الخاضع للإشراف (unsupervised learning)
```

2024-09-13 03:31 UTC, closed without merging