[i18n-ar] Translated file : `docs/source/ar/multilingual.md` into Arabic
huggingface/transformers pull request #33048
Opened 2024-08-22 20:21 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/multilingual.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-10-22 22:40 UTC, abodacs requested changes
السﻻم عليكم
 @AhmedAlmaghz 
 تمت المراجعة جزاء الله خيرا

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +# النماذج متعددة اللغات للاستنتاج
```suggestion
# النماذج متعددة اللغات للاستدلال
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +هناك العديد من النماذج متعددة اللغات في مكتبة 🤗 Transformers، وتختلف طريقة استخدامها للاستنتاج عن النماذج أحادية اللغة. ولكن ليس كل استخدام النماذج متعددة اللغات مختلف. فبعض النماذج، مثل [google-bert
```suggestion
هناك العديد من النماذج متعددة اللغات في مكتبة 🤗 Transformers، وتختلف طريقة استخدامها للاستدلال عن النماذج أحادية اللغة. ولكن ليس كل استخدام النماذج متعددة اللغات مختلف. فبعض النماذج، مثل [google-bert/bert-base-multilingual-uncased](https://huggingface.co/google-bert/bert-base-multilingual-uncased)، يمكن استخدامها تمامًا مثل النموذج أحادي اللغة. سيوضح لك هذا الدليل كيفية استخدام النماذج متعددة اللغات التي تختلف طريقة استخدامها للاستدلال.
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +يحتوي XLM على عشر نقاط تفتيش مختلفة، واحدة منها فقط أحادية اللغة. ويمكن تقسيم نقاط تفتيش النماذج التسع المتبقية إلى فئتين: نقاط التفتيش التي تستخدم تضمينات اللغة وتلك التي لا تستخدمها.
```suggestion
يحتوي XLM على عشر نسخ مختلفة، واحدة منها فقط أحادية اللغة. ويمكن تقسيم نسخ النماذج التسع المتبقية إلى فئتين: نسخ التي تستخدم تضمينات اللغة (language embeddings)  وتلك التي لا تستخدمها.
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +تستخدم النماذج التالية من XLM تضمينات اللغة لتحديد اللغة المستخدمة في الاستنتاج:
```suggestion
تستخدم النماذج التالية من XLM تضمينات اللغة لتحديد اللغة المستخدمة أثناء الاستدلال:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +تُمثل تضمينات اللغة على شكل مصفوفة بنفس شكل `input_ids` التي يتم تمريرها إلى النموذج. وتعتمد القيم في هذه المصفوفات على اللغة المستخدمة ويتم تحديدها بواسطة سمات المحلل `lang2id` و `id2lang`.
```suggestion
تُمثل تضمينات اللغة على شكل مصفوفة بنفس شكل  `input_ids` التي يتم تمريره إلى النموذج. وتعتمد القيم في هذه المصفوفات على اللغة المستخدمة ويتم تحديدها بواسطة معاملى المجزىء `lang2id` و `id2lang`.
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +في هذا المثال، قم بتحميل نقطة تفتيش `FacebookAI/xlm-clm-enfr-1024` (نمذجة اللغة السببية، الإنجليزية-الفرنسية):
```suggestion
في هذا المثال، قم بتحميل نسخة `FacebookAI/xlm-clm-enfr-1024` ( نمذجة اللغة السببية، الإنجليزية-الفرنسية):
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +تُظهر سمة `lang2id` في المحلل اللغات وأرقام تعريفها في هذا النموذج:
```suggestion
تُظهر خاصية `lang2id` في المجزىء اللغات وأرقام تعريفها في هذا النموذج:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +تُستخدم هذه النماذج لتمثيل الجمل العامة، على عكس نقاط تفتيش XLM السابقة.
```suggestion
تُستخدم هذه النماذج لتمثيل الجمل العامة، على عكس نسح XLM السابقة.
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +لا تتطلب هذه النماذج تضمينات اللغة أثناء الاستنتاج. يجب أن تحدد اللغة من السياق وتستنتج وفقاً لذلك.
```suggestion
لا تتطلب هذه النماذج تضمينات اللغة أثناء الاستدلال. يجب أن تُحدّد اللغة من السياق وتستنتج وفقاً لذلك.
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +في هذا المثال، قم بتحميل نقطة تفتيش `facebook/m2m100_418M` لترجمة النص من الصينية إلى الإنجليزية. يمكنك تعيين اللغة المصدر في المحلل:
```suggestion
في هذا المثال، قم بتحميل نسحة  `facebook/m2m100_418M` لترجمة النص من الصينية إلى الإنجليزية. يمكنك تعيين اللغة المصدر في المجزىء اللغوى:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +قم بتحليل النص:
```suggestion
تقسيم النّص إلى رموز:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +يجبر M2M100 معرف اللغة الهدف كأول رمز مولد للترجمة إلى لغة الهدف. قم بتعيين `forced_bos_token_id` إلى `en` في طريقة `generate` للترجمة إلى الإنجليزية:
```suggestion
يجبر M2M100 معرف اللغة الهدف كأول رمز مولد للترجمة إلى اللغة الهدف. قم بتعيين `forced_bos_token_id` إلى `en` في طريقة `generate` للترجمة إلى الإنجليزية:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +في هذا المثال، قم بتحميل نقطة تفتيش `facebook/mbart-large-50-many-to-many-mmt` لترجمة النص من الفنلندية إلى الإنجليزية. يمكنك تعيين اللغة المصدر في المحلل:
```suggestion
في هذا المثال، قم بتحميل نسخة `facebook/mbart-large-50-many-to-many-mmt` لترجمة النص من الفنلندية إلى الإنجليزية. يمكنك تعيين اللغة المصدر في المجزىء:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +قم بتحليل النص:
```suggestion
تقسيم النّص إلى رموز:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +يجبر MBart معرف لغة الهدف كأول رمز مولد للترجمة إلى لغة الهدف. قم بتعيين `forced_bos_token_id` إلى `en` في طريقة `generate` للترجمة إلى الإنجليزية:
```suggestion
يجبر MBart معرف لغة الهدف كأول رمز مولد للترجمة إلى اللغة الهدف. قم بتعيين `forced_bos_token_id` إلى `en` في طريقة `generate` للترجمة إلى الإنجليزية:
```

2024-10-22 22:40 UTC, abodacs commented on docs/source/ar/multilingual.md
> +إذا كنت تستخدم نقطة تفتيش `facebook/mbart-large-50-many-to-one-mmt`، فلا تحتاج إلى إجبار معرف لغة الهدف كأول رمز مولد، وإلا فإن الاستخدام هو نفسه.
```suggestion
إذا كنت تستخدم نسخة `facebook/mbart-large-50-many-to-one-mmt`، فلا تحتاج إلى إجبار معرف لغة الهدف كأول رمز مولد، وإلا فإن الاستخدام هو نفسه.
```

2024-10-26 20:53 UTC, AhmedAlmaghz commented
Thank you @abodacs

2024-10-28 18:16 UTC, stevhliu reviewed
Cool, thanks for the translation! Remember to add it to the toctree 🙂

2024-10-30 03:40 UTC, AhmedAlmaghz commented
Done @stevhliu 
Please, merging

2024-10-30 06:25 UTC, AhmedAlmaghz commented
The following pull requests have been added to the current pull request to be merged once
- [ ]  Run inference with multilingual models #33048
- [ ]  Use model-specific APIs #33030
- [ ]  Share a custom model #33031
- [ ]  Templates for chat models #33026
- [ ]  Interoperability with GGUF files #33037
- [ ]  Export to TFLite #33077

@abodacs  @stevhliu

2024-10-30 16:10 UTC, stevhliu reviewed
The tflite and gguf docs are also missing from the toctree ;)

2024-10-30 17:36 UTC, AhmedAlmaghz commented
Done 
@stevhliu

2024-10-30 19:07 UTC, stevhliu reviewed
A few more comments

2024-10-30 19:41 UTC, AhmedAlmaghz commented
Thank you @stevhliu 
Done

2024-10-30 20:17 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33048). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-31 23:00 UTC, stevhliu approved these changes
Awesome, thanks!

2024-10-31 23:10 UTC, merged

2024-11-01 16:47 UTC, AhmedAlmaghz commented
Thank you:
@abodacs 
@stevhliu