[i18n-ar] Translated file : `docs/source/ar/llm_tutorial_optimization.md` into Arabic
huggingface/transformers pull request #33043
Opened 2024-08-22 20:21 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/llm_tutorial_optimization.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-09-27 18:18 UTC, abodacs requested changes
السﻻم عليكم
@AhmedAlmaghz 
اعتقد ان هنالك بعض الفقرات الناقصة فى الترحمه

2024-09-27 18:18 UTC, abodacs commented on docs/source/ar/llm_tutorial_optimization.md
> +كل ما يهم هو أن توزيع الرمز التالي *logit* يظل كما هو تقريبًا بحيث تعطي عملية `argmax` أو `topk` نفس النتائج.
```suggestion
دون الدخول في الكثير من التفاصيل، تهدف مخططات التكميم إلى تخفيض دقة الأوزان مع محاولة الحفاظ على دقة نتائج النموذج كما هي (*أي* أقرب ما يمكن إلى bfloat16).
لاحظ أن التكميم يعمل بشكل خاص جيدًا لتوليد النص حيث كل ما نهتم به هو اختيار *مجموعة الرموز الأكثر احتمالًا التالية* ولا نهتم حقًا بالقيم الدقيقة لتوزيع الرمز التالي *logit*.
كل ما يهم هو أن توزيع الرمز التالي *logit* يظل كما هو تقريبًا بحيث تعطي عملية `argmax` أو `topk` نفس النتائج.
```

2024-09-27 18:18 UTC, abodacs commented on docs/source/ar/llm_tutorial_optimization.md
> +هناك تقنيات تحويل مختلفة، والتي لن نناقشها بالتفصيل هنا، ولكن بشكل عام، تعمل جميع تقنيات التحويل كما يلي:
```suggestion
هناك عدة تقنيات للتكميم، والتي لن نناقشها بالتفصيل هنا، ولكن بشكل عام، تعمل جميع تقنيات التكميم كما يلي:
```

2024-09-27 18:18 UTC, abodacs commented on docs/source/ar/llm_tutorial_optimization.md
> +-   3.  قم بتحويل الأوزان ديناميكيًا إلى bfloat1
```suggestion
-   1.  تكميم جميع الأوزان إلى الدقة المستهدفة
-   2.  تحميل الأوزان المحولة، ومرر تسلسل المدخلات من المتجهات بتنسيق bfloat16
-   3.  قم بتحويل الأوزان ديناميكيًا إلى bfloat1  لإجراء الحسابات مع متجهات المدخلات بدقة `bfloat16`
```

2024-09-27 18:18 UTC, abodacs commented on docs/source/ar/llm_tutorial_optimization.md
> +لم أترجم النصوص الخاصة ولا الأكواد البرمجية ولا الروابط ولا رموز HTML و CSS، كما طلبت.
```suggestion
```

2024-09-27 18:18 UTC, abodacs commented on docs/source/ar/llm_tutorial_optimization.md
> +باختصار، سرعان ما يصبح خوارزمية الاهتمام الذاتي الافتراضية مكلفة للغاية من حيث الذاكرة بالنسبة لسياقات الإدخال الكبيرة.
```suggestion
باختصار، سرعان ما يصبح خوارزمية الانتباه الذاتي الافتراضية مكلفة للغاية من حيث الذاكرة بالنسبة لسياقات الإدخال الكبيرة.
```

2024-09-27 18:18 UTC, abodacs commented on docs/source/ar/llm_tutorial_optimization.md
> +لنلقِ نظرة على مثال عملي.
```suggestion
```

2024-10-02 13:10 UTC, AhmedAlmaghz commented
مرحبا أخي عبدالله @abodacs 
اشكرك على المراجعة وأعذرني على الإنقطاع اليومين السابقين لقد  كنت مريضاً
سوف أراجع الملف و اتحقق من الناقص

يمكنك البدء بالقسم التالي :

# DEVELOPER GUIDES

- [ ]  Use fast tokenizers from 🤗 Tokenizers #33034
- [ ]  Run inference with multilingual models #33048
- [ ]  Use model-specific APIs #33030
- [ ]  Share a custom model #33031
- [ ]  Templates for chat models #33026
- [ ]  Trainer #33080
- [ ]  Run training on Amazon SageMaker #33071
- [ ]  Export to ONNX #33072
- [ ]  Export to TFLite #33077
- [ ]  Export to TorchScript #33079
- [ ]  Benchmarks #33023
- [ ]  Notebooks with examples #33049
- [ ]  Community resources #33027
- [ ]  Troubleshoot #33017
- [ ]  Interoperability with GGUF files #33037

2024-10-02 14:24 UTC, abodacs commented
@AhmedAlmaghz 
شفاك الله وعافاك أخى

سأحاول أراجع ﻷن السبوع القادم عندى امتحانات

2024-10-02 14:30 UTC, AhmedAlmaghz commented
حفظك الله ورعاك أخي عبدالله @abodacs 
بالتوفيق إن شاء الله في إمتحاناتك
اعمل approving  لكل PRs الجاهزة حتى يتم دمجها
لقد راجعت هذا الملف وأكملت الناقص أشكرك  يمكنك مراجعته

تحياتي وتقديري الكبيرين لشخصكم الكريم

2024-10-05 11:02 UTC, abodacs approved these changes
@AhmedAlmaghz 
برجاء معالجة التعارض

2024-10-05 19:17 UTC, closed without merging