[i18n-ar] Translated file : `docs/source/ar/model_memory_anatomy.md` into Arabic
huggingface/transformers pull request #33045
Opened 2024-08-22 20:21 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/model_memory_anatomy.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-09-26 20:59 UTC, abodacs requested changes
السﻻم عليكم

@AhmedAlmaghz 
تمت المراجعة 

جزاء الله خيرا

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +لفهم سبب ذلك بشكل أفضل، دعنا نلقي نظرة على عمليات النموذج واحتياجاته من الذاكرة.
```suggestion
يمكننا أن نرى أن حجم دفعة صغير نسبيًا يملأ تقريبًا ذاكرة GPU بالكامل. ومع ذلك، غالبًا ما يؤدي حجم دفعة أكبر  في تقارب نموذج أسرع أو أداء أفضل في النهاية. لذلك نريد أن نضبط حجم الدفعة وفقًا لاحتياجات النموذج لدينا وليس  مع قيود وحدة GPU. ما يثير الاهتمام هو أننا نستخدم ذاكرة أكثر بكثير من حجم النموذج. 
لفهم سبب ذلك بشكل أفضل، دعنا نلقي نظرة على عمليات النموذج واحتياجاته من الذاكرة.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +تتضمن هندسة المحولات 3 مجموعات رئيسية من العمليات مجمعة أدناه حسب كثافة الحساب.
```suggestion
تتضمن بنية المحولات 3 مجموعات رئيسية من العمليات مُجمعة أدناه حسب كثافة العمليات الحسابية.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +1. **التعاقدات المنسوجة**
```suggestion
1. **عمليات ضرب المصفوفات**
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +    تقوم الطبقات الخطية ومكونات الانتباه متعدد الرؤوس جميعها بعمليات **ضرب المصفوفة بالمصفوفة**. هذه العمليات هي الجزء الأكثر كثافة في الحساب من تدريب المحول.
```suggestion
    تقوم الطبقات الخطية ومكونات الانتباه متعدد الرؤوس جميعها بعمليات ضرب ** المصفوفة بالمصفوفة** على دفعات. هذه العمليات هي أكثر أجزاء تدريب المحولات كثافة من الناحية الحسابية.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +2. **التطبيعات الإحصائية**
```suggestion
2. **عمليات التسوية الإحصائية**
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +    Softmax والتطبيع الطبقي أقل كثافة في الحساب من التعاقدات المنسوجة، وتنطوي على عملية أو أكثر من عمليات **الاختزال**، والتي يتم تطبيق نتيجتها بعد ذلك عبر خريطة.
```suggestion
تُعد  عمليات  Softmax والتسوية الطبقية أقل كثافة من ناحية  الحسابية من عمليات ضرب المصفوفات، وتنطوي على عملية أو أكثر من عمليات **الاختزال**، والتي يتم تطبيق نتيجتها بعد ذلك عبر خريطة.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +3. **المشغلون عنصر الحكمة**
```suggestion
3. **العمليات على مستوى العناصر**
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +يمكن أن تكون هذه المعرفة مفيدة لمعرفة عند تحليل اختناقات الأداء.
```suggestion
    هذه هي العمليات المتبقية: **الانحيازات، والتسرب، ووظائف التنشيط، والوصلات المتبقية**. هذه هي عمليات أقل كثافة من الناحية الحسابية.

يمكن أن تكون هذه المعرفة مفيدة لمعرفة عند تحليل اختناقات الأداء.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +تم اشتقاق هذا الملخص من [Data Movement Is All You Need: A Case Study on Optimizing Transformers 2020](https://arxiv.org/abs/2007.00072)
```suggestion
هذا الملخص مُشتق من [نقل البيانات هو كل ما تحتاجه: دراسة حالة حول تحسين المحولات 2020](https://arxiv.org/abs/2007.00072)
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +6. ذاكرة محددة الوظائف
```suggestion
1. أوزان النموذج
2. الدول المُحسّن
3. المُتدرجات
4. تنشيطات المسار الأمامي المحفوظة لحساب  المُتدرجات
5. المخازن المؤقتة
6. ذاكرة محددة الوظائف
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +معلمة نموذج للدقة المختلطة الاستدلال، بالإضافة إلى ذاكرة التنشيط.
```suggestion
يتطلب نموذج نموذجي مدرب بدقة مختلطة 18 بايت للمُحسّن AdamW كل معلمة نموذج بالإضافة إلى ذاكرة التنشيط. للاستدلال لا توجد حالات مُحسّن و مُتدرجات، لذلك يمكننا طرح تلك. وهكذا ننتهي مع 6 بايت لكل 
معلمة نموذج للدقة المختلطة الاستدلال، بالإضافة إلى ذاكرة التنشيط.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +- 6 بايت * عدد المعلمات لتدريب الدقة المختلطة (يحافظ على نموذج في fp32 وواحد في fp16 في الذاكرة)
```suggestion
- 4 بايت * عدد المعلمات للتدريب على دقة fp32
- 6 بايت * عدد المعلمات لتدريب الدقة المختلطة (يحافظ على نموذج في fp32 وآخر بدقة fp16 في الذاكرة)
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +**حالات المحسن:**
```suggestion
**حالات المُحسّن:**
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +- 4 بايت * عدد المعلمات لمحسنات مثل SGD مع الزخم (يحافظ على حالة واحدة فقط)
```suggestion
- 8 بايت * عدد المعلمات للمُحسّن AdamW العادي (يحافظ على حالتين)
- 2 بايت * عدد المعلمات لمُحسّنات 8 بت AdamW مثل [bitsandbytes](https://github.com/TimDettmers/bitsandbytes)
- 4 بايت * عدد المعلمات لمُحسّنات مثل SGD مع الزخم momentum (يحافظ على حالة واحدة فقط)
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +**التدرجات**
```suggestion
**المُتدرجات**
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +- 4 بايت * عدد المعلمات للتدريب fp32 أو الدقة المختلطة (التدرجات تكون دائمًا في fp32)
```suggestion
- 4 بايت * عدد المعلمات للتدريب بدقة fp32 أو بدقة مختلطة (المُتدرجات تكون دائمًا بدقة fp32)
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +**تنشيطات إلى الأمام**
```suggestion
**تنشيطات المسار الأمامي**
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +- يعتمد الحجم على العديد من العوامل، وأهمها طول التسلسل وحجم المخفية وحجم الدفعة.
```suggestion
- يعتمد الحجم على العديد من العوامل، وأهمها طول التسلسل وحجم المخفية وحجم الدُفعة.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +هناك الإدخال والإخراج الذي يتم تمريره وإعادته بواسطة وظائف إلى الأمام والخلف وتنشيطات إلى الأمام المحفوظة لحساب التدرج.
```suggestion
هناك  المدخلات والمخرجات لذي يتم تمريرها وإرجاعها بواسطة وظائف المسار  الأمامي والمسار الخلفي وتنشيطات المسار الأمامي المحفوظة لحساب المُتدرجات.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +بشكل استراتيجي حول هذه المتغيرات المؤقتة وأحيانًا تحريرها بشكل صريح بمجرد عدم الحاجة إليها.
```suggestion
بالإضافة إلى ذلك، هناك جميع أنواع المتغيرات المؤقتة التي يتم تحريرها بمجرد الانتهاء من الحساب، ولكن في 
لحظة يمكن أن تتطلب هذه المتغيرات المؤقتة ذاكرة إضافية ويقد تؤدي إلى نفاد  الذاكرة المُخصصة (OOM). لذلك، عند البرمجة، من المهم التفكير بشكل استراتيجي حول هذه المتغيرات المؤقتة وأحيانًا تحريرها بشكل صريح بمجرد عدم الحاجة إليها.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +ثم، قد يكون لبرنامجك متطلبات ذاكرة خاصة. على سبيل المثال، عند إنشاء نص باستخدام البحث الشعاعي، يحتاج البرنامج
```suggestion
ثم، قد يكون لبرنامجك احتياجات خاصة بالذاكرة. على سبيل المثال، عند إنشاء نص باستخدام البحث الشعاعي، يحتاج البرنامج 
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +للحفاظ على عدة نسخ من الإدخالات والمخرجات.
```suggestion
إلى الاحتفاظ بنسخ متعددة من المدخلات والمخرجات.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +بالنسبة للضربات والطبقات الخطية، هناك 2x flops في الخلف مقارنة بالخط الأمامي، والتي تترجم عمومًا إلى ~2x أبطأ (أحيانًا أكثر، لأن الأحجام في الخلف تميل إلى أن تكون أكثر إزعاجًا). عادةً ما تكون التنشيط
```suggestion
بالنسبة للالتفافات والطبقات الخطية، هناك ضِعف عدد العمليات 2x flops في المسار الخلفى مقارنة بالمسار الأمامي، والتي يُترجم عمومًا إلى ~2x أبطأ (أحيانًا أكثر، لأن الأحجام في المسار الخلفى تميل إلى أن تكون أكثر صعوبة). عادةً ما تكون عمليات التنشيط محدودة بعرض  النطاق  الترددي، ومن المعتاد أن يتعين على التنشيط قراءة المزيد من البيانات في المسار الخلفى أكثر من المسار الأمامى.
```

2024-09-26 20:59 UTC, abodacs commented on docs/source/ar/model_memory_anatomy.md
> +والكتابة مرة واحدة، gradInput).
```suggestion
(على سبيل المثال، قراءة التنشيط المسار الأمامى مرة واحدة، وتكتب مرة واحدة، وبينما  تقرأ  عملية التنشيط الخلفي مرتين، gradOutput وإخراج الأمام، وتكتب مرة واحدة، gradInput).
```

2024-09-27 07:08 UTC, AhmedAlmaghz commented
Thank you @abodacs

2024-09-27 07:13 UTC, AhmedAlmaghz commented
اشكرك اخي عبدالله @abodacs  على جهودك الرائعة.

عمل رائع وعظيم 

التالي (الأخير في القائمة الحالية) : 🥇 

# CONCEPTUAL GUIDES

- [x]  Philosophy #33064
- [x]  Glossary #33038
- [x]  What 🤗 Transformers can do #33073
- [x]  How 🤗 Transformers solve tasks #33074
- [x]  The Transformer model family #33047
- [x]  Summary of the tokenizers #33078
- [ ]  Attention #33021
- [ ]  Padding and truncation #33050
- [ ]  BERTology #33024
- [ ]  Perplexity of fixed-length models #33063
- [ ]  Pipelines for webserver inference #33066
- [ ]  Model training anatomy #33045
- [ ] Getting the most out of LLMs #33043

2024-10-05 11:06 UTC, abodacs approved these changes
@AhmedAlmaghz
برجاء معالجة التعارض

2024-10-05 19:16 UTC, closed without merging