[i18n-ar] Translated file : `docs/source/ar/index.md` into Arabic
huggingface/transformers pull request #33040
Opened 2024-08-22 20:20 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/index.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-08-29 18:00 UTC, abodacs requested changes
شكرا على مجهودك با @AhmedAlmaghz   

اضفت بعض التعليقات

2024-08-30 15:01 UTC, abodacs approved these changes

2024-08-30 16:38 UTC, stevhliu commented on docs/source/ar/index.md
> +<!--يتم تحديث هذا الجدول تلقائيًا من الوحدات النمطية التلقائية مع _make fix-copies_. لا تقم بالتحديث يدويًا!-->
Do you mean translate the table or `make fix-copies`? It looks good to me here

2024-08-30 16:42 UTC, stevhliu reviewed
Thanks for translating `index.md`! Can you actually integrate this into #32696? You can check out my comment [here](https://github.com/huggingface/transformers/pull/32696#issuecomment-2315824767) for more information.

2024-08-30 16:42 UTC, stevhliu commented on docs/source/ar/index.md
> +لمحة عامة
I think you're missing the top level header here `# Transformers`

2024-08-30 16:42 UTC, stevhliu commented on docs/source/ar/index.md
> +آخر تحديث: 06/08/2024
```suggestion
```

2024-08-30 17:03 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33040). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-09-13 03:26 UTC, closed without merging