[i18n-ar] Translated file : `docs/source/ar/preprocessing.md` into Arabic
huggingface/transformers pull request #33068
Opened 2024-08-22 20:23 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/preprocessing.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-09-02 20:10 UTC, abodacs requested changes
السﻻم عليكم
شكرا لمجهودك 
@AhmedAlmaghz 
تم المراجعة

2024-09-02 20:10 UTC, abodacs commented on docs/source/ar/preprocessing.md
> +أساليب ما بعد المعالجة. تحول هذه الأساليب المخرجات الخام للنموذج إلى تنبؤات ذات معنى مثل صناديق الحدود،
```suggestion
تقوم هذه الطرق بتحويل النواتج الأولية للنموذج إلى تنبؤات ذات معنى مثل مربعات الحدود،
```

2024-09-02 20:10 UTC, abodacs commented on docs/source/ar/preprocessing.md
> +في بعض الحالات، على سبيل المثال، عند ضبط نموذج [DETR](./model_doc/detr) بدقة، يقوم النموذج بتطبيق زيادة المقياس في وقت التدريب. قد يتسبب ذلك في اختلاف أحجام الصور في دفعة واحدة. يمكنك استخدام [`DetrI
```suggestion
في بعض الحالات، على سبيل المثال، عند ضبط نموذج [DETR](./model_doc/detr) بدقة، يقوم النموذج بتطبيق زيادة المقياس أثناء التدريب. قد يتسبب ذلك في اختلاف أحجام الصور في دفعة واحدة. يمكنك استخدام [`DetrImageProcessor.pad`]
```

2024-09-02 20:10 UTC, abodacs commented on docs/source/ar/preprocessing.md
> +من [`DetrImageProcessor`] وتعريف `collate_fn` مخصص لتجميع الصور معًا.
```suggestion
من [`DetrImageProcessor`] وتحديد دالة `collate_fn` مخصصة لتجميع الصور معًا.
```

2024-09-02 20:10 UTC, abodacs commented on docs/source/ar/preprocessing.md
> +بالنسبة للمهام التي تتضمن إدخالات متعددة الوسائط، ستحتاج إلى معالج [processor](main_classes/processors) لإعداد مجموعة البيانات الخاصة بك للنمذجة. يربط المعالج بين كائنين للمعالجة مثل الرموز المميزة و
```suggestion
بالنسبة للمهام التي تتطلب مدخلات متعددة الوسائط، ستحتاج إلى معالج [processor](main_classes/processors) لإعداد مجموعة البيانات الخاصة بك لتناسب النموذج. يقترن المعالج بين  بمعالجين آخرين مثل محول النص إلى رمز ومستخرج الميزات.
```

2024-09-04 04:32 UTC, AhmedAlmaghz commented
Thank You @abodacs

2024-09-13 03:28 UTC, closed without merging