[i18n-ar] Translated file : `docs/source/ar/quicktour.md` into Arabic
huggingface/transformers pull request #33069
Opened 2024-08-22 20:23 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/quicktour.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-08-29 20:34 UTC, abodacs requested changes
سﻻم عليكم

شكرا لمجهودك @AhmedAlmaghz 

تم اضافة بعض تعليقات

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +يقوم النموذج بإخراج التنشيطات النهائية في سمة `logits`. طبق دالة softmax على `logits` لاسترداد الاحتمالات:
```suggestion
يُخرج النموذج التنشيطات النهائية في سمة `logits`. طبق دالة softmax على `logits` للحصول على الاحتمالات:
```

باختصار:

logits هي القيم الخام التي يحسبها النموذج، و softmax هي الدالة التي تحول هذه القيم إلى احتمالات يمكن فهمها بسهولة.

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +تخرج جميع نماذج 🤗 Transformers (PyTorch أو TensorFlow) المصفوفات *قبل* دالة التنشيط النهائية (مثل softmax) لأن دالة التنشيط النهائية غالبًا ما تكون مدمجة مع الخسارة. مخرجات النموذج عبارة عن فئات بيان
```suggestion
تخرج جميع نماذج 🤗 Transformers (PyTorch أو TensorFlow) المصفوفات *قبل* دالة التنشيط النهائية (مثل softmax) لأن دالة التنشيط النهائية غالبًا ما تكون مدمجة مع دالة الخسارة. نواتج النموذج عبارة عن فئات بيانات خاصة، لذلك يتم استكمال سماتها تلقائيًا في IDE. وتتصرف مخرجات النموذج مثل زوج مرتب أو قاموس (يمكنك الفهرسة باستخدام عدد صحيح ، شريحة، أو سلسلة)، وفي هذه الحالة، يتم تجاهل السمات التي تساوي None.
```

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +## بناء نموذج مخصص
```suggestion
## إنشاء نماذج مخصصة
```

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +يمكنك تعديل فئة تكوين النموذج لتغيير كيفية بناء النموذج. يحدد التكوين سمات النموذج، مثل عدد الطبقات المخفية أو رؤوس الاهتمام. تبدأ من الصفر عند تهيئة نموذج من فئة تكوين مخصص. يتم تهيئة سمات النموذج ب
```suggestion
يمكنك تعديل فئة تكوين النموذج لتغيير كيفية بناء النموذج. يحدد التكوين سمات النموذج، مثل عدد الطبقات المخفية أو رؤوس الاهتمام. تبدأ من الصفر عند تهيئة نموذج من فئة تكوين مخصصة. يتم تهيئة سمات النموذج بشكل عشوائي، ويجب تدريب النموذج قبل استخدامه للحصول على نتائج ذات معنى.
```

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +عندما تكون مستعدًا، اتصل بـ [`~Trainer.train`] لبدء التدريب:
```suggestion
عندما تكون مستعدًا، استدعِ [`~Trainer.train`] لبدء التدريب:
```

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +بالنسبة للمهام - مثل الترجمة أو تلخيص - التي تستخدم نموذج تسلسل إلى تسلسل، استخدم فئات [`Seq2SeqTrainer`] و [`Seq2SeqTrainingArguments`] بدلاً من ذلك.
```suggestion
بالنسبة للمهام - مثل الترجمة أو التلخيص - التي تستخدم نموذج تسلسل إلى تسلسل، استخدم فئات [`Seq2SeqTrainer`] و [`Seq2SeqTrainingArguments`] بدلاً من ذلك.
```

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +الآن بعد أن أكملت الجولة السريعة في 🤗 Transformers، راجع أدلةنا وتعرف على كيفية القيام بأشياء أكثر تحديدًا مثل كتابة نموذج مخصص، وضبط نموذج لمهمة، وكيفية تدريب نموذج باستخدام نص برمجي. إذا كنت مهتمًا
```suggestion
الآن بعد أن أكملت الجولة السريعة في 🤗 Transformers، راجع أدلتنا لمعرفة كيفية القيام بأشياء أكثر تحديدًا مثل كتابة نموذج مخصص، وضبط نموذج مسبق التدريب لمهمة معينة، وكيفية تدريب نموذج باستخدام نص برمجي. إذا كنت مهتمًا بمعرفة المزيد عن المفاهيم الأساسية لـ 🤗 Transformers، فاحصل على فنجان من القهوة واطلع على أدلة المفاهيم الخاصة بنا!
```

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +جميع النماذج عبارة عن [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model) قياسية، لذا يمكن تدريبها في TensorFlow باستخدام واجهة برمجة تطبيقات Keras. يوفر 🤗 Transformers طريق
```suggestion
جميع النماذج عبارة عن [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model) قياسية، لذا يمكن تدريبها في TensorFlow باستخدام واجهة برمجة تطبيقات Keras. يوفر 🤗 Transformers طريقة [`~TFPreTrainedModel.prepare_tf_dataset`] لتحميل مجموعة البيانات الخاصة بك بسهولة كـ `tf.data.Dataset` حتى تتمكن من البدء في التدريب على الفور باستخدام دالتي `compile` و`fit` في Keras.
```

2024-08-29 20:34 UTC, abodacs commented on docs/source/ar/quicktour.md
> +والطريقة الأخرى لتخصيص حلقة التدريب هي باستخدام [المستدعيات](./main_classes/callback). يمكنك استخدام المستدعيات للاندماج مع المكتبات الأخرى وفحص حلقة التدريب للإبلاغ عن التقدم أو إيقاف التدريب مبكرًا
```suggestion
والطريقة الأخرى لتخصيص حلقة التدريب هي باستخدام [المستدعيات](./main_classes/callback). يمكنك استخدام المستدعيات للتكامل مع المكتبات الأخرى ومراقبة حلقة التدريب للإبلاغ عن التقدم أو إيقاف التدريب مبكرًا. لا تعدل المستدعيات أي شيء في حلقة التدريب نفسها. لتخصيص شيء مثل دالة الخسارة، تحتاج إلى إنشاء فئة فرعية من [`Trainer`] بدلاً من ذلك.
```

2024-08-29 20:38 UTC, abodacs commented
Hi, @stevhliu 

Any tag `Tip` rendered from left-to-right instead of right-to-left

Any Tip :) to make it work in Arabic right-to-left

cc: @AhmedAlmaghz

2024-08-29 23:04 UTC, AhmedAlmaghz commented
اشكرك أخي عبدالله @abodacs  
جزيل الشكر على المراجعة والملاحظات القيمة.
تحياتي وتقديري الكبيرين لشخصكم الكريم

2024-08-29 23:10 UTC, AhmedAlmaghz commented
@abodacs 
مشكلة  RTL  و LTR سوف تٌحل عند تشغيل الوثائق في الموقع 
<html lang="ar" dir="RTL" >

2024-08-29 23:12 UTC, AhmedAlmaghz commented
@abodacs 

التالي : 
Installation #33041

2024-08-30 14:59 UTC, abodacs approved these changes

2024-08-30 16:50 UTC, stevhliu reviewed
Great work, thanks!

2024-08-30 17:06 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33069). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-09-13 03:27 UTC, closed without merging