[i18n-ar] Translated file : `docs/source/ar/pipeline_tutorial.md` into Arabic
huggingface/transformers pull request #33065
Opened 2024-08-22 20:23 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/pipeline_tutorial.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-09-01 20:44 UTC, abodacs requested changes
سﻻم عليكم
شكرا لمجهودك @AhmedAlmaghz 

تم اضافة بعض المﻻحظات

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +إذا كان لديك عدة مدخلات، فيمكنك تمرير إدخالك كقائمة:
```suggestion

```
لوجود نفس الجمله مكرره

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +الآن تبدو هذه النتيجة أكثر دقة! للحصول على مقارنة متعمقة حول Wav2Vec2 مقابل Whisper، راجع [دورة Audio Transformers](https://huggingface.co/learn/audio-course/chapter5/asr_models).
```suggestion
الآن تبدو هذه النتيجة أكثر دقة! لمقارنة عميقة حول Wav2Vec2 مقابل Whisper، راجع [دورة Audio Transformers](https://huggingface.co/learn/audio-course/chapter5/asr_models).
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +نحن نشجعك بشدة على التحقق من Hub للحصول على نماذج بلغات مختلفة، ونماذج متخصصة في مجالك، وأكثر من ذلك.
```suggestion
نشجعك بشدة على التحقق من Hub للحصول على نماذج بلغات مختلفة، ونماذج متخصصة في مجالك، وأكثر من ذلك.
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +أو التعامل مع الحالات الحدية بشكل أفضل من غيرها.
```suggestion
أو التعامل مع الحالات الخاصة بشكل أفضل من غيرها.
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +إذا كان لديك عدة مدخلات، فيمكنك تمرير إدخالك كقائمة:
```suggestion
إذا كان لديك عدة مدخلات، يمكنك تمرير مدخلك كقائمة:
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +تعد خطوط الأنابيب رائعة للتجريب نظرًا لأن التبديل من نموذج إلى آخر أمر بسيط؛ ومع ذلك، هناك بعض الطرق لتحسينها لأحمال عمل أكبر من التجريب. راجع الأدلة التالية التي تتناول بالتفصيل التكرار عبر مجموعات
```suggestion
تعد خطوط الأنابيب مثالية للتجريب نظرًا لأن التبديل من نموذج إلى آخر أمر بسيط للغاية؛ ومع ذلك، هناك بعض الطرق لتحسينها لأحمال عمل أكبر من التجريب. راجع الأدلة التالية التي تتعمق فى التكرار عبر مجموعات البيانات الكاملة أو استخدام خطوط الأنابيب في خادم ويب:
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +بدلاً من ذلك، يمكنك تعيين `device_map="auto"` لتحديد كيفية تحميل مخزنات النموذج وتخزينها تلقائيًا. يتطلب استخدام حجة `device_map` حزمة 🤗 [Accelerate](https://huggingface.co/docs/accelerate):
```suggestion
بدلاً من ذلك، يمكنك تعيين `device_map="auto"` لتحديد كيفية تحميل مخزنات النموذج وتخزينها تلقائيًا. يتطلب استخدام معامل `device_map` مكتبه 🤗 [Accelerate](https://huggingface.co/docs/accelerate):
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +بشكل افتراضي، لن تقوم خطوط الأنابيب بتجزئة الاستدلال لأسباب موضحة بالتفصيل [هنا](https://huggingface.co/docs/transformers/main_classes/pipelines#pipeline-batching). والسبب هو أن التجزئة ليست أسرع بال
```suggestion
بشكل افتراضي، لن تقوم خطوط الأنابيب بتجميع الاستدلال لأسباب مفصلة [هنا](https://huggingface.co/docs/transformers/main_classes/pipelines#pipeline-batching). والسبب هو أن التجميع ليست أسرع بالضرورة، ويمكن أن تكون أبطأ في الواقع في بعض الحالات.
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +هذا يشغل خط الأنابيب على ملفات الصوت الأربعة المقدمة، ولكنه سيمررها في دفعات من 2
```suggestion
هذا يشغل خط الأنابيب على ملفات الصوت الأربعة المتاحة، ولكنه سيمررها على دفعتين
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +إلى النموذج (الذي يوجد على وحدة معالجة الرسومات (GPU)، حيث من المرجح أن تساعد التجزئة) دون الحاجة إلى أي رمز إضافي منك.
```suggestion
إلى النموذج (الذي يوجد على وحدة معالجة الرسومات (GPU)، حيث من المرجح أن تساعد التجميع) دون الحاجة إلى أي رمز إضافي منك. 
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +يجب أن تتطابق الإخراج دائمًا مع ما كنت ستحصل عليه دون التجزئة. المقصود منه فقط كطريقة لمساعدتك في الحصول على مزيد من السرعة من خط الأنابيب.
```suggestion
يجب أن تتطابق الإخراج دائمًا مع ما كنت ستحصل عليه دون التجميع. المقصود منه فقط كطريقة لمساعدتك في الحصول على سرعة أكبر من خط الأنابيب.
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +يمكن لخطوط الأنابيب أيضًا تخفيف بعض تعقيدات التجزئة لأنه، بالنسبة لبعض خطوط الأنابيب، يجب تقسيم عنصر واحد (مثل ملف صوتي طويل) إلى أجزاء متعددة لمعالجته بواسطة نموذج. يقوم خط الأنابيب بأداء هذه التجزئ
```suggestion
يمكن لخطوط الأنابيب أيضًا تخفيف بعض تعقيدات التجميع لأنه، بالنسبة لبعض خطوط الأنابيب، يجب تقسيم عنصر واحد (مثل ملف صوتي طويل) إلى أجزاء متعددة لمعالجته بواسطة نموذج. يقوم خط الأنابيب بأداء هذه  العملية التي تسمى تجميع الأجزاء [*batch batching*](./main_classes/pipelines#pipeline-chunk-batching) نيابة عنك.
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +كما ترون، استنتج النموذج النص وأخرج أيضًا **متى** تم نطق الجمل المختلفة.
```suggestion
كما ترون، استنتج النموذج النص.وكذلك حدد **وقت** نطق الجمل المختلفة.
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +تتوفر العديد من المعلمات لكل مهمة، لذا تحقق من مرجع API لكل مهمة لمعرفة ما يمكنك العبث به!
```suggestion
تتوفر العديد من المعلمات لكل مهمة، لذا تحقق من مرجع API لكل مهمة لمعرفة ما يمكنك تعديله!
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +يمكن أيضًا تشغيل خط الأنابيب للاستدلال على مجموعة بيانات كبيرة. أسهل طريقة نوصي بها للقيام بذلك هي باستخدام مؤشر:
```suggestion
يمكن أيضًا تشغيل خط الأنابيب للاستدلال على مجموعة بيانات كبيرة. أسهل طريقة نوصي بها للقيام بذلك هي باستخدام المتكرر (iterator).:
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +يقوم المؤشر `data()` بإرجاع كل نتيجة، ويعترف خط الأنابيب تلقائيًا
```suggestion
يقوم المؤشر `data()` بإرجاع كل نتيجة، ويتعرف خط الأنابيب تلقائيًا
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +الإدخال قابل للتحديد ويبدأ في جلب البيانات أثناء
```suggestion
المدخل قابل للتحديد ويبدأ في جلب البيانات أثناء
```

2024-09-01 20:44 UTC, abodacs commented on docs/source/ar/pipeline_tutorial.md
> +نظرًا لأن التجزئة قد تسرع الأمور، فقد يكون من المفيد ضبط معلمة `batch_size` هنا.
```suggestion
نظرًا لأن التجميع قد تسرع الأمور، فقد يكون من المفيد ضبط معلمة `batch_size` هنا.
```

2024-09-04 04:13 UTC, AhmedAlmaghz commented
Thank you @abodacs

2024-09-13 03:27 UTC, closed without merging