[i18n-ar] Translated file : `docs/source/ar/training.md` into Arabic
huggingface/transformers pull request #33081
Opened 2024-08-22 20:24 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/training.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-09-02 21:43 UTC, abodacs requested changes
السﻻم عليكم
شكرا لمجهودك
@AhmedAlmaghz 

تمت المراجعة

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +بعد ذلك، قم بإنشاء فئة [`TrainingArguments`] والتي تحتوي على جميع فرط المعالم التي يمكنك ضبطها بالإضافة إلى أعلام لتنشيط خيارات التدريب المختلفة. بالنسبة لهذا البرنامج التعليمي، يمكنك البدء بفرط المع
```suggestion
بعد ذلك، قم بإنشاء كائن من فئة [`TrainingArguments`] والتي تحتوي على جميع العوامل والمتغيرات التي يمكنك ضبطها بالإضافة إلى خيارات تنشيط التدريب المختلفة. بالنسبة لهذا البرنامج التعليمي، يمكنك البدء بمعاملات التدريب الافتراضية [hyperparameters](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments)، ولكن لا تتردد في تجربتها للعثور على الإعدادات المثلى.
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +حدد مكان حفظ نقاط الفحص من تدريبك:
```suggestion
حدد مكان حفظ النسخ من تدريبك:
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +لا يقوم [`Trainer`] تلقائيًا بتقييم أداء النموذج أثناء التدريب. ستحتاج إلى تمرير دالة إلى [`Trainer`] لحساب الإبلاغ عن المقاييس. توفر مكتبة [🤗 Evaluate](https://huggingface.co/docs/evaluate/index) دا
```suggestion
لا يقوم [`Trainer`] تلقائيًا بتقييم أداء النموذج أثناء التدريب. ستحتاج إلى تمرير دالة إلى [`Trainer`] لحساب وإبلاغ المقاييس. توفر مكتبة [🤗 Evaluate](https://huggingface.co/docs/evaluate/index) دالة [`accuracy`](https://huggingface.co/spaces/evaluate-metric/accuracy) بسيطة يمكنك تحميلها باستخدام الدالة [`evaluate.load`] (راجع هذا [الدليل السريع](https://huggingface.co/docs/evaluate/a_quick_tour) لمزيد من المعلومات):
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +قم بالاتصال بـ [`~evaluate.compute`] على `metric` لحساب دقة تنبؤاتك. قبل تمرير تنبؤاتك إلى `compute`، تحتاج إلى تحويل logits إلى تنبؤات (تذكر أن جميع نماذج 🤗 Transformers تعيد logits):
```suggestion
استدعِ دالة [`~evaluate.compute`] على `metric` لحساب دقة تنبؤاتك. قبل تمرير تنبؤاتك إلى دالة `compute`، تحتاج إلى تحويل  النتائج الخام logits إلى تنبؤات نهائية (تذكر أن جميع نماذج 🤗 Transformers تعيد نتائج الخام logits):
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +...     التوقعات = np.argmax (logits، المحور = -1)
```suggestion
...     predictions = np.argmax(logits, axis=-1)
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +...     return metric.compute (التنبؤات = التوقعات، المراجع = العلامات)
```suggestion
...     return metric.compute(predictions=predictions, references=labels)

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +إذا كنت ترغب في مراقبة مقاييس التقييم الخاصة بك أثناء الضبط الدقيق، فحدد معلمة `eval_strategy` في حجج التدريب الخاصة بك للإبلاغ عن المقياس في نهاية كل حقبة:
```suggestion
إذا كنت ترغب في مراقبة مقاييس التقييم الخاصة بك أثناء الضبط الدقيق، فحدد معلمة `eval_strategy` في معاملات التدريب الخاصة بك لإظهار مقياس التقييم في نهاية كل حقبة تدريبه:
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +قم بإنشاء كائن [`Trainer`] باستخدام نموذجك، وحجج التدريب، ومجموعات البيانات التدريبية والاختبارية، ودالة التقييم:
```suggestion
قم بإنشاء كائن [`Trainer`] باستخدام نموذجك، ومعاملات التدريب، ومجموعات البيانات التدريبية والاختبارية، ودالة التقييم:
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +بعد ذلك، قم بتحميل أداة تعلم علامات الترقيم وقم بترميز البيانات كمصفوفات NumPy. لاحظ أن التصنيفات هي بالفعل قائمة من 0 و 1،
```suggestion
بعد ذلك، قم بتحميل أداة المُجزّئ اللغوي وقم بترميز البيانات كمصفوفات NumPy. لاحظ أن التصنيفات هي بالفعل قائمة من 0 و 1،
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +المصفوفات "المسننة"، لذا يجب أن يتم ترميز كل عينة بالطول الأقصى للعينة في مجموعة البيانات بأكملها. سيؤدي ذلك إلى زيادة حجم المصفوفة لديك، وستبطئ جميع رموز الترقيم من عملية التدريب أيضًا!
```suggestion
المصفوفات"غير المنتظمة"، لذا حشو كل عينة  إلى طول أطول عينة في مجموعة البيانات بأكملها. سيؤدي ذلك إلى زيادة حجم المصفوفة لديك، وستبطئ الرموز الزائده من عملية التدريب أيضًا!
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +قبل أن تتمكن من استخدام [`~TFPreTrainedModel.prepare_tf_dataset`]، ستحتاج إلى إضافة نواتج أداة تعلم علامات الترقيم إلى مجموعة البيانات الخاصة بك كأعمدة، كما هو موضح في
```suggestion
قبل أن تتمكن من استخدام [`~TFPreTrainedModel.prepare_tf_dataset`]، ستحتاج إلى إضافة مخرجات المُجزئ إلى مجموعة البيانات الخاصة بك كأعمدة، كما هو موضح في
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +لاحظ أنه في عينة التعليمات البرمجية أعلاه، تحتاج إلى تمرير أداة تعلم علامات الترقيم إلى `prepare_tf_dataset` حتى تتمكن من ترميز الدفعات بشكل صحيح أثناء تحميلها.
```suggestion
لاحظ أنه في عينة التعليمات البرمجية أعلاه، تحتاج إلى تمرير المُجزئ اللغوي إلى `prepare_tf_dataset` حتى تتمكن من حشو الدُفعات بشكل صحيح أثناء تحميلها.
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +إذا كانت جميع العينات في مجموعة البيانات الخاصة بك بنفس الطول ولم يكن الترميز ضروريًا، فيمكنك تخطي هذا الحجة.
```suggestion
إذا كانت جميع العينات في مجموعة البيانات الخاصة بك بنفس الطول ولم يكن الترميز ضروريًا، فيمكنك تخطي هذا المعامل.
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +فيمكنك استخدام حجة `collate_fn` بدلاً من ذلك لتمرير دالة يتم استدعاؤها لتحويل
```suggestion
فيمكنك استخدام معامل `collate_fn` بدلاً من ذلك لتمرير دالة يتم استدعاؤها لتحويل
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +حذف النموذج
```suggestion
del model
```

2024-09-02 21:43 UTC, abodacs commented on docs/source/ar/training.md
> +حذف المدرب
```suggestion
del trainer
```

2024-09-04 04:39 UTC, AhmedAlmaghz commented
Thank you @abodacs

2024-09-13 03:28 UTC, closed without merging