🌐 [i18n-KO] Translated `blip-2.md` to Korean
huggingface/transformers pull request #33516
Opened 2024-09-16 17:32 UTC by cjfghk5697

# What does this PR do?

Translated the `blip-2.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-09-19 01:42 UTC, mreraser commented on docs/source/ko/model_doc/blip-2.md
> +# BLIP-2
```suggestion
# BLIP-2[[blip-2]]
```

TOC가 누락되어 추가하였습니다.

2024-09-19 01:47 UTC, mreraser commented on docs/source/ko/model_doc/blip-2.md
> +BLIP-2 모델은 Junnan Li, Dongxu Li, Silvio Savarese, Steven Hoi의 [BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models](https://arxiv.org/abs/2301.12597
```suggestion
BLIP-2 모델은 Junnan Li, Dongxu Li, Silvio Savarese, Steven Hoi의 [BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models](https://arxiv.org/abs/2301.12597) 논문에서 제안되었습니다. BLIP-2는 동결된 사전 학습 이미지 인코더와 대규모 언어 모델(LLM)을 연결하는 12층의 경량 Transformer 인코더를 학습시켜, 여러 비전-언어 작업에서 SOTA(현재 최고의 성능)을 달성했습니다. 특히, BLIP-2는 800억 개의 파라미터를 가진 Flamingo 모델보다 제로샷 VQAv2에서 8.7% 더 높은 성능을 기록했으며, 학습 가능한 파라미터 수는 Flamingo보다 54배 적습니다.
```
조금 더 자연스러운 한국말로 바꿔보았습니다.

2024-09-19 01:49 UTC, mreraser commented on docs/source/ko/model_doc/blip-2.md
> +<small> BLIP-2 구조. <a href="https://arxiv.org/abs/2301.12597">논문 원본</a> 에서 발췌. </small>
```suggestion
<small> BLIP-2 구조. <a href="https://arxiv.org/abs/2301.12597">원본 논문</a> 에서 발췌. </small>
```
엄청 중요한건 아닌데, original paper는 `원본 논문`이 좀 더 맞지 않나 싶어 제안드립니다.

2024-09-28 10:36 UTC, yijun-lee requested changes

2024-09-28 10:36 UTC, yijun-lee commented on docs/source/ko/model_doc/blip-2.md
> +- BLIP-2는 이미지와 조건에 따라 텍스트 프롬프트를 입력받아 조건부 텍스트 생성합니다. 추론 시 [`generate`] 메소드를 사용하는 것이 권장됩니다.
```suggestion
- BLIP-2는 이미지와 조건에 따라 텍스트 프롬프트를 입력받아 조건부 텍스트를 생성합니다. 추론 시 [`generate`] 메소드를 사용하는 것이 권장됩니다.
```

2024-09-28 10:36 UTC, yijun-lee commented on docs/source/ko/model_doc/blip-2.md
> +- BLIP-2는 이미지와 조건에 따라 텍스트 프롬프트를 입력받아 조건부 텍스트 생성합니다. 추론 시 [`generate`] 메소드를 사용하는 것이 권장됩니다.
'조건부 텍스트를 생성합니다' 혹은 '조건부 텍스트 생성을 수행합니다'가 보다 자연스러울 것 같습니다!

2024-09-28 10:36 UTC, yijun-lee commented on docs/source/ko/model_doc/blip-2.md
> +- BLIP-2는 이미지와 조건에 따라 텍스트 프롬프트를 입력받아 조건부 텍스트 생성합니다. 추론 시 [`generate`] 메소드를 사용하는 것이 권장됩니다.
이외에는 완벽한 것 같습니다. 수고 많으셨습니다 :)

2024-10-09 00:46 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33516). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-09 01:00 UTC, stevhliu approved these changes
Thanks, we can merge once the conflict is resolved! 🤗

2024-10-15 18:21 UTC, merged