🌐 [i18n-KO] Translated `logging.md` to Korean
huggingface/transformers pull request #33543
Opened 2024-09-17 15:31 UTC by chhaewxn

# What does this PR do?

Translated the `logging.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-09-28 16:14 UTC, fabxoe requested changes
fix: suggestions

2024-09-28 16:14 UTC, fabxoe commented on docs/source/ko/main_classes/logging.md
> +아래에서 `captureWarnings` 메서드에 대한 참고 사항을 확인할 수 있습니다.
```suggestion
아래에서 `captureWarnings` 메소드에 대한 참고 사항을 확인할 수 있습니다.
```
이 부분은 glossary를 따라서 `메소드`로 바꿨어요. 개인적으로 오히려 `메서드`가 다른 책이나 튜토리얼에서 충분히 많이 쓰이고 있어서 사람들에게 익숙하고 혼용해도 문제가 없다고 생각을 하는데, 팍팍 하지만 일단 통일감을 위해서 바꿨어요. :)

2024-09-30 05:07 UTC, jun048098 reviewed
fix: suggestionfix: suggestions

2024-09-30 05:07 UTC, jun048098 commented on docs/source/ko/main_classes/logging.md
> +이 로깅 모듈의 모든 메서드는 아래에 문서화되어 있으며, 주요 메서드는 현재 로거의 출력 수준을 가져오는 [logging.get_verbosity]와 원하는 출력 수준으로 설정하는 [logging.set_verbosity]입니다. 출력 수준은 (가장 적은 출력에서 가장 많은 출력 순으로) 다음과 같으며, 해당 수준에 대응하는 정수 값은 괄호 안에 표시됩니
```suggestion
이 로깅 모듈의 모든 메서드는 아래에 문서화되어 있으며, 주요 메서드는 현재 로거의 출력 수준을 가져오는 [logging.get_verbosity]와 원하는 출력 수준으로 설정하는 [logging.set_verbosity]입니다. 출력 수준은 (가장 적은 출력에서 가장 많은 출력 순으로) 다음과 같으며, 해당 수준에 대응하는 정숫값은 괄호 안에 표시됩니다.
```

2024-09-30 05:07 UTC, jun048098 commented on docs/source/ko/main_classes/logging.md
> +- `transformers.logging.CRITICAL` 또는 `transformers.logging.FATAL` (정수 값, 50): 가장 심각한 오류만 보고합니다.
```suggestion
- `transformers.logging.CRITICAL` 또는 `transformers.logging.FATAL` (정숫값, 50): 가장 심각한 오류만 보고합니다.
```

2024-09-30 05:07 UTC, jun048098 commented on docs/source/ko/main_classes/logging.md
> +- `transformers.logging.ERROR` (정수 값, 40): 오류만 보고합니다.
```suggestion
- `transformers.logging.ERROR` (정숫값, 40): 오류만 보고합니다.
```

2024-09-30 05:07 UTC, jun048098 commented on docs/source/ko/main_classes/logging.md
> +- `transformers.logging.WARNING` 또는 `transformers.logging.WARN` (정수 값, 30): 오류와 경고만 보고합니다. 이는 라이브러리에서 기본으로 사용되는 수준입니다.
```suggestion
- `transformers.logging.WARNING` 또는 `transformers.logging.WARN` (정숫값, 30): 오류와 경고만 보고합니다. 이는 라이브러리에서 기본으로 사용되는 수준입니다.
```

2024-09-30 05:07 UTC, jun048098 commented on docs/source/ko/main_classes/logging.md
> +- `transformers.logging.INFO` (정수 값, 20): 오류, 경고, 그리고 기본적인 정보를 보고합니다.
```suggestion
- `transformers.logging.INFO` (정숫값, 20): 오류, 경고, 그리고 기본적인 정보를 보고합니다.
```

2024-09-30 05:07 UTC, jun048098 commented on docs/source/ko/main_classes/logging.md
> +- `transformers.logging.DEBUG` (정수 값, 10): 모든 정보를 보고합니다.
```suggestion
- `transformers.logging.DEBUG` (정숫값, 10): 모든 정보를 보고합니다.
```

2024-10-01 14:29 UTC, ahnjj requested changes

2024-10-01 14:29 UTC, ahnjj commented on docs/source/ko/main_classes/logging.md
> +라이브러리 개발자에게는 다음과 같은 지침을 따르는 것이 좋습니다.
```suggestion
라이브러리 개발자는 다음과 같은 지침을 따르는 것이 좋습니다.
```

2024-10-01 14:29 UTC, ahnjj commented on docs/source/ko/main_classes/logging.md
> +- `warnings`는 라이브러리 개발자와 `transformers`에 의존하는 라이브러리 개발자들에게 유리할 것입니다.
```suggestion
- `warnings`는 라이브러리 개발자와 `transformers`에 의존하는 라이브러리 개발자들에게 유리합니다.
```
더 자연스러운 것 같아 표현을 바꿔봤어요! :)

2024-10-01 14:29 UTC, ahnjj commented on docs/source/ko/main_classes/logging.md
> +- `logging`은 평범한 프로젝트에서 라이브러리를 개발하기보다는 라이브러리를 사용하는 최종 사용자들에게 유리할 것입니다.
```suggestion
- `logging`은 일반적인 프로젝트 라이브러리 개발자보다는, 라이브러리를 사용하는 최종 사용자들에게 유리할 것입니다.
```
더 이해가 될것 같은 표현으로 개발자를 붙여봤어요!

2024-10-07 22:22 UTC, stevhliu approved these changes
Thanks! 🤗

2024-10-07 22:32 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33543). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-07 22:34 UTC, merged