🌐 [i18n-KO] Translated `model_doc/patchtst.md` to Korean
huggingface/transformers pull request #33589
Opened 2024-09-19 11:36 UTC by fabxoe

# What does this PR do?

Translated the `model_doc/patchtst.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-10-04 13:42 UTC, jun048098 reviewed
fix: docs suggestions

2024-10-04 13:42 UTC, jun048098 commented on docs/source/ko/model_doc/patchtst.md
> +## Usage tips[[usage-tips]]
```suggestion
## 사용 팁[[usage-tips]]
```

2024-10-05 02:20 UTC, heuristicwave commented on docs/source/ko/model_doc/patchtst.md
> +    우리의 채널 독립적 패치 시계열 트랜스포머(PatchTST)는 최신 트랜스포머 기반 모델들과 비교했을 때 장기 예측 정확도를 크게 향상시킬 수 있습니다. 또한 모델을 자기 감독 사전 훈련 작업에 적용하여, 대규모 데이터셋에 대해 감독 학습시키는 것을 능가하는 아주 뛰어난 미세 조정 성능을 달성했습니다. 한 데이터셋에서 마스크된 사전 훈련 표현을 다
```suggestion
    우리의 채널 독립적 패치 시계열 트랜스포머(PatchTST)는 최신 트랜스포머 기반 모델들과 비교했을 때 장기 예측 정확도를 크게 향상시킬 수 있습니다. 또한 모델을 자기지도 사전 훈련 작업에 적용하여, 대규모 데이터셋에 대한 지도 학습을 능가하는 아주 뛰어난 미세 조정 성능을 달성했습니다. 한 데이터셋에서 마스크된 사전 훈련 표현을 다른 데이터셋으로 전이하는 것도 최고 수준의 예측 정확도(SOTA)를 산출했습니다.*
```

2024-10-05 02:20 UTC, heuristicwave commented on docs/source/ko/model_doc/patchtst.md
> +    우리의 채널 독립적 패치 시계열 트랜스포머(PatchTST)는 최신 트랜스포머 기반 모델들과 비교했을 때 장기 예측 정확도를 크게 향상시킬 수 있습니다. 또한 모델을 자기 감독 사전 훈련 작업에 적용하여, 대규모 데이터셋에 대해 감독 학습시키는 것을 능가하는 아주 뛰어난 미세 조정 성능을 달성했습니다. 한 데이터셋에서 마스크된 사전 훈련 표현을 다
Glossary를 참고하여 수정했습니다.

2024-10-05 03:00 UTC, nuatmochoi requested changes

2024-10-08 21:48 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33589). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:28 UTC, stevhliu reviewed
Thanks! Just one question about the consistency of translations, but otherwise, we should be able to merge!

2024-10-08 23:28 UTC, stevhliu commented on docs/source/ko/model_doc/patchtst.md
> +## Overview[[overview]]
I noticed in other PRs, the `Overview` is translated to `개요`. Can we also do that here to keep it consistent (same with `Usage tips` and `Resources`)?

2024-10-09 03:17 UTC, fabxoe reviewed
fix: resolve suggestions

2024-10-09 03:17 UTC, fabxoe commented on docs/source/ko/model_doc/patchtst.md
> +## Resources[[resources]]
```suggestion
## 자료[[resources]]
```

2024-10-09 18:15 UTC, stevhliu approved these changes
Thanks again! 👍

2024-10-09 18:15 UTC, merged