🌐 [i18n-KO] Translated `model_doc/informer.md` to Korean
huggingface/transformers pull request #33585
Opened 2024-09-19 10:21 UTC by fabxoe

# What does this PR do?

Translated the `model_doc/informer.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-09-30 13:43 UTC, ahnjj requested changes

2024-09-30 13:43 UTC, ahnjj commented on docs/source/ko/model_doc/informer.md
> +해당 논문의 초록입니다:
```suggestion
논문 초록:
```

2024-09-30 13:43 UTC, ahnjj commented on docs/source/ko/model_doc/informer.md
> +*실제로 많은 응용프로그램에서는 장기 시퀀스 시계열 예측(LSTF)을 필요로 합니다. LSTF는 모델의 높은 예측 능력을 요구하며, 이는 출력과 입력간의 정확한 장거리 의존성 결합을 효율적으로 포착하는 능력입니다. 최근 연구에 따르면 트랜스포머가 예측 능력을 향상시킬 수 있는 잠재력을 보여주고 있습니다. 그러나 트랜스포머를 LSTF에 직접 적용하는 것을
```suggestion
*실제로 많은 응용프로그램에서는 장기 시퀀스 시계열 예측(LSTF)을 필요로 합니다. LSTF는 출력 - 입력 간 정확한 장기 의존성 결합도를 포착해내는 높은 예측 능력을 모델에 요구합니다. 최근 연구들은 예측 능력을 향상시킬 수 있는 트랜스포머의 잠재력을 보여주고 있습니다. 그러나, 트랜스포머를 LSTF에 직접 적용하지 못하도록 막는 몇 심각한 문제점들이 있습니다. 예로, 이차 시간 복잡도, 높은 메모리 사용량, 인코더-디코더 아키텍처의 본질적 한계를 들 수 있습니다. 이러한 문제를 해결하기 위해 LSTF를 위한 효율적인 트랜스포머 기반 모델인 Informer를 설계했습니다.
```

2024-09-30 13:43 UTC, ahnjj commented on docs/source/ko/model_doc/informer.md
> +(ii) 자기 주의 증류는 계단식 레이어 입력을 반으로 줄여 지배적인 주의를 강조하고 극도로 긴 입력 시퀀스를 효율적으로 처리합니다.
```suggestion
(ii) 셀프 어텐션 증류는 계단식 레이어 입력을 반으로 줄여 지배적인 어텐션을 강조하고 극단적으로 긴 입력 시퀀스를 효율적으로 처리합니다. 
```

2024-09-30 13:43 UTC, ahnjj commented on docs/source/ko/model_doc/informer.md
> +(iii) 생성 스타일 디코더는 개념적으로 단순하지만 장기 시계열 시퀀스를 단계별 방식이 아닌 한 번의 전방 연산으로 예측하여 장기 시퀀스 예측의 추론 속도를 크게 향상시킵니다. 네 개의 대규모 데이터셋에 대한 광범위한 실험은 Informer가 기존 방법들을 크게 능가하며 LSTF 문제에 새로운 해결책을 제공함을 보여줍니다.*
```suggestion
(iii) 생성 스타일 디코더는 개념적으로 단순하지만 장기 시계열 시퀀스를 단계별 방식이 아닌 한 번의 전방 연산으로 예측하여 장기 시퀀스 예측의 추론 속도를 크게 향상시킵니다. 4개의 대규모 데이터셋에 걸친 광범위한 실험은 Informer가 기존 방법들을 크게 능가하며 LSTF 문제에 새로운 해결책을 제공함을 보여줍니다.*
```

2024-09-30 13:43 UTC, ahnjj commented on docs/source/ko/model_doc/informer.md
> +시작하는 데 도움이 되는 Hugging Face와 community 자료 목록(🌎로 표시됨) 입니다. 여기에 포함될 자료를 제출하고 싶으시다면 PR(Pull Request)를 열어주세요. 리뷰 해드리겠습니다! 자료는 기존 자료를 복제하는 대신 새로운 내용을 담고 있어야 합니다.
```suggestion
초심자분들께 도움이 될 Hugging Face와 community 공식 자료 목록(🌎로 표시됨) 입니다. 이 커뮤니티에 속할 자료를 제출하고 싶으시다면, PR(Pull Request)를 열어주세요. 리뷰 해드리겠습니다! 자료는 기존 자료를 복제하는 대신 새로운 내용을 담고 있어야 합니다.
```

2024-10-04 13:32 UTC, jun048098 reviewed
fix: docs suggestions

2024-10-04 13:32 UTC, jun048098 commented on docs/source/ko/model_doc/informer.md
> +이 모델은 [elisim](https://huggingface.co/elisim)와 [kashif](https://huggingface.co/kashif)에 의해 기여 되었습니다.
```suggestion
이 모델은 [elisim](https://huggingface.co/elisim)와 [kashif](https://huggingface.co/kashif)가 기여했습니다.
```

2024-10-07 03:32 UTC, fabxoe reviewed
fix: resolve suggestions

2024-10-08 21:47 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33585). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:33 UTC, stevhliu approved these changes
Thank you!

2024-10-09 17:41 UTC, merged