🌐 [i18n-KO] Translated `model_doc/time_series_transformer.md` to Korean
huggingface/transformers pull request #33596
Opened 2024-09-19 15:34 UTC by fabxoe

# What does this PR do?

Translated the `model_doc/time_series_transformer.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

2024-09-30 14:44 UTC, ahnjj requested changes

2024-09-30 14:44 UTC, ahnjj commented on docs/source/ko/model_doc/time_series_transformer.md
> +# Time Series Transformer[[time-series-transformer]]
```suggestion
# 시계열 트랜스포머 [[time-series-transformer]]
```

2024-09-30 14:44 UTC, ahnjj commented on docs/source/ko/model_doc/time_series_transformer.md
> +## Usage tips[[usage-tips]]
```suggestion
## 활용 팁 [[usage-tips]]
```

2024-09-30 14:44 UTC, ahnjj commented on docs/source/ko/model_doc/time_series_transformer.md
> +## Resources[[resources]]
```suggestion
## 자료 [[resources]]
```

2024-09-30 14:44 UTC, ahnjj commented on docs/source/ko/model_doc/time_series_transformer.md
> +## Overview[[overview]]
```suggestion
## 개요[[overview]]
```

2024-09-30 14:44 UTC, ahnjj commented on docs/source/ko/model_doc/time_series_transformer.md
> +시작하는 데 도움이 되는 Hugging Face와 community 자료 목록(🌎로 표시됨) 입니다. 여기에 포함될 자료를 제출하고 싶으시다면 PR(Pull Request)를 열어주세요. 리뷰 해드리겠습니다! 자료는 기존 자료를 복제하는 대신 새로운 내용을 담고 있어야 합니다.
```suggestion
초심자에게 도움이 될 Hugging Face와 커뮤니티 자료 목록(🌎로 표시됨) 입니다. 이곳에 포함될 자료를 제출하고 싶으시다면 PR(Pull Request)를 열어주세요. 리뷰 해드리겠습니다! 자료는 기존 자료를 복제하는 대신 새로운 내용을 담고 있어야 합니다.
```

2024-09-30 15:27 UTC, chhaewxn reviewed
전반적으로 깔끔하게 번역을 잘해주셔서 많이 배울 수 있었습니다 😊😊 자연스럽게 다듬을 수 있는 몇 가지 포인트와 오타 부분만 수정 제안드려요!

2024-09-30 15:27 UTC, chhaewxn commented on docs/source/ko/model_doc/time_series_transformer.md
> +- 다은 라이브러리의 모델들과 마찬가지로, [`TimeSeriesTransformerModel`]은 상단에 헤드가 없는 기본적인 트랜스포머 입니다. [`TimeSeriesTransformerForPrediction`]은 상단에 분포 헤드를 추가하여 시계열 예측에 사용할 수 있습니다. 이 모델은 이른바 확률적 예측 모델이며, 포인트 예측 모델이 아닙니다.
```suggestion
- 다른 라이브러리의 모델들과 마찬가지로, [`TimeSeriesTransformerModel`]은 상단에 헤드가 없는 기본적인 트랜스포머 입니다. [`TimeSeriesTransformerForPrediction`]은 상단에 분포 헤드를 추가하여 시계열 예측에 사용할 수 있습니다. 이 모델은 이른바 확률적 예측 모델이며, 포인트 예측 모델이 아닙니다. 즉 샘플링할 수 있는 분포를 학습하며, 값을 직접 출력 하지는 않습니다.
```

2024-09-30 15:27 UTC, chhaewxn commented on docs/source/ko/model_doc/time_series_transformer.md
> +- [`TimeSeriesTransformerForPrediction`]은 두개의 블록으로 구성되어 있습니다. 인코더는 `context_length`의  시계열 값을 입력(`past_values`라고 부름)으로 받아들이며, 디코더는 미래의 `prediction_length`만큼 시계열 값을 예측합니다(called `future_values`라고 부름).
```suggestion
- [`TimeSeriesTransformerForPrediction`]은 두개의 블록으로 구성되어 있습니다. 인코더는 `context_length`의  시계열 값을 입력(`past_values`라고 부름)으로 받아들이며, 디코더는 미래의 `prediction_length`만큼 시계열 값을 예측합니다(`future_values`라고 부름). 학습중에는 모델에 `past_values` 와 `future_values`쌍을 모델에 제공해야 합니다.
```
called 번역 과정에서 삭제가 안된 것 같아 제거하였습니다.

2024-09-30 15:27 UTC, chhaewxn commented on docs/source/ko/model_doc/time_series_transformer.md
> +    예시: 특정 시계열 값이 8월 11일에 얻어졌다면, [11, 8]을 시간 특성 벡터로 사용할 수 있습니다 (11은 "월의 일", 8은 "연도의 월").
```suggestion
    예시: 특정 시계열 값이 8월 11일에 기록되었다면, [11, 8]을 시간 특성 벡터로 사용할 수 있습니다 (11은 "월의 일", 8은 "연도의 월").
```
시계열 데이터 관련 맥락에서 얻어지다 -> 기록되어지다가 더 적합할 것 같아 제안드립니다.

2024-10-04 13:28 UTC, jun048098 commented on docs/source/ko/model_doc/time_series_transformer.md
> +- 다은 라이브러리의 모델들과 마찬가지로, [`TimeSeriesTransformerModel`]은 상단에 헤드가 없는 기본적인 트랜스포머 입니다. [`TimeSeriesTransformerForPrediction`]은 상단에 분포 헤드를 추가하여 시계열 예측에 사용할 수 있습니다. 이 모델은 이른바 확률적 예측 모델이며, 포인트 예측 모델이 아닙니다.
```suggestion
- 다은 라이브러리의 모델들과 마찬가지로, [`TimeSeriesTransformerModel`]은 상단에 헤드가 없는 기본적인 트랜스포머입니다. [`TimeSeriesTransformerForPrediction`]은 상단에 분포 헤드를 추가하여 시계열 예측에 사용할 수 있습니다. 이 모델은 이른바 확률적 예측 모델이며, 포인트 예측 모델이 아닙니다. 즉 샘플링할 수 있는 분포를 학습하며, 값을 직접 출력 하지는 않습니다.
```

2024-10-04 13:29 UTC, jun048098 reviewed
fix: docs suggestions

2024-10-07 03:37 UTC, fabxoe reviewed
fix: resolve suggestions

2024-10-07 03:38 UTC, fabxoe reviewed
fix: resolve suggestions

2024-10-07 03:39 UTC, fabxoe reviewed
fix: resolve suggestions

2024-10-08 21:47 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33596). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:35 UTC, stevhliu approved these changes
Thanks much! 🤗

2024-10-09 17:40 UTC, merged