🌐 [i18n-KO] Translated `main_classes/model.md` to Korean
huggingface/transformers pull request #33606
Opened 2024-09-20 02:57 UTC by fabxoe

# What does this PR do?

Translated the `main_classes/model.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-10-03 12:34 UTC, chhaewxn reviewed
양질의 번역을 다수 해주셔서 많이 배우고 갑니다🤗👍

2024-10-03 12:34 UTC, chhaewxn commented on docs/source/ko/main_classes/model.md
> +기본 클래스 [`PreTrainedModel`], [`TFPreTrainedModel`], [`FlaxPreTrainedModel`]는 로컬 파일과 디렉토리로부터 모델을 로드하고 저장하거나 또는 (허깅페이스 AWS S3 리포지토리로부터 다운로드된) 라이브러리에서 제공하는 사전훈련 모델 설정값을 로드하고 저장하는 것을 지원하는 기본 메소드를 구현하였습니다.
```suggestion
기본 클래스 [`PreTrainedModel`], [`TFPreTrainedModel`], [`FlaxPreTrainedModel`]는 로컬 파일과 디렉토리로부터 모델을 로드하고 저장하거나 또는 (허깅페이스 AWS S3 리포지토리로부터 다운로드된) 라이브러리에서 제공하는 사전 훈련된 모델 설정을 로드하고 저장하는 것을 지원하는 기본 메소드를 구현하였습니다.   
```

2024-10-03 12:34 UTC, chhaewxn commented on docs/source/ko/main_classes/model.md
> +- 모델의 어텐션 헤드를 가지치기합니다.
```suggestion
- 모델의 어텐션 헤드를 가지치기 합니다.
```

2024-10-03 12:34 UTC, chhaewxn commented on docs/source/ko/main_classes/model.md
> +사용자정의 모델은 superfast init이 특정모델에 적용될 수 있는지 여부를 결정하는 `_supports_assign_param_buffer`도 포함해야합니다.
```suggestion
사용자 정의 모델은 초고속 초기화가 특정 모델에 적용될 수 있는지 여부를 결정하는 `_supports_assign_param_buffer`도 포함해야 합니다.
```
superfast init도 번역을 하면 좋을 것 같아 제안드립니다!😊

2024-10-04 04:42 UTC, ahnjj requested changes

2024-10-04 04:42 UTC, ahnjj commented on docs/source/ko/main_classes/model.md
> +기본 클래스 [`PreTrainedModel`], [`TFPreTrainedModel`], [`FlaxPreTrainedModel`]는 로컬 파일과 디렉토리로부터 모델을 로드하고 저장하거나 또는 (허깅페이스 AWS S3 리포지토리로부터 다운로드된) 라이브러리에서 제공하는 사전훈련 모델 설정값을 로드하고 저장하는 것을 지원하는 기본 메소드를 구현하였습니다.
```suggestion
기본 클래스 [`PreTrainedModel`], [`TFPreTrainedModel`], [`FlaxPreTrainedModel`]는 로컬 파일 및 디렉토리에서 모델을 로드하고 저장하거나,
 또는 허깅페이스 AWS S3 리포지토리에서 다운로드한 라이브러리에서 제공하는 사전훈련 모델 설정값으로부터 모델을 로드하고 저장하는 기본 메소드를 구현하였습니다.   
```
가독성을 높이려 표현을 바꿔보았습니다 !

2024-10-04 04:42 UTC, ahnjj commented on docs/source/ko/main_classes/model.md
> +[`PreTrainedModel`]과 [`TFPreTrainedModel`]은 또한 모든 모델들에 공통적으로 지원하는 몇가지 메소드를 구현하였습니다:
```suggestion
[`PreTrainedModel`]과 [`TFPreTrainedModel`]은 모든 모델들에 공통적으로 지원되는 몇 메소드를 구현하였습니다:
```

2024-10-04 04:42 UTC, ahnjj commented on docs/source/ko/main_classes/model.md
> +`test_save_and_load_from_pretrained`이 실패하면, 당신의 모델이 `_supports_assign_param_buffer`를 필요로 하는지 확인하세요.
```suggestion
`test_save_and_load_from_pretrained` 실패 시, 모델이 `_supports_assign_param_buffer`를 필요로 하는지 확인하세요.
```

2024-10-04 07:08 UTC, jun048098 reviewed
fix: docs suggestion

2024-10-04 07:08 UTC, jun048098 commented on docs/source/ko/main_classes/model.md
> +각 모델에 공통인 다른 메소드들은 다음과 같은 클래스에 정의 되어있습니다.
표현을 바꾸었습니다.

2024-10-07 04:52 UTC, fabxoe commented on docs/source/ko/main_classes/model.md
> +사용자 정의 모델은 초고속 초기화가 특정 모델에 적용될 수 있는지 여부를 결정하는 `_supports_assign_param_buffer`도 포함해야 합니다.
```suggestion
사용자 정의 모델은 초고속 초기화(superfast init)가 특정 모델에 적용될 수 있는지 여부를 결정하는 `_supports_assign_param_buffer`도 포함해야 합니다.
```

2024-10-07 04:53 UTC, fabxoe commented on docs/source/ko/main_classes/model.md
> +[`PreTrainedModel`]과 [`TFPreTrainedModel`]은 또한 모든 모델들에 공통적으로 지원하는 몇가지 메소드를 구현하였습니다:
```suggestion
[`PreTrainedModel`]과 [`TFPreTrainedModel`]은 또한 모든 모델들을 공통적으로 지원하는 메소드 여러개를 구현하였습니다:
```

2024-10-08 21:48 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33606). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:58 UTC, stevhliu approved these changes
Thanks, we can merge once the conflict is resolved! 🤗

2024-10-09 17:40 UTC, merged