🌐 [i18n-KO] Translated `main_classes/onnx.md` to Korean
huggingface/transformers pull request #33601
Opened 2024-09-19 17:47 UTC by fabxoe

# What does this PR do?

Translated the `main_classes/onnx.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-10-04 05:29 UTC, ahnjj requested changes

2024-10-04 05:29 UTC, ahnjj commented on docs/source/ko/main_classes/onnx.md
> +각 ONNX 설정은 다양한 유형의 토폴로지나 작업에 대해 모델을 내보낼 수 있게 해주는 _features_ 세트와 연관되어 있습니다.
```suggestion
각 ONNX 설정은 다양한 유형의 토폴로지나 작업의 모델을 익스포트 해주는 _features_ 세트와 관련이 있습니다.
```
export가 glossary에 안올라와 있어서, 임의로 익스포트로 바꿔보았습니다!

2024-10-04 05:29 UTC, ahnjj commented on docs/source/ko/main_classes/onnx.md
> +* 인코더 기반 모델은 [`~onnx.config.OnnxConfig`]에서 상속받습니다.
```suggestion
* 인코더 기반 모델은 [`~onnx.config.OnnxConfig`]을 상속받습니다.
```

2024-10-04 05:29 UTC, ahnjj commented on docs/source/ko/main_classes/onnx.md
> +* 디코더 기반 모델은 [`~onnx.config.OnnxConfigWithPast`]에서 상속받습니다.
```suggestion
* 디코더 기반 모델은 [`~onnx.config.OnnxConfigWithPast`]을 상속받습니다.
```

2024-10-04 05:29 UTC, ahnjj commented on docs/source/ko/main_classes/onnx.md
> +* 인코더-디코더 기반 모델은 [`~onnx.config.OnnxSeq2SeqConfigWithPast`]에서 상속받습니다.
```suggestion
* 인코더-디코더 기반 모델은 [`~onnx.config.OnnxSeq2SeqConfigWithPast`]을 상속받습니다.
```

2024-10-04 05:29 UTC, ahnjj commented on docs/source/ko/main_classes/onnx.md
> +내보내고자 하는 모델 아키텍처의 유형에 따라 상속받아야 할 세 가지 추상 클래스를 제공합니다:
```suggestion
익스포트하고자하는 모델 아키텍처 유형에 따라 상속받아야 할 세 가지 추상 클래스를 제공합니다:
```

2024-10-04 05:29 UTC, ahnjj commented on docs/source/ko/main_classes/onnx.md
> +🤗 트랜스포머는 `transformers.onnx` 패키지를 제공하며, 패키지를 통해 설정 객체를 활용함으로써 모델 체크포인트를 ONNX 그래프로 변환할 수 있게 합니다.
```suggestion
🤗 트랜스포머는 `transformers.onnx` 패키지를 제공하며, 이 패키지는 설정 객체를 활용하여 모델 체크포인트를 ONNX 그래프로 변환할 수 있게 합니다.
```

2024-10-05 03:29 UTC, nuatmochoi requested changes
다른 트랜스포머 문서에서는 Transformers를 따로 번역하지 않았던 것으로 기억해서 수정해보았습니다.

2024-10-05 03:29 UTC, nuatmochoi commented on docs/source/ko/main_classes/onnx.md
> +# 🤗 트랜스포머 모델을 ONNX로 내보내기[[exporting--transformers-models-to-onnx]]
```suggestion
# 🤗 Transformers 모델을 ONNX로 내보내기[[exporting--transformers-models-to-onnx]]
```

2024-10-05 03:29 UTC, nuatmochoi commented on docs/source/ko/main_classes/onnx.md
> +🤗 트랜스포머는 `transformers.onnx` 패키지를 제공하며, 패키지를 통해 설정 객체를 활용함으로써 모델 체크포인트를 ONNX 그래프로 변환할 수 있게 합니다.
```suggestion
🤗 Transformers는 `transformers.onnx` 패키지를 제공하며, 패키지를 통해 설정 객체를 활용함으로써 모델 체크포인트를 ONNX 그래프로 변환할 수 있게 합니다.
```

2024-10-05 03:29 UTC, nuatmochoi commented on docs/source/ko/main_classes/onnx.md
> +🤗 트랜스포머에 대한 자세한 내용은 [이 가이드](../serialization)를 참조하세요.
```suggestion
🤗 Transformers에 대한 자세한 내용은 [이 가이드](../serialization)를 참조하세요.
```

2024-10-07 03:44 UTC, fabxoe commented on docs/source/ko/main_classes/onnx.md
> +내보내고자 하는 모델 아키텍처의 유형에 따라 상속받아야 할 세 가지 추상 클래스를 제공합니다:
```suggestion
내보내려는(export) 모델 아키텍처의 유형에 따라 상속받아야 할 세 가지 추상 클래스를 제공합니다:
```

2024-10-07 03:45 UTC, fabxoe commented on docs/source/ko/main_classes/onnx.md
> +각 ONNX 설정은 다양한 유형의 토폴로지나 작업에 대해 모델을 내보낼 수 있게 해주는 _features_ 세트와 연관되어 있습니다.
```suggestion
각 ONNX 설정은 다양한 유형의 토폴로지나 작업에 대해 모델을 내보낼 수 있게(exporting) 해주는 _features_ 세트와 연관되어 있습니다.
```

2024-10-08 21:48 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33601). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:57 UTC, stevhliu approved these changes
💯

2024-10-09 00:15 UTC, merged