🌐 [i18n-KO] Translated `model_doc/paligemma.md` to Korean
huggingface/transformers pull request #33612
Opened 2024-09-20 08:01 UTC by fabxoe

# What does this PR do?

Translated the `model_doc/paligemma.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-10-01 15:13 UTC, ahnjj requested changes

2024-10-01 15:13 UTC, ahnjj commented on docs/source/ko/model_doc/paligemma.md
> +## 오버뷰[[overview]]
오버뷰 -> 개요

2024-10-01 15:13 UTC, ahnjj commented on docs/source/ko/model_doc/paligemma.md
> +PaliGemma 모델은 구글이 제안한 [PaliGemma – Google의 최첨단 오픈 비전 언어 모델](https://huggingface.co/blog/paligemma)로 소개 되었습니다. PaliGemma는 [SigLIP](siglip) 비전 인코더와 [Gemma](gemma) 언어 인코더로 구성된 3B 규모의 비전-언어 모델로, 두 인코더가 멀
```suggestion
PaliGemma 모델은 구글이 제안한 [PaliGemma – Google의 최첨단 오픈 비전 언어 모델](https://huggingface.co/blog/paligemma)에서 소개 되었습니다. PaliGemma는 [SigLIP](siglip) 비전 인코더와 [Gemma](gemma) 언어 인코더로 구성된 3B 규모의 비전-언어 모델로, 두 인코더가 멀티모달 선형 프로젝션으로 연결되어 있습니다. 이 모델은 이미지를 고정된 수의 VIT토큰으로 분할하고 이를 선택적 프롬프트 앞에 추가 하며, 모든 이미지 토큰과 입력 텍스트 토큰에 대해 전체 블록 어텐션을 사용하는 특징을 가지고 있습니다.
```
projection이 그로서리에 없어서,, 투영으로 안하고 프로젝션으로 표기했습니다.

2024-10-01 15:13 UTC, ahnjj commented on docs/source/ko/model_doc/paligemma.md
> +PaliGemma의 추론은 다음처럼 수행됩니다:
```suggestion
PaliGemma의 추론 수행
```

2024-10-01 15:13 UTC, ahnjj commented on docs/source/ko/model_doc/paligemma.md
> +- `PaliGemmaProcessor`를 사용하여 모델에 필요한 이미지, 텍스트 및 선택적 레이블을 준비하는데 사용할 수 있습니다. PaliGemma 모델을 미세 조정할 때는, 프로세서에 `suffix`인자를 전달하여 다음 처럼 모델의 `labels`를 생성할 수 있습니다:
```suggestion
- 모델에 필요한 이미지, 텍스트 및 선택적 레이블을 준비하는데 `PaliGemmaProcessor`를 사용할 수 있습니다. PaliGemma 모델을 미세 조정할 때는, 프로세서에 `suffix`인자를 전달하여 다음 처럼 모델의 `labels`를 생성할 수 있습니다:
```

2024-10-01 15:13 UTC, ahnjj commented on docs/source/ko/model_doc/paligemma.md
> +## 리소스[[resources]]
리소스 -> 자료

2024-10-07 04:05 UTC, fabxoe commented on docs/source/ko/model_doc/paligemma.md
> +## 오버뷰[[overview]]
```suggestion
## 개요[[overview]]
```

2024-10-07 04:06 UTC, fabxoe commented on docs/source/ko/model_doc/paligemma.md
> +## 리소스[[resources]]
```suggestion
## 자료[[resources]]
```

2024-10-07 04:06 UTC, fabxoe commented on docs/source/ko/model_doc/paligemma.md
> +## 사용팁[[usage-tips]]
```suggestion
## 사용 팁[[usage-tips]]
```

2024-10-08 21:48 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33612). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:42 UTC, stevhliu approved these changes
Nice, thanks! :)

2024-10-09 00:13 UTC, merged