🌐 [i18n-KO] Translated `model_doc/llama3.md` to Korean
huggingface/transformers pull request #33635
Opened 2024-09-20 19:24 UTC by fabxoe

# What does this PR do?

Translated the `model_doc/llama3.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-09-30 15:50 UTC, chhaewxn reviewed
간단하게 몇 가지 수정사항 제안드려봅니다! 꼼꼼하게 번역해주셔서 많이 배우고 가요🤗

2024-09-30 15:50 UTC, chhaewxn commented on docs/source/ko/model_doc/llama3.md
> +*오늘, 광범위한 사용을 위해 이용 가능한 라마의 차세대 모델인 메타 라마3의 첫 두 모델을 공유하게 되어 기쁩니다. 이번 출시는 8B와 70B 매개변수를 가진 사전 훈련 및 지시 미세 조정된 언어 모델을 특징으로 하며, 광범위한 사용 사례를 지원할 수 있습니다. 라마의 이 차세대 모델은 다양한 산업 벤치마크에서 최첨단의 성능을 보여주며, 개선된 추론 능
```suggestion
*오늘, 광범위한 사용을 위해 이용 가능한 라마의 차세대 모델인 메타 라마3의 첫 두 모델을 공유하게 되어 기쁩니다. 이번 출시는 8B와 70B 매개변수를 가진 사전 훈련 및 지시 미세 조정된 언어 모델을 특징으로 하며, 광범위한 사용 사례를 지원할 수 있습니다. 라마의 이 차세대 모델은 다양한 산업 벤치마크에서 최첨단의 성능을 보여주며, 개선된 추론 능력을 포함한 새로운 기능을 제공합니다. 우리는 이것들이 단연코 해당 클래스에서 최고의 오픈 소스 모델이라고 믿습니다. 오랜 개방적 접근 방식을 유지하며, 우리는 라마3를 커뮤니티에 맡기고 있습니다. 애플리케이션에서 개발자 도구, 평가, 추론 최적화 등에 이르기까지 AI 스택 전반에 걸친 다음 혁신의 물결을 촉발하길 희망합니다. 여러분이 무엇을 만들지 기대하며 여러분의 피드백을 고대합니다.*
```
"커뮤니티의 손에"라는 표현이 조금 어색해서 수정해보았습니다.

2024-09-30 15:50 UTC, chhaewxn commented on docs/source/ko/model_doc/llama3.md
> +    이 스크립트를 실행시키려면 모델 전체를 float16 정밀도로 호스팅할 수 있는 충분한 메인메모리가 필요하다는 점을 유의하세요. 가장 큰 버전이 여러 체크포인트로 나뉘어 있더라도, 각 체크포인트가 모델의 가중치 일부를 포함하고 있기 때문에 이를 모두 RAM에 로드해야 합니다. 75B 모델을 예를들면 대략 145GB의 램이 필요합니다.
```suggestion
    이 스크립트를 실행시키려면 모델 전체를 float16 정밀도로 호스팅할 수 있는 충분한 메인메모리가 필요하다는 점을 유의하세요. 가장 큰 버전이 여러 체크포인트로 나뉘어 있더라도, 각 체크포인트가 모델의 가중치 일부를 포함하고 있기 때문에 이를 모두 RAM에 로드해야 합니다. 75B 모델을 예로 들면 대략 145GB의 RAM이 필요합니다. 
```
앞 부분에서 RAM이라고 표기되어서 램 -> RAM으로 수정해보았습니다.

2024-10-01 14:59 UTC, ahnjj requested changes

2024-10-01 14:59 UTC, ahnjj commented on docs/source/ko/model_doc/llama3.md
> +## 오버뷰[[overview]]
오버뷰 -> 개요

2024-10-01 14:59 UTC, ahnjj commented on docs/source/ko/model_doc/llama3.md
> +*오늘, 광범위한 사용을 위해 이용 가능한 라마의 차세대 모델인 메타 라마3의 첫 두 모델을 공유하게 되어 기쁩니다. 이번 출시는 8B와 70B 매개변수를 가진 사전 훈련 및 지시 미세 조정된 언어 모델을 특징으로 하며, 광범위한 사용 사례를 지원할 수 있습니다. 라마의 이 차세대 모델은 다양한 산업 벤치마크에서 최첨단의 성능을 보여주며, 개선된 추론 능
```suggestion
*오늘, 범용적으로 이용 가능한 라마의 차세대 모델, 메타 라마3의 첫 두 모델을 공유하게 되어 기쁩니다. 이번 출시의 특징으로는, 범용적인 사용 사례들을 지원하는 매개변수 8B와 70B를 가진 사전 훈련 및 지시 미세 조정된 언어 모델에 있습니다. 라마의 이 차세대 모델은 다양한 산업 벤치마크에서 최첨단의 성능을 보여주며, 개선된 추론 능력을 포함한 새로운 기능을 제공합니다. 우리는 이 모델이 해당 클래스에서 최고의 오픈 소스 모델이라 자부합니다. 오랜 기간 이어온 우리의 개방적인 방식을 지지하며, 라마3를 커뮤니티의 손에 맡기고 있습니다. 애플리케이션에서 개발자 도구, 평가, 추론 최적화 등에 이르기까지 AI 스택 전반에 걸친 차세대 혁신의 물결을 일으키길 희망합니다. 여러분이 무엇을 만들지 기대하며 여러분들의 피드백을 기대합니다.*
```

2024-10-01 14:59 UTC, ahnjj commented on docs/source/ko/model_doc/llama3.md
> +온라인 가중치의 `dtype`은 `model = AutoModelForCausalLM.from_pretrained("path", torch_dtype = "auto")`를 사용하여 모델을 초기화할 때 `torch_dtype="auto"`를 사용하지 않는 한 대부분 무관합니다. 그 이유는 모델이 먼저 다운로드되고(온라인 체크포인트의 `dtype`을 사용하여
```suggestion
 `model = AutoModelForCausalLM.from_pretrained("path", torch_dtype = "auto")`를 사용하여 모델을 초기화할 때, 온라인 가중치의 `dtype`는 `torch_dtype="auto"`를 사용하지 않는 한 대부분 무관합니다. 그 이유는 모델이 먼저 다운로드되고(온라인 체크포인트의 `dtype`를 사용), 그 다음 `torch`의 `dtype`으로 변환되어(`torch.float32`가 됨), 마지막으로 config에 `torch_dtype`이 제공된 경우 가중치가 사용되기 때문입니다.
```
좀 더 읽기 쉽게 바꿔보았습니다>!

2024-10-01 14:59 UTC, ahnjj commented on docs/source/ko/model_doc/llama3.md
> +## 리소스[[resources]]
```suggestion
## 자료[[resources]]
```

2024-10-01 14:59 UTC, ahnjj commented on docs/source/ko/model_doc/llama3.md
> +많은 멋진 자료들이 이미 [라마2](./llama2) 문서 페이지에서 제공되고 있으며, 여기에서 라마3를 위한 새로운 자료를 추가하도록 기여자들을 초대합니다! 🤗
```suggetstion
이미 [라마2](./llama2) 문서 페이지에서는 수 많은 유익한 자료들이  제공되고 있으며, 이곳에 라마3에 대한 새로운 자료를 더해주실 컨트리뷰터들을 초대합니다! 🤗
```

2024-10-04 12:01 UTC, jun048098 reviewed
fix: docs suggestions

2024-10-07 04:14 UTC, fabxoe commented on docs/source/ko/model_doc/llama3.md
> +## 오버뷰[[overview]]
```suggestion
## 개요[[overview]]
```

2024-10-07 04:15 UTC, fabxoe commented on docs/source/ko/model_doc/llama3.md
> +*오늘, 광범위한 사용을 위해 이용 가능한 라마의 차세대 모델인 메타 라마3의 첫 두 모델을 공유하게 되어 기쁩니다. 이번 출시는 8B와 70B 매개변수를 가진 사전 훈련 및 지시 미세 조정된 언어 모델을 특징으로 하며, 광범위한 사용 사례를 지원할 수 있습니다. 라마의 이 차세대 모델은 다양한 산업 벤치마크에서 최첨단의 성능을 보여주며, 개선된 추론 능
```suggestion
*오늘, 광범위한 사용을 위해 이용 가능한 라마의 차세대 모델인 메타 라마3의 첫 두 모델을 공유하게 되어 기쁩니다. 이번 출시는 8B와 70B 매개변수를 가진 사전 훈련 및 지시 미세 조정된 언어 모델을 특징으로 하며, 광범위한 사용 사례를 지원할 수 있습니다. 라마의 이 차세대 모델은 다양한 산업 벤치마크에서 최첨단의 성능을 보여주며, 개선된 추론 능력을 포함한 새로운 기능을 제공합니다. 우리는 이것들이 단연코 해당 클래스에서 최고의 오픈 소스 모델이라고 믿습니다. 오랜 개방적 접근 방식을 지지하며, 우리는 라마3를 커뮤니티 기여자들에게 맡기고 있습니다. 애플리케이션에서 개발자 도구, 평가, 추론 최적화 등에 이르기까지 AI 스택 전반에 걸친 다음 혁신의 물결을 촉발하길 희망합니다. 여러분이 무엇을 만들지 기대하며 여러분의 피드백을 고대합니다.*
```

2024-10-07 04:27 UTC, fabxoe commented on docs/source/ko/model_doc/llama3.md
> +많은 멋진 자료들이 이미 [라마2](./llama2) 문서 페이지에서 제공되고 있으며, 여기에서 라마3를 위한 새로운 자료를 추가하도록 기여자들을 초대합니다! 🤗
```suggestion
[라마2](./llama2) 문서 페이지에서는 이미 수 많은 멋지고 유익한 자료들을  제공하고 있습니다. 이곳에 라마3에 대한 새로운 자료를 더해주실 컨트리뷰터들을 초대합니다! 🤗
```

2024-10-08 21:48 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33635). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:45 UTC, stevhliu approved these changes
Thanks for the translation!

2024-10-09 00:13 UTC, merged