🌐 [i18n-KO] Translated `model_doc/mistral.md` to Korean
huggingface/transformers pull request #33648
Opened 2024-09-21 15:38 UTC by fabxoe

# What does this PR do?

Translated the `model_doc/mistral.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-09-30 15:43 UTC, chhaewxn reviewed
전체적으로 번역이 잘 되어 있어 글이 잘 읽히네요 ㅎㅎ 띄어쓰기 부분만 간단하게 수정 요청드립니다 😊

2024-09-30 15:43 UTC, chhaewxn commented on docs/source/ko/model_doc/mistral.md
> +미스트랄은 Albert Jiang, Alexandre Sablayrolles, Arthur Mensch, Chris Bamford, Devendra Singh Chaplot, Diego de las Casas, Florian Bressand, Gianna Lengyel, Guillaume Lample, Lélio Renard Lavaud, Lucile S
```suggestion
미스트랄은 Albert Jiang, Alexandre Sablayrolles, Arthur Mensch, Chris Bamford, Devendra Singh Chaplot, Diego de las Casas, Florian Bressand, Gianna Lengyel, Guillaume Lample, Lélio Renard Lavaud, Lucile Saulnier, Marie-Anne Lachaux, Pierre Stock, Teven Le Scao, Thibaut Lavril, Thomas Wang, Timothée Lacroix, William El Sayed가 작성한 [이 블로그 포스트](https://mistral.ai/news/announcing-mistral-7b/)에서 소개되었습니다.
```

2024-09-30 15:43 UTC, chhaewxn commented on docs/source/ko/model_doc/mistral.md
> +미스트랄-7B는 [mistral.ai](https://mistral.ai/)에서 출시한 첫번째 대규모 언어 모델(LLM)입니다.
```suggestion
미스트랄-7B는 [mistral.ai](https://mistral.ai/)에서 출시한 첫 번째 대규모 언어 모델(LLM)입니다.
```

2024-09-30 15:43 UTC, chhaewxn commented on docs/source/ko/model_doc/mistral.md
> +- 바이트 폴백(Byte-fallback) BPE 토크나이저: 문자들이 절대 어휘 목록 외 토큰으로 매핑되지 않도록 보장합니다.
```suggestion
- 바이트 폴백(Byte-fallback) BPE 토크나이저: 문자들이 절대 어휘 목록 외의 토큰으로 매핑되지 않도록 보장합니다.
```

2024-09-30 15:43 UTC, chhaewxn commented on docs/source/ko/model_doc/mistral.md
> +지시 조정 모델은 입력이 올바른 형식으로 준비되도록 하기 위해 [채팅 템플릿](../chat_templating)을 적용해야 합니다.
```suggestion
지시 조정 모델은 입력이 올바른 형식으로 준비되도록 [채팅 템플릿](../chat_templating)을 적용해야 합니다.
```
문장 구조를 조금 더 간결하게 수정해보았습니다.

2024-10-01 14:23 UTC, ahnjj requested changes

2024-10-01 14:23 UTC, ahnjj commented on docs/source/ko/model_doc/mistral.md
> +- GQA(Grouped Query Attention): 더 빠른 추론과 더 작은 캐시 크기를 가능하게 합니다.
```suggestion
- GQA(Grouped Query Attention): 더 빠른 추론과 더 작은 캐시 크기를 구현할 수 있습니다.
```

2024-10-01 14:23 UTC, ahnjj commented on docs/source/ko/model_doc/mistral.md
> +- 지시 조정 모델인 [미스트랄-7B-Instruct-v0.1](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1)은 지도 미세 조정(SFT)과 직접 선호도 최적화(DPO)를 사용하여 채팅 목적으로 최적화된 기본 모델입니다.
```suggestion
- 지시 조정 모델인 [미스트랄-7B-Instruct-v0.1](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1)은 지도 미세 조정(SFT)과 직접 선호도 최적화(DPO)를 사용한 채팅에 최적화된 기본 모델입니다.
```

2024-10-01 14:23 UTC, ahnjj commented on docs/source/ko/model_doc/mistral.md
> +- Hugging Face 도구를 사용하여 2024년에 LLM을 미세 조정하는 방법에 대한 [블로그 포스트](https://www.philschmid.de/fine-tune-llms-in-2024-with-trl). 🌎
```suggestion
- 2024년에 Hugging Face 도구를 사용해 LLM을 미세 조정하는 방법에 대한 [블로그 포스트](https://www.philschmid.de/fine-tune-llms-in-2024-with-trl). 🌎
```

2024-10-04 13:26 UTC, jun048098 reviewed
fix: docs suggestions

2024-10-04 13:26 UTC, jun048098 commented on docs/source/ko/model_doc/mistral.md
> +플래시 어텐션2와 호환되는 하드웨어를 가지고 있는지도 확인하세요. 이에 대한 자세한 내용은 [플래시 어텐션 저장소](https://github.com/Dao-AILab/flash-attention)의 공식 문서에서 확인할 수 있습니다. 또한 모델을 반정밀도(예: `torch.float16`)로 불러오는 것을 잊지 마세요.
```suggestion
플래시 어텐션2와 하드웨어가 호환하는지 확인이 필요합니다. 이에 대한 자세한 내용은 [플래시 어텐션 저장소](https://github.com/Dao-AILab/flash-attention)의 공식 문서에서 확인할 수 있습니다. 또한 모델을 반정밀도(예: `torch.float16`)로 불러와야 합니다.
```

2024-10-04 13:26 UTC, jun048098 commented on docs/source/ko/model_doc/mistral.md
> +이 모델은 [Younes Belkada](https://huggingface.co/ybelkada)와 [Arthur Zucker](https://huggingface.co/ArthurZ)에 의해 기여 되었습니다.
```suggestion
이 모델은 [Younes Belkada](https://huggingface.co/ybelkada)와 [Arthur Zucker](https://huggingface.co/ArthurZ)가 기여했습니다.
```

2024-10-04 13:26 UTC, jun048098 commented on docs/source/ko/model_doc/mistral.md
> +미스트랄을 시작하는 데 도움이 되는 Hugging Face와 community 자료 목록(🌎로 표시됨) 입니다. 여기에 포함될 자료를 제출하고 싶으시다면 PR(Pull Request)를 열어주세요. 리뷰 해드리겠습니다! 자료는 기존 자료를 복제하는 대신 새로운 내용을 담고 있어야 합니다.
```suggestion
미스트랄을 시작하는 데 도움이 되는 Hugging Face와 community 자료 목록(🌎로 표시됨) 입니다. 여기에 포함될 자료를 제출하고 싶으시다면 PR(Pull Request)를 열어주세요. 리뷰해 드리겠습니다! 자료는 기존 자료를 복제하는 대신 새로운 내용을 담고 있어야 합니다.
```

2024-10-04 13:26 UTC, jun048098 commented on docs/source/ko/model_doc/mistral.md
> +- Hugging Face의 [미세조정 최적화(Alignment) 핸드북](https://github.com/huggingface/alignment-handbook)에는 미스트랄-7B를 사용한 지도형 미세 조정(SFT) 및 직접 선호 최적화를 수행하기 위한 스크립트와 레시피가 포함되어 있습니다. 여기에는 단일 GPU에서 QLoRa 및 다중 GPU를 사용한
```suggestion
- Hugging Face의 [정렬(Alignment) 핸드북](https://github.com/huggingface/alignment-handbook)에는 미스트랄-7B를 사용한 지도형 미세 조정(SFT) 및 직접 선호 최적화(DPO)를 수행하기 위한 스크립트와 레시피가 포함되어 있습니다. 여기에는 단일 GPU에서 QLoRa 및 다중 GPU를 사용한 전체 미세 조정을 위한 스크립트가 포함되어 있습니다.
```

2024-10-04 13:26 UTC, jun048098 commented on docs/source/ko/model_doc/mistral.md
> +- Hugging Face의 [미세조정 최적화(Alignment) 핸드북](https://github.com/huggingface/alignment-handbook)에는 미스트랄-7B를 사용한 지도형 미세 조정(SFT) 및 직접 선호 최적화를 수행하기 위한 스크립트와 레시피가 포함되어 있습니다. 여기에는 단일 GPU에서 QLoRa 및 다중 GPU를 사용한
[Alignment Handbook]은 SFT와 DPO로 alignment 방법을 설명하는 쿡북 같습니다.

2024-10-07 04:28 UTC, fabxoe commented on docs/source/ko/model_doc/mistral.md
> +## 사용팁[[usage-tips]]
```suggestion
## 사용 팁[[usage-tips]]
```

2024-10-08 21:47 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33648). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-08 23:48 UTC, stevhliu approved these changes
LGTM, thank you!

2024-10-09 00:14 UTC, merged