Allow tokenization of sequences > 512 for caching
huggingface/transformers pull request #337
Opened 2019-03-03 00:30 UTC by CatalinVoss

For many applications requiring randomized data access, it's easier to cache the tokenized representations than the words. So why not turn this into a warning?

2019-03-05 14:53 UTC, rodgzilla approved these changes

2019-03-05 14:55 UTC, rodgzilla requested changes
I approve this change but I think you should do it for all the tokenizers.

2019-03-05 20:32 UTC, CatalinVoss commented
OK, done. Thanks!

2019-03-06 08:45 UTC, thomwolf commented
Nice, thanks @CatalinVoss (and @rodgzilla)!

2019-03-06 08:45 UTC, merged