Fix data_seed unused
huggingface/transformers pull request #33731
Opened 2024-09-26 15:10 UTC by MekkCyber

# What does this PR do?
This PR fixes the problem related to the data_seed being unused. It was removed during a refactor of how samplers were used. See this PR for more information.

Fixes https://github.com/huggingface/transformers/issues/31818 https://github.com/huggingface/trl/issues/1810

You need to use this accelerate PR : https://github.com/huggingface/accelerate/pull/3130

2024-09-26 15:34 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33731). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-09-26 15:34 UTC, vignesh1507 requested changes
can you elaborate more about the changes you made in the code?

2024-10-01 15:13 UTC, SunMarc approved these changes
LGTM as we discussed offline !

2024-10-01 15:13 UTC, SunMarc commented on src/transformers/trainer.py
> +                raise RuntimeError("data_seed requires accelerate >= 0.34.0, please install the latest version of accelerate")
make sure to update this when we fix the issue on accelerate

2024-10-03 09:25 UTC, LysandreJik approved these changes
Let's merge if it unblocks, and Zach feel free to comment when back if it's not up to your standards

2024-10-09 16:14 UTC, SunMarc commented
cc @MekkCyber  let's update the PR since we merged this PR : https://github.com/huggingface/accelerate/pull/3150#event-14575790028

2024-10-09 17:26 UTC, muellerzr reviewed
Some direction on where to go from here:

2024-10-09 17:26 UTC, muellerzr commented on src/transformers/trainer.py
> +        self.data_sampler_generator = generator
With the new version what should essentially happen is:

Instead we should modify `create_accelerator_and_postprocess` and modify this chunk of it https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L4860-L4866

With something like:

```python
        if is_accelerate_available("0.28.0"):
            dataloader_config = DataLoaderConfiguration(
                split_batches=accelerator_config.pop("split_batches"),
                dispatch_batches=accelerator_config.pop("dispatch_batches"),
                even_batches=accelerator_config.pop("even_batches"),
                use_seedable_sampler=accelerator_config.pop("use_seedable_sampler"),
            )
            if is_accelerate_available("1.1.0"):
                dataloader_config.data_seed = self.args.data_seed
```
And then in `TrainingArguments.__post_init__` check if a `data_seed` was passed/not the default. If so, do a check for the accelerate version and raise a `NotImplementedError()` telling users to upgrade their accelerate version.

2024-10-10 12:13 UTC, SunMarc approved these changes
Nice and simple ! Let's fix the merge conflits and we are good to merge !

2024-10-10 13:28 UTC, merged