Make ASR pipeline compliant with Hub spec + add tests
huggingface/transformers pull request #33769
Opened 2024-09-27 16:06 UTC by Rocketknight1

2024-09-27 16:09 UTC, Rocketknight1 commented
cc @LysandreJik @osanseviero @Wauplin - there will be quite a lot of these if I do pipelines individually, maybe I should batch them into PRs with a few pipelines each?

2024-09-27 16:16 UTC, vignesh1507 requested changes
I agree with the changes, could you elaborate more about the changes?

2024-09-27 17:12 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33769). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-09-30 16:43 UTC, Wauplin approved these changes
Thanks @Rocketknight1! 
I'm not against some batching now that the main helpers are implemented. But note that I'm not a `transformers` maintainers so my approval is mehh :smile:

2024-10-01 11:36 UTC, LysandreJik commented
@vignesh1507 you've been posting this message on a few PRs; please explain exactly what you mean as it feels like spam. Thank you.

2024-10-01 11:38 UTC, LysandreJik approved these changes
:fire:

2024-10-01 11:38 UTC, LysandreJik commented on src/transformers/pipelines/automatic_speech_recognition.py
> +                "`max_new_tokens` is deprecated and will be removed in version 5 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.",
```suggestion
                "`max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.",
```

2024-10-01 11:39 UTC, LysandreJik commented
I don't feel strongly about batching PRs, if it makes things simpler then let's do it yeah

2024-10-01 15:07 UTC, HuggingFaceDocBuilderDev commented
Hey! 🤗 Thanks for your contribution to the `transformers` library!

Before merging this pull request, slow tests CI should be triggered. To enable this:
- Add the `run-slow` label to the PR
- When your PR is ready for merge and all reviewers' comments have been addressed, push an empty commit with the command `[run-slow]` followed by a comma separated list of all the models to be tested, i.e. `[run_slow] model_to_test_1, model_to_test_2`
  - If the pull request affects a lot of models, put at most 10 models in the commit message
- A `transformers` maintainer will then approve the workflow to start the tests

(For maintainers) The documentation for slow tests CI on PRs is [here](https://www.notion.so/huggingface2/CI-for-pull-requests-8335bd9217d24d1e8ed1d3a016f39804).

2024-10-01 15:08 UTC, Rocketknight1 commented
I'll batch simpler/related ones, in that case, which should save time without making it overwhelming to review.

2024-10-01 17:15 UTC, merged