🌐 [i18n-KO] Translated `model_doc/bart.md` to Korean
huggingface/transformers pull request #33893
Opened 2024-10-02 14:58 UTC by fabxoe

# What does this PR do?

Translated the `model_doc/bart.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-10-02 15:28 UTC, fabxoe reviewed
fix: suggestions

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartConfig
```suggestion
## BartConfig[[transformers.BartConfig]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartTokenizer
```suggestion
## BartTokenizer[[transformers.BartTokenizer]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartTokenizerFast
```suggestion
## BartTokenizerFast[[transformers.BartTokenizerFast]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartModel
```suggestion
## BartModel[[transformers.BartModel]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartForConditionalGeneration
```suggestion
## BartForConditionalGeneration[[transformers.BartForConditionalGeneration]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartForSequenceClassification
```suggestion
## BartForSequenceClassification[[transformers.BartForSequenceClassification]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartForQuestionAnswering
```suggestion
## BartForQuestionAnswering[[transformers.BartForQuestionAnswering]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## BartForCausalLM
```suggestion
## BartForCausalLM[[transformers.BartForCausalLM]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## TFBartModel
```suggestion
## TFBartModel[[transformers.TFBartModel]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## TFBartForConditionalGeneration
```suggestion
## TFBartForConditionalGeneration[[transformers.TFBartForConditionalGeneration]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## TFBartForSequenceClassification
```suggestion
## TFBartForSequenceClassification[[transformers.TFBartForSequenceClassification]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## FlaxBartModel
```suggestion
## FlaxBartModel[[transformers.FlaxBartModel]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## FlaxBartForConditionalGeneration
```suggestion
## FlaxBartForConditionalGeneration[[transformers.FlaxBartForConditionalGeneration]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## FlaxBartForSequenceClassification
```suggestion
## FlaxBartForSequenceClassification[[transformers.FlaxBartForSequenceClassification]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## FlaxBartForQuestionAnswering
```suggestion
## FlaxBartForQuestionAnswering[[transformers.FlaxBartForQuestionAnswering]]
```

2024-10-02 15:28 UTC, fabxoe commented on docs/source/ko/model_doc/bart.md
> +## FlaxBartForCausalLM
```suggestion
## FlaxBartForCausalLM[[transformers.FlaxBartForCausalLM]]
```

2024-10-04 04:51 UTC, ahnjj requested changes

2024-10-04 04:51 UTC, ahnjj commented on docs/source/ko/model_doc/bart.md
> +## 오버뷰[[overview]]
```suggestion
## 개요 [[overview]]
```

2024-10-04 04:51 UTC, ahnjj commented on docs/source/ko/model_doc/bart.md
> +추가적으로 볼 것들:
```suggestion
추가 자료:
```

2024-10-04 04:51 UTC, ahnjj commented on docs/source/ko/model_doc/bart.md
> +- [Trainer 클래스를 사용하여 두 언어로 요약하기 위한 BART를 미세 조정](https://colab.research.google.com/github/elsanns/xai-nlp-notebooks/blob/master/fine_tune_bart_summarization_two_langs.ipynb)하는 방법에 대한 노트북. 🌎
```suggestion
- [Trainer 클래스를 사용하여 두 가지 언어로 요약하기 위한 BART 미세 조정](https://colab.research.google.com/github/elsanns/xai-nlp-notebooks/blob/master/fine_tune_bart_summarization_two_langs.ipynb)하는 방법에 대한 노트북. 🌎
```
더 자연스러운 표현으로 바꾸었습니다 :)

2024-10-04 04:51 UTC, ahnjj commented on docs/source/ko/model_doc/bart.md
> +  [`~BartTokenizer.encode`]를 사용한다.
```suggestion
  [`~BartTokenizer.encode`]를 사용합니다.
```
다른 부분들은 높임체(?)로 쓰셔서 통일했습니다!

2024-10-04 04:51 UTC, ahnjj commented on docs/source/ko/model_doc/bart.md
> +- Model predictions are intended to be identical to the original implementation when
```suggestion

```
아래줄에 번역 해두신 것 같아 삭제되어야할 것 같습니다.

2024-10-04 04:51 UTC, ahnjj commented on docs/source/ko/model_doc/bart.md
> +  `forced_bos_token_id=0`. This only works, however, if the string you pass to
```suggestion
```
아래줄에 번역 해두신 것 같아 삭제되어야할 것 같습니다.

2024-10-04 04:51 UTC, ahnjj commented on docs/source/ko/model_doc/bart.md
> +  [`fairseq.encode`] starts with a space.
```suggestion
```
아래줄에 번역 해두신 것 같아 삭제되어야할 것 같습니다.

2024-10-04 06:19 UTC, jun048098 commented on docs/source/ko/model_doc/bart.md
> +- 인코더와 디코더가 있는 seq2seq 모델입니다. 인코더에는 손상된 버전의 토큰이 입력되고, 디코더에는 원래 토큰이 입력됩니다(단, 일반적인 트랜스포머 디코더처럼 미래 단어를 숨기는 마스크가 있습니다). 사전 훈련 작업에서 인코더에 적용되는 변환들의 구성은 다음과 같습니다:
```suggestion
- 인코더와 디코더가 있는 seq2seq 모델입니다. 인코더에는 손상된 토큰이(corrupted tokens) 입력되고, 디코더에는 원래 토큰이 입력됩니다(단, 일반적인 트랜스포머 디코더처럼 미래 단어를 숨기는 마스크가 있습니다). 사전 훈련 작업에서 인코더에 적용되는 변환들의 구성은 다음과 같습니다:
```

2024-10-04 06:21 UTC, jun048098 commented on docs/source/ko/model_doc/bart.md
> +- Bart는 시퀀스 분류에 `token_type_ids`를 사용하지 않는다. 적절하게 나누기 위해서 [`BartTokenizer`]나
```suggestion
- Bart는 시퀀스 분류에 `token_type_ids`를 사용하지 않습니다. 적절하게 나누기 위해서 [`BartTokenizer`]나
```

2024-10-04 06:22 UTC, jun048098 commented on docs/source/ko/model_doc/bart.md
> +- [`BartModel`]의 정방향 전달은 `decoder_input_ids`가 전달되지 않으면 `decoder_input_ids`를 자동으로 생성할 것입니다. 이는 다른 일부 모델링 API와 다른 점이라 할 수 있습니다. 이 기능의 일반적인 사용 사례는 마스크 채우기(mask filling)입니다.
```suggestion
- [`BartModel`]의 정방향 전달은 `decoder_input_ids`가 전달되지 않으면 `decoder_input_ids`를 자동으로 생성할 것입니다. 이는 다른 일부 모델링 API와 다른 점입니다. 이 기능의 일반적인 사용 사례는 마스크 채우기(mask filling)입니다.
```

2024-10-04 06:24 UTC, jun048098 commented on docs/source/ko/model_doc/bart.md
> +  모델 예측은 `forced_bos_token_id=0`일 때 기존 구현과 동일하게 작동하도록 의도되었습니다. 하지만, [fairseq.encode]에 전달하는 문자열이 공백으로 시작할 때만 이 기능이 작동합니다.
```suggestion
  모델 예측은 `forced_bos_token_id=0`일 때 기존 구현과 동일하게 작동하도록 의도되었습니다. 하지만, [`fairseq.encode`]에 전달하는 문자열이 공백으로 시작할 때만 이 기능이 작동합니다.
```

2024-10-04 06:36 UTC, jun048098 commented on docs/source/ko/model_doc/bart.md
> +- 이 [논문](https://arxiv.org/abs/2010.13002)에서는 [증류된 체크포인트](https://huggingface.co/models?search=distilbart)에 대해 설명합니다.
```suggestion
- 이 [논문](https://arxiv.org/abs/2010.13002)은 [증류된 체크포인트](https://huggingface.co/models?search=distilbart)에 대해 설명합니다.
```

2024-10-05 14:06 UTC, fabxoe reviewed
fix: resolve suggestions

2024-10-05 14:08 UTC, fabxoe reviewed
fix: resolve suggestions

2024-10-08 23:52 UTC, stevhliu reviewed
Thanks! Just one suggestion, otherwise LGTM 👍

2024-10-08 23:52 UTC, stevhliu commented on docs/source/ko/model_doc/bart.md
> +  모델 예측은 `forced_bos_token_id=0`일 때 기존 구현과 동일하게 작동하도록 의도되었습니다. 하지만, [`fairseq.encode`]에 전달하는 문자열이 공백으로 시작할 때만 이 기능이 작동합니다.
I think this should be two separate items here.
```suggestion
- [`BartModel`]의 정방향 전달은 `decoder_input_ids`가 전달되지 않으면 `decoder_input_ids`를 자동으로 생성할 것입니다. 이는 다른 일부 모델링 API와 다른 점입니다. 이 기능의 일반적인 사용 사례는 마스크 채우기(mask filling)입니다.
-  모델 예측은 `forced_bos_token_id=0`일 때 기존 구현과 동일하게 작동하도록 의도되었습니다. 하지만, [`fairseq.encode`]에 전달하는 문자열이 공백으로 시작할 때만 이 기능이 작동합니다.
```

2024-10-09 17:32 UTC, stevhliu approved these changes
👍

2024-10-09 17:33 UTC, merged