🌐 [i18n-KO] Translated `main_classes/quantization.md` to Korean
huggingface/transformers pull request #33959
Opened 2024-10-04 17:55 UTC by fabxoe

# What does this PR do?

Translated the `main_classes/quantization.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-10-05 15:21 UTC, ahnjj requested changes

2024-10-05 15:21 UTC, ahnjj commented on docs/source/ko/main_classes/quantization.md
> +Quantization techniques reduce memory and computational costs by representing weights and activations with lower-precision data types like 8-bit integers (int8). This enables loading larger models yo
```suggestion
```
아래 번역 해두신것 같아 원문부분 삭제했습니다~!

2024-10-05 15:21 UTC, ahnjj commented on docs/source/ko/main_classes/quantization.md
> +Quantization techniques that aren't supported in Transformers can be added with the [`HfQuantizer`] class.
```suggestion
```
아래 번역 해두신것 같아 원문부분 삭제했습니다~!

2024-10-05 15:21 UTC, ahnjj commented on docs/source/ko/main_classes/quantization.md
> +이 [양자화](../quantization) 가이드를 통해서 모델을 양자화하는 방법을 배울 수 있습니다.
```suggestion
 모델을 양자화하는 방법은 이  [양자화](../quantization) 가이드를 통해 배울 수 있습니다.
```
좀더 가독성 있어보이게 바꾸었습니다!

2024-10-08 21:19 UTC, stevhliu approved these changes
Nice, thank you!

2024-10-08 21:30 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/transformers/pr_33959). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-09 00:10 UTC, merged