🌐 [i18n-KO] Translated `main_classes/data_collator.md` to Korean
huggingface/transformers pull request #33954
Opened 2024-10-04 17:24 UTC by fabxoe

# What does this PR do?

Translated the `main_classes/data_collator.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [ ] Check for missing / redundant translations (번역 누락/중복 검사)
- [ ] Grammar Check (맞춤법 검사)
- [ ] Review or Add new terms to glossary (용어 확인 및 추가)
- [ ] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [ ] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@chhaewxn, @ahnjj, @jun048098, @fabxoe, @nuatmochoi, @heuristicwave

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

2024-10-05 07:31 UTC, nuatmochoi requested changes
glossary 참고하여 수정하였습니다:)

2024-10-05 07:31 UTC, nuatmochoi commented on docs/source/ko/main_classes/data_collator.md
> +# 데이터 수집기(Data Collator)[[data-collator]]
```suggestion
# 데이터 콜레이터(Data Collator)[[data-collator]]
```

2024-10-05 07:31 UTC, nuatmochoi commented on docs/source/ko/main_classes/data_collator.md
> +데이터 콜레이터는 데이터셋 요소들의 리스트를 입력으로 사용하여 배치를 형성하는 객체입니다. 이러한 요소들은 `train_dataset` 또는 `eval_dataset의` 요소들과 동일한 타입 입니다. 배치를 구성하기 위해, 데이터 수집기는 (패딩과 같은) 일부 처리를 적용할 수 있습니다. [`DataCollatorForLanguageModeling`]과
```suggestion
데이터 콜레이터는 데이터셋 요소들의 리스트를 입력으로 사용하여 배치를 형성하는 객체입니다. 이러한 요소들은 `train_dataset` 또는 `eval_dataset의` 요소들과 동일한 타입 입니다. 배치를 구성하기 위해, 데이터 수집기는 (패딩과 같은) 일부 처리를 적용할 수 있습니다. [`DataCollatorForLanguageModeling`]과 같은 일부 콜레이터는 형성된 배치에 (무작위 마스킹과 같은) 일부 무작위 데이터 증강도 적용합니다. 사용 예시는 [예제 스크립트](../examples)나 [예제 노트북](../notebooks)에서 찾을 수 있습니다.
```

2024-10-05 07:31 UTC, nuatmochoi commented on docs/source/ko/main_classes/data_collator.md
> +## 기본 데이터 수집기[[transformers.default_data_collator]]
```suggestion
## 기본 데이터 콜레이터[[transformers.default_data_collator]]
```

2024-10-05 14:04 UTC, fabxoe commented on docs/source/ko/main_classes/data_collator.md
> +## 기본 데이터 수집기[[transformers.default_data_collator]]
이번에 수집기라고 작성한 것은, 가짜연구소 아카데미 시기 때 철화님이 구글시트에 데이터 수집기라는 단어로 glossary에 남겨서 이렇게 해봤어요.
<img width="890" alt="image" src="https://github.com/user-attachments/assets/a8cc6f27-2e67-4da0-b254-41c5297d8288">

2024-10-05 15:14 UTC, ahnjj commented
다른분들이 올려주신 리뷰외에 LGTM입니다!!!

2024-10-07 04:32 UTC, fabxoe commented on docs/source/ko/_toctree.yml
> +      title: 데이터 수집기
```suggestion
      title: 데이터 콜레이터
```

2024-10-07 04:33 UTC, fabxoe commented on docs/source/ko/main_classes/data_collator.md
> +데이터 콜레이터는 데이터셋 요소들의 리스트를 입력으로 사용하여 배치를 형성하는 객체입니다. 이러한 요소들은 `train_dataset` 또는 `eval_dataset의` 요소들과 동일한 타입 입니다. 배치를 구성하기 위해, 데이터 수집기는 (패딩과 같은) 일부 처리를 적용할 수 있습니다. [`DataCollatorForLanguageModeling`]과
```suggestion
데이터 콜레이터는 데이터셋 요소들의 리스트를 입력으로 사용하여 배치를 형성하는 객체입니다. 이러한 요소들은 `train_dataset` 또는 `eval_dataset의` 요소들과 동일한 타입 입니다. 배치를 구성하기 위해, 데이터 콜레이터는 (패딩과 같은) 일부 처리를 적용할 수 있습니다. [`DataCollatorForLanguageModeling`]과 같은 일부 콜레이터는 형성된 배치에 (무작위 마스킹과 같은) 일부 무작위 데이터 증강도 적용합니다. 사용 예시는 [예제 스크립트](../examples)나 [예제 노트북](../notebooks)에서 찾을 수 있습니다.
```

2024-10-08 23:55 UTC, stevhliu approved these changes
Thank you, just need to resolve the merge conflict!

2024-10-09 18:14 UTC, merged