[i18n-ar] Translated file : docs/source/ar/tasks/sequence_classification.md into Arabic
huggingface/transformers pull request #35192
Opened 2024-12-10 21:37 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/tasks/sequence_classification.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-12-10 21:38 UTC, AhmedAlmaghz commented
مرحباً أخي عبالله @abodacs 
هذه قائمة المهام التالية للترجمة والمراجعة

# TASK GUIDES

## NATURAL LANGUAGE PROCESSING
- [ ]  Text classification #35192
- [ ]  Token classification
- [ ]  Question answering
- [ ]  Causal language modeling
- [ ]  Masked language modeling
- [ ]  Translation
- [ ]  Summarization 
- [ ]  Multiple choice

## AUDIO
- [ ]  Audio classification
- [ ]  Automatic speech recognition

## COMPUTER VISION
- [ ]  Image classification
- [ ]  Image segmentation
- [ ]  Video classification
- [ ]  Object detection
- [ ]  Zero-shot object detection
- [ ]  Zero-shot image classification
- [ ]  Depth estimation
- [ ]  Image-to-Image
- [ ]  Image Feature Extraction
- [ ]  Mask Generation
- [ ]  Keypoint Detection
- [ ]  Knowledge Distillation for Computer Vision

## Multimodal
- [ ]  Image captioning
- [ ]  Document Question Answering
- [ ]  Visual Question Answering
- [ ]  Text to speech
- [ ]  Image-text-to-text
- [ ]  Video-text-to-text

## Generation
- [ ]  Customize the generation strategy
- [ ]  Best Practices for Generation with Cache

## Prompting
- [ ]  Image tasks with IDEFICS
- [ ]  LLM prompting guide


أشكرك على جهودك الرائعة

2024-12-11 03:21 UTC, AhmedAlmaghz commented
> السلام عليكم هل من الممكن ربط المهام برقمها؟ وأيضا التأكد من عدم وجود مهام لم تترجم للعربية؟

وعليكم السلام ورحمة الله وبركاته 

سنعمل على مجموعة مجموعة
سنبداء ب : NATURAL LANGUAGE PROCESSING

ثم الذي تليها وهكذا

تحياتي وتقديري أخي عبدالله @abodacs

2024-12-21 14:35 UTC, AhmedAlmaghz commented
مرحبا أخي عبدالله @abodacs 
كيف حالك ؟ هل أنت مشغول ؟
لماذا لم تتم المراجعة ؟

تحياتي وتقديري لشخصكم الكريم

2025-01-17 22:12 UTC, abodacs requested changes
السﻻم عليكم
تمت المراجعة 
@AhmedAlmaghz 
جزاك الله خيرا

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +ثم قم بإنشاء وظيفة تقوم بتمرير تنبؤاتك وتصنيفاتك إلى [`~evaluate.EvaluationModule.compute`] لحساب الدقة:
```suggestion
ثم أنشئ دالة تقوم بتمرير تنبؤاتك وتصنيفاتك إلى [`~evaluate.EvaluationModule.compute`] لحساب الدقة:
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +وظيفتك `compute_metrics` جاهزة الآن، وستعود إليها عندما تقوم بإعداد تدريبك.
```suggestion
دالة `compute_metrics` جاهزة الآن، وستعود إليها عند إعداد التدريب.
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +3. قم باستدعاء [`~Trainer.train`] لضبط نموذجك الدقيق.
```suggestion
1.  حدد مُعامِلات التدريب في [`TrainingArguments`]. المُعامل المطلوب الوحيد هو `output_dir`، لتحديد مكان حفظ النموذج. يمكنك رفع النموذج إلى Hub بتعيين `push_to_hub=True` (يجب تسجيل الدخول إلى Hugging Face لرفع النموذج). سيقوم `Trainer` بتقييم الدقة وحفظ نقاط التحقق في نهاية كل حقبة.
2.  مرر مُعامِلات التدريب إلى `Trainer` مع النموذج، ومجموعة البيانات، والمحلل اللغوي، ومُجمِّع البيانات، ووظيفة `compute_metrics`.
3.  استدعِ [`~Trainer.train`] لضبط النموذج.
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +يطبق [`Trainer`] الحشو الديناميكي بشكل افتراضي عند تمرير `tokenizer` إليه. في هذه الحالة، لا تحتاج إلى تحديد مجمع بيانات بشكل صريح.
```suggestion
يستخدم [`Trainer`] الحشو الديناميكي افتراضيًا عند تمرير `tokenizer` إليه. في هذه الحالة،  لا تحتاج لتحديد مُجمِّع البيانات صراحةً. 
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +بمجرد اكتمال التدريب، شارك نموذجك على Hub باستخدام طريقة [`~transformers.Trainer.push_to_hub`] حتى يتمكن الجميع من استخدام نموذجك:
```suggestion
بعد اكتمال التدريب، شارك نموذجك على Hub باستخدام الطريقة [`~transformers.Trainer.push_to_hub`] ليستخدمه الجميع:
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +ثم يمكنك تحميل DistilBERT مع [`TFAutoModelForSequenceClassification`] جنبًا إلى جنب مع عدد التصنيفات المتوقعة، وخرائط التصنيف:
```suggestion
ثم يمكنك تحميل DistilBERT مع [`TFAutoModelForSequenceClassification`] بالإضافة إلى عدد التصنيفات المتوقعة، وتعيينات التسميات:
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +ثم اربط استدعاءاتك معًا:
```suggestion
ثم اجمع الاستدعاءات معًا:
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +أسهل طريقة لتجربة نموذجك المضبوط للاستدلال هي استخدامه في [`pipeline`]. قم بتنفيذ `pipeline` لتحليل المشاعر مع نموذجك، ومرر نصك إليه:
```suggestion
أسهل طريقة لتجربة النموذج المضبوط للاستدلال هي استخدامه ضمن [`pipeline`]. قم بإنشاء `pipeline` لتحليل المشاعر مع نموذجك، ومرر نصك إليه:
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +قم بتمرير مدخلاتك إلى النموذج وإرجاع `logits`:
```suggestion
مرر المدخلات إلى النموذج واسترجع `logits`:
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +احصل على الفئة ذات أعلى احتمال، واستخدم خريطة `id2label` الخاصة بالنموذج  لتحويلها إلى تصنيف نصي:
```suggestion
استخرج الفئة ذات الاحتمالية الأعلى، واستخدم `id2label` لتحويلها إلى تصنيف نصي:
```

2025-01-17 22:12 UTC, abodacs commented on docs/source/ar/tasks/sequence_classification.md
> +احصل على الفئة ذات أعلى احتمال، واستخدم خريطة `id2label` الخاصة بالنموذج لتحويلها إلى تصنيف نصي:
```suggestion
استخرج الفئة ذات الاحتمالية الأعلى، واستخدم `id2label` لتحويلها إلى تصنيف نصي:
```

2025-01-18 00:49 UTC, closed without merging