[i18n-ar] Translated file: `docs/source/ar/tasks/summarization.md` into Arabic
huggingface/transformers pull request #35195
Opened 2024-12-11 01:59 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/tasks/summarization.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### Who can review?
@stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-12-21 20:22 UTC, abodacs requested changes
السﻻم عليكم

@AhmedAlmaghz 
تمت المراجعة

جزاك الله خيرا

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +يُنشئ التلخيص نسخةً مختصرةً من مستند أو مقال ويلتقط جميع المعلومات المهمة. إلى جانب الترجمة، يُعدّ مثالاً آخر على مهمة يمكن صياغتها كمهمة تسلسل إلى تسلسل. يمكن أن يكون التلخيص:
```suggestion
يقوم التلخيص بإنشاء نسخة مختصرة من مستند أو مقال، حيث يلتقط جميع المعلومات المهمة. بالإضافة إلى الترجمة، يعتبر التلخيص مثالاً آخر على مهمة يمكن صياغتها كتسلسل إلى تسلسل. يمكن أن يكون التلخيص:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +2. استخدام النموذج المضبوط بدقة للاستدلال.
```suggestion
1. ضبط دقيق [T5](https://huggingface.co/google-t5/t5-small) على مجموعة فرعية من مشاريع قوانين ولاية كاليفورنيا من مجموعة بيانات [BillSum](https://huggingface.co/datasets/billsum) للتلخيص التجريدي.
2. استخدام النموذج المضبوط بدقة للتنبؤ.
```
1.  تدريب نموذج [T5](https://huggingfac

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +ابدأ بتحميل مجموعة فرعية أصغر من مشاريع قوانين ولاية كاليفورنيا من مجموعة بيانات BillSum من مكتبة 🤗 Datasets:
```suggestion
ابدأ بتحميل جزء صغير من بيانات مشاريع القوانين الخاصة بولاية كاليفورنيا من مجموعة بيانات BillSum في مكتبة 🤗 Datasets:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +قسّم مجموعة البيانات إلى مجموعة تدريب ومجموعة اختبار باستخدام طريقة [`~datasets.Dataset.train_test_split`]:
```suggestion
قسّم مجموعة البيانات إلى مجموعتي تدريب واختبار باستخدام الدالة [`~datasets.Dataset.train_test_split`]:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +هناك حقلان سترغب في استخدامهما:
```suggestion
هناك مُدخلان سترغب في استخدامهما:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +الخطوة التالية هي تحميل مجزء النص T5 لمعالجة `text` و `summary`:
```suggestion
الخطوة التالية هي تحميل مجزء النصوص T5 لمعالجة `text` و `summary`:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +دالة المعالجة المسبقة التي تريد إنشاؤها تحتاج إلى:
```suggestion
وظيفة المعالجة المسبقة التي تريد إنشاءها تحتاج إلى:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +3. اقتطاع التسلسلات بحيث لا يزيد طولها عن الحد الأقصى الذي تم تعيينه بواسطة معامل `max_length`.
```suggestion
1. إضافة بادئة للمُدخل باستخدام توجيه حتى يعرف T5 أن هذه مهمة تلخيص. تتطلب بعض النماذج القادرة على مهام البرمجة اللغوية العصبية المتعددة توجيهات لمهام مُحددة.
2. استخدام مُعامل الكلمة الرئيسية `text_target` عند ترميز التصنيفات.
3. قصّ التسلسلات بحيث لا يزيد طولها عن الحد الأقصى الذي تم تعيينه بواسطة مُعامل `max_length`.
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +الآن قم بإنشاء دفعة من الأمثلة باستخدام [`DataCollatorForSeq2Seq`].  الأكثر كفاءة *الحشو الديناميكي* للجمل إلى أطول طول في دفعة أثناء التجميع، بدلاً من حشو مجموعة البيانات بأكملها إلى الحد الأقصى للط
```suggestion
الآن قم بإنشاء دفعة من الأمثلة باستخدام [`DataCollatorForSeq2Seq`].  الأكثر كفاءة *الحشو الديناميكي* للجمل إلى أطول طول في دفعة أثناء عملية التجميع، بدلاً من حشو مجموعة البيانات بأكملها إلى الحد الأقصى للطول.
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +يُعد تضمين مقياس أثناء التدريب مفيدًا غالبًا لتقييم أداء نموذجك. يمكنك تحميل طريقة تقييم بسرعة باستخدام مكتبة 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index). لهذه المهمة، قم بتحميل مقياس [R
```suggestion
يُعد تضمين مقياس أثناء التدريب مفيدًا غالبًا لتقييم أداء نموذجك. يمكنك تحميل طريقة تقييم بسرعة باستخدام مكتبة 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index). لهذه المهمة، قم بتحميل مقياس [ROUGE](https://huggingface.co/spaces/evaluate-metric/rouge) (راجع [الجولة السريعة](https://huggingface.co/docs/evaluate/a_quick_tour) الخاصة بـ 🤗 Evaluate لمعرفة المزيد حول كيفية تحميل وحساب مقياس):
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +3. استدعي [`~Trainer.train`] لضبط نموذجك.
```suggestion
1. حدد مُعامِلات التدريب الخاصة بك في [`Seq2SeqTrainingArguments`]. المعامل الوحيد المطلوب هو `output_dir` الذي يُحدد مكان حفظ نموذجك. ستدفع هذا النموذج إلى Hub عن طريق تعيين `push_to_hub=True` (تحتاج إلى تسجيل الدخول إلى Hugging Face لتحميل نموذجك). في نهاية كل حقبة، سيقوم [`Trainer`] بتقييم مقياس ROUGE وحفظ نقطة تفتيش التدريب.
2. مرر مُعامِلات التدريب إلى [`Seq2SeqTrainer`] جنبًا إلى جنب مع النموذج ومجموعة البيانات والمُحلِّل اللغوي وجامع البيانات ودالة `compute_metrics`.
3. استدعِ [`~Trainer.train`] لضبط نموذجك.
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +ابتكر بعض النص الذي ترغب في تلخيصه. بالنسبة لـ T5، تحتاج إلى إضافة بادئة إلى مُدخلاتك اعتمادًا على المهمة التي تعمل عليها. بالنسبة للتجميع، يجب عليك إضافة بادئة إلى مُدخلاتك كما هو موضح أدناه:
```suggestion
خدد بعض النصوص الذي ترغب في تلخيصها. بالنسبة لـ T5، تحتاج إلى إضافة بادئة إلى مُدخلاتك اعتمادًا على المهمة التي تعمل عليها. بالنسبة التلخيص، يجب عليك إضافة بادئة إلى مُدخلاتك كما هو موضح أدناه:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +أبسط طريقة لتجربة نموذجك المضبوط للاستدلال هي استخدامه في [`pipeline`]. قم بإنشاء مثيل لـ `pipeline` للتجميع باستخدام نموذجك، ومرر نصك إليه:
```suggestion
أبسط طريقة لتجربة نموذجك المضبوط للاستدلال هي استخدامه في [`pipeline`]. استخدم `pipeline` للتلخيص باستخدام نموذجك، ومرر نصك إليه:
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +استخدم طريقة [`~transformers.generation_tf_utils.TFGenerationMixin.generate`] لإنشاء التجميع. لمزيد من التفاصيل حول استراتيجيات توليد النص المختلفة والمعلمات للتحكم في التوليد، راجع واجهة برمجة تطبيق
```suggestion
استخدم طريقة [`~transformers.generation_tf_utils.TFGenerationMixin.generate`] لإنشاء التلخيص. لمزيد من التفاصيل حول استراتيجيات توليد النص المختلفة والمعلمات للتحكم في التوليد، راجع واجهة برمجة تطبيقات [توليد النص](../main_classes/text_generation).
```

2024-12-21 20:22 UTC, abodacs commented on docs/source/ar/tasks/summarization.md
> +استخدم طريقة [`~generation.GenerationMixin.generate`] لإنشاء التجميع. لمزيد من التفاصيل حول استراتيجيات توليد النص المختلفة والمعلمات للتحكم في التوليد، راجع واجهة برمجة تطبيقات [توليد النص](../main_
```suggestion
استخدم طريقة [`~generation.GenerationMixin.generate`] لإنشاء التلخيص. لمزيد من التفاصيل حول استراتيجيات توليد النص المختلفة والمعلمات للتحكم في التوليد، راجع واجهة برمجة تطبيقات [توليد النص](../main_classes/text_generation).
```

2024-12-31 00:57 UTC, AhmedAlmaghz commented
Thank you @abodacs

2024-12-31 16:35 UTC, stevhliu approved these changes
Thanks for your contribution!

2024-12-31 16:35 UTC, merged