[i18n-ar] Translated file : docs/source/ar/tasks/token_classification.md into Arabic
huggingface/transformers pull request #35193
Opened 2024-12-10 22:47 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/tasks/token_classification.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

 ### Who can review?
 @stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2025-01-04 18:24 UTC, abodacs requested changes
سﻻم عليكم
@AhmedAlmaghz 
تمت المراحعة
جزاك الله خيرا

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +كما رأيت في حقل `tokens` المثال أعلاه، يبدو أن الإدخال قد تم تحليله بالفعل. لكن الإدخال لم يتم تجزئته بالفعل بعد وسيتعين عليك تعيين `is_split_into_words=True` لتحليل الكلمات إلى كلمات فرعية. على سبيل
```suggestion
كما رأيت في حقل `tokens` المثال أعلاه، يبدو أن المدخل قد تم تحليله بالفعل. لكن المدخل  لم يُجزأ بعد ويتعيّن عليك ضبط `is_split_into_words=True` لتقسيم الكلمات إلى كلمات فرعية. على سبيل المثال:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +هنا كيف يمكنك إنشاء وظيفة لإعادة محاذاة الرموز والتسميات، وقص السلاسل لتكون أطول من طول الإدخال الأقصى لـ DistilBERT:
```suggestion
1. ربط كل رمز بالكلمة الأصلية باستخدام الخاصية [`word_ids`](https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.BatchEncoding.word_ids).
2. تعيين التسمية `-100` للرموز الخاصة `[CLS]` و`[SEP]` بحيث يتم تجاهلها بواسطة دالة الخسارة PyTorch (انظر [CrossEntropyLoss](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html)).
3. تسمية الرمز الأول فقط لكلمة معينة. قم بتعيين `-100` لأجزاء الكلمة الأخرى.

هنا كيف يمكنك إنشاء وظيفة لإعادة محاذاة الرموز والتسميات، وقص الجمل لتتجاوز الحد الأقصى لطول مُدخلات DistilBERT:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +ومع ذلك، يضيف هذا بعض الرموز الخاصة `[CLS]` و`[SEP]` وتحليل الكلمات الفرعية يخلق عدم تطابق بين الإدخال والتسميات. قد يتم تقسيم كلمة واحدة تقابل تسمية واحدة الآن إلى كلمتين فرعيتين. ستحتاج إلى إعادة م
```suggestion
ومع ذلك، يضيف هذا بعض الرموز الخاصة `[CLS]` و`[SEP]` وتقسيم الكلمات إلى أجزاء يُنشئ عدم تطابق بين المُدخلات والتسميات. قد يتم تقسيم كلمة واحدة تقابل تسمية واحدة الآن إلى كلمتين فرعيتين. ستحتاج إلى إعادة محاذاة الرموز والتسميات عن طريق:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +لتطبيق وظيفة المعالجة المسبقة على مجموعة البيانات بأكملها، استخدم وظيفة [`~datasets.Dataset.map`] لمجموعة بيانات 🤗. يمكنك تسريع وظيفة `map` عن طريق تعيين `batched=True` لمعالجة عناصر متعددة من مجموعة
```suggestion
لتطبيق هذه العملية على كامل مجموعة البيانات، استخدم الدالة [`~datasets.Dataset.map`] لمجموعة بيانات 🤗. يمكنك تسريع الدالة `map` عن طريق تعيين `batched=True` لمعالجة عناصر متعددة من مجموعة البيانات في وقت واحد:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +الآن قم بإنشاء دفعة من الأمثلة باستخدام [`DataCollatorWithPadding`]. من الأكثر كفاءة *التحديد الديناميكي* للجمل إلى أطول طول في دفعة أثناء التجميع، بدلاً من تحديد مجموعة البيانات بالكامل إلى الطول ال
```suggestion
الآن قم بإنشاء دفعة من الأمثلة باستخدام [`DataCollatorWithPadding`].من الأفضل استخدام *الحشو الديناميكي* للجمل إلى أطول طول في دفعة أثناء التجميع، بدلاً من حشو مجموعة البيانات بالكامل إلى الطول الأقصى.
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +غالبًا ما يكون تضمين مقياس أثناء التدريب مفيدًا لتقييم أداء نموذجك. يمكنك تحميل طريقة تقييم بسرعة مع مكتبة 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index). لهذه المهمة، قم بتحميل إطار [seqev
```suggestion
يُعدّ تضمين مقياس أثناء التدريب مفيدًا في تقييم أداء نموذجك. يمكنك تحميل طريقة تقييم بسرعة مع مكتبة 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index). لهذه المهمة، قم بتحميل إطار [seqeval](https://huggingface.co/spaces/evaluate-metric/seqeval) (انظر جولة 🤗 Evaluate [quick tour](https://huggingface.co/docs/evaluate/a_quick_tour) لمعرفة المزيد حول كيفية تحميل وحساب مقياس). يُخرج seqeval عدة نتائج: الدقة، والاستذكار، ومقياس F1، والدقة.
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +احصل على تسميات الكيانات المسماة (NER) أولاً، ثم قم بإنشاء دالة تمرر تنبؤاتك وتسمياتك الصحيحة إلى [`~evaluate.EvaluationModule.compute`] لحساب الدرجات:
```suggestion
احصل على تسميات الكيانات المسماة (NER) أولاً،ثم أنشئ دالة تُمرر تنبؤاتك وتسمياتك الصحيحة إلى [`~evaluate.EvaluationModule.compute`] لحساب النتائج:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +دالة `compute_metrics` الخاصة بك جاهزة الآن، وستعود إليها عند إعداد تدريبك.
```suggestion
دالة `compute_metrics` جاهزة للاستخدام، وستحتاج إليها عند إعداد التدريب.
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +قبل البدء في تدريب نموذجك، قم بإنشاء خريطة للتعريفات المتوقعة إلى تسمياتها باستخدام `id2label` و`label2id`:
```suggestion
قبل تدريب النموذج، جهّز خريطة تربط بين المعرّفات المتوقعة وتسمياتها باستخدام `id2label` و `label2id`:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +أنت مستعد الآن لبدء تدريب نموذجك! قم بتحميل DistilBERT مع [`AutoModelForTokenClassification`] إلى جانب عدد التصنيفات المتوقعة، وتخطيطات التسميات:
```suggestion
أنت مستعد الآن لبدء تدريب نموذجك! قم بتحميل DistilBERT مع [`AutoModelForTokenClassification`] إلى جانب عدد التصنيفات المتوقعة، وخريطة التسميات:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +3. قم باستدعاء [`~Trainer.train`] لتعديل نموذجك.
```suggestion
1. حدد معلمات التدريب الخاصة بك في [`TrainingArguments`]. المعامل الوحيد المطلوب هو `output_dir` الذي يحدد مكان حفظ نموذجك. ستقوم بدفع هذا النموذج إلى Hub عن طريق تعيين `push_to_hub=True` (يجب أن تكون مسجلاً الدخول إلى Hugging Face لتحميل نموذجك). في نهاية كل حقبة، سيقوم [`Trainer`] بتقييم درجات seqeval وحفظ تسخة التدريب.
2. قم بتمرير معاملات التدريب إلى [`Trainer`] إلى جانب النموذج، ومجموعة البيانات، والمُجزِّئ اللغوي، و`data collator`، ودالة `compute_metrics`.
3.استدعِ [`~Trainer.train`] لتدريب نموذجك.
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +قم بتهيئة النموذج للتدريب مع [`compile`](https://keras.io/api/models/model_training_apis/#compile-method). لاحظ أن نماذج Transformers لديها جميعها دالة خسارة ذات صلة بالمهمة بشكل افتراضي، لذلك لا تحت
```suggestion
هيّئ النموذج للتدريب باستخدام [`compile`](https://keras.io/api/models/model_training_apis/#compile-method). لاحظ أن نماذج Transformers تتضمن دالة خسارة افتراضية مرتبطة بالمهمة، لذلك لا تحتاج إلى تحديد واحدة إلا إذا كنت ترغب في ذلك:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +ثم قم بتجميع مكالماتك معًا:
```suggestion
ثم جمّع callbacks الخاصة بك معًا:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +أخيرًا، أنت مستعد الآن لبدء تدريب نموذجك! قم باستدعاء [`fit`](https://keras.io/api/models/model_training_apis/#fit-method) مع مجموعات بيانات التدريب والتحقق، وعدد الحقبات، ومكالماتك لتعديل النموذج:
```suggestion
أخيرًا، أنت جاهز الآن لبدء تدريب نموذجك! قم باستدعاء [`fit`](https://keras.io/api/models/model_training_apis/#fit-method) مع بيانات التدريب والتحقق، وعدد الحقبات، وcallbacks لتعديل النموذج:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +أو [دفتر TensorFlow](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/token_classification-tf.ipynb).
```suggestion
للحصول على مثال أكثر تفصيلاً حول كيفية تعديل نموذج لتصنيف الرموز، ألق نظرة على الدفتر المقابل
[دفتر PyTorch](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/token_classification.ipynb)
أو [دفتر TensorFlow](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/token_classification-tf.ipynb).
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +قم بتقسيم النص إلى رموز وعودة تنسورات PyTorch:
```suggestion
قسّم النص إلى رموز وأرجع المُوتّرات بلغة PyTorch:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +احصل على الفئة ذات الاحتمالية الأعلى، واستخدم خريطة `id2label` للنموذج لتحويلها إلى تسمية نصية:
```suggestion
استخرج الفئة ذات الاحتمالية الأعلى، واستخدم جدول `id2label` الخاصة بالنموذج لتحويلها إلى تسمية نصية:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +قم بتقسيم النص إلى رموز وعودة تنسورات TensorFlow:
```suggestion
قسّم النص إلى رموز وأرجع المُوتّرات ب TensorFlow:
```

2025-01-04 18:24 UTC, abodacs commented on docs/source/ar/tasks/token_classification.md
> +احصل على الفئة ذات الاحتمالية الأعلى، واستخدم خريطة `id2label` للنموذج لتحويلها إلى تسمية نصية:
```suggestion
استخرج الفئة ذات الاحتمالية الأعلى، واستخدم جدول `id2label` الخاصة بالنموذج لتحويلها إلى تسمية نصية:
```

2025-01-05 17:25 UTC, AhmedAlmaghz commented
احسنت أخي عبدالله @abodacs 
إلى الأمام
اشكرك على جهودك الرائعة !

2025-01-05 17:56 UTC, abodacs approved these changes

2025-01-12 00:21 UTC, AhmedAlmaghz commented
Thank you @abodacs  and  @stevhliu

2025-01-12 00:42 UTC, AhmedAlmaghz commented
إحترامي وتقديري الكبيرين لك أخي عبدالله @abodacs 
دعنا نكمل المهام في مجموعة ## NATURAL LANGUAGE PROCESSING
نريد أن ننجز بشكل أكبر كلما أتيحت لنا الفرصة


# TASK GUIDES

## NATURAL LANGUAGE PROCESSING
- [ ]  Text classification #35192
- [ ]  Token classification #35193 
- [x]  Question answering #35196 
- [ ]  Causal language modeling #35197
- [ ]  Masked language modeling #35198
- [x]  Translation #35194 
- [x]  Summarization #35195 
- [x]  Multiple choice #35199

## AUDIO
- [ ]  Audio classification
- [ ]  Automatic speech recognition

## COMPUTER VISION
- [ ]  Image classification
- [ ]  Image segmentation
- [ ]  Video classification
- [ ]  Object detection
- [ ]  Zero-shot object detection
- [ ]  Zero-shot image classification
- [ ]  Depth estimation
- [ ]  Image-to-Image
- [ ]  Image Feature Extraction
- [ ]  Mask Generation
- [ ]  Keypoint Detection
- [ ]  Knowledge Distillation for Computer Vision

## Multimodal
- [ ]  Image captioning
- [ ]  Document Question Answering
- [ ]  Visual Question Answering
- [ ]  Text to speech
- [ ]  Image-text-to-text
- [ ]  Video-text-to-text

## Generation
- [ ]  Customize the generation strategy
- [ ]  Best Practices for Generation with Cache

## Prompting
- [ ]  Image tasks with IDEFICS
- [ ]  LLM prompting guide


أشكرك على جهودك الرائعة

2025-01-13 17:32 UTC, stevhliu approved these changes
LGTM, thanks!

2025-01-13 17:32 UTC, merged