[i18n-ar] Translated file: `docs/source/ar/tasks/multiple_choice.md` into Arabic
huggingface/transformers pull request #35199
Opened 2024-12-11 02:57 UTC by AhmedAlmaghz

## What does this PR do?
Translated the `docs/source/ar/tasks/multiple_choice.md` file of the documentation to `Arabic العربية`. I use transformers for my side-project and wanted to contribute. As a beginner, this seemed appropriate.

### Some questions:

- I can't access the pr documentation endpoint for `Arabic العربية`. Is there a missing step?
- I left all the other files alone after copying the English docs. Is this acceptable for future updates or should I add contents to the `_toctree.yml` only when translation is complete? Should I delete all other files for a cleaner review?
- In `Arabic`, people use both `Transformer` and `المحولات` to describe the model. However, as this is more of a product of HuggingFace I opted not to translate it. May you please let me know which you would prefer?

Thank you in advance for your review.

Part of #32435

### Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/) ?Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### Who can review?
@stevhliu , @MKhalusova , @abodacs, may you please review this PR?

2024-12-25 00:30 UTC, abodacs requested changes
السﻻم عليكم
@AhmedAlmaghz 
تمت المراجعة
جزاك الله خيرا

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +تشبه مهمة الاختيار من متعدد مهمة الإجابة على الأسئلة، باستثناء أنه يتم توفير العديد من الإجابات المرشحة مع سياق ويتم تدريب النموذج على اختيار الإجابة الصحيحة.
```suggestion
مهمة الاختيار من متعدد مشابهة لمهمة الإجابة على الأسئلة، ولكن مع توفير عدة إجابات محتملة مع سياق، ويُدرّب النموذج على تحديد الإجابة الصحيحة.
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +2. استخدام النموذج المضبوط للاستدلال.
```suggestion
1. ضبط نموذج [BERT](https://huggingface.co/google-bert/bert-base-uncased)  باستخدام الإعداد `regular` لمجموعة بيانات [SWAG](https://huggingface.co/datasets/swag) لاختيار الإجابة الأفضل من بين الخيارات المتعددة المتاحة مع السياق.
2. استخدام النموذج المضبوط للاستدلال.
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +- `label`: يحدد نهاية الجملة الصحيحة.
```suggestion
على الرغم من أن الحقول تبدو كثيرة، إلا أنها في الواقع بسيطة جداً:

- `sent1` و `sent2`: يعرض هذان الحقلان بداية الجملة، وبدمجهما معًا، نحصل على حقل `startphrase`.
- `ending`: يقترح نهاية محتملة للجملة، واحدة منها فقط هي الصحيحة.
- `label`: يحدد نهاية الجملة الصحيحة.
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +الخطوة التالية هي تحميل مُجزئ BERT لمعالجة بدايات الجمل والنهايات الأربع المحتملة:
```suggestion
الخطوة التالية هي استدعاء مُجزئ BERT لمعالجة بدايات الجمل والنهايات الأربع المحتملة:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +3. تسوية هاتين القائمتين حتى تتمكن من تجزئتهما، ثم إلغاء تسويتهما بعد ذلك بحيث يكون لكل مثال حقول `input_ids` و `attention_mask` و `labels` مقابلة.
```suggestion
تحتاج دالة المعالجة المسبقة التي تريد إنشاءها إلى:

1.  إنشاء أربع نسخ من حقل `sent1` ودمج كل منها مع `sent2` لإعادة إنشاء كيفية بدء الجملة.
2. دمج `sent2` مع كل من نهايات الجمل الأربع المحتملة.
3. تتجميع هاتين القائمتين لتتمكن من تجزئتهما، ثم إعادة ترتيبها بعد ذلك بحيث يكون لكل مثال حقول `input_ids` و `attention_mask` و `labels` مقابلة.

```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +لا يحتوي 🤗 Transformers على مجمع بيانات للاختيار من متعدد، لذلك ستحتاج إلى تكييف [`DataCollatorWithPadding`] لإنشاء دفعة من الأمثلة. من الأكثر كفاءة *حشو* الجمل ديناميكيًا إلى أطول طول في دفعة أثناء
```suggestion
لا يحتوي 🤗 Transformers على مجمع بيانات للاختيار من متعدد، لذلك ستحتاج إلى تكييف [`DataCollatorWithPadding`] لإنشاء دفعة من الأمثلة. من الأكفأ إضافة حشو (padding) ديناميكي للجمل إلى أطول طول في دفعة أثناء التجميع، بدلاً من حشو مجموعة البيانات بأكملها إلى الحد الأقصى للطول.
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +يسوي `DataCollatorForMultipleChoice` جميع مدخلات النموذج، ويطبق الحشو، ثم يلغي تسوية النتائج:
```suggestion
يقوم `DataCollatorForMultipleChoice` بتجميع جميع مدخلات النموذج، ويطبق الحشو، ثم يعيد تجميع النتائج في شكلها الأصلي:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +من المفيد غالبًا تضمين مقياس أثناء التدريب لتقييم أداء نموذجك. يمكنك تحميل طريقة تقييم بسرعة باستخدام مكتبة 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index). لهذه المهمة، قم بتحميل مقياس [الد
```suggestion
يُفضل غالبًا تضمين مقياس أثناء التدريب لتقييم أداء نموذجك. يمكنك تحميل طريقة تقييم بسرعة باستخدام مكتبة 🤗 [Evaluate](https://huggingface.co/docs/evaluate/index). لهذه المهمة، قم بتحميل مقياس [الدقة](https://huggingface.co/spaces/evaluate-metric/accuracy) (انظر إلى [الجولة السريعة](https://huggingface.co/docs/evaluate/a_quick_tour) لـ 🤗 Evaluate لمعرفة المزيد حول كيفية تحميل المقياس وحسابه):
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +ثم قم بإنشاء دالة تمرر تنبؤاتك وتسمياتك إلى [`~evaluate.EvaluationModule.compute`] لحساب الدقة:
```suggestion
ثم أنشئ دالة لتمرير التنبؤات والتسميات إلى [`~evaluate.EvaluationModule.compute`] لحساب الدقة:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +3. استدعي [`~Trainer.train`] لضبط نموذجك.
```suggestion
في هذه المرحلة، تبقى ثلاث خطوات فقط:

1. حدد معلمات التدريب الخاصة بك في [`TrainingArguments`]. المعلمة الوحيدة المطلوبة هي `output_dir` التي تحدد مكان حفظ نموذجك. ستدفع هذا النموذج إلى Hub عن طريق تعيين `push_to_hub=True` (يجب عليك تسجيل الدخول إلى Hugging Face لتحميل نموذجك). في نهاية كل حقبة، سيقوم [`Trainer`] بتقييم الدقة وحفظ نقطة فحص التدريب.
2. مرر معلمات التدريب إلى [`Trainer`] جنبًا إلى جنب مع النموذج ومُجمِّع البيانات والمعالج ودالة تجميع البيانات ودالة `compute_metrics`.
3. استدعي [`~Trainer.train`] لضبط نموذجك.
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +قم بتكوين النموذج للتدريب باستخدام [`compile`](https://keras.io/api/models/model_training_apis/#compile-method). لاحظ أن جميع نماذج Transformers تحتوي على دالة خسارة ذات صلة بالمهمة بشكل افتراضي، لذل
```suggestion
قم بتهيئة النموذج للتدريب باستخدام [`compile`](https://keras.io/api/models/model_training_apis/#compile-method). لاحظ أن جميع نماذج Transformers تحتوي على دالة خسارة مناسبة للمهمة بشكل افتراضي، لذلك لا تحتاج إلى تحديد واحدة ما لم ترغب في ذلك:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +الشيئان الأخيران اللذان يجب إعدادهما قبل بدء التدريب هما حساب الدقة من التنبؤات، وتوفير طريقة لدفع نموذجك إلى Hub. يتم كلاهما باستخدام [استدعاءات Keras](../main_classes/keras_callbacks).
```suggestion
الخطوتان الأخيرتان قبل بدء التدريب هما: حساب دقة التنبؤات، وتوفير طريقة لرفع النموذج إلى Hub. ويمكن تحقيق ذلك باستخدام [استدعاءات Keras](../main_classes/keras_callbacks)
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +ثم قم بتجميع استدعاءاتك معًا:
```suggestion
ثم قم بتضمين الاستدعاءات معًا:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +أخيرًا، أنت جاهز لبدء تدريب نموذجك! اتصل بـ [`fit`](https://keras.io/api/models/model_training_apis/#fit-method) مع مجموعات بيانات التدريب والتحقق من الصحة وعدد الحقب واستدعاءاتك لضبط النموذج:
```suggestion
أخيرًا، أنت جاهز لبدء تدريب نموذجك! استدعِ[`fit`](https://keras.io/api/models/model_training_apis/#fit-method) مع مجموعات بيانات التدريب والتحقق من الصحة وعدد الحقب والاستدعاءات لضبط النموذج:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +ابتكر بعض النص وإجابتين مرشحتين:
```suggestion
قم بإنشاء نص واقتراح إجابتين محتملتين:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +قم بتحليل كل مطالبة وزوج إجابة مرشح وأعد تنسورات PyTorch. يجب عليك أيضًا إنشاء بعض `التسميات`:
```suggestion
قم بتحليل كل مطالبة وزوج إجابة مرشح وأعد تنسورات PyTorch. يجب عليك أيضًا إنشاء بعض `العلامات`:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +مرر مدخلاتك وتسمياتك إلى النموذج وأرجع`logits`:
```suggestion
مرر مدخلاتك والعلامات إلى النموذج وأرجع`logits`:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +احصل على الفئة ذات الاحتمالية الأعلى:
```suggestion
استخرج الفئة ذات الاحتمالية الأكبر:
```

2024-12-25 00:30 UTC, abodacs commented on docs/source/ar/tasks/multiple_choice.md
> +احصل على الفئة ذات الاحتمالية الأعلى:
```suggestion
استخرج الفئة ذات الاحتمالية الأكبر:
```

2025-01-01 19:25 UTC, AhmedAlmaghz commented
Thank you @abodacs

2025-01-01 19:44 UTC, AhmedAlmaghz commented
We add #35194 to this PR  
thank you @abodacs

2025-01-01 19:48 UTC, AhmedAlmaghz commented
إحترامي وتقديري الكبيرين لك أخي عبدالله @abodacs 
دعنا نكمل المهام في مجموعة ## NATURAL LANGUAGE PROCESSING
نريد أن ننجز بشكل أكبر كلما أتيحت لنا الفرصة


# TASK GUIDES

## NATURAL LANGUAGE PROCESSING
- [ ]  Text classification #35192
- [ ]  Token classification #35193 
- [x]  Question answering #35196 
- [ ]  Causal language modeling #35197
- [ ]  Masked language modeling #35198
- [x]  Translation #35194 
- [x]  Summarization #35195 
- [x]  Multiple choice #35199

## AUDIO
- [ ]  Audio classification
- [ ]  Automatic speech recognition

## COMPUTER VISION
- [ ]  Image classification
- [ ]  Image segmentation
- [ ]  Video classification
- [ ]  Object detection
- [ ]  Zero-shot object detection
- [ ]  Zero-shot image classification
- [ ]  Depth estimation
- [ ]  Image-to-Image
- [ ]  Image Feature Extraction
- [ ]  Mask Generation
- [ ]  Keypoint Detection
- [ ]  Knowledge Distillation for Computer Vision

## Multimodal
- [ ]  Image captioning
- [ ]  Document Question Answering
- [ ]  Visual Question Answering
- [ ]  Text to speech
- [ ]  Image-text-to-text
- [ ]  Video-text-to-text

## Generation
- [ ]  Customize the generation strategy
- [ ]  Best Practices for Generation with Cache

## Prompting
- [ ]  Image tasks with IDEFICS
- [ ]  LLM prompting guide


أشكرك على جهودك الرائعة

2025-01-05 17:27 UTC, AhmedAlmaghz commented
أخي عبدالله @abodacs  قم بالموافقة على هذا PR  ليتم دمجه

2025-01-05 17:55 UTC, abodacs approved these changes

2025-01-08 22:17 UTC, stevhliu approved these changes
Looks good, thanks for your translations!

2025-01-08 22:17 UTC, merged

2025-01-09 11:07 UTC, abodacs commented
@stevhliu 
Can you check https://github.com/huggingface/doc-builder/pull/525?

Translation efforts can go in vain as it is not readable 
![image](https://github.com/user-attachments/assets/2f77cd3d-9bd1-4bdf-924f-6d11d3ae6f82)


Thanks

2025-01-12 00:25 UTC, AhmedAlmaghz commented
> @stevhliu Can you check [huggingface/doc-builder#525](https://github.com/huggingface/doc-builder/pull/525)?
> 
> Translation efforts can go in vain as it is not readable ![image](https://private-user-images.githubusercontent.com/554032/401513645-2f77cd3d-9bd1-4bdf-924f-6d11d3ae6f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2NDE2OTgsIm5iZiI6MTczNjY0MTM5OCwicGF0aCI6Ii81NTQwMzIvNDAxNTEzNjQ1LTJmNzdjZDNkLTliZDEtNGJkZi05MjRmLTZkMTFkM2FlNmY4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQwMDIzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTI2MjA2MWM2YjI0NjM3M2M0NDkzMTdmN2I2ZDUxNDIxYTNjYWUzZjcwNDFiNmUzNzFjYTE1MmRhZDRhZDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dBRByNoDEazOy3HWM-cUaAEzMdzRqUq5P4SGEwnSvOs)
> 
> Thanks



That's right !

Thank you @abodacs  and @stevhliu