Training args
huggingface/transformers pull request #3939
Opened 2020-04-24 04:50 UTC by parmarsuraj99

Added a little more description to the metadata of training args for new scripts. 
`--overwrite_output_dir` can be used to continue training from checkpoint if `--output_dir` points to a directory already having checkpoints.

This can help reduce the confusion when migrating from older script.

2020-04-24 13:25 UTC, julien-c requested changes
Looks good to me with small tweaks

2020-04-24 13:25 UTC, julien-c commented on src/transformers/training_args.py
> +                "Limit the total amount of checkpoints"
checkpoints and delete are going to be glued together in the resulting --help

2020-04-24 13:25 UTC, julien-c commented on src/transformers/training_args.py
> +                "continue training if output_dir points to a checkpoint directory."
```suggestion
                "Use this to continue training if output_dir points to a checkpoint directory."
```

2020-04-24 14:10 UTC, parmarsuraj99 reviewed
This would really help making it more clear

2020-04-24 20:21 UTC, julien-c commented on src/transformers/training_args.py
> +                "delete the older checkpoints in the output_dir, does not delete by default"
```suggestion
                "Limit the total amount of checkpoints."
                "Delete the older checkpoints in the output_dir, does not delete by default"
```

2020-04-29 04:07 UTC, parmarsuraj99 commented
Updates committed

2020-05-01 02:13 UTC, julien-c approved these changes

2020-05-01 02:13 UTC, julien-c commented on src/transformers/training_args.py
> +                "Delete the older checkpoints in the output_dir, does not delete by default"
```suggestion
                "Deletes the older checkpoints in the output_dir. Default is unlimited checkpoints"
```

2020-05-01 02:14 UTC, merged

2020-05-01 02:14 UTC, julien-c commented
Thanks!