Add patience argument to Trainer
huggingface/transformers pull request #4186
Opened 2020-05-06 21:48 UTC by thesamuel

# Summary
Often, we want to stop training if loss does not improve for a number of epochs. This PR adds a "patience" argument, which is a limit on the number of times we can get a non-improving eval loss before stopping training early.

It is implemented by other NLP frameworks, such as AllenNLP (see [trainer.py](https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L95) and [metric_tracker.py](https://github.com/allenai/allennlp/blob/1a8a12cd1b065d74fec3d2e80105a684736ff709/allennlp/training/metric_tracker.py#L6)).

# Motivation
This feature allows faster fine-tuning by breaking the training loop early and avoids users the toil of checking metrics on Tensorboard.

# Caveats
Often, models are evaluated once per epoch, but run_lm_finetuning.py has an option to evaluate after a set number of model update steps (dictated by `--logging_steps` if `--evaluate_during_training` is true). Because of this, I've elected to tie patience to the number of evaluations without improvement in loss.

2020-05-06 21:48 UTC, thesamuel commented
This supercedes https://github.com/huggingface/transformers/pull/2840, where I added patience to the outdated `run_language_modeling.py` script.

2020-06-15 07:28 UTC, BramVanroy commented
Looking good! Can you add a reference to your original post that this closes https://github.com/huggingface/transformers/issues/4894? Thanks

2020-06-15 12:28 UTC, julien-c requested changes
Looks good! Small suggestions there

2020-06-15 12:28 UTC, julien-c commented on src/transformers/trainer.py
> +        evals_without_improvement = 0
nit: prefix those with `patience_` as they're specific to this

```suggestion
        patience_best_eval_loss = None
        patience_evals_without_improvement = 0
        patience_should_stop = False
```

2020-06-15 12:28 UTC, julien-c commented on src/transformers/trainer.py
> +                                            )
```suggestion
                                            patience_should_stop = True
                                            logger.info(
                                                f"Patience threshold ({self.args.patience}) exceeded, stopping training"
                                            )
```

2020-06-15 12:28 UTC, julien-c commented on src/transformers/trainer.py
> +                        (self.args.patience > 0 and evals_without_improvement >= self.args.patience)):
```suggestion
                if ((self.args.max_steps > 0 and global_step > self.args.max_steps) or
                        patience_should_stop):
```

2020-06-15 12:28 UTC, julien-c commented on src/transformers/trainer.py
> +                    (self.args.patience > 0 and evals_without_improvement >= self.args.patience)):
same here

2020-07-21 06:44 UTC, kevin-yauris commented
Hello, when this feature will be merged? I would like to use it. Thank you.

2020-08-13 07:20 UTC, BramVanroy commented
> Hello, when this feature will be merged? I would like to use it. Thank you.

There are some changes requested that @thesamuel should fix before this can be merged.

2020-09-02 00:13 UTC, misrasaurabh1 commented
Bump. Early stopping is critical for an automated Trainer that reliably gives us the best model. Current way of figuring out the training stopping point seems to be specifying a static train_epochs but the training duration a model can take depends on way too many factors like learning rate, data complexity, model, model size, optimizer and so on that it is unreasonable to ask the user to specify the epochs in advance.
I believe the current assumption is that people train with very small learning rates so that the loss always seems to keep decreasing very slowly but according to my experience (and on my data) it is a sub-optimal schedule which takes too much time. I see that training with higher learning rates with larger batch sizes and stopping at the early stopping point results in an equally good if not better models. Although this requires use of early stopping.

2020-09-09 07:25 UTC, PhilipMay commented
I would like to use this early stopping on downstream training.
The current implementation only stops training by monitoring loss. IMO it should also be possible to monitor other metrics like F1 and ROC-AUC. 

I also would like to add a feature that stores the model each time when the monitored metric improves and then optionaly loads the model it after training. Then later evaluation can be done on this "best" model.

@thesamuel @julien-c what do you think?

2020-09-09 11:51 UTC, sgugger commented
I plan to work on this once I'm finished with the Funnel Transformer model @PhilipMay (so end of this week, beginning of the next).

2020-09-09 11:57 UTC, PhilipMay commented
> 
> 
> I plan to work on this once I'm finished with the Funnel Transformer model @PhilipMay (so end of this week, beginning of the next).

@sgugger That would be awsome. Maybe you want to get some inspiration from the FARM training loop which is pretty nice IMO:

https://github.com/PhilipMay/FARM/blob/nested_xval/farm/train.py#L262-370

2020-09-29 18:37 UTC, PhilipMay commented
I just found this PR that was already merged: #7431
I think it solved this...

2020-09-29 19:08 UTC, sgugger commented
Not quite, but it makes implementing it easier.

2020-09-30 06:41 UTC, PhilipMay commented
> Not quite, but it makes implementing it easier.

Yes - you are right. The patience part is still missing.

2020-11-30 16:02 UTC, BramVanroy commented
@sgugger Should we keep this open? You wrote in this thread you will work on this if you find the time, but I am not sure if you plan to use another PR for that.

2020-11-30 16:04 UTC, sgugger commented
There has been a PR merged adding the `EarlyStoppingCallback` (#8581) so I think this can be closed now.

2020-11-30 16:04 UTC, closed without merging

2020-12-02 02:24 UTC, thesamuel commented
Thanks @cbrochtrup @sgugger! Sorry I didn't get around to this...

2020-12-02 15:57 UTC, cbrochtrup commented
You're welcome, happy to help!