Send slack message if self-scheduled runner fails
huggingface/transformers pull request #4948
Opened 2020-06-12 00:46 UTC by sshleifer

2020-06-16 20:26 UTC, sshleifer commented
@julien-c do you know an easy way to test whether this works without merging?

2020-06-17 20:11 UTC, julien-c requested changes

2020-06-17 20:11 UTC, julien-c commented on .github/workflows/self-scheduled.yml
> +  USE_CUDA: yes
those envs are only for one command so I'm fine with where they were

2020-06-17 20:11 UTC, julien-c commented on .github/workflows/self-scheduled.yml
> +      - uses: actions/checkout@v2
please no whitespace-only change

2020-06-17 20:11 UTC, julien-c commented on .github/workflows/self-scheduled.yml
> +      - if: failure()
I'm fine with this though there are other options that don't require modifying this file

2020-09-25 14:16 UTC, closed without merging