[dbart] push picture
huggingface/transformers pull request #5278
Opened 2020-06-25 14:51 UTC by sshleifer

2020-06-25 19:40 UTC, sshleifer commented
This looks obnoxiously large in the diff viewer. Should we do some fancy markdown instead of
```markdown
![DBART](https://github.com/sshleifer/transformers_fork/raw/add-distilbart-pic/examples/seq2seq/distilbart_w_logos.png)
```

2020-06-25 22:37 UTC, julien-c commented
The README view is fixed-width on GitHub so you should be fine.

However, I would try to find a more permanent host/URL for your image, I suspect your fork's branch will get deleted at some point.

2020-06-26 00:56 UTC, JetRunner requested changes

2020-06-26 00:56 UTC, JetRunner commented on examples/seq2seq/README.md
> +![DBART](https://github.com/sshleifer/transformers_fork/raw/add-distilbart-pic/examples/seq2seq/distilbart_w_logos.png)
I’ll make you a version that is suitable for README (like the one I used for PABEE). Also I think uploading the image to our own server is a good idea, like this: https://huggingface.co/front/thumbnails/microsoft.png

2020-06-26 03:57 UTC, JetRunner commented on examples/seq2seq/README.md
> +![DBART](https://github.com/sshleifer/transformers_fork/raw/add-distilbart-pic/examples/seq2seq/distilbart_w_logos.png)
I've sent @sshleifer on Slack

2020-06-30 10:11 UTC, JetRunner commented
#5394

2020-06-30 10:11 UTC, closed without merging