Add DeeBERT (entropy-based early exiting for *BERT)
huggingface/transformers pull request #5477
Opened 2020-07-02 21:38 UTC by Ji-Xin

Add DeeBERT (entropy-based early exiting for *BERT).
Paper: https://www.aclweb.org/anthology/2020.acl-main.204/
Based on its original repository: https://github.com/castorini/DeeBERT

2020-07-03 12:24 UTC, JetRunner requested changes
Thanks for your contribution!

some high-level comments here:

1. how many iterations do your test run? You may want to reduce the `max_iteration` a little to make it faster.
2. `/examples/deebert/src/` seems to be better than `/examples/deebert/deebert/`

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/run_glue_deebert.py
> +from deebert.modeling_highway_roberta import DeerobertaForSequenceClassification
Are `DeeBertForSequenceClassification` and `DeeRobertaForSequenceClassification` better?

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/run_glue_deebert.py
> +    else:
```suggestion
    elif args.model_type == "roberta":
```

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/run_glue_deebert.py
> +
```suggestion
      else:
          raise NotImplementedError()
```

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/run_glue_deebert.py
> +            else:
same here

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/README.md
> +```
See the comment for `requirements.txt`

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/deebert/modeling_highway_bert.py
> +        if attention_mask.dim() == 3:
https://github.com/huggingface/transformers/blob/97355339f69e75df75fa91670d79a1edc0060389/examples/bert-loses-patience/pabee/modeling_pabee_bert.py#L155

we now have a util function. you can refactor these codes

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/deebert/modeling_highway_bert.py
> +        if head_mask is not None:
https://github.com/huggingface/transformers/blob/97355339f69e75df75fa91670d79a1edc0060389/examples/bert-loses-patience/pabee/modeling_pabee_bert.py#L173

we now have a util function. you can refactor these codes

2020-07-03 12:24 UTC, JetRunner commented on examples/deebert/README.md
> +This is for evaluating fine-tuned DeeBERT models, given a number of different early exit entropy thresholds.
You may want to elaborate a little on what variable is what in these scripts?

2020-07-03 12:29 UTC, stefan-it commented on examples/deebert/requirements.txt
> +tensorboardX
I think all of these are already specified in the top-level requirements from `examples` folder:

https://github.com/huggingface/transformers/blob/master/examples/requirements.txt

So there's no need to add it here (exept `boto3`)

2020-07-03 14:17 UTC, stefan-it commented
Btw: would be awesome so see a token classification example 😅

2020-07-03 16:57 UTC, JetRunner commented on examples/deebert/requirements.txt
> +tensorboardX
Yes! @stefan-it w.r.t. https://github.com/huggingface/transformers/pull/5477#discussion_r449543899

2020-07-03 19:23 UTC, Ji-Xin commented
Hi @JetRunner, thanks for the review! I have updated according to your suggestions.

2020-07-03 19:48 UTC, Ji-Xin commented
2 checks fail, however they don't seem relevant to my commits.

2020-07-05 16:41 UTC, JetRunner approved these changes
Thanks @Ji-Xin ! It looks much better now!

Please wait for the final approval of @LysandreJik

2020-07-06 22:31 UTC, LysandreJik approved these changes
Cool, very clean!

2020-07-06 22:31 UTC, LysandreJik commented on examples/deebert/src/modeling_highway_bert.py
> +        super(DeeBertEncoder, self).__init__()
(nit) we don't need to specify that since we're not python 2 compatible
```suggestion
        super().__init__()
```

2020-07-06 22:31 UTC, LysandreJik commented on examples/deebert/src/modeling_highway_roberta.py
> +        self.embeddings.word_embeddings = value
Those should already be defined in the `DeeBertModel`?

2020-07-07 20:42 UTC, Ji-Xin commented
@LysandreJik Thanks for the comments and I've updated accordingly!

2020-07-08 00:17 UTC, merged