Generate up to max_target_length sequences
huggingface/transformers pull request #5618
Opened 2020-07-09 07:16 UTC by tetsef

* Modifies the generate() call to allow for generation of sequences up to and including max_target_length number of tokens.
* Previous to this commit, implementation caps generation at 20 tokens and may result in poor performance. 
* See related recent generation_utils.py commit: https://github.com/huggingface/transformers/blob/c4d4e8bdbd25d9463d41de6398940329c89b7fb6/src/transformers/generation_utils.py#L139

2020-07-11 18:49 UTC, tetsef commented
@sshleifer

2020-07-11 23:05 UTC, sshleifer commented
This should depend on `config.max_length`, no?

2020-07-12 02:07 UTC, sshleifer commented
Were your summaries getting truncated like #5656 ?

2020-07-12 02:22 UTC, sshleifer requested changes
I think this should be configured by locally saving a config with desired max_length and passing it through finetune.py.

2020-07-12 16:29 UTC, tetsef commented
That seems like a better solution. I had been using a different prefix, without an associated config, so the max_length must have defaulted to 20.

2020-07-12 19:49 UTC, closed without merging