Add functioning early stopping (patience) and weighted random sampling
huggingface/transformers pull request #5958
Opened 2020-07-22 01:59 UTC by Breakend

This is to fix the issues in #4186 (hopefully) to get it merged in. Also adds weighted random sampling for imbalanced classes.

2020-07-22 12:20 UTC, sgugger requested changes
Thanks for the PR. The early stopping part looks good to me, apart from one variable name and some documentation to add.

I have mixed feelings about the weight sampler, especially since it requires a special method on the dataset, thus requiring people changing a function inside the library. I feel a better design would be to let the user pass a custom training sampler and then show your functions as an example that people can easily adapt.

@julien-c, tagging you if you have any thoughts.

2020-07-22 12:20 UTC, sgugger commented on src/transformers/trainer.py
> +                                    patience_should_stop = True
Maybe name the flag `stop_training`? This way it can be reused by other components introduced later that might need to abort training as well.

2020-07-22 12:20 UTC, sgugger commented on src/transformers/trainer.py
> +                if (self.args.max_steps > 0 and self.global_step > self.args.max_steps) or patience_should_stop:
```suggestion
                if (self.args.max_steps > 0 and self.global_step > self.args.max_steps) or stop_training:
```

2020-07-22 12:20 UTC, sgugger commented on src/transformers/trainer.py
> +            if (self.args.max_steps > 0 and self.global_step > self.args.max_steps) or patience_should_stop:
```suggestion
            if (self.args.max_steps > 0 and self.global_step > self.args.max_steps) or strop_training:
```

2020-07-22 12:20 UTC, sgugger commented on src/transformers/training_args.py
> +    patience: int = field(
Please document those two new arguments with the rest in the docstring.

2020-09-24 08:23 UTC, gborodin commented
when this will be added to library?

2020-12-04 22:07 UTC, closed without merging