Bart ce loss ignores pad_token_id instead of -100
huggingface/transformers pull request #6804
Opened 2020-08-28 18:57 UTC by sshleifer

cc @ibeltagy who noticed this.

I think it is better to ignore pad_token_id then -100, but this is semi-breaking because old training code might have replaced pad token id with -100 in labels.

Maybe I should check for both?

2020-08-31 12:35 UTC, sgugger approved these changes
Isn't the default in the config to -100? I think this is fine.

2020-08-31 23:47 UTC, sshleifer commented
What do you mean default in config?
The default `ignore_index` is -100 for CrossEntropyLoss.
`pad_token_id` is overwritten by BartConfig.

2020-08-31 23:48 UTC, sshleifer commented on src/transformers/modeling_bart.py
>              # TODO(SS): do we need to ignore pad tokens in labels?
```suggestion
```

2020-09-01 02:54 UTC, sgugger commented
Sorry mixed things up. This would make `BartForConditionalGeneration` behave differently from all the others models (all ModelForMaskedLM and T5ForConditionalGeneration use -100) so I think this is pretty breaking. Users probably have special code to changed padded token to -100, plus you may want to mask other things than the padding for loss computation (more relevant for masked LM than seq2seq but still).

I think this is some preprocessing work to do on the labels, for instance the `DataCollatorForLanguageModeling` replaces all non-masked tokens by -100 in the labels.

2020-09-01 07:41 UTC, LysandreJik requested changes
As @sgugger said, let's not have BART behave differently to other models here.

2020-09-01 13:26 UTC, closed without merging