[TF] replace keras dense by keras.layers.DenseEinsum
huggingface/transformers pull request #6877
Opened 2020-09-01 11:25 UTC by patrickvonplaten

Fixes #6771.

This PR might speed up TF runtime on GPU.

2020-09-01 11:36 UTC, patrickvonplaten commented
As a comparision. When running this line on current `master`:
```
TF_CPP_MIN_LOG_LEVEL=3 python examples/benchmarking/run_benchmark_tf.py --models bert-base-uncased --no_memory --batch_sizes 1 --sequence_lengths 128 256 512
```

one gets the following results: 

```
====================       INFERENCE - SPEED - RESULT       ====================
--------------------------------------------------------------------------------
          Model Name             Batch Size     Seq Length     Time in s   
--------------------------------------------------------------------------------
      bert-base-uncased              1              128            0.006     
      bert-base-uncased              1              256            0.009     
      bert-base-uncased              1              512            0.017     
--------------------------------------------------------------------------------

====================        ENVIRONMENT INFORMATION         ====================
- transformers_version: 3.0.2
- framework: TensorFlow
- eager_mode: False
- use_xla: False
- framework_version: 2.3.0
- python_version: 3.6.10
- system: Linux
- cpu: x86_64
- architecture: 64bit
- date: 2020-09-01
- time: 11:23:30.836691
- fp16: False
- use_multiprocessing: True
- only_pretrain_model: False
- cpu_ram_mb: 32088
- use_gpu: True
- num_gpus: 1
- gpu: TITAN RTX
- gpu_ram_mb: 24217
- gpu_power_watts: 280.0
- gpu_performance_state: 2
- use_tpu: False
```

for a TITAN RTX GPU.

When running the above line on this branch, one gets the following results:

```
====================       INFERENCE - SPEED - RESULT       ====================
--------------------------------------------------------------------------------
          Model Name             Batch Size     Seq Length     Time in s   
--------------------------------------------------------------------------------
      bert-base-uncased              1              128            0.006     
      bert-base-uncased              1              256            0.008     
      bert-base-uncased              1              512            0.016     
--------------------------------------------------------------------------------

====================        ENVIRONMENT INFORMATION         ====================
- transformers_version: 3.0.2
- framework: TensorFlow
- eager_mode: False
- use_xla: False
- framework_version: 2.3.0
- python_version: 3.6.10
- system: Linux
- cpu: x86_64
- architecture: 64bit
- date: 2020-09-01
- time: 11:28:12.021389
- fp16: False
- use_multiprocessing: True
- only_pretrain_model: False
- cpu_ram_mb: 32088
- use_gpu: True
- num_gpus: 1
- gpu: TITAN RTX
- gpu_ram_mb: 24217
- gpu_power_watts: 280.0
- gpu_performance_state: 2
- use_tpu: False
```

So, I cannot see a real difference here :-/ @jlei2

2020-09-01 11:40 UTC, patrickvonplaten commented
I will see whether the benchmark results are better on a GPU-V100 GPU. 
@jlei2 - could you post the code you used to benchmark HF Bert vs. Google Bert ? This would help a lot for reproducability.

2020-09-02 10:46 UTC, LysandreJik requested changes

2020-09-02 10:46 UTC, LysandreJik commented on src/transformers/modeling_tf_bert.py
> +    return tf.keras.layers.experimental.EinsumDense(
Maybe check to see the TF version here?  We should support tf 2.0+ for the lib's internals

2020-09-02 10:47 UTC, LysandreJik commented
oops didn't see it was [WIP]

2020-09-09 08:57 UTC, jplu commented
@patrickvonplaten can you update your code with the version given by @jlei2 [here](https://github.com/jlei2/transformers/pull/2) when you have time please. Thanks a lot!

2020-10-19 09:22 UTC, closed without merging