Added TF TransfoXL Sequence Classification
huggingface/transformers pull request #9169
Opened 2020-12-17 15:16 UTC by spatil6

This PR implements Sequence classification for TF TransfoXL model.
TFTransfoXLForSequenceClassification uses the last token in order to do the classification, as other causal models (e.g. GPT-1 ,GPT-2) do.

Fixes #7623

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

 @LysandreJik @jplu

2020-12-18 19:10 UTC, LysandreJik requested changes
This LGTM. @jplu if you have nothing to say, feel free to merge the PR.

2020-12-18 19:10 UTC, LysandreJik approved these changes
Meant to approve, finger slipped.

2020-12-19 04:10 UTC, spatil6 commented on tests/test_modeling_tf_transfo_xl.py
> +        config.num_labels = self.num_labels
@LysandreJik I have defined 'num_labels' here.
Now,I'll move it to 'prepare_config_and_inputs'

2020-12-19 07:18 UTC, spatil6 commented on tests/test_modeling_tf_transfo_xl.py
>          )
done

2020-12-19 13:43 UTC, jplu approved these changes
LGTM

2020-12-19 13:44 UTC, merged